import { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, Bookmark, CheckCircle2, ChevronRight, Clock, Download, Film, Search, ShieldCheck } from 'lucide-react';
import { useStore } from './context';
import { DownloadLink, Empty, PageHeading, SubjectCard, useText } from './components';
import { searchMatch, toggleBookmark } from './domain';
import { saveVideo } from './storage';
import type { Lesson } from './types';

export default function Learn() {
  const { subjectId } = useParams();
  const { catalog } = useStore();
  const [query, setQuery] = useState('');
  const subject = catalog.subjects.find(s => s.id === subjectId);
  if (subjectId && !subject) return <Empty title="Subject not found" link="/learn">Choose a subject from the catalogue.</Empty>;
  return <><PageHeading eyebrow="MAKE CONNECTIONS. BUILD UNDERSTANDING." title={subject?.title || 'A whole world to explore'}>{subject ? `${subject.chapters.length} chapters, one clear learning path. Open a topic to explore its concepts and available questions.` : '26 subjects. Follow your curiosity, or focus on your next exam.'}</PageHeading>{subject && <Link to="/learn" className="text-link">← All subjects</Link>}<label className="search-field"><Search size={20} /><span className="sr-only">Find a subject or topic</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder={subject ? 'Find a chapter or topic…' : 'Find a subject…'} /></label>{!subject ? <div className="subject-grid all-subjects">{catalog.subjects.filter(s => searchMatch(query, s.title, s.titleHindi)).map(s => <SubjectCard subject={s} key={s.id} />)}</div> : <div className="chapter-list">{subject.chapters.filter(c => searchMatch(query, c.title) || c.topics.some(t => searchMatch(query, t.title))).map((c, i) => <section className="card chapter" key={c.id}><div className="chapter-heading"><span className="chapter-number">{String(i + 1).padStart(2, '0')}</span><div><p className="eyebrow">CHAPTER</p><h2>{c.title}</h2></div><span className="chip neutral">{c.topics.length} topics</span></div>{c.topics.filter(t => searchMatch(query, t.title, c.title)).map(t => <Link to={`/topic/${t.id}`} key={t.id} className="topic-row"><div><h3>{t.title}</h3><p>{t.concepts.length} concepts · {t.questionCount ? `${t.questionCount} verified questions` : 'Evidence collection pending'}</p></div><span className={`chip ${t.questionCount ? '' : 'neutral'}`}>{t.questionCount ? 'Practice available' : 'In preparation'}</span><ChevronRight size={19} /></Link>)}</section>)}</div>}<p className="muted small">The catalogue shows the planned coverage. Available question counts and lesson statuses show what has actually been verified.</p></>;
}

export function TopicPage() {
  const { topicId } = useParams();
  const { catalog, state, facts, questions, sources, update, toast } = useStore();
  const text = useText();
  const subject = catalog.subjects.find(s => s.chapters.some(c => c.topics.some(t => t.id === topicId)));
  const chapter = subject?.chapters.find(c => c.topics.some(t => t.id === topicId));
  const topic = chapter?.topics.find(t => t.id === topicId);
  const [lesson, setLesson] = useState<Lesson>();
  const [loadError, setLoadError] = useState('');
  const video = useRef<HTMLVideoElement>(null);
  const milestones = useRef(new Set<string>());
  useEffect(() => { setLesson(undefined); setLoadError(''); milestones.current.clear(); const controller = new AbortController(); if (topicId) fetch(`/data/lessons/${topicId}.json`, { signal: controller.signal }).then(r => { if (!r.ok) throw new Error('Lesson metadata is unavailable offline.'); return r.json(); }).then(setLesson).catch(e => { if (e.name !== 'AbortError') setLoadError(e.message); }); return () => controller.abort(); }, [topicId]);
  if (!topic || !chapter || !subject) return <Empty title="Topic not found" link="/learn">Explore a topic from the subject catalogue.</Empty>;
  const topicFacts = facts.filter(f => f.topicId === topicId);
  const topicQuestions = questions.filter(q => q.topicId === topicId);
  const mastered = topic.concepts.filter(c => state.progress[c.id]?.state === 'MASTERED').length;
  const availableVideo = lesson && ['APPROVED', 'PUBLISHED'].includes(lesson.status) && lesson.media && (!lesson.validUntil || Date.parse(lesson.validUntil) > Date.now());
  const track = (milestone: string) => { if (milestones.current.has(milestone)) return; milestones.current.add(milestone); update(s => ({ ...s, videoEvents: [...s.videoEvents, { videoId: lesson!.videoId, milestone, at: Date.now() }] })); };
  return <><div className="breadcrumbs"><Link to="/learn">Learn</Link><ChevronRight size={14} /><Link to={`/learn/${subject.id}`}>{subject.shortTitle}</Link><ChevronRight size={14} /><span>{chapter.title}</span></div><PageHeading eyebrow="UNDERSTAND → RECALL → PRACTICE" title={topic.title} action={<button className="secondary" aria-pressed={state.bookmarks.includes(topic.id)} onClick={() => update(s => toggleBookmark(s, topic.id))}><Bookmark size={17} />{state.bookmarks.includes(topic.id) ? 'Saved' : 'Save topic'}</button>}>{mastered} / {topic.concepts.length} concepts mastered through practice</PageHeading><div className="topic-layout"><section><div className="video-panel">{availableVideo ? <video ref={video} controls playsInline preload="metadata" poster={lesson.media!.poster} onPlay={() => track('started')} onEnded={() => track('completed')} onTimeUpdate={() => { const v = video.current; if (v && Number.isFinite(v.duration)) for (const n of [25, 50, 75]) if (v.currentTime / v.duration * 100 >= n) track(`${n}%`); }}><source src={lesson.media!.url} type="video/mp4" /><track kind="captions" src={lesson.media!.subtitlePath} srcLang="hi" label="हिंदी" default /></video> : <div className="video-pending"><Film size={40} strokeWidth={1.2} /><span className="chip neutral">HINDI LESSON · IN PREPARATION</span><h2>Understanding comes first.</h2><p>{lesson?.status === 'PROMPT_READY' ? 'The source-grounded Hindi script is prepared. Google Flow generation and video review are pending.' : 'This lesson is waiting for verified evidence and production. Explore the learning path below.'}</p><span className="small">No approved video is available for this topic yet.</span></div>}</div>{loadError && <p role="status" className="small muted">{loadError}</p>}{availableVideo && <div className="video-controls"><span><Clock size={16} />{Math.round(lesson.targetDurationSec)} seconds</span><label>Speed<select onChange={e => { if (video.current) video.current.playbackRate = Number(e.target.value); }} defaultValue="1"><option value="0.75">0.75×</option><option value="1">1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option></select></label><button className="secondary" onClick={() => saveVideo(lesson.media!.url, lesson.media!.sha256, lesson.media!.size).then(() => toast('Video saved for offline viewing.')).catch(e => toast(e.message))}><Download size={16} />Save offline</button></div>}
    <section className="card topic-section"><h2>What you will learn</h2><ul className="concept-list">{topic.concepts.map(c => <li key={c.id}><CheckCircle2 size={17} /><span>{c.title}</span><span className="muted small">{state.progress[c.id]?.state.replaceAll('_', ' ') || 'NEW'}</span></li>)}</ul></section>
    {topicFacts.length > 0 && <section className="card topic-section"><h2>Facts you can trace</h2>{topicFacts.map(f => <article key={f.id} className="fact"><p>{state.profile.language === 'hi' ? f.canonicalStatementHindi : f.canonicalStatement}</p><details><summary>View evidence & source</summary>{f.evidence.map((e, i) => <blockquote key={i}>{e.quote}<cite>{e.locator}</cite></blockquote>)}{f.sourceIds.map(id => { const source = sources.find(s => s.id === id); return source && <a key={id} href={source.url} target="_blank" rel="noreferrer">{source.publisher} · {source.title} ↗</a>; })}<p className="small muted">Verified {new Date(f.verifiedAt).toLocaleDateString()}</p></details></article>)}</section>}
    {lesson?.narrationHindi && <details className="card topic-section"><summary>Hindi transcript {availableVideo ? '' : '— script draft, video not generated'}</summary><p lang="hi" className="transcript">{lesson.narrationHindi}</p></details>}
    {topicQuestions.length > 0 && <section className="card topic-section"><h2>Common confusions & memory cues</h2>{topicQuestions.slice(0, 3).map(q => <p key={q.id}>{text(q.memoryCue)}</p>)}</section>}
    </section><aside><div className="card topic-section sticky"><span className="eyebrow">MAKE IT STICK</span><h2>A quick recall goes a long way.</h2><p>Close your notes. Retrieve the idea. Then see how it connects.</p>{topicQuestions.length ? <><Link className="button full" to={`/practice?topic=${topic.id}&count=5`}>Quick check<ArrowRight size={17} /></Link><Link className="secondary full" to={`/practice?topic=${topic.id}`}>Practice this topic</Link><p className="small muted">{topicQuestions.length} questions available on this device.</p></> : <><p>{topic.questionCount ? 'Download this subject’s pack to practice here.' : 'Questions will appear after evidence and answer review.'}</p><DownloadLink /></>}<hr /><p className="small"><ShieldCheck size={16} /> Watching alone does not establish mastery. Your recall and revision history determine progress.</p></div></aside></div></>;
}
