import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Bookmark, CalendarDays, CheckCircle2, Search, Sparkles, Target } from 'lucide-react';
import { useStore } from './context';
import { DownloadLink, Empty, PageHeading, useText } from './components';
import { revisionQuestions, searchMatch, toggleBookmark } from './domain';

export default function Library({ page }: { page: string }) {
  const { state, questions, facts, catalog, update } = useStore();
  const text = useText();
  const [query, setQuery] = useState('');
  const [limit, setLimit] = useState(30);
  const topics = catalog.subjects.flatMap(s => s.chapters.flatMap(c => c.topics));
  if (page === 'current-affairs' || page === 'pyq') return <><PageHeading eyebrow="EVIDENCE BEFORE PUBLICATION" title={page === 'pyq' ? 'Previous year questions' : 'Current affairs'}>{page === 'pyq' ? 'Actual exam papers, official answer keys, and clear provenance.' : 'Fresh events, official sources, and visible verification dates.'}</PageHeading><Empty title={page === 'pyq' ? 'Official papers are awaiting ingestion.' : 'No fresh current-affairs pack is published.'} link="/practice" label="Explore verified practice">{page === 'pyq' ? 'This checkpoint contains 0 actual PYQs. Exam, stage, year, paper, shift and official answer provenance are required before publication. Practice questions are never presented as past-paper questions.' : 'Every event needs a source, event date, verification time and expiry. Unverified or expired news is excluded from practice.'}</Empty><section className="card topic-section"><h2>{page === 'pyq' ? 'How provenance is checked' : 'How freshness is maintained'}</h2><p>{page === 'pyq' ? 'Official paper → question number → official answer key → evidence review → verified question. Missing or ambiguous records remain unavailable.' : 'Official report → event record → deduplication → verified FactCard → question pack. Expired claims are removed from eligible questions until reverified.'}</p></section></>;
  if (page === 'performance') {
    const correct = state.attempts.filter(a => a.correct).length;
    const accuracy = state.attempts.length ? Math.round(correct / state.attempts.length * 100) : 0;
    const avg = state.attempts.length ? Math.round(state.attempts.reduce((n, a) => n + a.elapsedMs, 0) / state.attempts.length / 1000) : 0;
    const last7 = Array.from({ length: 7 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - 6 + i); return { label: d.toLocaleDateString('en', { weekday: 'short' }), count: state.attempts.filter(a => new Date(a.at).toDateString() === d.toDateString()).length }; });
    const max = Math.max(1, ...last7.map(x => x.count));
    return <><PageHeading eyebrow="SMALL STEPS ADD UP" title="Your learning, in perspective.">A reflection of practice on this device. No comparison needed.</PageHeading><div className="metric-grid">{[[state.attempts.length, 'Questions attempted'], [`${accuracy}%`, 'Answer accuracy'], [`${avg}s`, 'Average answer time'], [Object.values(state.progress).filter(p => p.state === 'MASTERED').length, 'Concepts mastered']].map(([n, label]) => <div className="card metric" key={label}><strong>{n}</strong><span>{label}</span></div>)}</div><div className="two-column"><section className="card topic-section"><h2>A week of curiosity</h2><div className="bar-chart" aria-label="Practice activity over the last seven days">{last7.map((x, i) => <div key={i}><span>{x.count}</span><div className="bar-track"><div style={{ height: `${x.count / max * 100}%` }} /></div><span>{x.label}</span></div>)}</div></section><section className="card topic-section"><h2>Find your next focus</h2>{catalog.subjects.map(s => ({ s, attempts: state.attempts.filter(a => a.subjectId === s.id) })).filter(x => x.attempts.length).map(({ s, attempts }) => <div className="subject-performance" key={s.id}><span>{s.shortTitle}</span><strong>{Math.round(attempts.filter(a => a.correct).length / attempts.length * 100)}%</strong></div>)}{!state.attempts.length && <p>Your strengths and areas to revisit will appear after your first practice session.</p>}<Link className="text-link" to="/notebook">Review weak concepts<ArrowRight size={16} /></Link></section></div><h2>Session history</h2>{state.results.length ? [...state.results].reverse().map(r => <details className="card history-row" key={r.id}><summary>{r.mode} · {r.correct}/{r.total} correct · {r.score} points · {new Date(r.at).toLocaleString()}</summary><p>{Math.round(r.elapsedMs / 1000)} seconds · penalty {r.negativeMark} per wrong answer</p>{r.questionIds.map(id => { const q = questions.find(q => q.id === id); return <p key={id}>{q ? text(q.question) : `Question ${id} (pack not downloaded)`} — {r.answers[id] === undefined ? 'Unanswered' : q ? text(q.options[r.answers[id]]) : `Option ${r.answers[id] + 1}`}</p>; })}</details>) : <Empty title="Your story starts with one question." link="/practice" label="Start practicing">Completed practice sessions, mocks and challenges will appear here.</Empty>}</>;
  }
  if (page === 'search') {
    const subjectMatches = query.trim() ? catalog.subjects.filter(s => searchMatch(query, s.title, s.titleHindi)) : [];
    const chapterMatches = query.trim() ? catalog.subjects.flatMap(s => s.chapters.map(c => ({ ...c, subjectId: s.id }))).filter(c => searchMatch(query, c.title)) : [];
    const topicMatches = query.trim() ? topics.filter(t => searchMatch(query, t.title, ...t.concepts.map(c => c.title))) : [];
    const questionMatches = query.trim() ? questions.filter(q => searchMatch(query, q.question.en, q.question.hi, q.explanation.en, q.explanation.hi)) : [];
    const factMatches = query.trim() ? facts.filter(f => searchMatch(query, f.canonicalStatement, f.canonicalStatementHindi)) : [];
    return <><PageHeading eyebrow="FOLLOW A THREAD" title="What are you curious about?">Search subjects, chapters, topics, concepts, downloaded questions and source-grounded facts.</PageHeading><label className="search-field"><Search size={20} /><span className="sr-only">Search knowledge</span><input autoFocus value={query} onChange={e => { setQuery(e.target.value); setLimit(30); }} placeholder="Try planets, Harappan, units, संयुक्त राष्ट्र…" /></label>{query.trim() ? <><p className="muted">{subjectMatches.length + chapterMatches.length + topicMatches.length + questionMatches.length + factMatches.length} results · Questions and facts are searched locally.</p>{subjectMatches.map(s => <Link className="card search-result" key={s.id} to={`/learn/${s.id}`}><span className="eyebrow">SUBJECT</span><h3>{s.title}</h3><ArrowRight size={18} /></Link>)}{chapterMatches.slice(0, limit).map(c => <Link className="card search-result" key={c.id} to={`/learn/${c.subjectId}`}><span className="eyebrow">CHAPTER</span><h3>{c.title}</h3></Link>)}{topicMatches.slice(0, limit).map(t => <Link className="card search-result" key={t.id} to={`/topic/${t.id}`}><span className="eyebrow">TOPIC</span><h3>{t.title}</h3><p>{t.questionCount} verified questions</p></Link>)}{questionMatches.slice(0, limit).map(q => <Link className="card search-result" key={q.id} to={`/practice?question=${q.id}`}><span className="eyebrow">QUESTION</span><h3>{text(q.question)}</h3></Link>)}{factMatches.slice(0, limit).map(f => <Link className="card search-result" key={f.id} to={`/topic/${f.topicId}`}><span className="eyebrow">VERIFIED FACT</span><p>{state.profile.language === 'hi' ? f.canonicalStatementHindi : f.canonicalStatement}</p></Link>)}{Math.max(chapterMatches.length, topicMatches.length, questionMatches.length, factMatches.length) > limit && <button onClick={() => setLimit(n => n + 30)}>Show more results</button>}</> : <Empty title="Every discovery begins with a question.">People, places, books and events can be found through their mapped topics. Hindi scripts are represented through the verified facts they teach.</Empty>}</>;
  }
  const due = revisionQuestions(questions, state);
  const list = page === 'notebook' ? questions.filter(q => state.wrongIds.includes(q.id)) : page === 'bookmarks' ? questions.filter(q => state.bookmarks.includes(q.id)) : due;
  const title = page === 'notebook' ? 'Make a friend of your mistakes.' : page === 'bookmarks' ? 'Keep a little curiosity for later.' : 'Remember what matters.';
  const savedTopics = page === 'bookmarks' ? topics.filter(t => state.bookmarks.includes(t.id)) : [];
  const nextDue = Object.values(state.progress).map(p => p.due).filter(t => t > Date.now()).sort((a, b) => a - b)[0];
  return <><PageHeading eyebrow={page === 'notebook' ? 'WRONG ANSWER NOTEBOOK' : page === 'bookmarks' ? 'YOUR BOOKMARKS' : 'SMART REVISION'} title={title}>{page === 'revision' ? 'Spaced recall, guided by accuracy, confidence and recency. Previously unseen angles come first.' : page === 'notebook' ? 'An incorrect answer is a starting point. Understand why, then give it another try.' : 'Questions and topics you want to return to.'}</PageHeading>{page === 'revision' && <div className="revision-banner"><Sparkles size={30} /><div><h2>{due.length ? `${due.length} questions are ready for recall.` : 'You’re all caught up for now.'}</h2><p>{nextDue ? `Next scheduled review: ${new Date(nextDue).toLocaleString()}` : 'Your first practice session starts a personal revision schedule.'}</p></div>{!!due.length && <Link to="/practice?filter=due" className="button">Begin revision<ArrowRight size={17} /></Link>}</div>}{!!list.length && <Link to={`/practice?filter=${page === 'notebook' ? 'wrong' : page === 'bookmarks' ? 'saved' : 'due'}`} className="button">Practice these questions<ArrowRight size={17} /></Link>}{savedTopics.map(t => <Link to={`/topic/${t.id}`} className="card search-result" key={t.id}><span className="eyebrow">SAVED TOPIC</span><h3>{t.title}</h3></Link>)}{list.slice(0, limit).map(q => <article className="card notebook-card" key={q.id}><div><span className="chip neutral">{q.difficulty}</span><button className="icon-button" aria-label="Toggle bookmark" aria-pressed={state.bookmarks.includes(q.id)} onClick={() => update(s => toggleBookmark(s, q.id))}><Bookmark size={19} /></button></div><h2>{text(q.question)}</h2><p>{text(q.memoryCue)}</p><div className="actions"><Link className="text-link" to={`/practice?question=${q.id}`}><Target size={16} />Try again</Link><Link className="text-link" to={`/topic/${q.topicId}`}>Review the concept<ArrowRight size={16} /></Link></div></article>)}{list.length > limit && <button onClick={() => setLimit(n => n + 30)}>Show more</button>}{!list.length && !savedTopics.length && <Empty title={page === 'notebook' ? 'A fresh page for your learning.' : page === 'bookmarks' ? 'Something worth remembering?' : 'Build your recall rhythm.'} link="/practice" label="Start practice">{page === 'notebook' ? 'Questions you get wrong are saved here automatically. A correct retry resolves the entry while keeping your answer history.' : page === 'bookmarks' ? 'Use the bookmark button on a question or topic to save it here.' : 'Correct recall spaces reviews at 1, 3, 7, 14, 30 and 60 days. A mistake returns in 10 minutes.'}</Empty>}{page === 'revision' && <div className="revision-legend"><span><CalendarDays size={17} />Scheduled from recall</span><span><CheckCircle2 size={17} />Confidence-aware</span><span><Sparkles size={17} />Alternative angles first</span></div>}<DownloadLink /></>;
}
