# build_curriculum/group5_s15.py
# S15: World History & Major Revolutions (9 topics across 3 chapters)

DATA = {}

# S15-Cc19ffbe1 Classical Civilizations: Mesopotamia, Egypt, Greece & Rome (3 topics)
DATA["S15-Cc19ffbe1"] = [
    {
        "name_en": "Cradle of Civilization: Mesopotamia (Sumer, Babylon, Code of Hammurabi) & Nile Valley Civilization of Egypt",
        "name_hi": "सभ्यता का पालना: मेसोपोटामिया (सुमेर, बेबीलोन, हम्मुराबी की विधि संहिता) एवं मिस्र की नील नदी सभ्यता",
        "concepts_en": ["Mesopotamia ('Land between rivers'): Tigris and Euphrates rivers (modern-day Iraq); Sumerians invented Cuneiform script (wedge-shaped on clay tablets), wheel, sexagesimal base-60 number system (dividing hour into 60 mins and circle into 360°), and stepped temple towers (Ziggurats)", "Code of Hammurabi (Babylon, ~1750 BCE): One of the oldest deciphered legal codes, engraved on black diorite stele; famous principle of retributive justice 'Lex Talionis' ('An eye for an eye, a tooth for a tooth')", "Ancient Egypt ('Gift of the Nile' - Herodotus): Hieroglyphic script deciphered using Rosetta Stone (1799 by Champollion); Old Kingdom / Age of Pyramids (Great Pyramid of Giza for Pharaoh Khufu/Cheops, ~2560 BCE); mummification and belief in afterlife (Book of the Dead, Osiris, Anubis)"],
        "concepts_hi": ["मेसोपोटामिया (दजला और फरात नदियों के बीच की भूमि / आधुनिक इराक): सुमेरियन सभ्यता ने 'कीलाक्षर' (क्यूनीफॉर्म) लिपि, पहिया, 60-आधारित षटदशमलव संख्या प्रणाली (घंटे में 60 मिनट और वृत्त में 360°) और सीढ़ीदार मंदिर मीनारें 'जिगुरात' (Ziggurats) बनाईं", "हम्मुराबी की विधि संहिता (बेबीलोन, ~1750 ईसा पूर्व): काले डायराइट पत्थर पर उत्कीर्ण विश्व की प्राचीनतम कानून संहिता; प्रतिशोध का प्रसिद्ध नियम 'आंख के बदले आंख और दांत के बदले दांत' (Lex Talionis)", "प्राचीन मिस्र ('नील नदी का वरदान' - हेरोडोटस): चित्रलिपि (हाइरोग्लिफिक्स), जिसे रोसेटा स्टोन से पढ़ा गया; गीज़ा के विशाल पिरामिड (फराओ खूफू / चेओप्स का पिरामिड); ममीकरण एवं परलोक में विश्वास (मृतकों की पुस्तक / Book of the Dead)"],
        "q_en": "Which ancient Babylonian legal code, engraved on a towering black diorite stele around 1750 BCE, is world-famous for codifying the retributive justice principle of 'An eye for an eye, a tooth for a tooth'?",
        "q_hi": "लगभग 1750 ईसा पूर्व में काले पत्थर के खंभे पर उत्कीर्ण वह कौन सी प्राचीन बेबीलोनियन विधि संहिता है, जो 'आंख के बदले आंख और दांत के बदले दांत' के प्रतिशोध न्याय सिद्धांत को संहिताबद्ध करने हेतु विश्व प्रसिद्ध है?",
        "options_en": ["Code of Hammurabi (हम्मुराबी की विधि संहिता)", "Twelve Tables of Rome", "Edicts of Ashoka", "Justinian Code"],
        "options_hi": ["हम्मुराबी की विधि संहिता (Code of Hammurabi)", "रोम की बारह पट्टिकाएं (Twelve Tables)", "अशोक के शिलालेख", "जस्टिनियन की विधि संहिता"],
        "correct_idx": 0,
        "exp_en": "The Code of Hammurabi, promulgated by King Hammurabi of Babylon, comprises 282 legal laws dealing with property, commerce, and severe penalties based on exact retribution (Lex Talionis).",
        "exp_hi": "बेबीलोन के राजा हम्मुराबी की संहिता विश्व की सबसे प्राचीन लिखित कानूनी संहिताओं में से एक है, जिसमें 282 धाराएं हैं और 'जैसे को तैसा' (आंख के बदले आंख) का कठोर दंड सिद्धांत लागू किया गया था।",
        "cue_en": "Eye for an eye legal code = Code of Hammurabi (Babylon, 1750 BCE).",
        "cue_hi": "आंख के बदले आंख = हम्मुराबी की विधि संहिता (बेबीलोन)।",
        "wrong_en": ["Ancient Babylonian legal code of retribution.", "Early foundational Roman legal code.", "Moral and administrative pillars of Emperor Ashoka.", "Byzantine legal codification by Emperor Justinian."],
        "wrong_hi": ["बेबीलोन की प्राचीन संहिता।", "रोम की प्राचीन विधि।", "सम्राट अशोक के नैतिक लेख।", "बाइजेंटाइन साम्राज्य की संहिता।"]
    },
    {
        "name_en": "Classical Greece: Athenian Democracy (Pericles), Spartan Oligarchy & The Persian/Peloponnesian Wars",
        "name_hi": "शास्त्रीय यूनान (ग्रीस): एथेंस का प्रत्यक्ष लोकतंत्र (पेरिक्लीस), स्पार्टा का सैन्य तंत्र एवं पेलोपोनेसियन युद्ध",
        "concepts_en": ["Greek Polis (City-States): Athens (Cradle of Democracy, philosophy, maritime trade) vs Sparta (Militaristic oligarchy, Helot serfs, Agoge warrior training)", "Athenian Direct Democracy: Golden Age of Athens under Pericles (5th century BCE); Parthenon temple atop Acropolis; citizen assembly (Ecclesia), ostracism", "Greco-Persian Wars (499-449 BCE): Persian Empire under Darius I and Xerxes invaded Greece; Battle of Marathon (490 BCE, Greek victory, runner Pheidippides), Battle of Thermopylae (480 BCE, heroic stand of King Leonidas and 300 Spartans), Battle of Salamis (naval victory led by Themistocles)", "Peloponnesian War (431-404 BCE): Civil conflict between Delian League (Athens) and Peloponnesian League (Sparta), ending in Athenian defeat and Spartan hegemony; chronicled by Thucydides"],
        "concepts_hi": ["यूनानी नगर-राज्य (Polis): एथेंस (प्रत्यक्ष लोकतंत्र, दर्शन व व्यापार का केंद्र) बनाम स्पार्टा (कठोर सैन्य तानाशाही व योद्धा संस्कृति)", "एथेंस का प्रत्यक्ष लोकतंत्र: पेरिक्लीस के अधीन एथेंस का 'स्वर्ण युग' (5वीं सदी ई.पू.); एक्रोपोलिस पर पार्थेनन मंदिर; नागरिक सभा (एक्लेसिया)", "यूनान-फारस युद्ध (499-449 ई.पू.): डेरियस व ज़ेरक्सेस के फारसी आक्रमण; मैराथन का युद्ध (490 ई.पू. - यूनानी विजय), थर्मोपाइली का युद्ध (480 ई.पू. - राजा लियोनिडास और 300 स्पार्टन जांबाज), सलामिस की नौसैनिक लड़ाई", "पेलोपोनेसियन युद्ध (431-404 ई.पू.): एथेंस के डेलियन संघ और स्पार्टा के पेलोपोनेसियन संघ के बीच विनाशकारी गृहयुद्ध, जिसमें एथेंस की पराजय हुई; इतिहासकार थ्यूसीडाइड्स द्वारा लिखित"],
        "q_en": "In 480 BCE, King Leonidas and his heroic band of 300 Spartan warriors made their immortal last stand against the colossal invading Persian army of Emperor Xerxes at which narrow mountain pass?",
        "q_hi": "480 ईसा पूर्व में फारसी सम्राट ज़ेरक्सेस की विशाल सेना के विरुद्ध राजा लियोनिडास और उनके 300 स्पार्टन योद्धाओं ने किस संकरे पहाड़ी दर्रे पर अपनी ऐतिहासिक अंतिम लड़ाई (Last Stand) लड़ी थी?",
        "options_en": ["Battle of Thermopylae (थर्मोपाइली का दर्रा)", "Battle of Marathon", "Battle of Salamis", "Battle of Chaeronea"],
        "options_hi": ["थर्मोपाइली का दर्रा (Pass of Thermopylae - 480 ई.पू.)", "मैराथन का मैदान (Battle of Marathon - 490 ई.पू.)", "सलामिस का जलडमरूमध्य (Battle of Salamis - नौसैनिक युद्ध)", "चेरोनिया का मैदान"],
        "correct_idx": 0,
        "exp_en": "At the Battle of Thermopylae in 480 BCE, King Leonidas I led 300 elite Spartan hoplites and allied Greek forces to block the narrow coastal pass of Thermopylae against hundreds of thousands of Persians for three days.",
        "exp_hi": "थर्मोपाइली के संकरे दर्रे में स्पार्टा के राजा लियोनिडास और उनके 300 वीर सैनिकों ने फारस के विशाल लश्कर को कई दिनों तक रोके रखा था; अंततः धोखेबाज द्वारा गुप्त रास्ता बताने पर वे सभी मातृभूमि हेतु बलिदान हो गए।",
        "cue_en": "300 Spartans last stand = Pass of Thermopylae (480 BCE).",
        "cue_hi": "300 स्पार्टन योद्धा = थर्मोपाइली का दर्रा (480 ई.पू.)।",
        "wrong_en": ["Pass of Spartan heroic defense (480 BCE).", "Plain where Athenians routed Persians (490 BCE).", "Naval sea battle won by Greeks (480 BCE).", "Philip of Macedon victory over Greece (338 BCE)."],
        "wrong_hi": ["थर्मोपाइली का ऐतिहासिक दर्रा।", "मैराथन का युद्ध।", "सलामिस की नौसैनिक विजय।", "मैसेडोनिया की विजय।"]
    },
    {
        "name_en": "Roman Republic to Empire: Julius Caesar, Pax Romana under Augustus & Fall of Western Rome (476 CE)",
        "name_hi": "रोमन गणराज्य से साम्राज्य: जूलियस सीजर, ऑगस्टस के अधीन पैक्स रोमाना एवं पश्चिमी रोम का पतन (476 ई.)",
        "concepts_en": ["Roman Republic (509 BCE): Governed by Senate and two annually elected Consuls; struggle between aristocratic Patricians and commoner Plebeians (Tribunes, Twelve Tables)", "Fall of Republic: First Triumvirate (Julius Caesar, Pompey, Crassus); Caesar crossed the Rubicon river in 49 BCE ('Alea iacta est' - the die is cast), appointed Dictator perpetuo; assassinated on the Ides of March (March 15, 44 BCE) by Brutus and Cassius in Senate", "Roman Empire (27 BCE): Octavian defeated Mark Antony and Cleopatra at Battle of Actium (31 BCE), assumed title 'Augustus' in 27 BCE becoming first Roman Emperor; ushered in Pax Romana (200 years of Roman peace and prosperity)", "Engineering Marvels: Colosseum, Pantheon (concrete dome), Aqueducts, Roman Roads, Hadrian's Wall", "Division and Fall: Emperor Diocletian split empire into Western and Eastern (Byzantine) in 286 CE; Western Roman Empire fell in 476 CE when Germanic chieftain Odoacer deposed the last emperor Romulus Augustulus; Eastern Byzantine Empire endured until 1453 (Ottoman conquest of Constantinople)"],
        "concepts_hi": ["रोमन गणराज्य (509 ई.पू.): सीनेट (Senate) और दो निर्वाचित कांसुलों द्वारा शासित; कुलीन पेट्रिशियन और आम प्लेबियन वर्ग", "गणराज्य का अंत: जूलियस सीजर ने 49 ई.पू. में रूबिकॉन नदी पार कर गृहयुद्ध जीता ('पासा फेंका जा चुका है'); आजीवन तानाशाह बने; सीनेट में 'आइड्स ऑफ मार्च' (15 मार्च 44 ई.पू.) को ब्रूटस और साथियों द्वारा सीजर की हत्या", "रोमन साम्राज्य (27 ई.पू.): ऑक्टेवियन ने एक्टियम की लड़ाई (31 ई.पू.) में एंटनी व क्लियोपेट्रा को हराया और 'ऑगस्टस' की उपाधि लेकर रोम के पहले सम्राट बने; 'पैक्स रोमाना' (200 वर्षों की रोमन शांति व समृद्धि का काल)", "रोमन स्थापत्य: कोलोसियम, पैंथियन, जलसेतु (एक्वाडक्ट्स) और कंक्रीट तकनीक", "रोम का पतन: डायोक्लेशियन ने साम्राज्य को पश्चिमी और पूर्वी (बाइजेंटाइन) में बांटा; 476 ईस्वी में जर्मनिक आक्रांता ओडोएकर द्वारा अंतिम पश्चिमी सम्राट रोमुलस ऑगस्टुलस को अपदस्थ करने के साथ पश्चिमी रोमन साम्राज्य का पतन हो गया (मध्यकाल की शुरुआत)"],
        "q_en": "Who became the historic FIRST Emperor of the Roman Empire in 27 BCE, ending centuries of the Roman Republic and establishing the two-century era of 'Pax Romana'?",
        "q_hi": "27 ईसा पूर्व में सदियों पुराने गणराज्य का अंत कर तथा दो शताब्दियों के 'पैक्स रोमाना' (रोमन शांति युग) की स्थापना कर रोमन साम्राज्य के पहले सम्राट (First Roman Emperor) कौन बने?",
        "options_en": ["Caesar Augustus / Octavian (सीजर ऑगस्टस / ऑक्टेवियन)", "Julius Caesar", "Nero", "Marcus Aurelius"],
        "options_hi": ["सीजर ऑगस्टस / ऑक्टेवियन (Caesar Augustus / Octavian)", "जूलियस सीजर (Julius Caesar - यह तानाशाह थे, पहले सम्राट नहीं)", "नीरो (Nero)", "मार्कस ऑरेलियस (दार्शनिक सम्राट)"],
        "correct_idx": 0,
        "exp_en": "Octavian, the adopted grand-nephew and heir of Julius Caesar, was granted the honorific title 'Augustus' by the Roman Senate in 27 BCE, establishing the Principate as Rome's first emperor.",
        "exp_hi": "जूलियस सीजर के दत्तक पुत्र ऑक्टेवियन ने 27 ईसा पूर्व में 'ऑगस्टस' की उपाधि धारण कर रोमन साम्राज्य की स्थापना की और वे रोम के पहले आधिकारिक सम्राट बने।",
        "cue_en": "First Roman Emperor = Augustus (Octavian, 27 BCE).",
        "cue_hi": "पहला रोमन सम्राट = ऑगस्टस (27 ई.पू.)।",
        "wrong_en": ["First Roman Emperor in 27 BCE.", "Dictator of Republic assassinated in 44 BCE.", "Infamous fifth emperor.", "Last of the Five Good Emperors."],
        "wrong_hi": ["रोमन साम्राज्य के प्रथम सम्राट।", "गणराज्य के तानाशाह (हत्या 44 ई.पू.)।", "कुख्यात रोमन सम्राट।", "दार्शनिक सम्राट।"]
    }
]

# S15-C4a2b9352 Renaissance, Enlightenment, American & French Revolutions (4 topics)
DATA["S15-C4a2b9352"] = [
    {
        "name_en": "The Italian Renaissance: Humanism, Medici Patronage, Leonardo da Vinci & Michelangelo",
        "name_hi": "इतालवी पुनर्जागरण (Renaissance): मानवतावाद, मेदिची संरक्षण, लियोनार्डो दा विंची एवं माइकलएंजेलो",
        "concepts_en": ["Renaissance ('Rebirth'): Cultural, artistic, and intellectual movement beginning in Florence, Italy in the 14th century, fueled by wealthy banking patrons like the Medici family (Lorenzo the Magnificent) and the influx of Greek scholars fleeing the Fall of Constantinople (1453)", "Humanism: Petrarch ('Father of Humanism') championed human agency, individual intellect, and study of classical Latin/Greek humanities over medieval scholastic dogma", "Movable Type Printing Press: Invented by Johannes Gutenberg in Mainz, Germany (~1440); printed Gutenberg Bible in 1455, democratizing knowledge and accelerating the spread of Renaissance and Reformation", "Polymaths: Leonardo da Vinci ('Renaissance Man': Mona Lisa / La Gioconda, The Last Supper, Vitruvian Man); Michelangelo (Sistine Chapel ceiling frescoes, David sculpture, Pieta, St. Peter's Basilica dome); Raphael (The School of Athens); Niccolò Machiavelli ('The Prince' - political realism)"],
        "concepts_hi": ["पुनर्जागरण (Renaissance / नवजागरण): 14वीं सदी में फ्लोरेंस (इटली) से प्रारंभ हुआ सांस्कृतिक, कलात्मक व बौद्धिक आंदोलन; मेदिची परिवार का वित्तीय संरक्षण और 1453 में कुस्तुंतुनिया के पतन के बाद ग्रीक विद्वानों का इटली पलायन", "मानवतावाद (Humanism): पेट्रार्क ('मानवतावाद के जनक'); मध्यकालीन चर्च की रूढ़ियों के स्थान पर मानव गरिमा, तर्क और जीवन की स्वतंत्रता पर बल", "छापाखाना (Printing Press): जोहान्स गुटेनबर्ग द्वारा जर्मनी में 1440 के आसपास आविष्कार; 1455 में पहली मुद्रित गुटेनबर्ग बाइबिल, जिसने पूरे यूरोप में ज्ञान क्रांति ला दी", "पुनर्जागरण के महानायक: लियोनार्डो दा विंची ('द लास्ट सपर', 'मोनालिसा', विट्रुवियन मैन); माइकलएंजेलो (सिस्टिन चैपल की छत पर भित्ति चित्र, डेविड की मूर्ति, पिएटा); राफेल ('द स्कूल ऑफ एथेंस'); मैकियावेली ('द प्रिंस' - आधुनिक राजनीति विज्ञान के जनक)"],
        "q_en": "Whose groundbreaking invention of the movable metal type mechanical printing press in Mainz, Germany around 1440 democratized literacy and ignited the European Renaissance and Scientific Revolution?",
        "q_hi": "1440 के आसपास जर्मनी के मेंज नगर में धातु के मूवेबल टाइप वाले यांत्रिक 'प्रिंटिंग प्रेस' (छापाखाना) का आविष्कार कर यूरोप में ज्ञान क्रांति की शुरुआत करने वाले आविष्कारक कौन थे?",
        "options_en": ["Johannes Gutenberg (जोहान्स गुटेनबर्ग)", "Petrarch", "Desiderius Erasmus", "Aldus Manutius"],
        "options_hi": ["जोहान्स गुटेनबर्ग (Johannes Gutenberg)", "पेट्रार्क (मानवतावाद के जनक)", "इरास्मस", "एल्डस मानुटियस"],
        "correct_idx": 0,
        "exp_en": "Johannes Gutenberg invented the movable type printing press in Germany around 1440, printing the 42-line Gutenberg Bible around 1455 and dramatically reducing the cost of books, sparking mass literacy across Europe.",
        "exp_hi": "जोहान्स गुटेनबर्ग ने 1440 के दशक में मूवेबल टाइप प्रिंटिंग प्रेस का आविष्कार किया और 1455 में गुटेनबर्ग बाइबिल छापी; इससे पहले पांडुलिपियां हाथ से लिखी जाती थीं।",
        "cue_en": "Inventor of movable type printing press = Johannes Gutenberg (c. 1440).",
        "cue_hi": "प्रिंटिंग प्रेस के आविष्कारक = जोहान्स गुटेनबर्ग (1440)।",
        "wrong_en": ["Pioneered movable type printing press.", "Father of Renaissance Humanism.", "Christian humanist scholar (In Praise of Folly).", "Venetian publisher who invented italic type."],
        "wrong_hi": ["छापाखाने के आविष्कारक।", "मानवतावाद के जनक।", "ईसाई मानवतावादी।", "इटैलिक टाइप आविष्कारक।"]
    },
    {
        "name_en": "The European Enlightenment: Voltaire, Rousseau, Montesquieu & Social Contract Theory",
        "name_hi": "यूरोपीय प्रबोधन युग (Enlightenment): वॉल्टेयर, रूसो (सामाजिक समझौता), मोंटेस्क्यू एवं तर्कवाद",
        "concepts_en": ["Age of Enlightenment (17th-18th century, 'Age of Reason'): Intellectual movement championing reason, empirical science, individual liberty, religious tolerance, and constitutional democracy over superstition, religious fanaticism, and absolute monarchical tyranny", "Core Philosophers:", "1. John Locke (Two Treatises of Government): Formulated Inalienable Natural Rights of 'Life, Liberty, and Property'; Tabula Rasa (blank slate mind); right of revolution if government breaches public trust", "2. Jean-Jacques Rousseau: Wrote 'The Social Contract' (1762) with famous opening: 'Man is born free, and everywhere he is in chains'; championed the General Will (Volonté Générale) and direct popular sovereignty", "3. Baron de Montesquieu: Wrote 'The Spirit of the Laws' (1748), articulating the foundational doctrine of SEPARATION OF POWERS into Executive, Legislative, and Judicial branches to prevent tyranny", "4. Voltaire (François-Marie Arouet): Crusader for freedom of speech, freedom of religion, and separation of church and state"],
        "concepts_hi": ["प्रबोधन युग / ज्ञानोदय (Enlightenment - 17वीं-18वीं सदी): विवेक, तर्क, व्यक्तिगत स्वतंत्रता, धार्मिक सहिष्णुता और लोकतंत्र का युग; चर्च के अंधविश्वासों और राजाओं के निरंकुश दैवी अधिकारों का जोरदार खंडन", "प्रमुख प्रबोधनकालीन दार्शनिक:", "1. जॉन लॉक: 'प्राकृतिक अधिकारों' (जीवन, स्वतंत्रता व संपत्ति का अधिकार) के प्रतिपादक; सरकार जनता की सहमति पर आधारित एक ट्रस्ट है", "2. ज्यां-ज्याक रूसो: अमर कृति 'द सोशल कॉन्ट्रैक्ट' (1762 - सामाजिक समझौता); प्रसिद्ध कथन: 'मनुष्य स्वतंत्र पैदा हुआ है, लेकिन वह सर्वत्र जंजीरों में जकड़ा हुआ है'; 'सामान्य इच्छा' (General Will) और लोकप्रिय संप्रभुता के प्रणेता", "3. मोंटेस्क्यू: पुस्तक 'द स्पिरिट ऑफ द लॉज' (1748); तानाशाही रोकने हेतु सरकार के तीनों अंगों (कार्यपालिका, विधायिका व न्यायपालिका) के बीच 'शक्ति पृथक्करण' (Separation of Powers) का सिद्धांत दिया", "4. वॉल्टेयर: अभिव्यक्ति की स्वतंत्रता और धर्मनिरपेक्षता के प्रखर समर्थक"],
        "q_en": "Which French Enlightenment philosopher formulated the doctrine of 'Separation of Powers' among the Executive, Legislative, and Judiciary in his monumental 1748 treatise 'The Spirit of the Laws'?",
        "q_hi": "किस फ्रांसीसी प्रबोधनकालीन दार्शनिक ने 1748 में प्रकाशित अपनी प्रसिद्ध पुस्तक 'द स्पिरिट ऑफ द लॉज' (The Spirit of the Laws) में शासन को निरंकुश होने से बचाने हेतु 'शक्ति पृथक्करण' (Separation of Powers) का सिद्धांत प्रतिपादित किया था?",
        "options_en": ["Baron de Montesquieu (मोंटेस्क्यू)", "Jean-Jacques Rousseau", "Voltaire", "Denis Diderot"],
        "options_hi": ["मोंटेस्क्यू (Baron de Montesquieu)", "रूसो (Jean-Jacques Rousseau - सामाजिक समझौता सिद्धांत)", "वॉल्टेयर (Voltaire - विचार व वाणी की स्वतंत्रता)", "डेनिस डिडरो (विश्वकोश / Encyclopedia के संपादक)"],
        "correct_idx": 0,
        "exp_en": "Montesquieu formulated the doctrine of the Separation of Powers in 'The Spirit of the Laws' (1748), which profoundly inspired the Framers of the United States Constitution and modern democratic systems worldwide.",
        "exp_hi": "मोंटेस्क्यू ने अपनी पुस्तक में बताया कि यदि कानून बनाने, लागू करने और न्याय करने की शक्ति एक ही व्यक्ति के हाथ में आ जाए तो स्वतंत्रता समाप्त हो जाती है; अतः कार्यपालिका, विधायिका और न्यायपालिका को अलग-अलग होना चाहिए।",
        "cue_en": "Separation of Powers = Montesquieu (The Spirit of the Laws, 1748).",
        "cue_hi": "शक्ति पृथक्करण = मोंटेस्क्यू (द स्पिरिट ऑफ द लॉज)।",
        "wrong_en": ["Formulated Separation of Powers doctrine.", "Formulated the Social Contract and General Will.", "Champion of free expression and religious tolerance.", "Chief editor of the Encyclopédie."],
        "wrong_hi": ["शक्ति पृथक्करण के सिद्धांतकार।", "सामाजिक समझौते के प्रणेता।", "अभिव्यक्ति स्वतंत्रता के समर्थक।", "विश्वकोश के मुख्य संपादक।"]
    },
    {
        "name_en": "American Revolution (1775-1783): Boston Tea Party, Declaration of Independence & George Washington",
        "name_hi": "अमेरिकी क्रांति (1775-1783): बोस्टन टी पार्टी, स्वतंत्रता का घोषणापत्र (4 जुलाई 1776) एवं जॉर्ज वॉशिंगटन",
        "concepts_en": ["Causes of American Revolution: British mercantile taxation without colonial representation in Parliament ('No Taxation Without Representation' - Stamp Act 1765, Townshend Acts)", "Boston Tea Party (December 16, 1773): Sons of Liberty disguised as Mohawk Native Americans boarded British East India Company ships in Boston Harbor and dumped 342 chests of tea into the water protesting the Tea Act", "Declaration of Independence (Adopted July 4, 1776, Philadelphia): Drafted primarily by Thomas Jefferson; declared that 'all men are created equal' endowed with unalienable rights to 'Life, Liberty and the pursuit of Happiness'", "War of Independence: George Washington commanded the Continental Army; decisive American victory at Siege of Yorktown (1781) with French naval support under General Lafayette", "Treaty of Paris (1783): Great Britain formally recognized the sovereign independence of the United States of America"],
        "concepts_hi": ["अमेरिकी क्रांति के कारण: ब्रिटिश संसद में उपनिवेशों का कोई प्रतिनिधि न होने के बावजूद उन पर नए कर लगाना ('बिना प्रतिनिधित्व कोई कराधान नहीं' - स्टाम्प एक्ट)", "बोस्टन टी पार्टी (16 दिसंबर 1773): अमेरिकी देशभक्तों (संस ऑफ लिबर्टी) ने बोस्टन बंदरगाह पर ईस्ट इंडिया कंपनी के जहाजों पर चढ़कर चाय की 342 पेटियां समुद्र में फेंक दीं, जो क्रांति का तात्कालिक चिंगारी बनी", "अमेरिकी स्वतंत्रता की घोषणा (4 जुलाई 1776, फिलाडेल्फिया): मुख्य रूप से थॉमस जेफरसन द्वारा लिखित; घोषित किया कि 'सभी मनुष्य समान बनाए गए हैं और उन्हें जीवन, स्वतंत्रता और सुख की खोज का अविभाज्य अधिकार प्राप्त है'", "स्वतंत्रता संग्राम: जॉर्ज वॉशिंगटन ने कॉन्टिनेंटल सेना का नेतृत्व किया; यॉर्कटाउन की लड़ाई (1781) में अंग्रेजों की अंतिम पराजय", "पेरिस की संधि (1783): ब्रिटेन ने संयुक्त राज्य अमेरिका (USA) की स्वतंत्रता को औपचारिक मान्यता दी"],
        "q_en": "Who served as the primary author and draftsman of the historic United States Declaration of Independence, adopted in Philadelphia on July 4, 1776?",
        "q_hi": "फिलाडेल्फिया में 4 जुलाई 1776 को अंगीकृत किए गए संयुक्त राज्य अमेरिका के ऐतिहासिक 'स्वतंत्रता के घोषणापत्र' (Declaration of Independence) के मुख्य लेखक और प्रारूपकार कौन थे?",
        "options_en": ["Thomas Jefferson (थॉमस जेफरसन)", "George Washington", "Benjamin Franklin", "John Adams"],
        "options_hi": ["थॉमस जेफरसन (Thomas Jefferson)", "जॉर्ज वॉशिंगटन (George Washington - सेनापति व प्रथम राष्ट्रपति)", "बेंजामिन फ्रैंकलिन (दार्शनिक व सह-प्रारूपकार)", "जॉन एडम्स"],
        "correct_idx": 0,
        "exp_en": "Thomas Jefferson was chosen by the Committee of Five to pen the original draft of the Declaration of Independence, enshrining the Enlightenment philosophy of inalienable rights.",
        "exp_hi": "थॉमस जेफरसन ने अमेरिकी स्वतंत्रता की घोषणा का मूल पाठ लिखा था, जिसमें उन्होंने जॉन लॉक के दर्शन से प्रेरणा लेकर जीवन, स्वतंत्रता और सुख की खोज के अधिकारों को अमर बना दिया।",
        "cue_en": "Author of US Declaration of Independence = Thomas Jefferson (July 4, 1776).",
        "cue_hi": "अमेरिकी स्वतंत्रता घोषणापत्र के लेखक = थॉमस जेफरसन (4 जुलाई 1776)।",
        "wrong_en": ["Principal author of Declaration of Independence.", "Commander-in-Chief and first US President.", "Senior statesman and co-draftsman.", "Advocate of independence and second US President."],
        "wrong_hi": ["घोषणापत्र के मुख्य लेखक।", "सेनापति व प्रथम राष्ट्रपति।", "वरिष्ठ राजनेता व सह-लेखक।", "दूसरे राष्ट्रपति।"]
    },
    {
        "name_en": "French Revolution (1789): Storming of the Bastille, Declaration of the Rights of Man & Reign of Terror",
        "name_hi": "फ्रांसीसी क्रांति (1789): बास्तील का पतन (14 जुलाई), मानव एवं नागरिक अधिकारों की घोषणा तथा आतंक का राज",
        "concepts_en": ["Ancien Régime Society: Divided into Three Estates - First Estate (Clergy - tax exempt), Second Estate (Nobility - tax exempt), and Third Estate (Commoners, peasants, bourgeoisie - paid all taxes; King Louis XVI and Queen Marie Antoinette)", "Storming of the Bastille (July 14, 1789): Parisian mob stormed the medieval royal fortress and prison of the Bastille, seizing gunpowder; commemorated as France's National Day (Bastille Day); symbolized the fall of monarchical autocracy", "Declaration of the Rights of Man and of the Citizen (August 1789): Proclaimed foundational motto: 'Liberté, Égalité, Fraternité' (Liberty, Equality, Fraternity - later incorporated into the Preamble of the Indian Constitution)", "Reign of Terror (1793-1794): Radical Jacobin dictator Maximilien Robespierre used the Committee of Public Safety and the Guillotine to execute over 16,000 'enemies of the revolution' (including King Louis XVI and Queen Marie Antoinette); ended with the Thermidorian Reaction and execution of Robespierre", "Rise of Napoleon Bonaparte: Coup of 18 Brumaire (1799) established the Consulate, followed by his coronation as Emperor in 1804 (Napoleonic Code)"],
        "concepts_hi": ["पुरातन व्यवस्था (Ancien Régime): तीन स्टेट्स में बंटा समाज - प्रथम स्टेट (पादरी - कर मुक्त), द्वितीय स्टेट (कुलीन - कर मुक्त) और तृतीय स्टेट (किसान, मजदूर, मध्यम वर्ग - सभी करों का बोझ इन्हीं पर; राजा लुई 16वां और रानी मेरी अंतोनेत)", "बास्तील के दुर्ग का पतन (14 जुलाई 1789): पेरिस की विद्रोही जनता ने निरंकुश राजशाही के प्रतीक बास्तील के किले पर धावा बोलकर हथियार छीन लिए और कैदियों को मुक्त कराया; यह दिन फ्रांस का 'राष्ट्रीय दिवस' (बास्तील दिवस) कहलाता है", "मानव एवं नागरिक अधिकारों की घोषणा (1789): अमर नारा दिया: 'स्वतंत्रता, समानता, बंधुत्व' (Liberty, Equality, Fraternity - जिसे बाद में भारतीय संविधान की प्रस्तावना में अपनाया गया)", "आतंक का राज (1793-1794): जैकोबिन नेता मैक्सिमिलियन रोबेस्पियर ने 'गिलोटिन' (Guillotine) द्वारा लुई 16वें, रानी मेरी अंतोनेत सहित 16,000 से अधिक लोगों का सिर कलम करवाया; रोबेस्पियर के निष्पादन के साथ समाप्त हुआ", "नेपोलियन बोनापार्ट का उदय: 1799 में तख्तापलट और 1804 में फ्रांस का सम्राट बनना (नेपोलियन कोड)"],
        "q_en": "On which historic date did the revolutionary citizens of Paris storm the medieval fortress-prison of the Bastille, marking the flashpoint of the French Revolution celebrated annually as France's National Day?",
        "q_hi": "पेरिस की क्रांतिकारी जनता ने किस ऐतिहासिक तारीख को निरंकुश राजशाही के प्रतीक बास्तील के किले (दुर्ग) पर धावा बोलकर उसे ध्वस्त कर दिया, जिसे फ्रांसीसी क्रांति का प्रस्थान बिंदु और फ्रांस का राष्ट्रीय दिवस माना जाता है?",
        "options_en": ["July 14, 1789 (14 जुलाई 1789 - बास्तील दिवस)", "August 4, 1789", "September 21, 1792", "May 5, 1789"],
        "options_hi": ["14 जुलाई 1789 (July 14, 1789 - बास्तील दिवस)", "4 अगस्त 1789 (सामंतवाद समाप्ति की घोषणा)", "21 सितंबर 1792 (फ्रांसीसी गणराज्य की स्थापना)", "5 मई 1789 (स्टेट्स जनरल की बैठक)"],
        "correct_idx": 0,
        "exp_en": "The Storming of the Bastille occurred on the afternoon of July 14, 1789, igniting the French Revolution and becoming France's principal national holiday (Bastille Day).",
        "exp_hi": "14 जुलाई 1789 को पेरिस की जनता ने बास्तील के किले को तोड़कर राजशाही की निरंकुशता को चुनौती दी थी; इसी दिन की याद में हर साल 14 जुलाई को फ्रांस में बास्तील दिवस मनाया जाता है।",
        "cue_en": "Storming of the Bastille = July 14, 1789 (French National Day).",
        "cue_hi": "बास्तील का पतन = 14 जुलाई 1789 (फ्रांसीसी राष्ट्रीय दिवस)।",
        "wrong_en": ["Storming of the Bastille date.", "Abolition of feudalism in France.", "Proclamation of the First French Republic.", "Convocation of the Estates-General."],
        "wrong_hi": ["बास्तील पतन की ऐतिहासिक तिथि।", "सामंतवाद उन्मूलन।", "प्रथम गणराज्य घोषणा।", "स्टेट्स जनरल बैठक।"]
    }
]

# S15-C8922c19d World War I, Russian Revolution, World War II & Cold War (2 topics)
DATA["S15-C8922c19d"] = [
    {
        "name_en": "World War I (1914-1918), Treaty of Versailles & Russian Bolshevik Revolution (1917 - Lenin)",
        "name_hi": "प्रथम विश्व युद्ध (1914-1918), वर्साय की संधि एवं रूसी बोल्शेविक क्रांति (1917 - लेनिन)",
        "concepts_en": ["World War I (The Great War, 1914-1918): Triggered on June 28, 1914 by the assassination of Archduke Franz Ferdinand of Austria-Hungary in Sarajevo by Gavrilo Princip (Black Hand society); Allied Powers (Britain, France, Russia, Italy, USA from 1917) vs Central Powers (Germany, Austria-Hungary, Ottoman Empire, Bulgaria); Trench warfare, poison gas, tanks; ended by Armistice of November 11, 1918", "Treaty of Versailles (June 28, 1919): Imposed punitive terms on defeated Germany in Hall of Mirrors (Article 231 'War Guilt Clause', colossal reparations of 132 billion gold marks, loss of Alsace-Lorraine and Danzig corridor, demilitarization of Rhineland), planting the seeds for World War II; League of Nations established (Woodrow Wilson's 14 Points)", "Russian Revolution (1917): February Revolution overthrew Tsar Nicholas II (Romanov dynasty ends); October/Bolshevik Revolution (November 7, 1917) led by Vladimir Lenin and Leon Trotsky ('Peace, Land, and Bread') stormed the Winter Palace, establishing the world's first socialist state (USSR in 1922)"],
        "concepts_hi": ["प्रथम विश्व युद्ध (1914-1918): तात्कालिक कारण: 28 जून 1914 को साराजेवो में ऑस्ट्रिया के राजकुमार आर्कड्यूक फ्रांज फर्डिनेंड की हत्या (गैवरिलो प्रिंसिप द्वारा); मित्र राष्ट्र (ब्रिटेन, फ्रांस, रूस, 1917 से अमेरिका) बनाम केंद्रीय शक्तियां (जर्मनी, ऑस्ट्रिया-हंगरी, ऑटोमन साम्राज्य); खंदक युद्ध (ट्रेंच वॉरफेयर), जहरीली गैसें; 11 नवंबर 1918 को युद्धविराम", "वर्साय की संधि (28 जून 1919): पेरिस के शीशमहल में पराजित जर्मनी पर अपमानजनक व कठोर शर्तें थोपी गईं (अनुच्छेद 231 'युद्ध अपराध धारा', विशाल क्षतिपूर्ति, अल्सास-लोरेन की वापसी, राइनलैंड का विसैन्यीकरण), जिसने द्वितीय विश्व युद्ध और नाजीवाद के बीज बोए; राष्ट्र संघ (League of Nations) की स्थापना", "रूसी क्रांति (1917): फरवरी क्रांति ने जार निकोलस द्वितीय की निरंकुश सत्ता समाप्त की; अक्टूबर/बोल्शेविक क्रांति (7 नवंबर 1917) में व्लादिमीर लेनिन के नेतृत्व में बोल्शेविकों ने विंटर पैलेस पर कब्जा कर दुनिया के पहले साम्यवादी देश (सोवियत संघ / USSR, 1922) की नींव रखी"],
        "q_en": "Which punitive and controversial article of the 1919 Treaty of Versailles explicitly forced Germany to accept sole moral and legal responsibility for causing all loss and damage in World War I, known as the 'War Guilt Clause'?",
        "q_hi": "1919 की वर्साय की संधि का वह कौन सा विवादास्पद अनुच्छेद था, जिसे 'युद्ध अपराध धारा' (War Guilt Clause) कहा जाता है और जिसके तहत जर्मनी को प्रथम विश्व युद्ध के समस्त विनाश का एकमात्र दोषी ठहराया गया था?",
        "options_en": ["Article 231 (अनुच्छेद 231 - युद्ध अपराध धारा)", "Article 48", "Article 10", "Article 119"],
        "options_hi": ["अनुच्छेद 231 (Article 231 - War Guilt Clause)", "अनुच्छेद 48 (यह वाइमर संविधान का आपातकालीन अनुच्छेद था)", "अनुच्छेद 10 (राष्ट्र संघ सुरक्षा की धारा)", "अनुच्छेद 119 (उपनिवेश जब्ती धारा)"],
        "correct_idx": 0,
        "exp_en": "Article 231 of the Treaty of Versailles, commonly known as the 'War Guilt Clause', compelled Germany to accept full responsibility for causing the war, serving as the legal basis for massive financial reparations.",
        "exp_hi": "वर्साय की संधि का अनुच्छेद 231 'वॉर गिल्ट क्लॉज' कहलाता था; इसने जर्मनी पर युद्ध छेड़ने का पूरा दोष मढ़कर भारी हर्जाना थोपा, जिसने जर्मन जनता में गहरा असंतोष पैदा किया और हिटलर के उभार का मार्ग प्रशस्त किया।",
        "cue_en": "Treaty of Versailles War Guilt Clause = Article 231.",
        "cue_hi": "वर्साय की संधि का युद्ध अपराध अनुच्छेद = आर्टिकल 231।",
        "wrong_en": ["War Guilt Clause of Versailles.", "Emergency decree article in Weimar Constitution.", "Collective security clause of League of Nations.", "Clause stripping German overseas colonies."],
        "wrong_hi": ["युद्ध अपराध धारा (आर्टिकल 231)।", "वाइमर आपातकाल धारा।", "राष्ट्र संघ की धारा।", "उपनिवेश धारा।"]
    },
    {
        "name_en": "World War II (1939-1945), The Holocaust, Hiroshima/Nagasaki Atomic Bombings & Cold War Bipolarity",
        "name_hi": "द्वितीय विश्व युद्ध (1939-1945), होलोकॉस्ट, हिरोशिमा व नागासाकी परमाणु बम एवं शीत युद्ध (Cold War)",
        "concepts_en": ["World War II (1939-1945): Began on September 1, 1939 when Nazi Germany invaded Poland (Blitzkrieg tactics); Allied Powers (Great Britain under Churchill, USSR under Stalin, USA under Roosevelt/Truman, France) vs Axis Powers (Germany under Hitler, Italy under Mussolini, Japan under Emperor Hirohito/Tojo)", "Turning Points: Battle of Stalingrad (1942-1943, catastrophic defeat of German 6th Army by Red Army), Battle of Midway (1942, US Navy sinks 4 Japanese aircraft carriers), D-Day / Normandy Landings (June 6, 1944, Operation Overlord)", "The Holocaust (Shoah): Systematic state-sponsored genocide of 6 million European Jews and millions of others by Nazi regime in concentration/death camps (Auschwitz-Birkenau, Treblinka)", "Atomic Bombings (August 1945): Manhattan Project directed by J. Robert Oppenheimer; US B-29 bomber 'Enola Gay' dropped uranium bomb 'Little Boy' on Hiroshima (August 6, 1945); 'Bockscar' dropped plutonium bomb 'Fat Man' on Nagasaki (August 9, 1945); Japan surrendered on September 2, 1945 aboard USS Missouri", "Cold War (1947-1991): Bipolar ideological confrontation between USA (Capitalist West, NATO 1949) and USSR (Communist East, Warsaw Pact 1955); Cuban Missile Crisis (1962); Fall of Berlin Wall (November 9, 1989) and dissolution of USSR on December 26, 1991"],
        "concepts_hi": ["द्वितीय विश्व युद्ध (1939-1945): शुरुआत: 1 सितंबर 1939 को नाजी जर्मनी द्वारा पोलैंड पर 'ब्लिट्ज़क्रीग' (तड़ित युद्ध) आक्रमण; मित्र राष्ट्र (ब्रिटेन [चर्चिल], सोवियत संघ [स्टालिन], अमेरिका [रूजवेल्ट/ट्रूमैन], फ्रांस) बनाम धुरी राष्ट्र (जर्मनी [हिटलर], इटली [मुसोलिनी], जापान [हिरोहितो])", "प्रमुख निर्णायक मोड़: स्टालिनग्राद की लड़ाई (1942-43 - जर्मन सेना की सोवियत संघ के हाथों निर्णायक पराजय), मिडवे की लड़ाई (1942 - प्रशांत महासागर में अमेरिकी नौसेना की जीत), डी-डे / नॉर्मंडी लैंडिंग (6 जून 1944 - ऑपरेशन ओवरलॉर्ड)", "होलोकॉस्ट (नरसंहार): हिटलर के नाजी शासन द्वारा 60 लाख यहूदियों का यातना शिविरों (ऑशवित्ज़-बिरकेनाउ) में गैस चैंबरों द्वारा सामूहिक संहार", "परमाणु बम विस्फोट (अगस्त 1945 - मैनहट्टन प्रोजेक्ट): 6 अगस्त 1945 को हिरोशिमा पर 'लिटिल बॉय' (यूरेनियम बम) गिराया गया; 9 अगस्त 1945 को नागासाकी पर 'फैट मैन' (प्लूटोनियम बम) गिराया गया; 2 सितंबर 1945 को जापान के आत्मसमर्पण से युद्ध समाप्त", "शीत युद्ध (Cold War - 1947-1991): अमेरिका (पूंजीवादी खेमा, नाटो 1949) और सोवियत संघ (साम्यवादी खेमा, वारसॉ पैक्ट 1955) के बीच वैचारिक द्वंद्व; क्यूबा मिसाइल संकट (1962); 9 नवंबर 1989 को बर्लिन की दीवार का गिरना और 26 दिसंबर 1991 को सोवियत संघ के विघटन के साथ शीत युद्ध समाप्त"],
        "q_en": "On which Japanese city was the world's very FIRST combat atomic bomb, codenamed 'Little Boy' (a uranium-235 gun-type fission weapon), dropped by the US B-29 bomber 'Enola Gay' on August 6, 1945?",
        "q_hi": "6 अगस्त 1945 को अमेरिकी बी-29 बमवर्षक विमान 'एनोला गे' द्वारा इतिहास का पहला परमाणु बम 'लिटिल बॉय' (यूरेनियम बम) किस जापानी शहर पर गिराया गया था?",
        "options_en": ["Hiroshima (हिरोशिमा - 6 अगस्त 1945)", "Nagasaki", "Tokyo", "Kyoto"],
        "options_hi": ["हिरोशिमा (Hiroshima - 6 अगस्त 1945)", "नागासाकी (Nagasaki - इस पर 9 अगस्त 1945 को 'फैट मैन' गिराया गया था)", "टोक्यो", "क्योटो"],
        "correct_idx": 0,
        "exp_en": "On August 6, 1945, the US Army Air Forces dropped the first nuclear weapon 'Little Boy' on the city of Hiroshima, followed three days later by the plutonium bomb 'Fat Man' on Nagasaki on August 9, 1945.",
        "exp_hi": "6 अगस्त 1945 की सुबह 8:15 बजे हिरोशिमा शहर पर 'लिटिल बॉय' नामक पहला परमाणु बम गिराया गया था जिसमें तुरंत 80,000 से अधिक लोग मारे गए थे; इसके तीन दिन बाद 9 अगस्त को नागासाकी पर दूसरा बम गिराया गया।",
        "cue_en": "First atomic bomb (August 6, 1945) = Hiroshima (Little Boy).",
        "cue_hi": "पहला परमाणु बम (6 अगस्त 1945) = हिरोशिमा (लिटिल बॉय)।",
        "wrong_en": ["Target of first atomic bomb (August 6).", "Target of second atomic bomb (August 9).", "Capital city subjected to firebombing.", "Spared from bombing list due to cultural value."],
        "wrong_hi": ["पहले परमाणु बम का निशाना।", "दूसरे परमाणु बम का निशाना।", "राजधानी टोक्यो।", "सांस्कृतिक शहर क्योटो।"]
    }
]

print("Loaded S15 successfully")
