# build_curriculum/group1_s03_part2.py
# S03: Ancient Indian History (Chapters 3, 4, 5 - 18 topics)

DATA = {}

# S03-C4734d498 Buddhism, Jainism & Religious Movements (7 topics)
DATA["S03-C4734d498"] = [
    {
        "name_en": "Gautama Buddha: Life, Enlightenment, Four Noble Truths & Eightfold Path",
        "name_hi": "गौतम बुद्ध: जीवन, संबोधि, चार आर्य सत्य एवं अष्टांगिक मार्ग",
        "concepts_en": ["Siddhartha Gautama born in Lumbini (Shakya clan)", "Enlightenment (Nirvana) at Bodh Gaya under Bodhi tree", "Dhammacakkappavattana (First Sermon) at Sarnath", "Four Noble Truths & Ashtangika Marga (Middle Path)"],
        "concepts_hi": ["सिद्धार्थ गौतम का जन्म लुंबिनी में (शाक्य कुल)", "बोधगया में बोधि वृक्ष के नीचे ज्ञान (संबोधि) प्राप्ति", "सारनाथ में धर्मचक्रप्रवर्तन (प्रथम उपदेश)", "चार आर्य सत्य एवं अष्टांगिक मार्ग (मध्यम प्रतिपदा)"],
        "q_en": "Where did Gautama Buddha deliver his first sermon, known in Buddhist tradition as the 'Dhammacakkappavattana' (Turning of the Wheel of Law)?",
        "q_hi": "गौतम बुद्ध ने अपना पहला धर्मोपदेश, जिसे 'धर्मचक्रप्रवर्तन' कहा जाता है, किस स्थान पर दिया था?",
        "options_en": ["Sarnath (सारनाथ, डियर पार्क)", "Bodh Gaya", "Kushinagar", "Lumbini"],
        "options_hi": ["सारनाथ (Sarnath - मृगदाव)", "बोधगया", "कुशीनगर", "लुंबिनी"],
        "correct_idx": 0,
        "exp_en": "Buddha gave his first discourse to his five ascetic companions at the deer park in Rishipatana (modern Sarnath near Varanasi).",
        "exp_hi": "ज्ञान प्राप्ति के बाद बुद्ध ने अपना पहला उपदेश वाराणसी के निकट सारनाथ (ऋषिपत्तन मृगदाव) में पांच ब्राह्मण संन्यासियों को दिया था।",
        "cue_en": "First Sermon = Sarnath.",
        "cue_hi": "पहला उपदेश = सारनाथ।",
        "wrong_en": ["First sermon site.", "Site of enlightenment.", "Site of Mahaparinirvana (death).", "Site of birth."],
        "wrong_hi": ["प्रथम उपदेश का स्थल।", "ज्ञान प्राप्ति का स्थल।", "महापरिनिर्वाण का स्थल।", "जन्म स्थल।"]
    },
    {
        "name_en": "The Four Buddhist Councils: Patrons, Venues, Presiding Monks & Outcomes",
        "name_hi": "चार बौद्ध संगीतियां: संरक्षक, स्थल, अध्यक्ष एवं ऐतिहासिक परिणाम",
        "concepts_en": ["First Council: Rajgriha (Ajatashatru, Mahakassapa) - compiled Sutta & Vinaya", "Second Council: Vaishali (Kalasoka, Sabakami) - Mahasanghikas split", "Third Council: Pataliputra (Ashoka, Moggaliputta Tissa) - Abhidhamma added", "Fourth Council: Kundalvana, Kashmir (Kanishka, Vasumitra) - Mahayana & Hinayana split"],
        "concepts_hi": ["प्रथम संगीति: राजगृह (अजातशत्रु, महाकस्सप) - सुत्त व विनय पिटक का संकलन", "द्वितीय संगीति: वैशाली (कालाशोक, सबाकामी) - स्थाविर व महासांघिक विभाजन", "तृतीय संगीति: पाटलिपुत्र (अशोक, मोग्गलिपुत्त तिस्स) - अभिधम्म पिटक जोड़ा गया", "चतुर्थ संगीति: कुंडलवन, कश्मीर (कनिष्क, वसुमित्र) - हीनयान व महायान में विभाजन"],
        "q_en": "During whose reign was the Fourth Buddhist Council held in Kashmir, which formalized the theological division between Hinayana and Mahayana Buddhism?",
        "q_hi": "कश्मीर के कुंडलवन में चतुर्थ बौद्ध संगीति किसके शासनकाल में आयोजित की गई थी, जिसमें बौद्ध धर्म का हीनयान और महायान में विभाजन हुआ?",
        "options_en": ["Kanishka (कनिष्क - कुषाण सम्राट)", "Ashoka", "Ajatashatru", "Harshavardhana"],
        "options_hi": ["कनिष्क (Kanishka - Kushan Emperor)", "अशोक", "अजातशत्रु", "हर्षवर्धन"],
        "correct_idx": 0,
        "exp_en": "The Fourth Buddhist Council was convened under Kushan emperor Kanishka in Kundalvana, Kashmir, presided over by Vasumitra with Ashvaghosha as vice-president.",
        "exp_hi": "कुषाण राजा कनिष्क के समय कश्मीर के कुंडलवन में चौथी संगीति हुई। इसके अध्यक्ष वसुमित्र और उपाध्यक्ष अश्वघोष थे।",
        "cue_en": "Fourth Council = Kanishka in Kashmir.",
        "cue_hi": "चौथी संगीति = कनिष्क, कश्मीर (कुंडलवन)।",
        "wrong_en": ["Patron of 4th Council.", "Patron of 3rd Council at Pataliputra.", "Patron of 1st Council at Rajgriha.", "Convened Kannauj assembly."],
        "wrong_hi": ["चौथी संगीति का संरक्षक।", "पाटलिपुत्र में तीसरी संगीति का संरक्षक।", "राजगृह में पहली संगीति का संरक्षक।", "कन्नौज धार्मिक सभा का आयोजक।"]
    },
    {
        "name_en": "Vardhamana Mahavira & Jain Philosophy: Triratna, Anekantavada & Syadvada",
        "name_hi": "वर्धमान महावीर एवं जैन दर्शन: त्रिरत्न, अनेकांतवाद एवं स्याद्वाद",
        "concepts_en": ["Vardhamana Mahavira (24th Tirthankara, Jnatrika clan)", "Kaivalya (supreme omniscience) under Sal tree at Jrimbhikagrama", "Triratna: Right Faith, Right Knowledge, Right Conduct", "Anekantavada (multiplicity of reality) and Syadvada (relativity of knowledge)"],
        "concepts_hi": ["वर्धमान महावीर (24वें तीर्थंकर, ज्ञातृक कुल)", "जृंभिकग्राम में ऋजुपालिका नदी तट पर साल वृक्ष के नीचे कैवल्य प्राप्ति", "त्रिरत्न: सम्यक दर्शन, सम्यक ज्ञान, सम्यक चरित्र", "अनेकांतवाद (सत्य के अनेक पहलू) एवं स्याद्वाद (सापेक्षता का सिद्धांत)"],
        "q_en": "In Jain philosophy, the doctrine of the multiplicity of viewpoints and complex reality is known as:",
        "q_hi": "जैन दर्शन में वस्तु के अनंत धर्मों एवं दृष्टिकोणों की बहुलता के दार्शनिक सिद्धांत को क्या कहा जाता है?",
        "options_en": ["Anekantavada (अनेकांतवाद)", "Kshanikavada", "Shunyavada", "Advaita"],
        "options_hi": ["अनेकांतवाद (Anekantavada)", "क्षणिकवाद", "शून्यवाद", "अद्वैतवाद"],
        "correct_idx": 0,
        "exp_en": "Anekantavada is the core Jain metaphysical doctrine asserting that reality is complex, multifaceted, and cannot be captured completely by any single perspective.",
        "exp_hi": "अनेकांतवाद जैन दर्शन का आधारभूत सिद्धांत है, जिसके अनुसार सत्य के अनंत पहलू होते हैं और किसी एक दृष्टिकोण से उसे पूर्णतः व्यक्त नहीं किया जा सकता।",
        "cue_en": "Anekantavada = Jain doctrine of manifold viewpoints.",
        "cue_hi": "अनेकांतवाद = जैन दर्शन का बहुलतावादी सिद्धांत।",
        "wrong_en": ["Core Jain doctrine.", "Buddhist doctrine of impermanence.", "Madhyamaka Buddhist doctrine of Nagarjuna.", "Vedantic non-dualism."],
        "wrong_hi": ["जैन धर्म का मूल सिद्धांत।", "बौद्ध धर्म का क्षणभंगुरता का सिद्धांत।", "नागार्जुन का बौद्ध शून्यवाद।", "शंकराचार्य का अद्वैत दर्शन।"]
    },
    {
        "name_en": "Sects of Jainism: Digambaras, Svetambaras & Sacred Agamas",
        "name_hi": "जैन धर्म के संप्रदाय: दिगंबर, श्वेतांबर एवं जैन आगम साहित्य",
        "concepts_en": ["Great famine in Magadha led Bhadrabahu to migrate to Shravanabelagola (Digambara)", "Sthulabhadra stayed in Magadha (Svetambara, white-clad)", "Council of Pataliputra and Council of Vallabhi compiled Agamas", "Prakrit / Ardhamagadhi language"],
        "concepts_hi": ["मगध अकाल के समय भद्रबाहु का दक्षिण (श्रवणबेलगोला) प्रवास (दिगंबर परंपरा)", "स्थूलभद्र का मगध में रहना (श्वेतांबर परंपरा, श्वेत वस्त्रधारी)", "पाटलिपुत्र और वल्लभी संगीतियों में आगम ग्रंथों का संकलन", "प्राकृत एवं अर्धमागधी भाषा में रचनाएं"],
        "q_en": "Which famous colossal monolithic statue of Bahubali (Gommateshwara), revered by Jains, was erected by Chavundaraya in Karnataka?",
        "q_hi": "कर्नाटक के श्रवणबेलगोला में बाहुबली (गोमटेश्वर) की 57 फीट ऊंची विशाल एकाश्म प्रतिमा का निर्माण 10वीं शताब्दी में किसने करवाया था?",
        "options_en": ["Chavundaraya (चामुंडराय - गंग वंश के मंत्री)", "Chandragupta Maurya", "Amoghavarsha", "Kharavela"],
        "options_hi": ["चामुंडराय (Chavundaraya - Ganga Dynasty Minister)", "चंद्रगुप्त मौर्य", "अमोघवर्ष", "खारवेल"],
        "correct_idx": 0,
        "exp_en": "Chavundaraya, a military commander and minister under the Western Ganga dynasty, commissioned the 57-foot monolithic statue of Gommateshwara at Shravanabelagola in 981 CE.",
        "exp_hi": "पश्चिमी गंग वंश के मंत्री चामुंडराय ने 981 ईस्वी में श्रवणबेलगोला में गोमटेश्वर (बाहुबली) की विश्व प्रसिद्ध एकाश्म प्रतिमा बनवाई थी।",
        "cue_en": "Gommateshwara statue = Chavundaraya at Shravanabelagola.",
        "cue_hi": "गोमटेश्वर बाहुबली प्रतिमा = चामुंडराय, श्रवणबेलगोला।",
        "wrong_en": ["Commissioned Gommateshwara statue.", "Performed Sallekhana at Shravanabelagola earlier.", "Rashtrakuta king and author.", "Jain king of Kalinga (Hathigumpha inscription)."],
        "wrong_hi": ["गोमटेश्वर प्रतिमा का निर्माता।", "यहां संलेखना करने वाले मौर्य सम्राट।", "राष्ट्रकूट शासक व कविराजमार्ग के रचयिता।", "कलिंग के महामेघवाहन शासक।"]
    },
    {
        "name_en": "Heterodox Philosophies: Charvaka (Lokayata) & Ajivika Sect",
        "name_hi": "नास्तिक व श्रमण संप्रदाय: चार्वाक (लोकायत) एवं आजीवक दर्शन",
        "concepts_en": ["Charvaka (Brihaspati): Materialism, Pratyaksha (perception) only valid pramana, rejection of afterlife/rebirth", "Makkhali Gosala founded Ajivikas", "Niyati (strict determinism/fatalism) in Ajivika thought", "Ashoka and Dasharatha gifted Barabar caves to Ajivikas"],
        "concepts_hi": ["चार्वाक (बृहस्पति): भौतिकवाद, केवल प्रत्यक्ष ही एकमात्र प्रमाण, पुनर्जन्म व मोक्ष का खंडन", "मक्खलि गोशाल द्वारा आजीवक संप्रदाय की स्थापना", "आजीवक दर्शन का मूल आधार नियतिवाद (सब कुछ पूर्वनिर्धारित)", "अशोक एवं दशरथ द्वारा बराबर गुफाएं आजीवकों को दान"],
        "q_en": "Who was the founder of the Ajivika philosophical school, which adhered to the doctrine of absolute determinism (Niyati)?",
        "q_hi": "आजीवक संप्रदाय के संस्थापक कौन थे, जिनका दर्शन पूर्ण नियतिवाद (Niyati) पर आधारित था?",
        "options_en": ["Makkhali Gosala (मक्खलि गोशाल)", "Ajita Kesakambalin", "Pakudha Kacchayana", "Sanjaya Belatthiputta"],
        "options_hi": ["मक्खलि गोशाल (Makkhali Gosala)", "अजित केशकमलिन", "पकुध कच्चायन", "संजय बेलट्ठिपुत्त"],
        "correct_idx": 0,
        "exp_en": "Makkhali Gosala was the founder of the Ajivika sect, teaching that human effort is powerless and everything is governed by cosmic destiny (Niyati).",
        "exp_hi": "मक्खलि गोशाल आजीवक संप्रदाय के संस्थापक थे। वे मानते थे कि मानव प्रयास निरर्थक है और सब कुछ 'नियति' द्वारा पहले से तय होता है।",
        "cue_en": "Ajivika = Makkhali Gosala (Niyati).",
        "cue_hi": "आजीवक संप्रदाय = मक्खलि गोशाल (नियतिवाद)।",
        "wrong_en": ["Founder of Ajivika sect.", "Early Indian materialist.", "Atomist philosopher.", "Agnostic/skeptic philosopher."],
        "wrong_hi": ["आजीवक संप्रदाय के संस्थापक।", "प्रारंभिक भौतिकवादी विचारक।", "भौतिक तत्ववादी विचारक।", "अज्ञेयवादी/संशयवादी विचारक।"]
    },
    {
        "name_en": "Buddhist Art: Stupas, Chaityas, Viharas & Sanchi",
        "name_hi": "बौद्ध कला: स्तूप, चैत्य, विहार एवं सांची का महास्तूप",
        "concepts_en": ["Stupa architectural elements: Anda, Harmika, Chhatra, Pradakshina Path, Torana gateways", "Sanchi Great Stupa in MP built by Ashoka, enlarged by Shungas", "Chaitya is a prayer hall; Vihara is a monastery dwelling", "Karle and Bhaja rock-cut chaityas"],
        "concepts_hi": ["स्तूप संरचना के अंग: अंड, हर्मिका, छत्र, प्रदक्षिणा पथ, तोरण द्वार", "सांची का महास्तूप (अशोक द्वारा निर्मित, शुंग काल में पाषाण वेष्टनी)", "चैत्य पूजा गृह एवं विहार भिक्षुओं का निवास स्थान", "कार्ले व भाजा के शैलकृत चैत्य"],
        "q_en": "In classical Buddhist stupa architecture, what is the square railing structure crowning the hemispherical dome (Anda) that houses the sacred relics called?",
        "q_hi": "पारंपरिक बौद्ध स्तूप स्थापत्य में अर्धगोलाकार गुंबद (अंड) के शीर्ष पर स्थित पवित्र धातु अवशेषों की रक्षा करने वाली चौकोर रेलिंग जैसी संरचना को क्या कहा जाता है?",
        "options_en": ["Harmika (हर्मिका)", "Torana", "Chhatra", "Medhi"],
        "options_hi": ["हर्मिका (Harmika)", "तोरण (Torana)", "छत्र (Chhatra)", "मेधि (Medhi)"],
        "correct_idx": 0,
        "exp_en": "The Harmika is the square balcony/railing crowning the Anda of a stupa, representing the abode of the gods and holding the sacred relics.",
        "exp_hi": "हर्मिका स्तूप के अंड के शीर्ष पर बनी चौकोर बालकनीनुमा संरचना होती है, जो देवलोक और पवित्र अवशेषों का प्रतीक मानी जाती है।",
        "cue_en": "Top railing of Stupa = Harmika.",
        "cue_hi": "स्तूप के शीर्ष पर स्थित रेलिंग = हर्मिका।",
        "wrong_en": ["Crowning balcony holding relics.", "Ornamented ceremonial gateway.", "Umbrella structure above harmika.", "Elevated circular terrace platform."],
        "wrong_hi": ["शीर्ष पर स्थित पवित्र चौकोर संरचना।", "अलंंकृत तोरण द्वार।", "हर्मिका के ऊपर लगा तीन छतरियों का छत्र।", "स्तूप का चबूतरा।"]
    },
    {
        "name_en": "Spread of Buddhism to Central, East & Southeast Asia",
        "name_hi": "मध्य, पूर्व एवं दक्षिण-पूर्व एशिया में बौद्ध धर्म का प्रसार",
        "concepts_en": ["Ashoka sent Mahendra and Sanghamitta to Sri Lanka (Tamraparni)", "Silk Road dissemination to China (Kashyapa Matanga, Kumarajiva)", "Nalanda and Vikramashila as international academic hubs", "Borobudur stupa in Java (Sailendra dynasty)"],
        "concepts_hi": ["अशोक ने पुत्र महेंद्र व पुत्री संघमित्रा को श्रीलंका (ताम्रपर्णी) भेजा", "रेशम मार्ग से चीन में प्रसार (कश्यप मातंग, कुमारजीव)", "नालंदा व विक्रमशिला अंतरराष्ट्रीय उच्च शिक्षा केंद्र", "जावा (इंडोनेशिया) में शैलेंद्र वंश द्वारा निर्मित बोरोबुदुर स्तूप"],
        "q_en": "Emperor Ashoka dispatched his son Mahendra and daughter Sanghamitra to propagate Buddhism to which kingdom?",
        "q_hi": "सम्राट अशोक ने बौद्ध धर्म के प्रचार-प्रसार हेतु अपने पुत्र महेंद्र और पुत्री संघमित्रा को किस देश भेजा था?",
        "options_en": ["Sri Lanka (Ceylon / Tamraparni)", "Burma (Myanmar)", "Tibet", "China"],
        "options_hi": ["श्रीलंका (ताम्रपर्णी / सीलोन)", "बर्मा (म्यांमार)", "तिब्बत", "चीन"],
        "correct_idx": 0,
        "exp_en": "Ashoka sent his son Mahendra and daughter Sanghamitra to Anuradhapura in Sri Lanka, where King Devanampiya Tissa embraced Buddhism.",
        "exp_hi": "सम्राट अशोक ने तीसरी बौद्ध संगीति के बाद महेंद्र और संघमित्रा को बोधिवृक्ष की शाखा देकर श्रीलंका भेजा, जहां राजा देवानांपिय तिस्स ने बौद्ध धर्म ग्रहण किया।",
        "cue_en": "Mahendra & Sanghamitra = Sri Lanka.",
        "cue_hi": "महेंद्र और संघमित्रा = श्रीलंका।",
        "wrong_en": ["Mission sent to Sri Lanka.", "Sona and Uttara sent to Suvarnabhumi.", "Padmasambhava brought Buddhism later.", "Monks went along Silk Route."],
        "wrong_hi": ["श्रीलंका में धर्म प्रचार किया।", "सोन और उत्तर सुवर्णभूमि भेजे गए।", "पद्मसंभव ने बाद में तिब्बत में प्रचार किया।", "रेशम मार्ग से चीन पहुंचे।"]
    }
]

# S03-C8a2f389f Mauryan Empire, Administration & Ashokan Edicts (4 topics)
DATA["S03-C8a2f389f"] = [
    {
        "name_en": "Chandragupta Maurya, Chanakya & Kautilya's Arthashastra Administration",
        "name_hi": "चंद्रगुप्त मौर्य, चाणक्य एवं कौटिल्य का अर्थशास्त्र: प्रशासनिक व्यवस्था",
        "concepts_en": ["Overthrow of Dhana Nanda (c. 321 BCE) with help of Kautilya (Vishnugupta)", "Arthashastra treatise on statecraft, economic policy and military strategy", "Saptanga theory of state: Swami, Amatya, Janapada, Durga, Kosha, Danda, Mitra", "Bureaucratic departments headed by Adhyakshas and Tirthas"],
        "concepts_hi": ["चाणक्य (विष्णुगुप्त) की सहायता से नंद वंश का उन्मूलन (321 ई.पू.)", "कौटिल्य का अर्थशास्त्र: राजनीति, प्रशासन, गुप्तचर और अर्थव्यवस्था का ग्रंथ", "सप्तांग सिद्धांत: स्वामी, अमात्य, जनपद, दुर्ग, कोष, दंड एवं मित्र", "अध्यक्षों (तीर्थ) द्वारा संचालित केंद्रीकृत नौकरशाही"],
        "q_en": "According to Kautilya's Arthashastra, how many limbs (Saptanga) constitute the sovereign state?",
        "q_hi": "कौटिल्य के अर्थशास्त्र के अनुसार राज्य के कितने अंग (सप्तांग सिद्धांत) माने गए हैं?",
        "options_en": ["7 limbs (Swami, Amatya, Janapada, Durga, Kosha, Danda, Mitra)", "5 limbs", "8 limbs", "12 limbs"],
        "options_hi": ["7 अंग (स्वामी, अमात्य, जनपद, दुर्ग, कोष, दंड, मित्र)", "5 अंग", "8 अंग", "12 अंग"],
        "correct_idx": 0,
        "exp_en": "Kautilya propounded the Saptanga theory of state comprising 7 elements: King (Swami), Minister (Amatya), Territory/People (Janapada), Fort (Durga), Treasury (Kosha), Army (Danda), and Ally (Mitra).",
        "exp_hi": "कौटिल्य के सप्तांग सिद्धांत के 7 प्रमुख अंग हैं: स्वामी (राजा), अमात्य (मंत्री), जनपद (भूमि व प्रजा), दुर्ग (किला), कोष (खजाना), दंड (सेना) और मित्र।",
        "cue_en": "Saptanga = 7 limbs of state in Arthashastra.",
        "cue_hi": "सप्तांग = राज्य के 7 अंग (कौटिल्य)।",
        "wrong_en": ["Seven limbs in Arthashastra.", "Understates limbs.", "Overstates limbs.", "Mandala theory has 12 kings."],
        "wrong_hi": ["कौटिल्य के 7 अंग।", "कम संख्या।", "अधिक संख्या।", "मंडल सिद्धांत में 12 राजा होते हैं।"]
    },
    {
        "name_en": "Megasthenes' Indica & Mauryan Municipal Administration of Pataliputra",
        "name_hi": "मेगस्थनीज की इंडिका एवं पाटलिपुत्र का नगर प्रशासन",
        "concepts_en": ["Megasthenes was Seleucid ambassador to Chandragupta Maurya's court", "Indica describes Pataliputra fortified with 570 towers and 64 gates", "Municipal council of 30 members divided into 6 boards of 5 each", "Seven classes of Indian society described by Megasthenes"],
        "concepts_hi": ["मेगस्थनीज सेल्यूकस निकेटर का राजदूत बनकर पाटलिपुत्र आया", "इंडिका में पाटलिपुत्र का वर्णन: 570 बुर्ज और 64 द्वार वाला विशाल नगर", "30 सदस्यों की नगर परिषद (5-5 सदस्यों की 6 समितियां)", "मेगस्थनीज द्वारा भारतीय समाज का 7 जातियों में विभाजन"],
        "q_en": "According to Greek ambassador Megasthenes, the municipal administration of the Mauryan capital Pataliputra was conducted by a commission of 30 members divided into how many boards?",
        "q_hi": "यूनानी राजदूत मेगस्थनीज के अनुसार मौर्य राजधानी पाटलिपुत्र का नगर प्रशासन 30 सदस्यों के आयोग द्वारा कितनी समितियों में विभाजित होकर किया जाता था?",
        "options_en": ["6 boards of 5 members each", "5 boards of 6 members each", "4 boards of 7 members each", "10 boards of 3 members each"],
        "options_hi": ["6 समितियां (प्रत्येक में 5 सदस्य)", "5 समितियां (प्रत्येक में 6 सदस्य)", "4 समितियां", "10 समितियां"],
        "correct_idx": 0,
        "exp_en": "Megasthenes noted that Pataliputra was governed by 6 boards of 5 members each, overseeing industries, foreigners, births/deaths, trade, manufacturing, and tax collection.",
        "exp_hi": "मेगस्थनीज के अनुसार पाटलिपुत्र का प्रशासन 6 समितियां (उद्योग, विदेशियों की देखरेख, जन्म-मरण पंजीकरण, व्यापार, शिल्प व कर संग्रह) करती थीं, जिनमें 5-5 सदस्य थे।",
        "cue_en": "Pataliputra administration = 6 boards × 5 members = 30.",
        "cue_hi": "पाटलिपुत्र प्रशासन = 6 समितियां × 5 सदस्य = कुल 30।",
        "wrong_en": ["Correct 6 boards of 5 members.", "Reversed configuration.", "Incorrect board count.", "Incorrect board count."],
        "wrong_hi": ["सही संरचना: 6 समितियां, प्रत्येक में 5।", "उल्टी संख्या।", "गलत समिति संख्या।", "गलत समिति संख्या।"]
    },
    {
        "name_en": "Ashoka's Kalinga War (261 BCE), Dhamma Policy & Rock/Pillar Edicts",
        "name_hi": "अशोक का कलिंग युद्ध (261 ई.पू.), धम्म नीति एवं शिलालेख/स्तंभलेख",
        "concepts_en": ["Kalinga War fought in 8th regnal year (261 BCE); described in Major Rock Edict XIII", "Bherighosha (war drum) replaced by Dhammaghosha (righteous sound)", "Appointment of Dhamma Mahamattas in 14th regnal year", "Decipherment of Brahmi script by James Prinsep in 1837"],
        "concepts_hi": ["राज्याभिषेक के 8वें वर्ष (261 ई.पू.) में कलिंग युद्ध; 13वें वृहद शिलालेख में हृदयविदारक वर्णन", "भेरीघोष के स्थान पर धम्मघोष की घोषणा", "धम्म महामात्रों की नियुक्ति (14वें वर्ष में)", "1837 में जेम्स प्रिंसेप द्वारा ब्राह्मी लिपि का उद्वाचन"],
        "q_en": "Which Major Rock Edict of Emperor Ashoka provides the poignant description of the devastation of the Kalinga War and his remorse?",
        "q_hi": "सम्राट अशोक के किस प्रमुख शिलालेख में कलिंग युद्ध के विनाश, भारी जनहानि और उसके पश्चाताप का मार्मिक वर्णन मिलता है?",
        "options_en": ["Major Rock Edict XIII (13वां शिलालेख)", "Major Rock Edict I", "Major Rock Edict X", "Major Rock Edict VII"],
        "options_hi": ["13वां शिलालेख (Major Rock Edict XIII)", "पहला शिलालेख", "10वां शिलालेख", "7वां शिलालेख"],
        "correct_idx": 0,
        "exp_en": "Major Rock Edict XIII explicitly describes the horrors of the Kalinga war, stating 100,000 were slain and 150,000 captive, turning Ashoka towards Dhamma.",
        "exp_hi": "13वें शिलालेख में कलिंग युद्ध की विभीषिका, 1 लाख मारे गए लोगों और डेढ़ लाख बंदियों का उल्लेख है, जिसके बाद अशोक ने धम्म विजय की नीति अपनाई।",
        "cue_en": "Kalinga War = Rock Edict XIII.",
        "cue_hi": "कलिंग युद्ध = 13वां शिलालेख।",
        "wrong_en": ["Describes Kalinga war and repentance.", "Prohibits animal sacrifice.", "Disapproves personal glory.", "Pleads for religious tolerance."],
        "wrong_hi": ["कलिंग युद्ध और धम्म विजय का वर्णन।", "पशु बलि पर प्रतिबंध।", "व्यक्तिगत ख्याति की निंदा।", "धार्मिक सहिष्णुता की अपील।"]
    },
    {
        "name_en": "Mauryan Art & Architecture: Ashokan Pillars, Lion Capital & Barabar Caves",
        "name_hi": "मौर्यकालीन कला एवं स्थापत्य: अशोक के एकाश्म स्तंभ, सिंह शीर्ष एवं बराबर गुफाएं",
        "concepts_en": ["Monolithic sandstone pillars with lustrous Mauryan polish (Chunar sandstone)", "Lion Capital of Sarnath adopted as National Emblem of India", "Rock-cut caves in Barabar Hills (Sudama, Lomas Rishi) excavated for Ajivikas", "Didarganj Yakshi polished stone sculpture"],
        "concepts_hi": ["चुनार के बलुआ पत्थर से बने चमकदार पॉलिश वाले एकाश्म स्तंभ", "सारनाथ का सिंह शीर्ष (भारत का राष्ट्रीय प्रतीक)", "बराबर पहाड़ियों में आजीवकों के लिए निर्मित शैलकृत गुफाएं (सुदामा, लोमश ऋषि)", "दीदारगंज की यक्षी की प्रसिद्ध मूर्ति"],
        "q_en": "The famous polished rock-cut caves in the Barabar Hills of Bihar were excavated by Emperor Ashoka and his grandson Dasharatha for which religious sect?",
        "q_hi": "बिहार में जहानाबाद के निकट बराबर की पहाड़ियों में स्थित प्रसिद्ध चमकदार शैलकृत गुफाएं अशोक और उसके पौत्र दशरथ द्वारा किस संप्रदाय के भिक्षुओं के लिए बनवाई गई थीं?",
        "options_en": ["Ajivika sect (आजीवक संप्रदाय)", "Digambara Jains", "Theravada Buddhists", "Charvakas"],
        "options_hi": ["आजीवक संप्रदाय (Ajivika Sect)", "दिगंबर जैन", "थेरवादी बौद्ध", "चार्वाक"],
        "correct_idx": 0,
        "exp_en": "The rock-cut caves of Barabar Hills (including Lomas Rishi and Sudama caves) were dedicated to ascetic monks of the Ajivika sect by Ashoka and Dasharatha.",
        "exp_hi": "बराबर की पहाड़ियों में सुदामा, कर्ण चौपड़, विश्वझोपड़ी और लोमश ऋषि गुफाएं आजीवक संप्रदाय के संन्यासियों के निवास हेतु दान में दी गई थीं।",
        "cue_en": "Barabar caves = Dedicated to Ajivikas.",
        "cue_hi": "बराबर गुफाएं = आजीवक संप्रदाय हेतु।",
        "wrong_en": ["Dedicated to Ajivikas.", "Jains received Udayagiri-Khandagiri.", "Buddhists used Ajanta/Karle.", "Charvakas had no monastic order."],
        "wrong_hi": ["आजीवकों को समर्पित।", "जैनों को उदयगिरि-खंडगिरि गुफाएं मिलीं।", "बौद्धों के लिए अजंता, कार्ले आदि थे।", "चार्वाकों का कोई मठवासी संघ नहीं था।"]
    }
]

# S03-C9ba1a621 Post-Mauryan, Guptas, Harsha & Sangam Dynasties (7 topics)
DATA["S03-C9ba1a621"] = [
    {
        "name_en": "Shungas, Kanvas & Indo-Greeks: Menander & Milinda Panha",
        "name_hi": "शुंग, कण्व एवं भारत-यूनानी: राजा मिनेंडर एवं मिलिंदपन्हो",
        "concepts_en": ["Pushyamitra Shunga assassinated Brihadratha (185 BCE), performed Ashvamedha", "Indo-Greek King Menander (Milinda) converted to Buddhism by Nagasena", "Milinda Panha (Questions of King Menander) philosophical text in Pali", "First gold coins issued by Indo-Greeks"],
        "concepts_hi": ["पुष्यमित्र शुंग ने अंतिम मौर्य राजा बृहद्रथ की हत्या कर शुंग वंश स्थापित किया (185 ई.पू.)", "भारत-यूनानी राजा मिनेंडर (मिलिंद) बौद्ध भिक्षु नागसेन द्वारा दीक्षित", "पाली भाषा का दार्शनिक ग्रंथ 'मिलिंदपन्हो' (मिलिंद के प्रश्न)", "भारत में पहली बार सोने के सिक्के जारी करने वाले हिंद-यवन शासक"],
        "q_en": "In the famous Buddhist philosophical text 'Milinda Panha', Indo-Greek king Menander discusses philosophical questions with which Buddhist sage?",
        "q_hi": "प्रसिद्ध बौद्ध दार्शनिक ग्रंथ 'मिलिंदपन्हो' में हिंद-यवन राजा मिनेंडर (मिलिंद) के दार्शनिक प्रश्नों का उत्तर किस बौद्ध भिक्षु द्वारा दिया गया है?",
        "options_en": ["Nagasena (नागसेन)", "Vasumitra", "Ashvaghosha", "Dharmakirti"],
        "options_hi": ["नागसेन (Nagasena)", "वसुमित्र", "अश्वघोष", "धर्मकीर्ति"],
        "correct_idx": 0,
        "exp_en": "Milinda Panha records the philosophical dialogue between the Indo-Greek King Menander I and the Buddhist monk Nagasena, leading to Menander's conversion.",
        "exp_hi": "'मिलिंदपन्हो' में हिंद-यवन शासक मिलिंद और बौद्ध भिक्षु नागसेन के बीच गहन दार्शनिक संवाद संकलित है।",
        "cue_en": "Milinda Panha = King Menander + Nagasena.",
        "cue_hi": "मिलिंदपन्हो = राजा मिनेंडर + नागसेन।",
        "wrong_en": ["Answered King Menander's questions.", "Presided over 4th Council.", "Wrote Buddhacharita.", "Later Buddhist logician."],
        "wrong_hi": ["मिलिंद के प्रश्नों का समाधान किया।", "चौथी संगीति के अध्यक्ष।", "बुद्धचरित के रचयिता।", "परवर्ती बौद्ध न्यायवेत्ता।"]
    },
    {
        "name_en": "Kushana Empire: Kanishka, Gandhara & Mathura Art Schools",
        "name_hi": "कुषाण साम्राज्य: कनिष्क, गांधार एवं मथुरा कला शैलियां",
        "concepts_en": ["Kanishka started Saka Era (78 CE), capital Purushapura (Peshawar)", "Patron of Fourth Buddhist Council and Ashvaghosha (Buddhacharita)", "Gandhara school: Greco-Roman influence, grey schist stone, Apollo-like Buddha", "Mathura school: Indigenous, spotted red sandstone, vigorous spiritual expression"],
        "concepts_hi": ["कनिष्क ने 78 ईस्वी में शक संवत प्रारंभ किया; राजधानी पुरुषपुर (पेशावर)", "चौथी बौद्ध संगीति और अश्वघोष (बुद्धचरित) के संरक्षक", "गांधार शैली: ग्रीको-रोमन प्रभाव, नीले-धूसर शिस्ट पत्थर, अपोलो सदृश बुद्ध", "मथुरा शैली: स्वदेशी भारतीय शैली, धब्बेदार लाल बलुआ पत्थर"],
        "q_en": "The Saka Era, adopted by the Government of India as its National Civil Calendar, was instituted in 78 CE by which monarch?",
        "q_hi": "भारत सरकार द्वारा आधिकारिक राष्ट्रीय पंचांग के रूप में स्वीकृत 'शक संवत' 78 ईस्वी में किस शासक द्वारा शुरू किया गया था?",
        "options_en": ["Kanishka (कनिष्क - कुषाण शासक)", "Chandragupta I", "Vikramaditya", "Rudradaman I"],
        "options_hi": ["कनिष्क (Kanishka)", "चंद्रगुप्त प्रथम", "विक्रमादित्य", "रुद्रदामन प्रथम"],
        "correct_idx": 0,
        "exp_en": "The Saka Era began in 78 CE with the accession of the Kushana ruler Kanishka I; it was adopted as India's National Calendar in 1957.",
        "exp_hi": "शक संवत की शुरुआत 78 ईस्वी में कुषाण सम्राट कनिष्क के राज्यारोहण के साथ हुई थी; 1957 में इसे भारत का राष्ट्रीय कैलेंडर घोषित किया गया।",
        "cue_en": "Saka Era 78 CE = Kanishka.",
        "cue_hi": "शक संवत 78 ईस्वी = कनिष्क।",
        "wrong_en": ["Founded Saka Era in 78 CE.", "Founded Gupta Era in 319-320 CE.", "Associated with Vikrama Samvat 57 BCE.", "Western Kshatrapa ruler of Junagadh."],
        "wrong_hi": ["78 ईस्वी में शक संवत चलाया।", "319-320 ईस्वी में गुप्त संवत चलाया।", "57 ई.पू. के विक्रम संवत से संबंधित।", "जूनागढ़ अभिलेख वाले शक क्षत्रप।"]
    },
    {
        "name_en": "Satavahana Dynasty: Gautamiputra Satakarni & Deccan Trade",
        "name_hi": "सातवाहन राजवंश: गौतमीपुत्र शातकर्णी एवं दक्कन का व्यापार",
        "concepts_en": ["Simuka founded Satavahanas in Deccan (capital Pratishthana/Paithan)", "Gautamiputra Satakarni titled 'Eka-Brahmana' (Nashik inscription of Gautami Balashri)", "Matronymics usage (named after mothers)", "Issued lead, potin, and copper coins; patronized Prakrit literature (Gaha Sattasai)"],
        "concepts_hi": ["सिमुक द्वारा दक्कन में सातवाहन वंश की स्थापना (राजधानी प्रतिष्ठान / पैठन)", "गौतमीपुत्र शातकर्णी को 'एक ब्राह्मण' व 'त्रि-समुद्र-तोय-पीत-वाहन' कहा गया (नासिक अभिलेख)", "मातृनामों का प्रयोग (माता के नाम पर राजाओं का नाम)", "सीसे, पोटीन और तांबे के सिक्के जारी किए; प्राकृत ग्रंथ 'गाथासप्तशती'"],
        "q_en": "In the famous Nashik cave inscription, which Satavahana monarch is eulogized as 'Eka-Brahmana' (peerless Brahmana) and destroyer of the Sakas, Yavanas, and Pahlavas?",
        "q_hi": "नासिक गुफा अभिलेख में किस सातवाहन शासक को 'एक-ब्राह्मण' (अद्वितीय ब्राह्मण) तथा शक, यवन व पहलवों का संहारक कहा गया है?",
        "options_en": ["Gautamiputra Satakarni (गौतमीपुत्र शातकर्णी)", "Simuka", "Vashishtiputra Pulumavi", "Hala"],
        "options_hi": ["गौतमीपुत्र शातकर्णी (Gautamiputra Satakarni)", "सिमुक", "वाशिष्ठीपुत्र पुलुमावी", "हाल"],
        "correct_idx": 0,
        "exp_en": "Gautamiputra Satakarni (reigned c. 106–130 CE) was hailed in the Nashik prasasti by his mother Gautami Balashri as 'Eka-Brahmana' and restorer of the Satavahana glory.",
        "exp_hi": "गौतमीपुत्र शातकर्णी की माता गौतमी बलश्री के नासिक अभिलेख में उन्हें 'एक-ब्राह्मण' और तीनों समुद्रों का जल पीने वाले घोड़ों का स्वामी कहा गया है।",
        "cue_en": "Eka-Brahmana = Gautamiputra Satakarni.",
        "cue_hi": "एक-ब्राह्मण = गौतमीपुत्र शातकर्णी।",
        "wrong_en": ["Celebrated in Nashik inscription.", "Founder of Satavahanas.", "Successor who expanded north.", "Author of Prakrit poem Gatha Saptashati."],
        "wrong_hi": ["नासिक प्रशस्ति में वर्णित महान सातवाहन शासक।", "सातवाहन वंश का संस्थापक।", "उनका उत्तराधिकारी।", "गाथासप्तशती के रचयिता राजा।"]
    },
    {
        "name_en": "Gupta Empire: Samudragupta's Prayag Prashasti & Military Campaigns",
        "name_hi": "गुप्त साम्राज्य: समुद्रगुप्त की प्रयाग प्रशस्ति एवं दिग्विजय अभियान",
        "concepts_en": ["Chandragupta I assumed title 'Maharajadhiraja' (Gupta Era 319-320 CE)", "Samudragupta called 'Indian Napoleon' by V.A. Smith", "Prayag Prashasti (Allahabad Pillar) composed in Champu style by court poet Harishena", "Policies: Digvijaya in North (Aryavarta), Grahan-Moksh-Anugraha in South (Dakshinapatha)"],
        "concepts_hi": ["चंद्रगुप्त प्रथम ने 'महाराजाधिराज' की उपाधि धारण की (गुप्त संवत 319-320 ईस्वी)", "वी.ए. स्मिथ द्वारा समुद्रगुप्त को 'भारत का नेपोलियन' कहा गया", "प्रयाग प्रशस्ति (इलाहाबाद स्तंभ) दरबारी कवि हरिषेण द्वारा चंपू काव्य शैली में रचित", "नीति: आर्यावर्त का उन्मूलन (प्रसभोद्धरण), दक्षिणापथ में ग्रहण-मोक्ष-अनुग्रह"],
        "q_en": "The Prayag Prashasti (Allahabad Pillar Inscription), detailing the military conquests of Samudragupta, was composed by which court poet in Sanskrit?",
        "q_hi": "समुद्रगुप्त की दिग्विजयों और अभियानों का विस्तृत विवरण देने वाली प्रसिद्ध 'प्रयाग प्रशस्ति' (इलाहाबाद स्तंभ अभिलेख) संस्कृत में किस दरबारी कवि द्वारा रची गई थी?",
        "options_en": ["Harishena (हरिषेण)", "Kalidasa", "Banabhatta", "Ravikirti"],
        "options_hi": ["हरिषेण (Harishena)", "कालिदास", "बाणभट्ट", "रविकीर्ति"],
        "correct_idx": 0,
        "exp_en": "Harishena, court poet and sandhivigrahika (minister for peace and war) under Samudragupta, composed the 33-line panegyric in refined Sanskrit on the Ashokan pillar at Prayagraj.",
        "exp_hi": "समुद्रगुप्त के महादंडनायक एवं संधि-विग्रहिक हरिषेण ने प्रयागराज के अशोक स्तंभ पर चंपू शैली (गद्य-पद्य मिश्रित) में 33 पंक्तियों की प्रयाग प्रशस्ति लिखी थी।",
        "cue_en": "Prayag Prashasti = Harishena (Samudragupta).",
        "cue_hi": "प्रयाग प्रशस्ति = हरिषेण (समुद्रगुप्त)।",
        "wrong_en": ["Court poet who composed Prayag Prashasti.", "Court poet of Chandragupta II.", "Court poet of Harsha (Harshacharita).", "Court poet of Pulakeshin II (Aihole Inscription)."],
        "wrong_hi": ["प्रयाग प्रशस्ति के रचयिता।", "चंद्रगुप्त द्वितीय के नवरत्न कवि।", "हर्षवर्धन के दरबारी कवि।", "पुलकेशिन द्वितीय के ऐहोल अभिलेख के रचयिता।"]
    },
    {
        "name_en": "Golden Age of Guptas: Sciences, Mathematics, Metallurgy & Nalanda University",
        "name_hi": "गुप्त काल का स्वर्ण युग: विज्ञान, गणित, धातु विज्ञान एवं नालंदा विश्वविद्यालय",
        "concepts_en": ["Aryabhata: Aryabhatiya, concept of zero, value of pi (3.1416), earth rotation", "Varahamihira: Brihat Samhita and Panchasiddhantika", "Rustless Iron Pillar of Mehrauli (Delhi) under Chandragupta II 'Vikramaditya'", "Kumaragupta I founded Nalanda Mahavihara in Bihar"],
        "concepts_hi": ["आर्यभट: आर्यभटीय, शून्य की अवधारणा, पाई का मान, पृथ्वी का अपनी धुरी पर घूर्णन", "वराहमिहिर: वृहत्संहिता एवं पंचसिद्धांतिका", "महरौली (दिल्ली) का जंगरहित लौह स्तंभ (चंद्रगुप्त द्वितीय 'विक्रमादित्य')", "कुमारगुप्त प्रथम द्वारा नालंदा महाविहार की स्थापना"],
        "q_en": "Which Gupta emperor founded the internationally celebrated ancient university of Nalanda in modern-day Bihar?",
        "q_hi": "प्राचीन भारत के विश्व प्रसिद्ध नालंदा विश्वविद्यालय की स्थापना 5वीं शताब्दी में किस गुप्त शासक द्वारा की गई थी?",
        "options_en": ["Kumaragupta I (कुमारगुप्त प्रथम - महेंद्रादित्य)", "Samudragupta", "Chandragupta II Vikramaditya", "Skandagupta"],
        "options_hi": ["कुमारगुप्त प्रथम (Kumaragupta I - Mahendraditya)", "समुद्रगुप्त", "चंद्रगुप्त द्वितीय विक्रमादित्य", "स्कंदगुप्त"],
        "correct_idx": 0,
        "exp_en": "Nalanda Mahavihara was established during the reign of Kumaragupta I (Shakraditya/Mahendraditya) in the early 5th century CE, flourishing as a premier Buddhist learning center.",
        "exp_hi": "नालंदा महाविहार की स्थापना 5वीं शताब्दी के आरंभ में गुप्त सम्राट कुमारगुप्त प्रथम (महेंद्रादित्य) द्वारा की गई थी।",
        "cue_en": "Nalanda founded by Kumaragupta I.",
        "cue_hi": "नालंदा विश्वविद्यालय = कुमारगुप्त प्रथम।",
        "wrong_en": ["Founder of Nalanda Mahavihara.", "Father of Chandragupta II.", "Known for Vikramaditya title and Navaratnas.", "Repulsed Huna invasions."],
        "wrong_hi": ["नालंदा के संस्थापक सम्राट।", "चंद्रगुप्त द्वितीय के पिता।", "नवरत्नों के संरक्षक विक्रमादित्य।", "हूणों को पराजित करने वाले गुप्त शासक।"]
    },
    {
        "name_en": "Harshavardhana: Kannauj Assembly, Prayag Mahamoksha Parishad & Xuanzang",
        "name_hi": "हर्षवर्धन: कन्नौज धर्मसभा, प्रयाग महामोक्ष परिषद एवं ह्वेनसांग का यात्रा वृत्तांत",
        "concepts_en": ["Pushyabhuti dynasty of Thanesar, shifted capital to Kannauj", "Authored Sanskrit plays: Ratnavali, Priyadarsika, Nagananda", "Chinese pilgrim Xuanzang (Hiuen Tsang) attended Kannauj Assembly (643 CE)", "Defeated by Chalukya King Pulakeshin II on Narmada banks (Aihole Inscription)"],
        "concepts_hi": ["थानेश्वर के पुष्यभूति वंश के शासक, कन्नौज को नई राजधानी बनाया", "तीन प्रसिद्ध संस्कृत नाटक लिखे: रत्नावली, प्रियदर्शिका, नागानंद", "चीनी बौद्ध यात्री ह्वेनसांग (तीर्थयात्रियों का राजकुमार) ने कन्नौज सभा में भाग लिया", "नर्मदा नदी के तट पर चालुक्य शासक पुलकेशिन द्वितीय से पराजित (ऐहोल प्रशस्ति)"],
        "q_en": "Which Chalukya ruler defeated Emperor Harshavardhana on the banks of the Narmada River, as recorded in the Aihole Inscription composed by Ravikirti?",
        "q_hi": "ऐहोल अभिलेख (रविकीर्ति द्वारा रचित) के अनुसार नर्मदा नदी के तट पर सम्राट हर्षवर्धन के दक्षिण अभियान को किस चालुक्य नरेश ने विफल किया था?",
        "options_en": ["Pulakeshin II (पुलकेशिन द्वितीय)", "Vikramaditya I", "Kirtivarman I", "Mangalesha"],
        "options_hi": ["पुलकेशिन द्वितीय (Pulakeshin II)", "विक्रमादित्य प्रथम", "कीर्तिवर्मन प्रथम", "मंगलेश"],
        "correct_idx": 0,
        "exp_en": "Badami Chalukya king Pulakeshin II checked Harsha's southward expansion along the Narmada, earning the title 'Parameshwara', celebrated in the 634 CE Aihole inscription.",
        "exp_hi": "वातापी के चालुक्य राजा पुलकेशिन द्वितीय ने नर्मदा के तट पर हर्षवर्धन को पराजित किया था, जिसका गौरवपूर्ण वर्णन रविकीर्ति रचित ऐहोल अभिलेख में मिलता है।",
        "cue_en": "Harsha defeated by Pulakeshin II at Narmada.",
        "cue_hi": "हर्षवर्धन पराजित = पुलकेशिन द्वितीय (नर्मदा तट, ऐहोल अभिलेख)।",
        "wrong_en": ["Defeated Harsha at Narmada.", "Son of Pulakeshin II.", "Father of Pulakeshin II.", "Uncle of Pulakeshin II."],
        "wrong_hi": ["हर्ष को पराजित करने वाले चालुक्य नरेश।", "पुलकेशिन द्वितीय के पुत्र।", "पुलकेशिन द्वितीय के पिता।", "पुलकेशिन द्वितीय के चाचा।"]
    },
    {
        "name_en": "Sangam Age: Cheras, Cholas, Pandyas, Tolkappiyam & Tamil Epics",
        "name_hi": "संगम काल: चेर, चोल, पांड्य, तोलकाप्पियम एवं तमिल महाकाव्य",
        "concepts_en": ["Three Sangams held in Madurai under Pandyan patronage", "Tolkappiyam ancient Tamil grammar by Tolkappiyar (Tinais concept)", "Early Chola king Karikala built Kallanai (Grand Anicut) on Kaveri", "Tamil epics: Silappadikaram (Ilango Adigal) and Manimekalai (Chithalai Chathanar)"],
        "concepts_hi": ["पांड्य राजाओं के संरक्षण में मदुरै में तीन संगमों का आयोजन", "तोलकाप्पियर द्वारा रचित प्राचीन तमिल व्याकरण 'तोलकाप्पियम' (तिणै व्यवस्था)", "प्रारंभिक चोल राजा करिकाल द्वारा कावेरी नदी पर कल्लानाई (ग्रैंड एनीकट बांध) का निर्माण", "तमिल महाकाव्य: सिलप्पादिकारम (इलांगो अडिगल) एवं मणिमेकलै (सीत्तलै सात्तनार)"],
        "q_en": "Who is the celebrated author of the ancient Tamil epic 'Silappadikaram' (The Tale of an Anklet), centering on Kannagi and Kovalan?",
        "q_hi": "कण्णगि और कोवलन के जीवन पर आधारित प्राचीन तमिल महाकाव्य 'सिलप्पादिकारम' (नूपुर की कहानी) के रचयिता कौन हैं?",
        "options_en": ["Ilango Adigal (इलांगो अडिगल - चेर राजकुमार)", "Chithalai Chathanar", "Tolkappiyar", "Tiruvalluvar"],
        "options_hi": ["इलांगो अडिगल (Ilango Adigal)", "सीत्तलै सात्तनार", "तोलकाप्पियर", "तिरुवल्लुवर"],
        "correct_idx": 0,
        "exp_en": "Ilango Adigal, a Jain monk and brother of Chera king Senguttuvan, authored the epic Silappadikaram narrating Kannagi's moral vengeance in Madurai.",
        "exp_hi": "चेर राजा सेनगुट्टुवन के भाई इलांगो अडिगल ने 'सिलप्पादिकारम' महाकाव्य की रचना की, जो तमिल साहित्य के पांच महाकाव्यों में सर्वप्रमुख है।",
        "cue_en": "Silappadikaram = Ilango Adigal (Kannagi's story).",
        "cue_hi": "सिलप्पादिकारम = इलांगो अडिगल (कण्णगि की कथा)।",
        "wrong_en": ["Author of Silappadikaram.", "Author of Manimekalai.", "Author of Tolkappiyam.", "Author of Tirukkural."],
        "wrong_hi": ["सिलप्पादिकारम के रचयिता।", "मणिमेकलै के रचयिता।", "तोलकाप्पियम के रचयिता।", "तिरुक्कुरल के रचयिता।"]
    }
]

print("Loaded S03 (Chapters 3, 4, 5)")
