# build_curriculum/group4_s12_part2.py
# S12: General Science: Biology (Chapter 4 - 10 topics)

DATA = {}

# S12-C60e112b2 Infectious Diseases, Pathogens, Vaccines & Nutrition (10 topics)
DATA["S12-C60e112b2"] = [
    {
        "name_en": "Bacterial Diseases: Tuberculosis, Cholera, Typhoid, Tetanus & Antibiotics",
        "name_hi": "जीवाणु जनित रोग: तपेदिक (टीबी), हैजा, टाइफाइड, टेटनस एवं एंटीबायोटिक्स",
        "concepts_en": ["Tuberculosis: Mycobacterium tuberculosis (discovered by Robert Koch 1882); affects lungs; diagnosed by Mantoux test; BCG vaccine", "Cholera: Vibrio cholerae (comma-shaped); waterborne severe watery diarrhea; rehydration with ORS", "Typhoid: Salmonella typhi; diagnosed by Widal Test; intestinal perforation", "Tetanus: Clostridium tetani; 'Lockjaw' neurotoxin tetanospasmin; DPT vaccine", "Antibiotics: Alexander Fleming (1928) discovered Penicillin from Penicillium notatum fungus; inhibit bacterial cell wall synthesis or bacterial 70S ribosomes (ineffective against viruses)"],
        "concepts_hi": ["तपेदिक / क्षयरोग (TB): माइकोबैक्टीरियम ट्यूबरकुलोसिस (रॉबर्ट कोच द्वारा 1882 में खोज); फेफड़ों को प्रभावित करता है; मंटू टेस्ट (Mantoux) द्वारा जांच; बीसीजी (BCG) का टीका", "हैजा (Cholera): विब्रियो कॉलेरी (कॉमा के आकार का जीवाणु); दूषित जल व भोजन से; ओआरएस (ORS) घोल से उपचार", "टाइफाइड (मियादी बुखार): साल्मोनेला टाइफी; 'विडाल परीक्षण' (Widal Test) द्वारा पुष्टि", "टेटनस (धनुषटंकार): क्लॉस्ट्रिडियम टिटैनी; 'लॉकजॉ' (जबड़ा भिंचना); डीपीटी (DPT) टीका", "एंटीबायोटिक्स: अलेक्जेंडर फ्लेमिंग (1928) ने पेनिसिलियम नोटेटम कवक से पेनिसिलिन की खोज की; जीवाणु कोशिका भित्ति को नष्ट करते हैं (विषाणुओं पर निष्प्रभावी)"],
        "q_en": "Which definitive diagnostic serological laboratory test is universally employed to confirm suspected Typhoid fever (Enteric fever)?",
        "q_hi": "टाइफाइड बुखार (मियादी बुखार / आंत्र ज्वर) की नैदानिक पुष्टि के लिए कौन सा सीरोलॉजिकल प्रयोगशाला परीक्षण (जांच) किया जाता है?",
        "options_en": ["Widal Test (विडाल परीक्षण)", "Mantoux Test", "ELISA Test", "Western Blot Test"],
        "options_hi": ["विडाल परीक्षण (Widal Test)", "मंटू परीक्षण (Mantoux Test)", "एलिसा परीक्षण (ELISA Test)", "वेस्टर्न ब्लॉट परीक्षण"],
        "correct_idx": 0,
        "exp_en": "The Widal Test (developed by Georges-Fernand Widal in 1896) detects agglutinating serum antibodies (O and H antigens) against Salmonella typhi to diagnose typhoid fever.",
        "exp_hi": "साल्मोनेला टाइफी जीवाणु के एंटीजन के विरुद्ध एंटीबॉडी की जांच करने के लिए 'विडाल टेस्ट' (Widal Test) किया जाता है।",
        "cue_en": "Typhoid test = Widal Test; TB test = Mantoux Test.",
        "cue_hi": "टाइफाइड की जांच = विडाल टेस्ट; टीबी की जांच = मंटू टेस्ट।",
        "wrong_en": ["Diagnostic test for Typhoid.", "Diagnostic skin test for Tuberculosis.", "Screening test for HIV/AIDS.", "Confirmatory test for HIV."],
        "wrong_hi": ["टाइफाइड की जांच।", "टीबी (क्षयरोग) की त्वचा जांच।", "एचआईवी की प्रारंभिक जांच।", "एचआईवी की पुष्टिकारी जांच।"]
    },
    {
        "name_en": "Viral Diseases: Polio, Rabies, Hepatitis, Dengue & HIV/AIDS",
        "name_hi": "विषाणु (वायरस) जनित रोग: पोलियो, रेबीज, हेपेटाइटिस, डेंगू एवं एड्स (HIV)",
        "concepts_en": ["Poliomyelitis: Poliovirus enters through oral-fecal route, destroys anterior horn motor neurons in spinal cord causing flaccid paralysis; Jonas Salk (Inactivated IPV 1955) and Albert Sabin (Oral OPV 1961); India certified Polio-free by WHO in 2014", "Rabies (Hydrophobia): Rhabdovirus; fatal viral encephalitis transmitted by bite of rabid animals; Louis Pasteur developed rabies vaccine", "Dengue: Flavivirus transmitted by daytime-biting female Aedes aegypti mosquito; severe thrombocytopenia (sharp drop in blood platelets)", "HIV/AIDS: Human Immunodeficiency Virus (retrovirus with RNA and reverse transcriptase) attacks CD4+ T-helper lymphocytes, causing immune failure; diagnosed by ELISA, confirmed by Western Blot / RT-PCR"],
        "concepts_hi": ["पोलियो: पोलियोवायरस दूषित जल/भोजन से आंतों में प्रवेश कर मेरुरज्जु की प्रेरक तंत्रिकाओं को नष्ट कर पक्षाघात करता है; जोनास साल्क ने 1955 में इंजेक्शन वाला टीका और अल्बर्ट साबिन ने 1961 में ओरल ड्रॉप (OPV) विकसित की; 2014 में भारत पोलियो मुक्त घोषित", "रेबीज (हाइड्रोफोबिया/जलातंक): रैबडोवायरस; पागल कुत्ते या जानवर के काटने से मस्तिष्क में संक्रमण; लुई पाश्चर ने रेबीज का टीका बनाया", "डेंगू (हड्डी-तोड़ बुखार): फ्लेविवायरस; मादा एडीज एजिप्टी मच्छर द्वारा दिन में काटने से; रक्त में प्लेटलेट्स की संख्या तेजी से गिरती है", "एड्स (HIV/AIDS): ह्यूमन इम्यूनोडेफिशिएंसी वायरस (आरएनए रेट्रोवायरस) शरीर की CD4+ टी-सहायक कोशिकाओं को नष्ट कर रोग प्रतिरोधक क्षमता खत्म कर देता है; एलिसा (ELISA) जांच"],
        "q_en": "The transmission of Dengue virus ('breakbone fever') and Chikungunya virus to humans is mediated primarily by which mosquito vector?",
        "q_hi": "डेंगू बुखार ('हड्डी-तोड़ बुखार') और चिकनगुनिया के विषाणुओं का संचरण मुख्य रूप से किस मच्छर के काटने से होता है?",
        "options_en": ["Female Aedes aegypti mosquito (मादा एडीज एजिप्टी मच्छर)", "Female Anopheles mosquito", "Culex mosquito", "Mansonia mosquito"],
        "options_hi": ["मादा एडीज एजिप्टी मच्छर (Female Aedes aegypti)", "मादा एनोफेलीज मच्छर (यह मलेरिया फैलाती है)", "क्यूलेक्स मच्छर (यह फाइलेरिया फैलाता है)", "मैनसोनिया मच्छर"],
        "correct_idx": 0,
        "exp_en": "Dengue and Chikungunya viruses are transmitted primarily by female mosquitoes of the species Aedes aegypti (identifiable by white markings on its legs, biting mostly during daylight).",
        "exp_hi": "डेंगू, चिकनगुनिया और जीका वायरस का संचरण दिन के समय काटने वाले मादा 'एडीज एजिप्टी' (चीता मच्छर) द्वारा होता है। (मलेरिया मादा एनोफेलीज से फैलता है)।",
        "cue_en": "Dengue & Chikungunya = Aedes mosquito; Malaria = Anopheles mosquito.",
        "cue_hi": "डेंगू = एडीज मच्छर; मलेरिया = एनोफेलीज मच्छर।",
        "wrong_en": ["Vector for Dengue and Chikungunya.", "Vector for Malaria protozoan.", "Vector for Lymphatic Filariasis / Encephalitis.", "Vector for Brugian filariasis."],
        "wrong_hi": ["डेंगू व चिकनगुनिया का वाहक।", "मलेरिया का वाहक।", "हाथीपांव (फाइलेरिया) का वाहक।", "अन्य परजीवी वाहक।"]
    },
    {
        "name_en": "Protozoan & Fungal Diseases: Malaria (Plasmodium Life Cycle) & Ringworm",
        "name_hi": "प्रोटोजोआ एवं कवक जनित रोग: मलेरिया (प्लाज्मोडियम जीवन चक्र), अमीबियासिस एवं दाद",
        "concepts_en": ["Malaria caused by protozoan parasite Plasmodium (P. vivax, P. falciparum [malignant cerebral malaria], P. malariae, P. ovale)", "Vector: Female Anopheles mosquito; Sir Ronald Ross discovered malaria transmission in Secunderabad in 1897 (Nobel Prize 1902)", "Plasmodium life cycle: Sporozoites injected into blood infect liver cells, undergo schizogony to form Merozoites, invade RBCs; rupture of RBCs releases toxic Hemozoin causing recurring chills and high fever every 48-72 hours", "Amoebiasis (amoebic dysentery) caused by Entamoeba histolytica; Kala-Azar (Visceral Leishmaniasis) caused by Leishmania donovani transmitted by Sandfly (Phlebotomus)", "Fungal diseases: Dermatophytosis (Ringworm) caused by Microsporum, Trichophyton, and Epidermophyton fungi"],
        "concepts_hi": ["मलेरिया: प्रोटोजोआ परजीवी प्लाज्मोडियम द्वारा (P. vivax, P. falciparum सर्वाधिक घातक दिमागी मलेरिया)", "वाहक: मादा एनोफेलीज मच्छर; सर रोनाल्ड रॉस ने 1897 में सिकंदराबाद में मलेरिया परजीवी के जीवन चक्र की खोज की (1902 का नोबेल पुरस्कार)", "प्लाज्मोडियम जीवन चक्र: मच्छर के डंक से स्पोरोजोआइट यकृत में जाते हैं, फिर आरबीसी को संक्रमित करते हैं; आरबीसी फटने से 'हीमोजोइन' (Hemozoin) विषाक्त पदार्थ निकलता है जिससे कंपकंपी के साथ तेज बुखार आता है", "कालाजार (दमदम बुखार): लीशमैनिया डोनोवानी प्रोटोजोआ; 'बालू मक्खी' (सैंडफ्लाई) द्वारा संचरण", "कवक रोग: दाद (Ringworm) ट्राइकोफाइटन और माइक्रोस्पोरम कवक द्वारा त्वचा संक्रमण"],
        "q_en": "The recurring bouts of severe chills and high fever characteristic of Malaria are triggered by the release of which toxic substance when infected red blood cells (RBCs) rupture?",
        "q_hi": "मलेरिया रोग में हर 48 से 72 घंटे में तेज कंपकंपी के साथ आने वाला तीव्र बुखार लाल रक्त कणिकाओं (RBCs) के फटने पर किस विषाक्त पदार्थ के रक्त में मुक्त होने से होता है?",
        "options_en": ["Hemozoin (हीमोजोइन विष)", "Histamine", "Interferon", "Bilirubin"],
        "options_hi": ["हीमोजोइन (Hemozoin)", "हिस्टामाइन (Histamine)", "इंटरफेरॉन (Interferon)", "बिलीरुबिन (Bilirubin)"],
        "correct_idx": 0,
        "exp_en": "When erythrocytic schizonts burst, hemoglobin digestion by-products are released as toxic Hemozoin granules along with merozoites into the blood, triggering the periodic malarial chills and fever.",
        "exp_hi": "प्लाज्मोडियम द्वारा आरबीसी के हीमोग्लोबिन को पचाने के बाद बचा अपशिष्ट 'हीमोजोइन' कहलाता है; आरबीसी के फटने पर इसके रक्त में मिलते ही तीव्र कंपकंपी और बुखार शुरू हो जाता है।",
        "cue_en": "Malarial fever and chills = Hemozoin toxin.",
        "cue_hi": "मलेरिया में कंपकंपी का कारण = हीमोजोइन।",
        "wrong_en": ["Toxin causing malarial fever paroxysm.", "Inflammatory mediator released in allergies.", "Antiviral protein released by infected cells.", "Bile pigment from hemoglobin breakdown."],
        "wrong_hi": ["मलेरिया का बुखार पैदा करने वाला विष।", "एलर्जी में निकलने वाला रसायन।", "वायरस रोधी प्रोटीन।", "पित्त वर्णक।"]
    },
    {
        "name_en": "Human Immune System: Innate vs Adaptive Immunity & B-cells and T-cells",
        "name_hi": "मानव प्रतिरक्षा तंत्र: सहज (प्राकृतिक) बनाम उपार्जित प्रतिरक्षा एवं बी-कोशिकाएं व टी-कोशिकाएं",
        "concepts_en": ["Innate Immunity (Non-specific, present from birth): Physical barriers (skin, mucous membranes), Physiological barriers (stomach HCl, saliva/tears lysozyme), Cellular barriers (neutrophils, macrophages, Natural Killer cells), Cytokine barriers (interferons protect uninfected cells from virus)", "Acquired/Adaptive Immunity (Specific, has memory): Mediated by lymphocytes", "Humoral (Antibody-Mediated) Immunity: B-lymphocytes differentiate into plasma cells producing Antibodies (Immunoglobulins: IgG, IgM, IgA [in mother's colostrum], IgE [in allergies], IgD)", "Cell-Mediated Immunity (CMI): T-lymphocytes (Cytotoxic CD8+ T cells destroy infected cells, CD4+ Helper T cells activate B cells); CMI is responsible for graft/organ transplant rejection"],
        "concepts_hi": ["सहज प्रतिरक्षा (Innate - जन्मजात व गैर-विशिष्ट): भौतिक अवरोधक (त्वचा, श्लेष्मा), कार्यिकीय अवरोधक (आमाशय का HCl, आंसुओं में लाइसोजाइम), कोशिकीय (न्यूट्रोफिल, मैक्रोफेज), साइटोकाइन (इंटरफेरॉन)", "उपार्जित प्रतिरक्षा (Acquired - विशिष्ट व स्मृति आधारित): रोगाणु के संपर्क के बाद विकसित", "तरल प्रतिरक्षा (Humoral Immunity): बी-लिम्फोसाइट्स द्वारा एंटीबॉडी (प्रतिरक्षी: IgG, IgM, IgA [मां के प्रथम दूध/कोलोस्ट्रम में], IgE [एलर्जी में]) का निर्माण", "कोशिका-माध्यित प्रतिरक्षा (Cell-Mediated Immunity - CMI): टी-लिम्फोसाइट्स द्वारा; अंग प्रत्यारोपण (Graft rejection) को अस्वीकार करने के लिए CMI ही जिम्मेदार होती है"],
        "q_en": "Which major class of immunoglobulins (antibodies) is abundantly present in yellow mother's first milk (colostrum) to confer passive immunity to the newborn infant?",
        "q_hi": "नवजात शिशु को संक्रामक रोगों से प्राकृतिक सुरक्षा प्रदान करने हेतु मां के पहले पीले गाढ़े दूध (कोलोस्ट्रम) में कौन सी एंटीबॉडी (इम्यूनोग्लोबुलिन) प्रचुर मात्रा में पाई जाती है?",
        "options_en": ["Immunoglobulin A (IgA / इम्यूनोग्लोबुलिन ए)", "Immunoglobulin E (IgE)", "Immunoglobulin M (IgM)", "Immunoglobulin D (IgD)"],
        "options_hi": ["इम्यूनोग्लोबुलिन ए (IgA)", "इम्यूनोग्लोबुलिन ई (IgE - यह एलर्जी में सक्रिय होती है)", "इम्यूनोग्लोबुलिन एम (IgM - प्राथमिक अनुक्रिया में सबसे पहले बनती है)", "इम्यूनोग्लोबुलिन डी (IgD)"],
        "correct_idx": 0,
        "exp_en": "Colostrum secreted by the mammary glands in early postpartum days contains abundant IgA antibodies that coat the infant's gut lining, providing vital mucosal passive immunity.",
        "exp_hi": "मां के प्रथम दूध (कोलोस्ट्रम) में IgA प्रतिरक्षी प्रचुर मात्रा में होती है, जो नवजात शिशु की आंतों और श्वसन मार्ग को जीवाणुओं व वायरसों से बचाती है।",
        "cue_en": "Mother's colostrum antibody = IgA; Placenta crossing antibody = IgG.",
        "cue_hi": "मां के दूध में एंटीबॉडी = IgA; प्लेसेंटा पार करने वाली = IgG।",
        "wrong_en": ["Abundant in breast colostrum.", "Mediates allergic reactions and asthma.", "First antibody produced in primary immune response.", "Present on B-cell surface as receptor."],
        "wrong_hi": ["कोलोस्ट्रम की मुख्य एंटीबॉडी।", "एलर्जी में सक्रिय।", "संक्रमण पर सबसे पहले बनने वाली भारी एंटीबॉडी।", "बी-सेल सतह पर ग्राही।"]
    },
    {
        "name_en": "Vaccines: Active vs Passive Immunity & Major Vaccine Platforms",
        "name_hi": "टीके (वैक्सीन): सक्रिय बनाम निष्क्रिय प्रतिरक्षा एवं प्रमुख वैक्सीन तकनीकें",
        "concepts_en": ["Edward Jenner (1796) developed first successful vaccine (Smallpox vaccine using cowpox virus); 'Father of Immunology'", "Active Immunity: Body produces its own antibodies following infection or vaccination; slow onset, long-lasting immunological memory", "Passive Immunity: Pre-formed ready-made antibodies introduced directly (e.g., Anti-Tetanus Serum ATS, Anti-Rabies Serum, Anti-Venom, maternal IgG crossing placenta, IgA in breast milk); immediate protection, short-lived with no memory", "Vaccine types: Live attenuated (OPV, BCG, MMR, Yellow Fever), Inactivated/Killed (Covaxin, Salk IPV, Rabies), Toxoids (Tetanus, Diphtheria), Subunit/Recombinant (Hepatitis B), mRNA vaccines (Pfizer, Moderna), Viral vector (Covishield/AstraZeneca using chimpanzee adenovirus)"],
        "concepts_hi": ["एडवर्ड जेनर (1796) ने चेचक (Smallpox) का पहला टीका विकसित किया; 'प्रतिरक्षा विज्ञान के जनक' (Father of Immunology)", "सक्रिय प्रतिरक्षा: शरीर स्वयं रोगाणु के विरुद्ध एंटीबॉडी बनाता है; धीमी किंतु दीर्घकालिक और स्मृति-युक्त", "निष्क्रिय प्रतिरक्षा: तैयार एंटीबॉडी सीधे शरीर में डालना (जैसे टिटनेस का सीरम ATS, एंटी-वेनम, रेबीज सीरम, प्लेसेंटा से शिशु में जाने वाली IgG); त्वरित सुरक्षा किंतु अल्पकालिक", "वैक्सीन के प्रकार: जीवित दुर्बलित (BCG, OPV, खसरा MMR), मृत/निष्क्रिय (कोवैक्सीन, पोलियो IPV), टॉक्साइड (टिटनेस, डिप्थीरिया), रीकॉम्बिनेंट (हेपेटाइटिस बी), एमआरएनए वैक्सीन (फाइजर, मॉडर्ना), वायरल वेक्टर (कोविशील्ड)"],
        "q_en": "Who is historically celebrated as the 'Father of Immunology' for developing the world's very first successful vaccine (the Smallpox vaccine in 1796)?",
        "q_hi": "1796 में विश्व का पहला सफल चेचक (स्मॉलपॉक्स) का टीका विकसित करने वाले किस ब्रिटिश चिकित्सक को 'प्रतिरक्षा विज्ञान का जनक' (Father of Immunology) कहा जाता है?",
        "options_en": ["Edward Jenner (एडवर्ड जेनर)", "Louis Pasteur", "Robert Koch", "Alexander Fleming"],
        "options_hi": ["एडवर्ड जेनर (Edward Jenner)", "लुई पाश्चर (Louis Pasteur)", "रॉबर्ट कोच (Robert Koch)", "अलेक्जेंडर फ्लेमिंग (Alexander Fleming)"],
        "correct_idx": 0,
        "exp_en": "Edward Jenner pioneered vaccination by demonstrating that inoculation with the milder cowpox virus conferred cross-immunity against deadly smallpox in 1796.",
        "exp_hi": "एडवर्ड जेनर ने 1796 में काउपॉक्स के सीरम से चेचक का टीका बनाकर टीकाकरण की नींव रखी थी, जिसके लिए उन्हें 'फादर ऑफ इम्यूनोलॉजी' कहा जाता है।",
        "cue_en": "First vaccine (Smallpox) = Edward Jenner (1796).",
        "cue_hi": "पहला टीका (चेचक) = एडवर्ड जेनर (1796)।",
        "wrong_en": ["Pioneered smallpox vaccine (1796).", "Developed rabies and anthrax vaccines.", "Formulated Koch's postulates for bacteria.", "Discovered penicillin in 1928."],
        "wrong_hi": ["चेचक के टीके के जनक।", "रेबीज के टीके के जनक।", "जीवाणु विज्ञान के नियम।", "पेनिसिलिन के खोजकर्ता।"]
    },
    {
        "name_en": "Vitamins: Fat-Soluble (A, D, E, K) & Water-Soluble (B-Complex, C) Functions and Deficiencies",
        "name_hi": "विटामिन्स: वसा में घुलनशील (A, D, E, K) एवं जल में घुलनशील (B-कॉम्प्लेक्स, C) विटामिन्स व हीनताजन्य रोग",
        "concepts_en": ["Term 'Vitamine' coined by Casimir Funk (1912)", "Fat-Soluble (stored in liver & adipose tissue): Vitamin A (Retinol - deficiency causes Night Blindness / Nyctalopia, Xerophthalmia); Vitamin D (Calciferol - 'sunshine vitamin', deficiency causes Rickets in children and Osteomalacia in adults); Vitamin E (Tocopherol - antioxidant, deficiency causes infertility/muscle weakness); Vitamin K (Phylloquinone - required for prothrombin synthesis in liver; deficiency impairs blood clotting)", "Water-Soluble (excreted in urine, must be replenished daily): Vitamin B1 (Thiamine - Beriberi); Vitamin B2 (Riboflavin - Cheilosis/cracked lips); Vitamin B3 (Niacin - Pellagra: 4Ds Dermatitis, Diarrhea, Dementia, Death); Vitamin B9 (Folic acid - Megaloblastic anemia and neural tube birth defects); Vitamin B12 (Cyanocobalamin - contains Cobalt metal; deficiency causes Pernicious Anemia); Vitamin C (Ascorbic acid - Scurvy, bleeding gums; heat-sensitive)"],
        "concepts_hi": ["'विटामिन' शब्द 1912 में कैसीमिर फंक द्वारा दिया गया", "वसा में घुलनशील (A, D, E, K): विटामिन A (रेटिनॉल - कमी से रतौंधी व जीरोफ्थैल्मिया); विटामिन D (कैल्सीफेरॉल - धूप से संश्लेषित, कमी से बच्चों में रिकेट्स/सूखा रोग व वयस्कों में ऑस्टियोमलेशिया); विटामिन E (टोकोफेरॉल - सौंदर्य/प्रजनन विटामिन); विटामिन K (फिलोक्विनोन - रक्त का थक्का जमाने हेतु प्रोथ्रोम्बिन निर्माण)", "जल में घुलनशील (B एवं C): विटामिन B1 (थायमिन - बेरी-बेरी); विटामिन B2 (राइबोफ्लेविन - होठ फटना); विटामिन B3 (नियासिन - पेलाग्रा); विटामिन B12 (सायनोकोबालामिन - इसमें कोबाल्ट धातु पाई जाती है; कमी से परनिशियस एनीमिया); विटामिन C (एस्कॉर्बिक अम्ल - स्कर्वी, मसूड़ों से खून आना; गर्म करने पर नष्ट हो जाता है)"],
        "q_en": "Which essential water-soluble vitamin uniquely contains the metallic element Cobalt (Co) in its organometallic ring, whose deficiency causes Pernicious Anemia?",
        "q_hi": "किस जल-घुलनशील विटामिन के केंद्र में धातु तत्व 'कोबाल्ट' (Co) पाया जाता है, जिसकी कमी से घातक रक्ताल्पता (परनिशियस एनीमिया) हो जाती है?",
        "options_en": ["Vitamin B12 (Cyanocobalamin / सायनोकोबालामिन)", "Vitamin B1 (Thiamine)", "Vitamin B6 (Pyridoxine)", "Vitamin C (Ascorbic Acid)"],
        "options_hi": ["विटामिन B12 (सायनोकोबालामिन)", "विटामिन B1 (थायमिन)", "विटामिन B6 (पाइरिडॉक्सिन)", "विटामिन C (एस्कॉर्बिक अम्ल)"],
        "correct_idx": 0,
        "exp_en": "Vitamin B12 (Cyanocobalamin) contains a cobalt ion centered in a corrin ring; intrinsic factor from stomach parietal cells is essential for its absorption in the ileum.",
        "exp_hi": "विटामिन B12 का रासायनिक नाम सायनोकोबालामिन है; इसमें कोबाल्ट धातु पाई जाती है। यह आरबीसी के परिपक्व होने और तंत्रिका तंत्र के स्वास्थ्य के लिए अनिवार्य है।",
        "cue_en": "Cobalt containing vitamin = Vitamin B12 (Cyanocobalamin).",
        "cue_hi": "कोबाल्ट युक्त विटामिन = विटामिन B12।",
        "wrong_en": ["Contains Cobalt; cures pernicious anemia.", "Deficiency causes Beriberi.", "Deficiency causes neurological seizures.", "Deficiency causes Scurvy."],
        "wrong_hi": ["कोबाल्ट युक्त विटामिन।", "कमी से बेरी-बेरी रोग।", "विटामिन B6।", "कमी से स्कर्वी रोग।"]
    },
    {
        "name_en": "Minerals in Human Nutrition: Iron, Iodine, Calcium, Sodium & Potassium",
        "name_hi": "मानव पोषण में आवश्यक खनिज लवण: लोहा, आयोडीन, कैल्शियम, सोडियम एवं पोटेशियम",
        "concepts_en": ["Iron (Fe): Essential component of Hemoglobin in RBCs and Myoglobin in muscle; deficiency leads to Microcytic Hypochromic Anemia, fatigue, and pallor; absorbed better in presence of Vitamin C", "Iodine (I): Essential for biosynthesis of thyroid hormones (Thyroxine T4 and Triiodothyronine T3); deficiency leads to Simple Goitre (enlarged thyroid) and congenital Cretinism (mental retardation in children); iodized salt", "Calcium (Ca): Major mineral constituent of bones and hydroxyapatite; essential for blood coagulation (Factor IV) and muscle contraction", "Sodium (Na⁺) & Potassium (K⁺): Maintained by Na⁺/K⁺ ATPase pump; regulate osmotic balance, blood pressure, and nerve impulse conduction"],
        "concepts_hi": ["लोहा (Iron - Fe): हीमोग्लोबिन और मायोग्लोबिन का मुख्य घटक; कमी से 'अरक्तता / एनीमिया' (रक्त की कमी, थकान, पीलापन); विटामिन C लोहे के अवशोषण को बढ़ाता है", "आयोडीन (Iodine - I): थायरॉयड ग्रंथि के थायरोक्सिन हार्मोन निर्माण हेतु अनिवार्य; कमी से 'घेंघा / गलगंड' (Goitre) रोग एवं बच्चों में मानसिक दुर्बलता (क्रेटिनिज्म); आयोडीन युक्त नमक", "कैल्शियम (Ca): हड्डियों व दांतों की मजबूती (हाइड्रॉक्सीएपेटाइट); रक्त का थक्का जमने (Clotting Factor IV) और मांसपेशियों के संकुचन हेतु अनिवार्य", "सोडियम और पोटेशियम: तंत्रिका आवेग संचरण और शरीर में परासरणी संतुलन बनाए रखने वाले प्रमुख इलेक्ट्रोलाइट्स"],
        "q_en": "Deficiency of which trace dietary mineral in food and drinking water is the primary cause of Simple Goitre (abnormal enlargement of the thyroid gland)?",
        "q_hi": "भोजन और पेयजल में किस खनिज तत्व की कमी 'घेंघा रोग' (गलगंड / Goitre - थायरॉयड ग्रंथि का फूल जाना) का मुख्य कारण बनती है?",
        "options_en": ["Iodine (आयोडीन)", "Iron", "Zinc", "Fluorine"],
        "options_hi": ["आयोडीन (Iodine)", "लोहा (Iron - कमी से एनीमिया होता है)", "जस्ता (Zinc)", "फ्लोरीन (Fluorine - अधिकता से फ्लोरोसिस)"],
        "correct_idx": 0,
        "exp_en": "Dietary iodine deficiency depresses thyroxine synthesis, causing the anterior pituitary to oversecrete TSH, which stimulates compensatory cellular hyperplasia and enlargement of the thyroid (Goitre).",
        "exp_hi": "आयोडीन की कमी होने पर थायरॉयड ग्रंथि पर्याप्त थायरोक्सिन नहीं बना पाती, जिससे पिट्यूटरी ग्रंथि से टीएसएच हार्मोन अधिक निकलता है और थायरॉयड ग्रंथि का आकार असामान्य रूप से बढ़ जाता है।",
        "cue_en": "Goitre = Iodine deficiency.",
        "cue_hi": "घेंघा रोग = आयोडीन की कमी।",
        "wrong_en": ["Deficiency causes Goitre and cretinism.", "Deficiency causes Anemia.", "Deficiency causes growth retardation and impaired immunity.", "Deficiency causes dental caries; excess causes fluorosis."],
        "wrong_hi": ["घेंघा रोग का कारण।", "एनीमिया का कारण।", "प्रतिरक्षा कमजोरी।", "दांतों से संबंधित।"]
    },
    {
        "name_en": "Macronutrients & Protein-Energy Malnutrition: Kwashiorkor vs Marasmus",
        "name_hi": "स्थूल पोषक तत्व एवं प्रोटीन-ऊर्जा कुपोषण (PEM): क्वाशिओरकोर बनाम मरास्मस (सूखा रोग)",
        "concepts_en": ["Carbohydrates: Primary energy source (4 kcal/g); simple sugars (glucose, fructose) and complex polysaccharides (starch, glycogen, cellulose fiber)", "Proteins: Polymers of amino acids linked by peptide bonds (building blocks of tissues, 4 kcal/g); 9 Essential Amino Acids that must come from diet", "Fats / Lipids: Most concentrated energy source (9 kcal/g); saturated vs unsaturated fatty acids", "Protein-Energy Malnutrition (PEM): Kwashiorkor is pure PROTEIN deficiency with adequate calories (manifests as edema/swelling of belly and limbs, Moon face, enlarged fatty liver); Marasmus is simultaneous severe deficiency of BOTH PROTEIN AND CALORIES (manifests as extreme emaciation, wasted muscles, ribs visible, wrinkled 'old man' face, NO edema)"],
        "concepts_hi": ["कार्बोहाइड्रेट: शरीर की ऊर्जा का प्राथमिक स्रोत (4 किलोकैलोरी/ग्राम); ग्लूकोज, स्टार्च, ग्लाइकोजन", "प्रोटीन: अमीनो अम्लों के बहुलक (ऊतकों का निर्माण व मरम्मत, 4 किलोकैलोरी/ग्राम); 9 अनिवार्य अमीनो अम्ल जो भोजन से मिलना जरूरी हैं", "वसा (Fats): सर्वाधिक संकेंद्रित ऊर्जा स्रोत (9 किलोकैलोरी/ग्राम); संतृप्त व असंतृप्त वसीय अम्ल", "प्रोटीन-ऊर्जा कुपोषण (PEM): (1) क्वाशिओरकोर (Kwashiorkor): मुख्य रूप से 'प्रोटीन की कमी' (पेट व पैरों में सूजन/एडिमा, फूला हुआ पेट, चंद्रमुख); (2) मरास्मस (Marasmus / सूखा रोग): प्रोटीन और कैलोरी (ऊर्जा) दोनों की गंभीर कमी (शरीर कंकाल जैसा सूख जाना, पसलियां दिखना, कोई सूजन नहीं)"],
        "q_en": "Which nutritional deficiency disease in young children is caused specifically by severe PROTEIN deficiency in the diet despite receiving adequate calories, characterized by an enlarged swollen belly (edema)?",
        "q_hi": "छोटे बच्चों में पर्याप्त कैलोरी मिलने के बावजूद केवल 'प्रोटीन की गंभीर कमी' के कारण कौन सा कुपोषण रोग हो जाता है, जिसमें बच्चे का पेट फूल जाता है और अंगों में सूजन (एडिमा) आ जाती है?",
        "options_en": ["Kwashiorkor (क्वाशिओरकोर)", "Marasmus", "Rickets", "Scurvy"],
        "options_hi": ["क्वाशिओरकोर (Kwashiorkor)", "मरास्मस (Marasmus - यह प्रोटीन व कैलोरी दोनों की कमी है)", "रिकेट्स (सूखा रोग - विटामिन D की कमी)", "स्कर्वी (विटामिन C की कमी)"],
        "correct_idx": 0,
        "exp_en": "Kwashiorkor is caused by severe protein deficiency while energy intake may be adequate. Hypoalbuminemia leads to fluid retention (edema), causing the characteristic swollen belly ('pot belly') and thin limbs.",
        "exp_hi": "क्वाशिओरकोर विशेष रूप से प्रोटीन की कमी से होता है; रक्त में एल्ब्यूमिन प्रोटीन की कमी होने से शरीर के ऊतकों में पानी भर जाता है (एडिमा) जिससे पेट मटके जैसा फूल जाता है।",
        "cue_en": "Protein deficiency with edema = Kwashiorkor; Protein + Calorie deficiency without edema = Marasmus.",
        "cue_hi": "केवल प्रोटीन की कमी (सूजन सहित) = क्वाशिओरकोर; प्रोटीन + ऊर्जा की कमी (बिना सूजन) = मरास्मस।",
        "wrong_en": ["Pure protein deficiency with edema.", "Combined protein and calorie deficiency with emaciation.", "Vitamin D deficiency.", "Vitamin C deficiency."],
        "wrong_hi": ["प्रोटीन की कमी का रोग (सूजन सहित)।", "प्रोटीन और कैलोरी दोनों की कमी।", "विटामिन D की कमी।", "विटामिन C की कमी।"]
    },
    {
        "name_en": "Human Genetic Disorders: Down Syndrome, Sickle Cell Anemia & Hemophilia",
        "name_hi": "मानव आनुवंशिक विकार: डाउन सिंड्रोम (मंगोलिज्म), सिकल सेल एनीमिया एवं हीमोफीलिया",
        "concepts_en": ["Chromosomal Disorders: Down Syndrome caused by Trisomy of chromosome 21 (47, XX/XY; flat facial profile, short stature, mental retardation); Turner Syndrome (45, XO; sterile females); Klinefelter Syndrome (47, XXY; sterile males with gynecomastia)", "Mendelian Disorders: Sickle Cell Anemia (autosomal recessive point mutation in beta-globin gene: GAG mutated to GUG, substituting Valine for Glutamic acid at position 6; RBCs become sickle-shaped under low O2, blocking capillaries; heterozygotes have resistance to falciparum malaria)", "Hemophilia ('Royal Disease'): X-linked recessive bleeding disorder; deficiency of clotting Factor VIII (Hemophilia A) or Factor IX (Hemophilia B); minor cuts lead to non-stop bleeding", "Color Blindness: X-linked recessive deficiency in red/green cone pigments"],
        "concepts_hi": ["गुणसूत्रीय विकार: डाउन सिंड्रोम (21वें गुणसूत्र की ट्राइसोमी / Trisomy 21; कुल 47 गुणसूत्र; चपटा चेहरा, मंगोलियाई आंखें, मंदबुद्धि); टर्नर सिंड्रोम (45, XO; बांझ महिलाएं); क्लाइनफेल्टर सिंड्रोम (47, XXY; पुरुष में स्त्री जैसे लक्षण)", "मेंडेलियन विकार: सिकल सेल एनीमिया (हंसियाकार रक्ताल्पता): हीमोग्लोबिन की बीटा-श्रृंखला के छठे स्थान पर ग्लूटैमिक अम्ल की जगह वैलीन आ जाना; आरबीसी हंसिया के आकार की होकर टूट जाती हैं; इस जीन के वाहक व्यक्तियों को मलेरिया नहीं होता", "हीमोफीलिया ('शाही बीमारी'): एक्स-सहलग्न अप्रभावी विकार; रक्त का थक्का बनाने वाले क्लॉटिंग फैक्टर VIII की कमी; चोट लगने पर रक्त का बहना नहीं रुकता", "वर्णांधता (Color Blindness): लाल और हरे रंग में भेद न कर पाना"],
        "q_en": "In Sickle Cell Anemia, which single amino acid substitution occurs at the 6th position of the beta-globin chain of hemoglobin due to a point mutation?",
        "q_hi": "सिकल सेल एनीमिया (हंसियाकार रक्ताल्पता) में एक बिंदु उत्परिवर्तन के कारण हीमोग्लोबिन की बीटा-ग्लोबिन श्रृंखला के छठे स्थान पर कौन सा अमीनो अम्ल ग्लूटैमिक अम्ल का स्थान ले लेता है?",
        "options_en": ["Valine replaces Glutamic Acid (ग्लूटैमिक अम्ल के स्थान पर वैलीन)", "Alanine replaces Glycine", "Lysine replaces Arginine", "Leucine replaces Isoleucine"],
        "options_hi": ["ग्लूटैमिक अम्ल के स्थान पर वैलीन (Valine replaces Glutamic Acid)", "ग्लाइसिन के स्थान पर एलानिन", "आर्जिनिन के स्थान पर लाइसिन", "आइसोल्यूसीन के स्थान पर ल्यूसीन"],
        "correct_idx": 0,
        "exp_en": "Sickle cell anemia is caused by a single base substitution (GAG to GUG in DNA) that replaces Glutamic acid (polar) with Valine (nonpolar) at position 6 of the beta-chain, causing hemoglobin polymerization under low oxygen.",
        "exp_hi": "सिकल सेल एनीमिया में हीमोग्लोबिन की बीटा श्रृंखला के छठे स्थान पर सामान्य 'ग्लूटैमिक अम्ल' के स्थान पर 'वैलीन' (Valine) अमीनो अम्ल आ जाता है, जिससे आरबीसी हंसिया के आकार की मुड़ जाती हैं।",
        "cue_en": "Sickle cell mutation = Glutamic Acid replaced by Valine at position 6.",
        "cue_hi": "सिकल सेल = छठे स्थान पर ग्लूटैमिक अम्ल की जगह वैलीन।",
        "wrong_en": ["Classic point mutation in sickle cell.", "Not involved in beta-globin defect.", "Not involved in sickle cell anemia.", "Not involved in sickle cell anemia."],
        "wrong_hi": ["सिकल सेल का सही उत्परिवर्तन।", "गलत अमीनो अम्ल।", "गलत अमीनो अम्ल।", "गलत अमीनो अम्ल।"]
    },
    {
        "name_en": "Antimicrobial Resistance (AMR), Superbugs & One Health Approach",
        "name_hi": "रोगाणुरोधी प्रतिरोध (AMR), सुपरबग्स एवं 'वन हेल्थ' (One Health) दृष्टिकोण",
        "concepts_en": ["Antimicrobial Resistance (AMR): Microorganisms (bacteria, viruses, fungi) evolve mechanisms to withstand antimicrobial medicines that previously killed them", "Causes: Overuse and misuse of antibiotics in human medicine and livestock/poultry feed, poor hygiene, hospital-acquired infections", "Superbugs: Bacterial strains resistant to multiple first-line and reserve antibiotics (e.g., MRSA - Methicillin-Resistant Staphylococcus aureus, Carbapenem-resistant Enterobacteriaceae)", "One Health Approach: Collaborative, multisectoral global framework recognizing that human health, animal health, and ecosystem/environmental health are inextricably interconnected (WHO, FAO, UNEP, WOAH Quadripartite)"],
        "concepts_hi": ["रोगाणुरोधी प्रतिरोध (AMR): जब जीवाणु और कवक समय के साथ उत्परिवर्तित होकर उन एंटीबायोटिक दवाओं के प्रति प्रतिरोधी हो जाते हैं जो पहले उन्हें नष्ट कर देती थीं", "कारण: बिना डॉक्टर की सलाह के एंटीबायोटिक दवाओं का अत्यधिक सेवन, पशुपालन व पोल्ट्री में वृद्धि हेतु एंटीबायोटिक्स का अंधाधुंध उपयोग", "सुपरबग्स (Superbugs): जीवाणुओं की ऐसी प्रजातियां जिन पर लगभग सभी प्रमुख एंटीबायोटिक्स बेअसर हो जाती हैं (जैसे MRSA, NDM-1)", "'वन हेल्थ' (One Health) दृष्टिकोण: यह एकीकृत अवधारणा मानती है कि मानव स्वास्थ्य, पशु स्वास्थ्य और पर्यावरण स्वास्थ्य परस्पर गहराई से जुड़े हुए हैं (WHO, FAO और UNEP का साझा मंच)"],
        "q_en": "The holistic global strategy recognizing that human health is fundamentally interconnected with the health of animals and the shared environment is known as the:",
        "q_hi": "यह समग्र वैश्विक रणनीति क्या कहलाती है, जो यह स्वीकार करती है कि मानव स्वास्थ्य प्रत्यक्ष रूप से पशुओं के स्वास्थ्य और पर्यावरण के स्वास्थ्य से परस्पर गहराई से जुड़ा हुआ है?",
        "options_en": ["One Health Approach ('वन हेल्थ' दृष्टिकोण)", "Global Shield Initiative", "Universal Healthcare Protocol", "Planetary Sanitation Model"],
        "options_hi": ["वन हेल्थ दृष्टिकोण (One Health Approach)", "ग्लोबल शील्ड पहल", "सार्वभौमिक स्वास्थ्य प्रोटोकॉल", "ग्रह स्वच्छता मॉडल"],
        "correct_idx": 0,
        "exp_en": "The 'One Health' approach is a collaborative, multisectoral, and transdisciplinary initiative operating at local, national, and global levels to achieve optimal health outcomes recognizing the interconnection between people, animals, plants, and their shared environment.",
        "exp_hi": "'वन हेल्थ' (One Health) दृष्टिकोण जूनोटिक बीमारियों (पशुओं से इंसानों में फैलने वाले रोग) और एंटीबायोटिक प्रतिरोध (AMR) से निपटने के लिए मानव, पशु और पर्यावरण स्वास्थ्य को एक साथ जोड़कर देखता है।",
        "cue_en": "Human + Animal + Environmental health = One Health Approach.",
        "cue_hi": "मानव + पशु + पर्यावरण स्वास्थ्य = वन हेल्थ।",
        "wrong_en": ["Official integrated paradigm.", "Climate risk financing initiative.", "General healthcare coverage concept.", "Fictitious term."],
        "wrong_hi": ["सही एकीकृत दृष्टिकोण।", "जलवायु वित्त पहल।", "सामान्य स्वास्थ्य बीमा।", "काल्पनिक नाम।"]
    }
]

print("Loaded S12 Part 2 successfully")
