# build_curriculum/group5_s16.py
# S16: International Organizations & Treaties (9 topics across 3 chapters)

DATA = {}

# S16-Cb8158434 United Nations: Charter, General Assembly & Security Council (4 topics)
DATA["S16-Cb8158434"] = [
    {
        "name_en": "United Nations Foundation: San Francisco Conference, UN Charter & Six Principal Organs",
        "name_hi": "संयुक्त राष्ट्र (UN) की स्थापना: सैन फ्रांसिस्को सम्मेलन (1945), यूएन चार्टर एवं छह प्रमुख अंग",
        "concepts_en": ["Establishment: Succeeded the defunct League of Nations; UN Charter signed on June 26, 1945 in San Francisco by 50 founding nations (India signed on October 15, 1945 as original founding member, represented by Sir Arcot Ramasamy Mudaliar); entered into force on October 24, 1945 (celebrated annually as United Nations Day)", "Headquarters: New York City (Manhattan, land donated by John D. Rockefeller Jr.); European offices in Geneva, Vienna, and Nairobi", "Six Principal Organs of the United Nations (Article 7 of Charter):", "1. General Assembly (UNGA - 'Town Hall of the World', all 193 members have equal 1-nation 1-vote)", "2. Security Council (UNSC - primary responsibility for maintenance of international peace and security)", "3. Economic and Social Council (ECOSOC - 54 members)", "4. Trusteeship Council (suspended operations in 1994 after Palau's independence)", "5. International Court of Justice (ICJ - 'World Court', situated at Peace Palace in The Hague, Netherlands)", "6. Secretariat (headed by the Secretary-General, currently António Guterres of Portugal)"],
        "concepts_hi": ["संयुक्त राष्ट्र की स्थापना: असफल राष्ट्र संघ के स्थान पर; 26 जून 1945 को सैन फ्रांसिस्को सम्मेलन में 50 देशों द्वारा यूएन चार्टर पर हस्ताक्षर (भारत ने 15 अक्टूबर 1945 को मूल संस्थापक के रूप में हस्ताक्षर किए, प्रतिनिधि सर अर्कोट रामासामी मुदलियार); 24 अक्टूबर 1945 को चार्टर लागू हुआ (प्रतिवर्ष 24 अक्टूबर को 'संयुक्त राष्ट्र दिवस' मनाया जाता है)", "मुख्यालय: न्यूयॉर्क शहर (मैनहट्टन); यूरोपीय कार्यालय जिनेवा, वियना और नैरोबी में", "संयुक्त राष्ट्र के छह (6) प्रमुख अंग (चार्टर का अनुच्छेद 7):", "1. महासभा (General Assembly - 'विश्व की संसद', सभी 193 सदस्य देशों को 1-राष्ट्र 1-वोट का समान अधिकार)", "2. सुरक्षा परिषद (Security Council - अंतरराष्ट्रीय शांति और सुरक्षा का मुख्य संरक्षक)", "3. आर्थिक एवं सामाजिक परिषद (ECOSOC - 54 सदस्य)", "4. न्यास परिषद (Trusteeship Council - 1994 में पलाऊ की स्वतंत्रता के बाद कार्य स्थगित)", "5. अंतर्राष्ट्रीय न्यायालय (ICJ - 'विश्व अदालत', इसका मुख्यालय हेग, नीदरलैंड के शांति महल में है)", "6. सचिवालय (महासचिव के अधीन, वर्तमान महासचिव एंटोनियो गुटेरेस)"],
        "q_en": "Which of the six principal organs of the United Nations is the ONLY one physically located outside the United States, situated at the Peace Palace in The Hague, Netherlands?",
        "q_hi": "संयुक्त राष्ट्र के छह प्रमुख अंगों में से वह एकमात्र अंग कौन सा है, जिसका मुख्यालय अमेरिका (न्यूयॉर्क) से बाहर नीदरलैंड के हेग में 'शांति महल' (Peace Palace) में स्थित है?",
        "options_en": ["International Court of Justice / ICJ (अंतर्राष्ट्रीय न्यायालय - हेग, नीदरलैंड)", "General Assembly", "Security Council", "Economic and Social Council"],
        "options_hi": ["अंतर्राष्ट्रीय न्यायालय (International Court of Justice - ICJ)", "संयुक्त राष्ट्र महासभा (UNGA - न्यूयॉर्क)", "संयुक्त राष्ट्र सुरक्षा परिषद (UNSC - न्यूयॉर्क)", "आर्थिक एवं सामाजिक परिषद (ECOSOC - न्यूयॉर्क)"],
        "correct_idx": 0,
        "exp_en": "The International Court of Justice (ICJ) is the principal judicial organ of the UN, established in June 1945 at the Peace Palace in The Hague, Netherlands, whereas the other five organs are located at UN Headquarters in New York.",
        "exp_hi": "अंतर्राष्ट्रीय न्यायालय (ICJ) संयुक्त राष्ट्र का एकमात्र मुख्य अंग है जो न्यूयॉर्क में नहीं, बल्कि द हेग (नीदरलैंड) में स्थित है; इसमें 15 न्यायाधीश 9 वर्ष के कार्यकाल हेतु चुने जाते हैं।",
        "cue_en": "ICJ headquarters = Peace Palace, The Hague, Netherlands.",
        "cue_hi": "अंतर्राष्ट्रीय न्यायालय (ICJ) = हेग, नीदरलैंड।",
        "wrong_en": ["Principal judicial organ located in The Hague.", "Located at UN Headquarters, New York.", "Located at UN Headquarters, New York.", "Located at UN Headquarters, New York."],
        "wrong_hi": ["हेग स्थित न्यायिक अंग।", "न्यूयॉर्क स्थित महासभा।", "न्यूयॉर्क स्थित सुरक्षा परिषद।", "न्यूयॉर्क स्थित इकोसॉक।"]
    },
    {
        "name_en": "UN Security Council (UNSC): P5 Permanent Members, The Veto Power & G4 Nations Demand for Reform",
        "name_hi": "संयुक्त राष्ट्र सुरक्षा परिषद (UNSC): P5 स्थायी सदस्य, वीटो शक्ति एवं G4 देशों द्वारा सुधार की मांग",
        "concepts_en": ["UNSC Composition (15 total members): 5 Permanent Members (P5: United States, United Kingdom, France, Russia [inherited USSR seat 1991], China [PRC replaced Taiwan/ROC in 1971]) and 10 Non-Permanent Members elected by the UNGA for 2-year terms on regional quota (India has served 8 terms, most recently 2021-2022)", "The Veto Power: Granted exclusively to the P5 under Article 27(3) of the UN Charter; any single negative vote by a P5 member blocks the adoption of any substantive resolution, regardless of international majority support (abstention is not a veto)", "Demand for UNSC Expansion & Reform:", "G4 Nations (India, Japan, Germany, Brazil): Coalition mutually supporting each other's bids for permanent seats with veto powers in an expanded Security Council", "Coffee Club / Uniting for Consensus (UfC): Coalition led by Italy, Pakistan, Mexico, and Argentina opposing expansion of permanent seats"],
        "concepts_hi": ["सुरक्षा परिषद की संरचना (कुल 15 सदस्य): 5 स्थायी सदस्य (P5: अमेरिका, ब्रिटेन, फ्रांस, रूस [1991 में सोवियत संघ की सीट ली] और चीन [1971 में ताइवान के स्थान पर]) तथा 10 अस्थायी सदस्य जो महासभा द्वारा 2-वर्षीय कार्यकाल के लिए चुने जाते हैं (भारत अब तक 8 बार अस्थायी सदस्य रह चुका है, पिछली बार 2021-22)", "वीटो शक्ति (Veto Power): चार्टर के अनुच्छेद 27(3) के तहत केवल P5 देशों को प्राप्त विशेषाधिकार; यदि 5 में से कोई भी एक देश 'नकारात्मक वोट' (वीटो) दे दे, तो बाकी 14 सदस्यों की सहमति के बावजूद प्रस्ताव स्वतः निरस्त हो जाता है", "सुरक्षा परिषद सुधार और G4 समूह:", "G4 समूह (भारत, जापान, जर्मनी, ब्राजील): एक-दूसरे को स्थायी सदस्यता दिलाने हेतु प्रयासरत चार प्रमुख देशों का गठबंधन", "कॉफी क्लब (Uniting for Consensus): इटली और पाकिस्तान के नेतृत्व वाला समूह जो स्थायी सीटों के विस्तार का विरोध करता है"],
        "q_en": "Which coalition of four influential nations, comprising India, Japan, Germany, and Brazil, works collectively to campaign for permanent seats on an expanded United Nations Security Council (UNSC)?",
        "q_hi": "भारत, जापान, जर्मनी और ब्राजील का वह कौन सा चार देशों का समूह (गठबंधन) है, जो संयुक्त राष्ट्र सुरक्षा परिषद (UNSC) में स्थायी सदस्यता प्राप्त करने हेतु साझा प्रयास कर रहा है?",
        "options_en": ["G4 Nations (G4 समूह - भारत, जापान, जर्मनी, ब्राजील)", "G7 Group", "BRICS Group", "Coffee Club"],
        "options_hi": ["G4 समूह (G4 Nations - India, Japan, Germany, Brazil)", "G7 समूह (विश्व की सात प्रमुख विकसित अर्थव्यवस्थाएं)", "ब्रिक्स समूह (BRICS)", "कॉफी क्लब (यह G4 की स्थायी सदस्यता का विरोध करने वाला समूह है)"],
        "correct_idx": 0,
        "exp_en": "The G4 nations (India, Germany, Japan, and Brazil) mutually support each other's legitimate bids for permanent seats on the UN Security Council as part of comprehensive multilateral reform.",
        "exp_hi": "G4 समूह (Group of Four) में भारत, जापान, जर्मनी और ब्राजील शामिल हैं; ये चारों देश सुरक्षा परिषद को समकालीन वैश्विक वास्तविकताओं के अनुरूप बनाने के लिए स्थायी सीट की मांग कर रहे हैं।",
        "cue_en": "UNSC permanent seat hopefuls = G4 (India, Japan, Germany, Brazil).",
        "cue_hi": "सुरक्षा परिषद स्थायी सीट के दावेदार = G4 (भारत, जापान, जर्मनी, ब्राजील)।",
        "wrong_en": ["UNSC permanent seat aspirant bloc.", "Advanced industrialized democratic economies.", "Emerging market bloc.", "Opposing group led by Italy and Pakistan."],
        "wrong_hi": ["स्थायी सीट हेतु G4 समूह।", "जी7 समूह।", "ब्रिक्स समूह।", "विरोध करने वाला कॉफी क्लब।"]
    },
    {
        "name_en": "UN Specialized Agencies: UNESCO, WHO, ILO, UNICEF & UNHCR Mandates",
        "name_hi": "संयुक्त राष्ट्र की प्रमुख विशिष्ट एजेंसियां: यूनेस्को, डब्ल्यूएचओ, आईएलओ, यूनिसेफ एवं यूएनएचसीआर",
        "concepts_en": ["Autonomous international organizations linked to the UN through the Economic and Social Council (ECOSOC):", "1. UNESCO (UN Educational, Scientific and Cultural Organization, 1945): Headquarters in Paris, France; designates World Heritage Sites, Intangible Cultural Heritage, and Biosphere Reserves", "2. WHO (World Health Organization, April 7, 1948): Headquarters in Geneva, Switzerland; World Health Day celebrated on April 7; eradicates epidemics (Smallpox 1980), declared COVID-19 pandemic", "3. ILO (International Labour Organization, 1919): Headquarters in Geneva; created by Treaty of Versailles (oldest UN specialized agency); won Nobel Peace Prize in 1969; tri-partite structure (governments, employers, workers)", "4. UNICEF (UN Children's Fund, 1946): Headquarters in New York; child welfare, nutrition, and vaccination; won Nobel Peace Prize in 1965", "5. UNHCR (UN High Commissioner for Refugees, 1950): Headquarters in Geneva; won Nobel Peace Prize twice (1954 and 1981)"],
        "concepts_hi": ["इकोसॉक (ECOSOC) के माध्यम से संयुक्त राष्ट्र से जुड़ी स्वायत्त अंतरराष्ट्रीय संस्थाएं:", "1. यूनेस्को (UNESCO, 1945): मुख्यालय पेरिस (फ्रांस); विश्व धरोहर स्थल, अमूर्त सांस्कृतिक धरोहर और बायोस्फीयर रिज़र्व की मान्यता", "2. विश्व स्वास्थ्य संगठन (WHO, 7 अप्रैल 1948): मुख्यालय जिनेवा (स्विट्जरलैंड); प्रतिवर्ष 7 अप्रैल को 'विश्व स्वास्थ्य दिवस'; 1980 में चेचक उन्मूलन; वैश्विक स्वास्थ्य मानकों का निर्धारण", "3. अंतर्राष्ट्रीय श्रम संगठन (ILO, 1919): मुख्यालय जिनेवा; वर्साय की संधि द्वारा स्थापित (संयुक्त राष्ट्र की सबसे पुरानी एजेंसी); 1969 में नोबेल शांति पुरस्कार; त्रिपक्षीय ढांचा (सरकार, नियोक्ता व श्रमिक)", "4. यूनिसेफ (UNICEF, 1946): मुख्यालय न्यूयॉर्क; बाल अधिकारों, पोषण व टीकाकरण हेतु समर्पित; 1965 में नोबेल शांति पुरस्कार", "5. यूएनएचसीआर (UNHCR, 1950): मुख्यालय जिनेवा; शरणार्थियों के संरक्षण हेतु समर्पित संस्था (1954 व 1981 में दो बार नोबेल शांति पुरस्कार विजेता)"],
        "q_en": "In which European capital city is the global headquarters of the United Nations Educational, Scientific and Cultural Organization (UNESCO) situated?",
        "q_hi": "विश्व भर में ऐतिहासिक धरोहर स्थलों और सांस्कृतिक विविधता का संरक्षण करने वाली संस्था 'यूनेस्को' (UNESCO) का वैश्विक मुख्यालय किस यूरोपीय शहर में स्थित है?",
        "options_en": ["Paris, France (पेरिस, फ्रांस)", "Geneva, Switzerland", "Vienna, Austria", "Rome, Italy"],
        "options_hi": ["पेरिस, फ्रांस (Paris, France)", "जिनेवा, स्विट्जरलैंड (यहां WHO, ILO, UNHCR स्थित हैं)", "वियना, ऑस्ट्रिया (यहां IAEA स्थित है)", "रोम, इटली (यहां FAO और WFP स्थित हैं)"],
        "correct_idx": 0,
        "exp_en": "UNESCO is headquartered in Paris, France (Place de Fontenoy), established in 1945 to promote peace and security through international educational, scientific, and cultural collaboration.",
        "exp_hi": "यूनेस्को (UNESCO) का मुख्यालय पेरिस (फ्रांस) में स्थित है। (खाद्य एवं कृषि संगठन FAO का मुख्यालय रोम में और परमाणु ऊर्जा एजेंसी IAEA का मुख्यालय वियना में है)।",
        "cue_en": "UNESCO headquarters = Paris, France.",
        "cue_hi": "यूनेस्को का मुख्यालय = पेरिस, फ्रांस।",
        "wrong_en": ["Headquarters city of UNESCO.", "Headquarters of WHO, ILO, WTO, and UNHCR.", "Headquarters of IAEA and UNODC.", "Headquarters of FAO and WFP."],
        "wrong_hi": ["यूनेस्को का मुख्यालय शहर।", "जिनेवा (WHO, ILO)।", "वियना (IAEA)।", "रोम (FAO)।"]
    },
    {
        "name_en": "UN Peacekeeping Operations: 'Blue Helmets', Dag Hammarskjöld Medal & India's Historic Contributions",
        "name_hi": "संयुक्त राष्ट्र शांति सेना: 'ब्लू हेलमेट्स', डैग हैमरशोल्ड पदक एवं भारत का ऐतिहासिक शांति योगदान",
        "concepts_en": ["UN Peacekeeping ('Blue Helmets' / 'Blue Berets'): Deployed under Chapter VI (Pacific Settlement) and Chapter VII (Action regarding Threats to Peace) of UN Charter; mandates authorized by UNSC", "Three core guiding principles: Consent of the main parties, Impartiality, and Non-use of force except in self-defence and defence of the mandate; won the Nobel Peace Prize in 1988", "Dag Hammarskjöld Medal: Posthumous award established in 1997 honoring peacekeepers who lost their lives in service, named after the second UN Secretary-General who died in a 1961 plane crash in Northern Rhodesia (Zambia)", "India's Stellar Contribution: India is historically the LARGEST cumulative troop-contributing nation to UN peacekeeping (over 280,000 personnel in 50+ missions); deployed the world's FIRST all-female formed police unit (FPU) to Liberia in 2007 (commanded by Seema Dhundia); over 180 Indian peacekeepers have made the supreme sacrifice (highest among all nations)"],
        "concepts_hi": ["संयुक्त राष्ट्र शांति सेना ('ब्लू हेलमेट्स' / नीली टोपी वाले): सुरक्षा परिषद के प्रस्तावों द्वारा संकटग्रस्त देशों में शांति स्थापना हेतु तैनात; 1988 में नोबेल शांति पुरस्कार से सम्मानित", "तीन मार्गदर्शक सिद्धांत: पक्षों की सहमति, निष्पक्षता एवं केवल आत्मरक्षा या जनादेश की रक्षा में ही बल प्रयोग", "डैग हैमरशोल्ड पदक: शांति अभियानों में सर्वोच्च बलिदान देने वाले जवानों को मरणोपरांत दिया जाने वाला सम्मान; संयुक्त राष्ट्र के दूसरे महासचिव डैग हैमरशोल्ड की याद में (जिनकी 1961 में जाम्बिया में विमान दुर्घटना में मृत्यु हुई थी)", "भारत का अतुलनीय योगदान: भारत संयुक्त राष्ट्र शांति सेना में इतिहास में सबसे अधिक सैनिक भेजने वाला देश है (2.8 लाख से अधिक जवान 50 से अधिक मिशनों में); 2007 में लाइबेरिया में विश्व की पहली 100% महिला शांति पुलिस टुकड़ी (FPU) भारत ने ही भेजी थी; 180 से अधिक भारतीय जवानों ने शांति की वेदी पर सर्वोच्च बलिदान दिया है"],
        "q_en": "In 2007, India made global peacekeeping history by deploying the world's very FIRST all-female Formed Police Unit (FPU) to which West African nation's UN peacekeeping mission?",
        "q_hi": "वर्ष 2007 में भारत ने संयुक्त राष्ट्र शांति स्थापना के इतिहास में पहली बार किस पश्चिमी अफ्रीकी देश के शांति मिशन में विश्व की पहली 'पूर्णतः महिला पुलिस टुकड़ी' (All-Female Formed Police Unit) तैनात कर विश्व कीर्तिमान स्थापित किया था?",
        "options_en": ["Liberia (लाइबेरिया - UNMIL)", "Sierra Leone", "Congo (DRC)", "Sudan"],
        "options_hi": ["लाइबेरिया (Liberia - UNMIL मिशन 2007)", "सिएरा लियोन (Sierra Leone)", "कांगो (DRC)", "सूडान (Sudan)"],
        "correct_idx": 0,
        "exp_en": "In 2007, India deployed the first-ever all-female Formed Police Unit to the UN Mission in Liberia (UNMIL), widely lauded by President Ellen Johnson Sirleaf for inspiring Liberian women to join the national police.",
        "exp_hi": "भारत ने 2007 में सीआरपीएफ की 125 जांबाज महिला जवानों की टुकड़ी को लाइबेरिया (UNMIL) में तैनात किया था; यह संयुक्त राष्ट्र के इतिहास में पहली बार था जब किसी देश ने 100% महिला सैन्य/पुलिस दस्ता भेजा।",
        "cue_en": "First all-female UN peacekeeping unit = India to Liberia (2007).",
        "cue_hi": "पहली पूर्ण महिला शांति सेना टुकड़ी = भारत द्वारा लाइबेरिया (2007)।",
        "wrong_en": ["Historic destination of India's all-female FPU.", "Site of earlier UNAMSIL mission.", "Site of MONUSCO mission.", "Site of UNMIS mission."],
        "wrong_hi": ["लाइबेरिया (सही उत्तर)।", "सिएरा लियोन।", "कांगो शांति मिशन।", "सूडान।"]
    }
]

# S16-C3cea2eaa Bretton Woods Institutions: World Bank Group & IMF Structure (3 topics)
DATA["S16-C3cea2eaa"] = [
    {
        "name_en": "The Bretton Woods Conference (1944): Genesis of IMF, World Bank & John Maynard Keynes",
        "name_hi": "ब्रेटन वुड्स सम्मेलन (1944): आईएमएफ (IMF) एवं विश्व बैंक का जन्म तथा जॉन मेनार्ड कीन्स",
        "concepts_en": ["United Nations Monetary and Financial Conference: Held in July 1944 at the Mount Washington Hotel in Bretton Woods, New Hampshire, USA; attended by 730 delegates from 44 Allied nations (including British India, represented by Sir C.D. Deshmukh, who later became first Indian RBI Governor)", "Architects: John Maynard Keynes (leading British delegation, proposed Bancor international currency) and Harry Dexter White (leading US Treasury, proposed US dollar-gold standard at $35/ounce)", "Created the 'Bretton Woods Twins':", "1. International Monetary Fund (IMF): To oversee international monetary stability, exchange rates, and provide balance-of-payments crisis lending", "2. International Bank for Reconstruction and Development (IBRD / World Bank): To finance post-war reconstruction of war-torn Europe and long-term economic development of poor nations", "Headquarters of both established in Washington, D.C., USA (convention: World Bank President is always an American, IMF Managing Director is always a European)"],
        "concepts_hi": ["ब्रेटन वुड्स सम्मेलन (जुलाई 1944): न्यू हैम्पशायर (अमेरिका) के माउंट वाशिंगटन होटल में 44 मित्र राष्ट्रों का मौद्रिक सम्मेलन (भारत का प्रतिनिधित्व सर सी.डी. देशमुख ने किया था, जो बाद में स्वतंत्र भारत के पहले भारतीय RBI गवर्नर बने)", "सम्मेलन के दो मुख्य वास्तुकार: जॉन मेनार्ड कीन्स (ब्रिटेन - जिन्होंने 'बैंकर' वैश्विक मुद्रा का प्रस्ताव दिया) एवं हैरी डेक्सटर व्हाइट (अमेरिका - जिन्होंने डॉलर-गोल्ड मानक तय कराया)", "'ब्रेटन वुड्स जुड़वां' (Bretton Woods Twins) संस्थाओं की स्थापना:", "1. अंतर्राष्ट्रीय मुद्रा कोष (IMF): विनिमय दर स्थिरता और देशों के भुगतान संतुलन (BoP) संकट में अल्पकालिक ऋण देने हेतु", "2. विश्व बैंक (IBRD): युद्ध से तबाह यूरोप के पुनर्निर्माण और विकासशील देशों में दीर्घकालिक विकास परियोजनाओं हेतु ऋण देने हेतु", "दोनों का मुख्यालय: वाशिंगटन, डी.सी. (परंपरा: विश्व बैंक का अध्यक्ष अमेरिकी और आईएमएफ का प्रबंध निदेशक यूरोपीय होता है)"],
        "q_en": "In which American town was the historic 1944 United Nations Monetary and Financial Conference held that created the 'Bretton Woods Twins' (the IMF and the World Bank)?",
        "q_hi": "1944 में वह ऐतिहासिक मौद्रिक सम्मेलन अमेरिका के किस शहर में आयोजित हुआ था, जिसने 'ब्रेटन वुड्स जुड़वां' (आईएमएफ और विश्व बैंक) की स्थापना की थी?",
        "options_en": ["Bretton Woods, New Hampshire (ब्रेटन वुड्स, न्यू हैम्पशायर)", "San Francisco, California", "New York City", "Geneva, Switzerland"],
        "options_hi": ["ब्रेटन वुड्स, न्यू हैम्पशायर (Bretton Woods, New Hampshire)", "सैन फ्रांसिस्को (यहां 1945 में यूएन चार्टर बना था)", "न्यूयॉर्क शहर", "जिनेवा, स्विट्जरलैंड"],
        "correct_idx": 0,
        "exp_en": "The 1944 conference took place at Bretton Woods, New Hampshire, establishing the post-World War II global financial architecture, the International Monetary Fund, and the World Bank.",
        "exp_hi": "जुलाई 1944 में न्यू हैम्पशायर के 'ब्रेटन वुड्स' में 44 देशों के प्रतिनिधियों ने मिलकर वैश्विक वित्तीय व्यवस्था और आईएमएफ व विश्व बैंक की स्थापना का ऐतिहासिक फैसला किया था।",
        "cue_en": "Birthplace of IMF and World Bank = Bretton Woods (1944).",
        "cue_hi": "आईएमएफ व विश्व बैंक का जन्मस्थान = ब्रेटन वुड्स (1944)।",
        "wrong_en": ["Site of 1944 monetary conference.", "Site of 1945 UN Charter conference.", "Site of UN Headquarters.", "European multilateral center."],
        "wrong_hi": ["ब्रेटन वुड्स सम्मेलन स्थल।", "सैन फ्रांसिस्को (यूएन सम्मेलन)।", "न्यूयॉर्क।", "जिनेवा।"]
    },
    {
        "name_en": "The World Bank Group: Five Distinct Institutions (IBRD, IDA, IFC, MIGA & ICSID)",
        "name_hi": "विश्व बैंक समूह (World Bank Group): 5 विशिष्ट संस्थाएं (आईबीआरडी, आईडीए, आईएफसी, मीगा एवं आईसीएसआईडी)",
        "concepts_en": ["The World Bank Group comprises FIVE closely affiliated international development institutions (President: Ajay Banga, Indian-American appointed 2023):", "1. IBRD (International Bank for Reconstruction and Development, 1944): Lends to middle-income and creditworthy poorer governments for development infrastructure (market-linked rates)", "2. IDA (International Development Association, 1960): 'Soft Loan Window' of the World Bank; provides zero-interest credits (concessional loans with 30-40 year maturities) and grants to the world's 75 poorest nations", "3. IFC (International Finance Corporation, 1956): Private sector arm; invests directly in private commercial enterprises in developing countries without government guarantees", "4. MIGA (Multilateral Investment Guarantee Agency, 1988): Provides political risk insurance and credit enhancement against non-commercial risks (war, expropriation, currency inconvertibility) to foreign investors", "5. ICSID (International Centre for Settlement of Investment Disputes, 1966): Conciliation and arbitration of investment disputes between foreign investors and host states (NOTE: India is NOT a member of ICSID, citing pro-investor bias)"],
        "concepts_hi": ["विश्व बैंक समूह में पांच (5) प्रमुख अंतरराष्ट्रीय विकास संस्थाएं शामिल हैं (वर्तमान अध्यक्ष: भारतीय-अमेरिकी अजय बंगा, 2023 में नियुक्त):", "1. आईबीआरडी (IBRD, 1944): मध्यम आय वाले और साख वाले विकासशील देशों की सरकारों को बुनियादी ढांचे हेतु ऋण देना", "2. आईडीए (IDA, 1960): विश्व बैंक की 'सॉफ्ट लोन विंडो' (रियायती खिड़की); विश्व के सबसे गरीब देशों को शून्य ब्याज पर 30-40 वर्षों के दीर्घकालिक ऋण और अनुदान प्रदान करना", "3. आईएफसी (IFC, 1956): निजी क्षेत्र की शाखा; विकासशील देशों में बिना सरकारी गारंटी के सीधे निजी कंपनियों व उद्योगों में निवेश करना", "4. मीगा (MIGA, 1988): विकासशील देशों में निवेश करने वाले विदेशी निवेशकों को राजनीतिक जोखिम (युद्ध, जब्ती आदि) के विरुद्ध बीमा गारंटी प्रदान करना", "5. आईसीएसआईडी (ICSID, 1966): विदेशी निवेशकों और सरकारों के बीच निवेश विवादों का निपटारा (विशेष तथ्य: भारत ICSID का सदस्य नहीं है, क्योंकि भारत इसे निष्पक्ष नहीं मानता)"],
        "q_en": "Which institution within the World Bank Group is universally termed the 'Soft Loan Window' for extending zero-interest, long-term concessional credits and grants to the world's poorest developing nations?",
        "q_hi": "विश्व बैंक समूह की वह कौन सी संस्था है, जिसे विश्व के सबसे निर्धन विकासशील देशों को बिना किसी ब्याज के दीर्घकालिक रियायती ऋण और अनुदान देने के कारण 'सॉफ्ट लोन विंडो' (रियायती ऋण खिड़की) कहा जाता है?",
        "options_en": ["International Development Association / IDA (अंतर्राष्ट्रीय विकास संघ)", "International Finance Corporation (IFC)", "Multilateral Investment Guarantee Agency (MIGA)", "International Bank for Reconstruction and Development (IBRD)"],
        "options_hi": ["अंतर्राष्ट्रीय विकास संघ (IDA - Soft Loan Window)", "अंतर्राष्ट्रीय वित्त निगम (IFC - यह निजी क्षेत्र की शाखा है)", "बहुपक्षीय निवेश गारंटी एजेंसी (MIGA - यह बीमा देती है)", "पुनर्निर्माण एवं विकास हेतु अंतर्राष्ट्रीय बैंक (IBRD)"],
        "correct_idx": 0,
        "exp_en": "The International Development Association (IDA), established in 1960, is the World Bank's fund for the poorest countries, providing zero-to-low interest loans ('credits') with long grace periods, termed the 'soft loan window'.",
        "exp_hi": "आईडीए (IDA) को विश्व बैंक की 'सॉफ्ट लोन विंडो' कहा जाता है क्योंकि यह सबसे गरीब देशों को 30 से 40 वर्ष की लंबी अवधि के लिए बिना ब्याज के रियायती ऋण देता है।",
        "cue_en": "Soft Loan Window of World Bank = IDA (International Development Association).",
        "cue_hi": "विश्व बैंक की सॉफ्ट लोन विंडो = आईडीए (IDA)।",
        "wrong_en": ["World Bank's soft loan window.", "Private sector commercial arm.", "Political risk insurance agency.", "Hard loan window for middle-income nations."],
        "wrong_hi": ["सॉफ्ट लोन विंडो (आईडीए)।", "निजी क्षेत्र की संस्था (आईएफसी)।", "बीमा एजेंसी (मीगा)।", "मध्यम आय देशों हेतु बैंक (आईबीआरडी)।"]
    },
    {
        "name_en": "International Monetary Fund (IMF): Quota System, Balance of Payments Crisis Lending & Special Drawing Rights",
        "name_hi": "अंतर्राष्ट्रीय मुद्रा कोष (IMF): कोटा प्रणाली, भुगतान संतुलन (BoP) संकट ऋण एवं एसडीआर संरचना",
        "concepts_en": ["IMF Purpose: Fosters global monetary cooperation, secures financial stability, facilitates international trade, promotes sustainable economic growth, and provides financial safety nets during Balance of Payments (BoP) crises; Managing Director: Kristalina Georgieva (Bulgaria); Chief Economist previously held by Raghuram Rajan and Gita Gopinath (currently First Deputy Managing Director)", "Quota System: Each member is assigned a quota based broadly on its relative size in the world economy (GDP, openness, economic variability, international reserves); Quotas determine:", "1. Voting power (United States holds largest voting share ~16.5%, giving it an effective unilateral VETO over major structural decisions requiring 85% supermajority)", "2. Maximum financial commitment to the IMF", "3. Maximum access to IMF financial resources", "Conditionality: Structural adjustment programs attached to IMF bailout packages (fiscal austerity, privatization, currency depreciation)", "Special Drawing Rights (SDR): Supplementary reserve asset created in 1969 to support liquidity"],
        "concepts_hi": ["आईएमएफ का मूल उद्देश्य: वैश्विक वित्तीय स्थिरता, अंतरराष्ट्रीय व्यापार का सुचारु संचालन और भुगतान संतुलन (Balance of Payments) के गंभीर संकट से जूझ रहे देशों को आपातकालीन वित्तीय बेलआउट पैकेज देना; प्रबंध निदेशक: क्रिस्टालिना जॉर्जीवा; गीता गोपीनाथ प्रथम उप-प्रबंध निदेशक (FDMD)", "कोटा प्रणाली (Quota System): प्रत्येक सदस्य देश को उसकी जीडीपी और विदेशी व्यापार के आकार के अनुसार एक कोटा आवंटित किया जाता है; कोटा तय करता है:", "1. मताधिकार प्रतिशत (अमेरिका के पास 16.5% वोट शेयर है, जिससे 85% बहुमत वाले किसी भी बड़े निर्णय पर अमेरिका के पास अकेला वीटो अधिकार है)", "2. आईएमएफ में देश का वित्तीय योगदान", "3. आपातकाल में देश द्वारा लिए जा सकने वाले ऋण की अधिकतम सीमा", "शर्तें (Conditionality): आईएमएफ ऋण के साथ वित्तीय अनुशासन, खर्चों में कटौती (Austerity) और सुधारों की कड़ी शर्तें जोड़ता है"],
        "q_en": "Because major structural decisions, constitutional amendments, and quota revisions at the International Monetary Fund (IMF) require an 85% supermajority, which single member country possesses an effective unilateral VETO power with its >16% voting share?",
        "q_hi": "चूंकि अंतर्राष्ट्रीय मुद्रा कोष (IMF) में महत्वपूर्ण नीतिगत निर्णयों और कोटा संशोधनों हेतु 85% विशेष बहुमत आवश्यक होता है, अतः 16% से अधिक वोट शेयर के साथ किस एकमात्र देश के पास व्यावहारिक रूप से एकतरफा 'वीटो अधिकार' है?",
        "options_en": ["United States of America (संयुक्त राज्य अमेरिका - ~16.5% वोट शेयर)", "China", "Japan", "Germany"],
        "options_hi": ["संयुक्त राज्य अमेरिका (United States of America - ~16.5% मताधिकार)", "चीन (China - ~6% मताधिकार)", "जापान (Japan - ~6.4% मताधिकार)", "जर्मनी"],
        "correct_idx": 0,
        "exp_en": "The United States holds 16.5% of the total voting power in the IMF. Since key charter changes and quota allocations require an 85% supermajority, the US alone can unilaterally block any major IMF reform.",
        "exp_hi": "आईएमएफ में अमेरिका का वोटिंग शेयर 16.5% है; चूंकि महत्वपूर्ण फैसलों हेतु 85% वोट अनिवार्य हैं, अतः अमेरिका के समर्थन के बिना कोई भी बड़ा संशोधन पारित नहीं हो सकता, जिससे अमेरिका को प्रभावी वीटो प्राप्त है।",
        "cue_en": "Sole country with veto power in IMF = United States (>16% voting share).",
        "cue_hi": "आईएमएफ में वीटो शक्ति वाला एकमात्र देश = अमेरिका।",
        "wrong_en": ["Sole nation with >15% voting share to veto 85% decisions.", "Second largest economy, but holds only ~6% voting share.", "Second largest quota holder, holds ~6.4%.", "Holds ~5.6% voting share."],
        "wrong_hi": ["वीटो शक्ति संपन्न अमेरिका।", "चीन (केवल ~6%)।", "जापान (~6.4%)।", "जर्मनी (~5.6%)।"]
    }
]

# S16-C865f07fa Global & Regional Blocs: G20, BRICS, ASEAN, SCO & WTO (2 topics)
DATA["S16-C865f07fa"] = [
    {
        "name_en": "The Group of Twenty (G20): Structure, Troika, New Delhi Leaders' Declaration (2023) & African Union Entry",
        "name_hi": "जी20 (G20) समूह: संरचना, ट्रायका, नई दिल्ली घोषणापत्र (2023) एवं अफ्रीकी संघ (AU) का ऐतिहासिक प्रवेश",
        "concepts_en": ["G20: Founded in 1999 following Asian Financial Crisis as a forum for Finance Ministers and Central Bank Governors; elevated to Leaders' Summit level in 2008 following global financial crisis; accounts for 85% of global GDP, 75% of global trade, and two-thirds of world population; has NO permanent secretariat; operates under rotating annual Presidency and 'Troika' (previous, current, and upcoming host nations)", "18th G20 Summit in New Delhi (September 9-10, 2023 under India's Presidency): Theme: 'Vasudhaiva Kutumbakam' (One Earth, One Family, One Future, drawn from Maha Upanishad); held at Bharat Mandapam, Pragati Maidan", "Historic Breakthroughs of New Delhi Summit:", "1. Admission of the African Union (AU - 55 African nations) as a permanent full member of the G20, formally transforming the grouping into G21", "2. 100% consensus on the New Delhi Leaders' Declaration (73 paragraphs, zero dissents/footnotes despite geopolitical tensions)", "3. Launch of the India-Middle East-Europe Economic Corridor (IMEC) and Global Biofuels Alliance (GBA)"],
        "concepts_hi": ["जी20 (G20): 1999 में एशियाई वित्तीय संकट के बाद वित्त मंत्रियों के मंच के रूप में गठित; 2008 की वैश्विक मंदी के बाद राष्ट्राध्यक्षों के शिखर सम्मेलन में बदला गया; विश्व की 85% जीडीपी, 75% व्यापार और दो-तिहाई आबादी का प्रतिनिधित्व; इसका कोई स्थायी सचिवालय नहीं है; वार्षिक अध्यक्षता और 'ट्रायका' (पिछला, वर्तमान व अगला मेजबान) द्वारा संचालन", "18वां जी20 शिखर सम्मेलन, नई दिल्ली (9-10 सितंबर 2023, भारत की अध्यक्षता): विषय: 'वसुधैव कुटुंबकम्' (एक पृथ्वी, एक परिवार, एक भविष्य - महा उपनिषद से); आयोजन स्थल: भारत मंडपम, प्रगति मैदान", "नई दिल्ली शिखर सम्मेलन की ऐतिहासिक उपलब्धियां:", "1. अफ्रीकी संघ (African Union - 55 देशों का संगठन) को जी20 का स्थायी पूर्ण सदस्य बनाया गया (जिससे यह समूह व्यावहारिक रूप से G21 बन गया)", "2. 100% सर्वसम्मति से 'नई दिल्ली लीडर्स घोषणापत्र' अंगीकृत हुआ", "3. भारत-मध्य पूर्व-यूरोप आर्थिक गलियारा (IMEC) एवं वैश्विक जैव ईंधन गठबंधन (GBA) का शुभारंभ"],
        "q_en": "At the 18th G20 Summit hosted under India's Presidency in New Delhi in September 2023, which continental multilateral body comprising 55 member states was officially admitted as a permanent full member of the G20?",
        "q_hi": "सितंबर 2023 में भारत की अध्यक्षता में नई दिल्ली में आयोजित 18वें जी20 शिखर सम्मेलन में 55 सदस्य देशों वाले किस महाद्वीपीय संगठन को जी20 का स्थायी पूर्ण सदस्य बनाया गया?",
        "options_en": ["African Union / AU (अफ्रीकी संघ - 55 सदस्य देश)", "European Union (already a member)", "Association of Southeast Asian Nations (ASEAN)", "Organization of American States (OAS)"],
        "options_hi": ["अफ्रीकी संघ (African Union - AU)", "यूरोपीय संघ (यह पहले से ही सदस्य था)", "आसियान (ASEAN - यह केवल आमंत्रित अतिथि था)", "अमेरिकी राज्यों का संगठन (OAS)"],
        "correct_idx": 0,
        "exp_en": "Under India's G20 Presidency at the New Delhi Summit on September 9, 2023, the 55-nation African Union was formally inducted as a permanent member of the G20, matching the European Union.",
        "exp_hi": "भारत की ऐतिहासिक पहल पर 9 सितंबर 2023 को भारत मंडपम में अफ्रीकी संघ (AU) को जी20 का नया स्थायी सदस्य बनाया गया, जिससे वैश्विक मंच पर ग्लोबल साउथ (विकासशील देशों) की आवाज बुलंद हुई।",
        "cue_en": "New permanent member of G20 admitted at New Delhi 2023 = African Union (AU).",
        "cue_hi": "जी20 का नया स्थायी सदस्य (नई दिल्ली 2023) = अफ्रीकी संघ (AU)।",
        "wrong_en": ["Newly inducted permanent G20 member (2023).", "Founding institutional member of G20.", "Regional bloc invited as guest.", "Regional Americas body."],
        "wrong_hi": ["2023 में शामिल नया स्थायी सदस्य।", "यूरोपीय संघ (पुराना सदस्य)।", "आसियान।", "अमेरिकी संगठन।"]
    },
    {
        "name_en": "BRICS, Shanghai Cooperation Organisation (SCO) & ASEAN: Geopolitical Counterweights",
        "name_hi": "ब्रिक्स (BRICS - 2024 विस्तार), शंघाई सहयोग संगठन (SCO) एवं आसियान (ASEAN) क्षेत्रीय मंच",
        "concepts_en": ["BRICS: Acronym coined by Goldman Sachs economist Jim O'Neill in 2001 (BRIC); South Africa joined in 2010; New Development Bank (NDB, headquartered in Shanghai, first president K.V. Kamath); Historic 2024 Expansion (Johannesburg/Kazan): Admitted Egypt, Ethiopia, Iran, and UAE as new members on January 1, 2024", "SCO (Shanghai Cooperation Organisation): Founded in 2001 in Shanghai; political, economic, and security alliance; Secretariat in Beijing, RATS (Regional Anti-Terrorist Structure) in Tashkent; India and Pakistan became full members simultaneously at Astana Summit in 2017; Iran joined in 2023, Belarus in 2024", "ASEAN (Association of Southeast Asian Nations): Founded on August 8, 1967 via Bangkok Declaration; 10 member states; Secretariat in Jakarta, Indonesia; motto: 'One Vision, One Identity, One Community'; India has strategic partnership through 'Act East Policy'"],
        "concepts_hi": ["ब्रिक्स (BRICS): 2001 में जिम ओ'नील द्वारा गढ़ा गया शब्द; 2010 में दक्षिण अफ्रीका शामिल हुआ; न्यू डेवलपमेंट बैंक (NDB - मुख्यालय शंघाई, पहले अध्यक्ष के.वी. कामथ); 2024 का ऐतिहासिक विस्तार: 1 जनवरी 2024 को मिस्र, इथियोपिया, ईरान और संयुक्त अरब अमीरात (UAE) को नए सदस्य के रूप में शामिल किया गया", "शंघाई सहयोग संगठन (SCO): 2001 में शंघाई में स्थापित यूरेशियाई सुरक्षा व आर्थिक संगठन; सचिवालय बीजिंग में, रैट्स (RATS - आतंकवाद रोधी अंग) ताशकंद में; भारत और पाकिस्तान 2017 के अस्ताना शिखर सम्मेलन में एक साथ पूर्ण सदस्य बने; 2023 में ईरान और 2024 में बेलारूस शामिल हुआ", "आसियान (ASEAN): 8 अगस्त 1967 को बैंकॉक घोषणापत्र द्वारा स्थापित; 10 दक्षिण-पूर्वी एशियाई देश; मुख्यालय जकार्ता (इंडोनेशिया); भारत की 'एक्ट ईस्ट पॉलिसी' (Act East Policy) का केंद्रीय स्तंभ"],
        "q_en": "At which landmark summit in 2017 did both India and Pakistan officially and simultaneously become full members of the Shanghai Cooperation Organisation (SCO)?",
        "q_hi": "वर्ष 2017 के किस ऐतिहासिक शिखर सम्मेलन में भारत और पाकिस्तान दोनों को एक साथ औपचारिक रूप से 'शंघाई सहयोग संगठन' (SCO) की पूर्ण सदस्यता प्रदान की गई थी?",
        "options_en": ["Astana Summit, Kazakhstan (अस्ताना शिखर सम्मेलन, कजाकिस्तान - 2017)", "Samarkand Summit, Uzbekistan", "Ufa Summit, Russia", "Bishkek Summit, Kyrgyzstan"],
        "options_hi": ["अस्ताना शिखर सम्मेलन, कजाकिस्तान (Astana Summit - 2017)", "समरकंद शिखर सम्मेलन (2022)", "उफा शिखर सम्मेलन (2015)", "बिश्केक शिखर सम्मेलन (2019)"],
        "correct_idx": 0,
        "exp_en": "India and Pakistan officially signed the memorandum of obligations and were formally admitted as full members of the Shanghai Cooperation Organisation at the Astana Summit in Kazakhstan on June 9, 2017.",
        "exp_hi": "9 जून 2017 को कजाकिस्तान की राजधानी अस्ताना में आयोजित SCO शिखर सम्मेलन में भारत और पाकिस्तान को संगठन के पूर्ण सदस्य के रूप में आधिकारिक रूप से शामिल किया गया था।",
        "cue_en": "India & Pakistan joined SCO = Astana Summit (2017).",
        "cue_hi": "भारत व पाक SCO के सदस्य बने = अस्ताना शिखर सम्मेलन (2017)।",
        "wrong_en": ["Historic summit where India joined SCO.", "2022 summit held in Uzbekistan.", "2015 summit where entry process initiated.", "2019 summit held in Kyrgyzstan."],
        "wrong_hi": ["अस्ताना शिखर सम्मेलन (सही उत्तर)।", "समरकंद सम्मेलन।", "उफा सम्मेलन।", "बिश्केक सम्मेलन।"]
    }
]

print("Loaded S16 successfully")
