# build_curriculum/group2_s05.py
# S05: Indian Polity & Constitutional Framework (17 topics across 4 chapters)

DATA = {}

# S05-Cd1fc9546 Constitutional Evolution, Constituent Assembly & Preamble (3 topics)
DATA["S05-Cd1fc9546"] = [
    {
        "name_en": "Constitutional Evolution: Regulating Act 1773 to Government of India Act 1935",
        "name_hi": "संवैधानिक विकास: 1773 का रेगुलेटिंग एक्ट से 1935 का भारत शासन अधिनियम",
        "concepts_en": ["Regulating Act 1773 established Supreme Court at Calcutta and made Governor of Bengal the Governor-General", "Charter Act 1833 made Lord William Bentinck first Governor-General of India", "Indian Councils Act 1909 (Morley-Minto Reforms) introduced separate electorates for Muslims", "Government of India Act 1935 introduced Provincial Autonomy, All-India Federation and Bicameralism (major blueprint for 1950 Constitution)"],
        "concepts_hi": ["1773 का रेगुलेटिंग एक्ट: कलकत्ता में सर्वोच्च न्यायालय की स्थापना व वारेन हेस्टिंग्स पहले गवर्नर-जनरल बने", "1833 का चार्टर एक्ट: लॉर्ड विलियम बेंटिंक भारत के पहले गवर्नर-जनरल बने", "1909 का मार्ले-मिंटो सुधार: मुसलमानों के लिए पृथक निर्वाचक मंडल की शुरुआत", "1935 का भारत शासन अधिनियम: प्रांतीय स्वायत्तता, अखिल भारतीय संघ व द्विसदनीय व्यवस्था (संविधान का मुख्य आधार)"],
        "q_en": "Which constitutional enactment served as the primary administrative blueprint, contributing roughly two-thirds of the provisions of the 1950 Constitution of India?",
        "q_hi": "1950 के भारतीय संविधान का प्राथमिक प्रशासनिक ढांचा किस अधिनियम पर आधारित था, जिससे संविधान के लगभग दो-तिहाई प्रावधान लिए गए हैं?",
        "options_en": ["Government of India Act 1935 (भारत शासन अधिनियम 1935)", "Government of India Act 1919", "Indian Independence Act 1947", "Cabinet Mission Plan 1946"],
        "options_hi": ["भारत शासन अधिनियम 1935 (Government of India Act 1935)", "भारत शासन अधिनियम 1919", "भारतीय स्वतंत्रता अधिनियम 1947", "कैबिनेट मिशन योजना 1946"],
        "correct_idx": 0,
        "exp_en": "The Government of India Act 1935 served as the bedrock for the structural, administrative, and federal provisions of the Constitution of India.",
        "exp_hi": "1935 का भारत शासन अधिनियम भारतीय संविधान का सबसे बड़ा एकाकी स्रोत है, जिससे संघीय तंत्र, राज्यपाल का पद, न्यायपालिका, लोक सेवा आयोग और आपातकालीन प्रावधान लिए गए।",
        "cue_en": "1950 Constitution blueprint = Government of India Act 1935.",
        "cue_hi": "भारतीय संविधान का मुख्य स्रोत = 1935 का भारत शासन अधिनियम।",
        "wrong_en": ["Primary structural blueprint.", "Introduced dyarchy in provinces (Mont-Ford).", "Transferred sovereignty in August 1947.", "Recommended Constituent Assembly framework."],
        "wrong_hi": ["संविधान का प्राथमिक आधार।", "प्रांतों में द्वैध शासन लागू करने वाला (मोंटेग्यू-चेम्सफोर्ड)।", "सत्ता हस्तांतरण का अधिनियम।", "संविधान सभा की योजना का दस्तावेज।"]
    },
    {
        "name_en": "Constituent Assembly: Formation, Committees, Drafting & Adoption (26 Nov 1949)",
        "name_hi": "संविधान सभा: गठन, समितियां, प्रारूप निर्माण एवं अंगीकरण (26 नवंबर 1949)",
        "concepts_en": ["Formed in Nov 1946 under Cabinet Mission Plan; 389 initial members, reduced to 299 after Partition", "First meeting on 9 Dec 1946 (Dr. Sachchidananda Sinha temporary President); Dr. Rajendra Prasad elected permanent President on 11 Dec", "Objectives Resolution moved by Jawaharlal Nehru on 13 Dec 1946 (adopted 22 Jan 1947)", "Drafting Committee appointed on 29 Aug 1947 chaired by Dr. B.R. Ambedkar ('Father of the Constitution'); took 2 years, 11 months, 18 days; adopted on 26 Nov 1949 (Constitution Day)"],
        "concepts_hi": ["कैबिनेट मिशन योजना के तहत नवंबर 1946 में गठन; विभाजन के बाद 299 सदस्य", "पहली बैठक 9 दिसंबर 1946 को (डॉ. सच्चिदानंद सिन्हा अस्थायी अध्यक्ष); 11 दिसंबर को डॉ. राजेंद्र प्रसाद स्थायी अध्यक्ष निर्वाचित", "13 दिसंबर 1946 को नेहरू द्वारा 'उद्देश्य प्रस्ताव' प्रस्तुत (22 जनवरी 1947 को स्वीकृत)", "29 अगस्त 1947 को डॉ. बी.आर. अम्बेडकर की अध्यक्षता में 7-सदस्यीय प्रारूप समिति; 2 वर्ष 11 माह 18 दिन लगे; 26 नवंबर 1949 को अंगीकृत (संविधान दिवस)"],
        "q_en": "Who served as the Chairman of the Drafting Committee of the Constituent Assembly of India, appointed on 29 August 1947?",
        "q_hi": "29 अगस्त 1947 को गठित भारत की संविधान सभा की प्रारूप समिति (Drafting Committee) के अध्यक्ष कौन थे?",
        "options_en": ["Dr. B.R. Ambedkar (डॉ. भीमराव अम्बेडकर)", "Dr. Rajendra Prasad", "Jawaharlal Nehru", "Sir B.N. Rau"],
        "options_hi": ["डॉ. बी.आर. अम्बेडकर (Dr. B.R. Ambedkar)", "डॉ. राजेंद्र प्रसाद", "जवाहरलाल नेहरू", "सर बी.एन. राव"],
        "correct_idx": 0,
        "exp_en": "Dr. Bhimrao Ramji Ambedkar chaired the 7-member Drafting Committee, leading the formulation of the draft Constitution.",
        "exp_hi": "डॉ. बी.आर. अम्बेडकर 7 सदस्यीय प्रारूप समिति के अध्यक्ष थे, जिन्होंने संविधान के अंतिम प्रारूप को तैयार करने में निर्णायक भूमिका निभाई।",
        "cue_en": "Drafting Committee Chairman = Dr. B.R. Ambedkar.",
        "cue_hi": "प्रारूप समिति के अध्यक्ष = डॉ. बी.आर. अम्बेडकर।",
        "wrong_en": ["Chairman of Drafting Committee.", "President of Constituent Assembly.", "Moved Objectives Resolution.", "Constitutional Advisor to Assembly."],
        "wrong_hi": ["प्रारूप समिति के अध्यक्ष।", "संविधान सभा के स्थायी अध्यक्ष।", "उद्देश्य प्रस्ताव प्रस्तुत करने वाले।", "संविधान सभा के संवैधानिक सलाहकार।"]
    },
    {
        "name_en": "The Preamble to the Constitution: Philosophy, Key Terms & 42nd Amendment",
        "name_hi": "संविधान की प्रस्तावना (उद्देशिका): दर्शन, मूल आदर्श एवं 42वां संविधान संशोधन",
        "concepts_en": ["Based on Nehru's Objectives Resolution; acts as the key/soul of the Constitution", "Key terms: Sovereign, Socialist, Secular, Democratic, Republic", "Objectives: Justice (Social, Economic, Political), Liberty, Equality, Fraternity", "Kesavananda Bharati case (1973): Preamble is an integral part of the Constitution and can be amended under Art 368 without altering basic structure", "42nd Amendment 1976 added three words: 'Socialist', 'Secular', and 'Integrity'"],
        "concepts_hi": ["नेहरू के उद्देश्य प्रस्ताव पर आधारित; के.एम. मुंशी द्वारा 'संविधान की जन्मकुंडली' कहा गया", "मूल शब्द: संपूर्ण प्रभुत्व-संपन्न, समाजवादी, पंथनिरपेक्ष, लोकतंत्रात्मक गणराज्य", "उद्देश्य: न्याय (सामाजिक, आर्थिक, राजनीतिक), स्वतंत्रता, समता, बंधुता", "केशवानंद भारती वाद (1973): प्रस्तावना संविधान का अभिन्न अंग है और मूल ढांचे को छोड़कर इसमें संशोधन किया जा सकता है", "42वें संशोधन (1976) द्वारा तीन नए शब्द जोड़े गए: 'समाजवादी', 'पंथनिरपेक्ष' और 'अखंडता'"],
        "q_en": "Which three words were incorporated into the Preamble of the Constitution of India by the 42nd Constitutional Amendment Act of 1976?",
        "q_hi": "1976 के 42वें संविधान संशोधन अधिनियम द्वारा भारतीय संविधान की प्रस्तावना में कौन से तीन नए शब्द जोड़े गए थे?",
        "options_en": ["Socialist, Secular, and Integrity (समाजवादी, पंथनिरपेक्ष और अखंडता)", "Justice, Liberty, and Equality", "Sovereign, Democratic, and Republic", "Federal, Unitary, and Secular"],
        "options_hi": ["समाजवादी, पंथनिरपेक्ष और अखंडता (Socialist, Secular, Integrity)", "न्याय, स्वतंत्रता और समता", "संपूर्ण प्रभुत्व-संपन्न, लोकतांत्रिक और गणराज्य", "संघीय, एकात्मक और पंथनिरपेक्ष"],
        "correct_idx": 0,
        "exp_en": "The 42nd Amendment (1976) modified the Preamble by adding the words 'Socialist', 'Secular', and replacing 'unity of the Nation' with 'unity and integrity of the Nation'.",
        "exp_hi": "42वें संविधान संशोधन 1976 द्वारा प्रस्तावना में 'समाजवादी', 'पंथनिरपेक्ष' और 'अखंडता' शब्द जोड़े गए। प्रस्तावना में अब तक केवल एक बार संशोधन हुआ है।",
        "cue_en": "42nd Amendment 1976 = Socialist, Secular, Integrity.",
        "cue_hi": "42वां संशोधन 1976 = समाजवादी, पंथनिरपेक्ष, अखंडता।",
        "wrong_en": ["Added by 42nd Amendment in 1976.", "Present in original 1949 Preamble.", "Present in original 1949 text.", "Not words in Preamble."],
        "wrong_hi": ["42वें संशोधन द्वारा जोड़े गए शब्द।", "मूल संविधान में पहले से उपस्थित।", "1949 के मूल पाठ का हिस्सा।", "प्रस्तावना में प्रयुक्त शब्द नहीं हैं।"]
    }
]

# S05-C2da5cfd3 Fundamental Rights, Directive Principles & Fundamental Duties (7 topics)
DATA["S05-C2da5cfd3"] = [
    {
        "name_en": "Concept of State (Article 12) & Doctrine of Judicial Review (Article 13)",
        "name_hi": "राज्य की परिभाषा (अनुच्छेद 12) एवं न्यायिक समीक्षा का सिद्धांत (अनुच्छेद 13)",
        "concepts_en": ["Part III of Constitution (Articles 12 to 35) called Magna Carta of India", "Article 12 defines 'State' including Parliament, legislatures, government authorities, local bodies, and PSUs/statutory corporations", "Article 13(2) declares laws inconsistent with Fundamental Rights void (Doctrine of Eclipse, Doctrine of Severability)", "Judicial Review is part of Basic Structure (Kesavananda Bharati, Minerva Mills)"],
        "concepts_hi": ["संविधान का भाग III (अनुच्छेद 12 से 35) 'भारत का अधिकार-पत्र' (मैग्नाकार्टा) कहलाता है", "अनुच्छेद 12 में 'राज्य' की व्यापक परिभाषा: संसद, विधानमंडल, सरकार, स्थानीय प्राधिकारी एवं अन्य सांविधिक निकाय", "अनुच्छेद 13(2) मूल अधिकारों से असंगत या उनका अल्पीकरण करने वाली विधियों को शून्य घोषित करता है (आच्छादन व पृथक्करणीयता का सिद्धांत)", "न्यायिक पुनरावलोकन (Judicial Review) संविधान के मूल ढांचे का हिस्सा है"],
        "q_en": "Under which Article of the Constitution of India are laws that contravene or abridge any Fundamental Right declared null and void (unconstitutional)?",
        "q_hi": "भारतीय संविधान के किस अनुच्छेद के तहत मूल अधिकारों से असंगत या उन्हें छीनने वाले किसी भी कानून को न्यायपालिका द्वारा अमान्य (शून्य) घोषित किया जा सकता है?",
        "options_en": ["Article 13 (अनुच्छेद 13)", "Article 12", "Article 14", "Article 19"],
        "options_hi": ["अनुच्छेद 13 (Article 13)", "अनुच्छेद 12", "अनुच्छेद 14", "अनुच्छेद 19"],
        "correct_idx": 0,
        "exp_en": "Article 13 expressly confers the power of judicial review on the Supreme Court and High Courts to strike down any pre- or post-constitutional law that infringes Part III rights.",
        "exp_hi": "अनुच्छेद 13 न्यायिक समीक्षा का प्रत्यक्ष आधार है, जो यह सुनिश्चित करता है कि संसद या विधानमंडल ऐसा कोई कानून न बनाए जो मूल अधिकारों को छीनता हो।",
        "cue_en": "Article 13 = Judicial review strikes down unconstitutional laws.",
        "cue_hi": "अनुच्छेद 13 = न्यायिक समीक्षा व मूल अधिकारों की सुरक्षा।",
        "wrong_en": ["Empowers judicial review of laws.", "Defines 'State'.", "Guarantees Equality before Law.", "Guarantees Six Freedoms."],
        "wrong_hi": ["न्यायिक समीक्षा की शक्ति देता है।", "राज्य को परिभाषित करता है।", "विधि के समक्ष समता देता है।", "छह स्वतंत्रताओं का अधिकार देता है।"]
    },
    {
        "name_en": "Right to Equality: Articles 14 to 18 (Equality before Law & Abolition of Untouchability)",
        "name_hi": "समता का अधिकार: अनुच्छेद 14 से 18 (विधि के समक्ष समता एवं अस्पृश्यता का अंत)",
        "concepts_en": ["Article 14: Equality before law (British concept) and Equal protection of the laws (US concept)", "Article 15: Prohibition of discrimination on grounds only of religion, race, caste, sex, or place of birth", "Article 16: Equality of opportunity in public employment (affirmative action)", "Article 17: Abolition of Untouchability and prohibition of its practice in any form (Protection of Civil Rights Act 1955)", "Article 18: Abolition of Titles (except military and academic)"],
        "concepts_hi": ["अनुच्छेद 14: विधि के समक्ष समता (ब्रिटिश अवधारणा) और विधियों का समान संरक्षण (अमेरिकी अवधारणा)", "अनुच्छेद 15: केवल धर्म, मूलवंश, जाति, लिंग या जन्मस्थान के आधार पर भेदभाव का निषेध", "अनुच्छेद 16: लोक नियोजन के मामलों में अवसर की समता (आरक्षण संबंधी प्रावधान)", "अनुच्छेद 17: अस्पृश्यता (छुआछूत) का पूर्ण उन्मूलन एवं किसी भी रूप में इसका आचरण दंडनीय (नागरिक अधिकार संरक्षण अधिनियम 1955)", "अनुच्छेद 18: उपाधियों का अंत (सैन्य और शैक्षणिक उपाधियों को छोड़कर)"],
        "q_en": "Which Article of the Indian Constitution completely abolishes 'Untouchability' and forbids its practice in any form, making it a punishable offense?",
        "q_hi": "भारतीय संविधान का कौन सा अनुच्छेद 'अस्पृश्यता' (छुआछूत) का पूर्ण उन्मूलन करता है और किसी भी रूप में इसके आचरण को दंडनीय अपराध घोषित करता है?",
        "options_en": ["Article 17 (अनुच्छेद 17)", "Article 14", "Article 15", "Article 18"],
        "options_hi": ["अनुच्छेद 17 (Article 17)", "अनुच्छेद 14", "अनुच्छेद 15", "अनुच्छेद 18"],
        "correct_idx": 0,
        "exp_en": "Article 17 unconditionally abolishes untouchability in all manifestations and declares its practice punishable under the Protection of Civil Rights Act 1955.",
        "exp_hi": "अनुच्छेद 17 अस्पृश्यता का अंत करता है। यह एक निरपेक्ष मूल अधिकार है जो निजी व्यक्तियों के विरुद्ध भी लागू होता है।",
        "cue_en": "Article 17 = Abolition of Untouchability.",
        "cue_hi": "अनुच्छेद 17 = अस्पृश्यता का अंत।",
        "wrong_en": ["Abolition of Untouchability.", "Equality before law.", "Prohibition of discrimination.", "Abolition of titles."],
        "wrong_hi": ["अस्पृश्यता का अंत।", "विधि के समक्ष समता।", "भेदभाव का प्रतिषेध।", "उपाधियों का अंत।"]
    },
    {
        "name_en": "Right to Freedom: Article 19 Freedoms & Protection in Conviction (Article 20)",
        "name_hi": "स्वतंत्रता का अधिकार: अनुच्छेद 19 की छह स्वतंत्रताएं एवं अपराधों के दोषसिद्धि के संबंध में संरक्षण (अनुच्छेद 20)",
        "concepts_en": ["Article 19(1) guarantees 6 freedoms: speech/expression, peaceful assembly, association/unions, free movement throughout India, residence/settlement, trade/profession", "Reasonable restrictions on grounds of sovereignty, public order, morality (Art 19(2)-(6))", "Article 20 protections: No ex-post facto law (Art 20(1)), No double jeopardy (Art 20(2)), No self-incrimination (Art 20(3))", "Articles 20 and 21 cannot be suspended even during a National Emergency (44th Amendment 1978)"],
        "concepts_hi": ["अनुच्छेद 19(1) में 6 मूल स्वतंत्रताएं: वाक् व अभिव्यक्ति, शांतिपूर्ण सम्मेलन, संगम/संघ/सहकारी समिति, भारत में निर्बाध संचरण, निवास और व्यापार/आजीविका", "सार्वजनिक व्यवस्था, संप्रभुता व सदाचार के आधार पर 'युक्तियुक्त निर्बंधन'", "अनुच्छेद 20 में तीन सुरक्षाएं: कार्योत्तर विधियों से संरक्षण, दोहरे दंड से मुक्ति (Double Jeopardy), अपने ही विरुद्ध गवाही देने से संरक्षण (Self-incrimination)", "44वें संशोधन (1978) के अनुसार राष्ट्रीय आपातकाल (अनुच्छेद 352) के दौरान भी अनुच्छेद 20 और 21 निलंबित नहीं किए जा सकते"],
        "q_en": "Which two Fundamental Rights guaranteed under the Indian Constitution cannot be suspended even during a Proclamation of National Emergency under Article 352?",
        "q_hi": "अनुच्छेद 352 के तहत राष्ट्रीय आपातकाल की घोषणा के दौरान भी कौन से दो मूल अधिकार किसी भी स्थिति में निलंबित नहीं किए जा सकते?",
        "options_en": ["Articles 20 and 21 (अनुच्छेद 20 और 21)", "Articles 14 and 19", "Articles 19 and 20", "Articles 21 and 22"],
        "options_hi": ["अनुच्छेद 20 और 21 (Articles 20 and 21)", "अनुच्छेद 14 और 19", "अनुच्छेद 19 और 20", "अनुच्छेद 21 और 22"],
        "correct_idx": 0,
        "exp_en": "By the 44th Constitutional Amendment Act 1978, the right to protection in respect of conviction for offences (Art 20) and the right to life and personal liberty (Art 21) cannot be suspended under Article 359 during emergencies.",
        "exp_hi": "44वें संशोधन 1978 द्वारा यह व्यवस्था की गई कि राष्ट्रपति आपातकाल में भी अनुच्छेद 20 (दोषसिद्धि से संरक्षण) और अनुच्छेद 21 (प्राण एवं दैहिक स्वतंत्रता) को निलंबित नहीं कर सकते।",
        "cue_en": "Emergency immune rights = Articles 20 & 21.",
        "cue_hi": "आपातकाल में भी सुरक्षित अधिकार = अनुच्छेद 20 एवं 21।",
        "wrong_en": ["Cannot be suspended during emergency.", "Article 19 automatically suspends under external emergency.", "Article 19 can be suspended.", "Article 22 can be suspended."],
        "wrong_hi": ["आपातकाल में भी निलंबित नहीं होते।", "अनुच्छेद 19 स्वतः निलंबित हो सकता है।", "अनुच्छेद 19 निलंबित हो सकता है।", "अनुच्छेद 22 निलंबित किया जा सकता है।"]
    },
    {
        "name_en": "Right to Life & Personal Liberty (Article 21), Right to Privacy & Right to Education (Article 21A)",
        "name_hi": "प्राण एवं दैहिक स्वतंत्रता (अनुच्छेद 21), निजता का अधिकार एवं शिक्षा का अधिकार (अनुच्छेद 21A)",
        "concepts_en": ["Article 21: 'No person shall be deprived of his life or personal liberty except according to procedure established by law'", "Maneka Gandhi case (1978) introduced 'Due Process of Law' (law must be just, fair and reasonable)", "K.S. Puttaswamy case (2017) unanimously declared Right to Privacy as a Fundamental Right under Article 21", "86th Constitutional Amendment 2002 inserted Article 21A: Free and compulsory education for all children aged 6 to 14 years (RTE Act 2009)"],
        "concepts_hi": ["अनुच्छेद 21: किसी व्यक्ति को उसके प्राण या दैहिक स्वतंत्रता से विधि द्वारा स्थापित प्रक्रिया के अनुसार ही वंचित किया जाएगा", "मेनका गांधी वाद (1978): 'विधि द्वारा स्थापित प्रक्रिया' की जगह 'विधि की सम्यक प्रक्रिया' (Just, Fair and Reasonable) की व्याख्या", "के.एस. पुट्टास्वामी वाद (2017): 9 जजों की संविधान पीठ ने 'निजता के अधिकार' (Right to Privacy) को अनुच्छेद 21 के तहत मूल अधिकार घोषित किया", "86वां संशोधन 2002: अनुच्छेद 21A जोड़ा गया, जिसके तहत 6 से 14 वर्ष के बच्चों को निःशुल्क एवं अनिवार्य शिक्षा का मूल अधिकार (RTE Act 2009) दिया गया"],
        "q_en": "By which Constitutional Amendment Act was Article 21A inserted into the Constitution of India, guaranteeing free and compulsory education to all children aged 6 to 14 years?",
        "q_hi": "किस संविधान संशोधन अधिनियम द्वारा भारतीय संविधान में अनुच्छेद 21A जोड़कर 6 से 14 वर्ष के बच्चों के लिए निःशुल्क एवं अनिवार्य शिक्षा को मूल अधिकार बनाया गया?",
        "options_en": ["86th Constitutional Amendment Act, 2002 (86वां संशोधन)", "44th Amendment Act, 1978", "91st Amendment Act, 2003", "103rd Amendment Act, 2019"],
        "options_hi": ["86वां संविधान संशोधन अधिनियम, 2002", "44वां संविधान संशोधन अधिनियम, 1978", "91वां संविधान संशोधन अधिनियम, 2003", "103वां संविधान संशोधन अधिनियम, 2019"],
        "correct_idx": 0,
        "exp_en": "The 86th Amendment Act 2002 enacted Article 21A, making education a fundamental right for children aged 6 to 14, operationalized by the RTE Act 2009.",
        "exp_hi": "86वें संशोधन 2002 द्वारा अनुच्छेद 21A जोड़ा गया, जिसे 1 अप्रैल 2010 से शिक्षा का अधिकार अधिनियम (RTE) के माध्यम से देश भर में प्रभावी बनाया गया।",
        "cue_en": "Right to Education (Art 21A) = 86th Amendment 2002.",
        "cue_hi": "शिक्षा का मूल अधिकार (अनुच्छेद 21A) = 86वां संशोधन (2002)।",
        "wrong_en": ["Inserted Article 21A.", "Removed Right to Property from Part III.", "Limited Council of Ministers size to 15%.", "Introduced 10% EWS reservation."],
        "wrong_hi": ["अनुच्छेद 21A को शामिल किया।", "संपत्ति के अधिकार को हटाया।", "मंत्रिपरिषद के आकार को 15% तक सीमित किया।", "ईडब्ल्यूएस हेतु 10% आरक्षण।"]
    },
    {
        "name_en": "Right to Freedom of Religion (Articles 25 to 28) & Cultural/Educational Rights (Articles 29-30)",
        "name_hi": "धार्मिक स्वतंत्रता का अधिकार (अनुच्छेद 25 से 28) एवं संस्कृति व शिक्षा संबंधी अधिकार (अनुच्छेद 29-30)",
        "concepts_en": ["Article 25: Freedom of conscience and free profession, practice and propagation of religion (subject to public order, morality, health)", "Article 26: Freedom to manage religious affairs", "Article 27: Freedom from paying taxes for promotion of any specific religion", "Article 28: Freedom from attendance at religious instruction in state-funded institutions", "Articles 29-30: Protection of interests of religious and linguistic minorities to establish and administer educational institutions"],
        "concepts_hi": ["अनुच्छेद 25: अंतःकरण की स्वतंत्रता, धर्म को अबाध रूप से मानने, आचरण और प्रचार करने का अधिकार (सार्वजनिक व्यवस्था, सदाचार व स्वास्थ्य के अधीन)", "अनुच्छेद 26: धार्मिक कार्यों के प्रबंध की स्वतंत्रता", "अनुच्छेद 27: किसी विशिष्ट धर्म के पोषण हेतु करों के संदाय से मुक्ति", "अनुच्छेद 28: राज्य-पोषित शिक्षण संस्थानों में धार्मिक शिक्षा देने का निषेध", "अनुच्छेद 29-30: अल्पसंख्यकों (धार्मिक व भाषाई) के हितों का संरक्षण तथा शिक्षण संस्थानों की स्थापना व प्रशासन का अधिकार"],
        "q_en": "Under Article 25 of the Constitution of India, the freedom to profess, practice, and propagate religion is expressly subject to which three constitutional grounds?",
        "q_hi": "भारतीय संविधान के अनुच्छेद 25 के अनुसार धर्म को अबाध रूप से मानने, आचरण और प्रचार करने की स्वतंत्रता किन तीन आधारों के अधीन सीमित की जा सकती है?",
        "options_en": ["Public order, morality, and health (लोक व्यवस्था, सदाचार और स्वास्थ्य)", "Sovereignty, integrity, and security", "Defamation, contempt, and incitement", "Foreign relations, trade, and morals"],
        "options_hi": ["लोक व्यवस्था, सदाचार और स्वास्थ्य (Public order, morality, health)", "संप्रभुता, अखंडता और सुरक्षा", "मानहानि, न्यायालय की अवमानना और अपराध-उद्दीपन", "विदेशी संबंध, व्यापार और सदाचार"],
        "correct_idx": 0,
        "exp_en": "Article 25(1) states that subject to public order, morality, and health, and to the other provisions of Part III, all persons are equally entitled to freedom of religion.",
        "exp_hi": "अनुच्छेद 25(1) स्पष्ट करता है कि लोक व्यवस्था, सदाचार और स्वास्थ्य के अधीन रहते हुए सभी व्यक्तियों को अंतःकरण की और धर्म के आचरण की स्वतंत्रता है।",
        "cue_en": "Art 25 restrictions = Public order, Morality, Health.",
        "cue_hi": "अनुच्छेद 25 के तीन प्रतिबंध = लोक व्यवस्था, सदाचार, स्वास्थ्य।",
        "wrong_en": ["Three explicit grounds under Article 25.", "Restrictions under Article 19(2).", "Restrictions under Article 19(2).", "General legal restrictions."],
        "wrong_hi": ["अनुच्छेद 25 के स्पष्ट आधार।", "अनुच्छेद 19(2) के आधार।", "अनुच्छेद 19(2) के आधार।", "सामान्य विधिक प्रतिबंध।"]
    },
    {
        "name_en": "Right to Constitutional Remedies (Article 32): The Five High Prerogative Writs",
        "name_hi": "संवैधानिक उपचारों का अधिकार (अनुच्छेद 32): पांच प्रकार की ऐतिहासिक रिटें",
        "concepts_en": ["Dr. B.R. Ambedkar called Article 32 the 'Heart and Soul of the Constitution'", "Direct access to Supreme Court for enforcement of Fundamental Rights (Art 32); High Courts under Art 226", "Habeas Corpus: 'To have the body' against illegal detention", "Mandamus: 'We command' public official/body to perform mandatory statutory duty", "Prohibition & Certiorari against lower judicial bodies; Quo Warranto challenging lawful authority of public office holder"],
        "concepts_hi": ["डॉ. बी.आर. अम्बेडकर ने अनुच्छेद 32 को 'संविधान का हृदय और आत्मा' कहा था", "मूल अधिकारों के प्रवर्तन हेतु सीधे सर्वोच्च न्यायालय जाने का अधिकार (अनुच्छेद 32); उच्च न्यायालय (अनुच्छेद 226)", "बंदी प्रत्यक्षीकरण (Habeas Corpus): अवैध रूप से बंदी बनाए गए व्यक्ति को न्यायालय के समक्ष प्रस्तुत करने का आदेश", "परमादेश (Mandamus): 'हम आदेश देते हैं' - सार्वजनिक पदाधिकारी को उसका कानूनी कर्तव्य करने का निर्देश", "प्रतिषेध व उत्प्रेषण (न्यायिक/अर्ध-न्यायिक निकायों के विरुद्ध) तथा अधिकार पृच्छा (Quo Warranto - अवैध पद धारण पर पूछताछ)"],
        "q_en": "Which constitutional writ, translating literally to 'You shall have the body', is issued by courts to secure the release of a person unlawfully detained by the State or a private individual?",
        "q_hi": "अदालतों द्वारा किसी व्यक्ति को गैरकानूनी हिरासत से मुक्त कराने हेतु कौन सी रिट जारी की जाती है, जिसका शाब्दिक अर्थ 'शरीर को प्रस्तुत किया जाए' होता है?",
        "options_en": ["Habeas Corpus (बंदी प्रत्यक्षीकरण)", "Mandamus (परमादेश)", "Certiorari (उत्प्रेषण)", "Quo Warranto (अधिकार पृच्छा)"],
        "options_hi": ["बंदी प्रत्यक्षीकरण (Habeas Corpus)", "परमादेश (Mandamus)", "उत्प्रेषण (Certiorari)", "अधिकार पृच्छा (Quo Warranto)"],
        "correct_idx": 0,
        "exp_en": "Habeas Corpus literally means 'to have the body'. It is a powerful remedy against illegal detention, enforceable against both public authorities and private entities.",
        "exp_hi": "बंदी प्रत्यक्षीकरण (Habeas Corpus) रिट किसी भी अवैध हिरासत के खिलाफ व्यक्तिगत स्वतंत्रता की सबसे मजबूत ढाल है, जिसके तहत बंदी को तुरंत अदालत में पेश करना होता है।",
        "cue_en": "Habeas Corpus = Release from unlawful custody.",
        "cue_hi": "बंदी प्रत्यक्षीकरण = अवैध हिरासत से मुक्ति की रिट।",
        "wrong_en": ["Remedy against unlawful detention.", "Commands performance of public duty.", "Quashes illegal lower court orders.", "Challenges usurper of public office."],
        "wrong_hi": ["अवैध नजरबंदी के विरुद्ध रिट।", "सार्वजनिक कर्तव्य का आदेश।", "निचली अदालतों के आदेश को रद्द करना।", "अवैध पद धारण की वैधता की जांच।"]
    },
    {
        "name_en": "Directive Principles of State Policy (Part IV) & Fundamental Duties (Article 51A)",
        "name_hi": "राज्य के नीति-निर्देशक तत्व (भाग IV) एवं मौलिक कर्तव्य (अनुच्छेद 51A)",
        "concepts_en": ["DPSP (Articles 36 to 51) borrowed from Irish Constitution (1937); non-justiciable (Art 37) but fundamental in governance to establish a Welfare State", "Classification: Socialistic (Arts 38, 39, 41), Gandhian (Arts 40 Gram Panchayats, 43, 47, 48), Liberal-Intellectual (Art 44 Uniform Civil Code, Art 48A Environment, Art 50 Separation of Judiciary)", "Fundamental Duties (Part IVA, Article 51A) recommended by Swaran Singh Committee; added by 42nd Amendment 1976 (borrowed from USSR)", "Originally 10 duties; 11th duty added by 86th Amendment 2002 (duty of parents to provide education to children aged 6-14)"],
        "concepts_hi": ["नीति-निर्देशक तत्व (अनुच्छेद 36 से 51): आयरलैंड के संविधान से प्रेरित; गैर-न्यायसंगत किंतु शासन में मूलभूत; 'कल्याणकारी राज्य' की स्थापना का लक्ष्य", "तीन श्रेणियां: समाजवादी (अनुच्छेद 38, 39), गांधीवादी (अनुच्छेद 40 ग्राम पंचायतें, 43, 47, 48 गो-वध निषेध), उदार-बौद्धिक (अनुच्छेद 44 समान नागरिक संहिता, 48A पर्यावरण, 50 कार्यपालिका से न्यायपालिका का पृथक्करण)", "मौलिक कर्तव्य (भाग IVA, अनुच्छेद 51A): स्वर्ण सिंह समिति की सिफारिश पर 42वें संशोधन 1976 द्वारा पूर्व सोवियत संघ से जोड़े गए", "प्रारंभ में 10 कर्तव्य थे; 86वें संशोधन 2002 द्वारा 11वां कर्तव्य (6-14 वर्ष के बच्चों को शिक्षा दिलाना माता-पिता का कर्तव्य) जोड़ा गया"],
        "q_en": "Which Article of the Constitution of India directs the State to secure for all citizens a Uniform Civil Code (UCC) throughout the territory of India?",
        "q_hi": "भारतीय संविधान का कौन सा अनुच्छेद राज्य को पूरे भारत में सभी नागरिकों के लिए एक 'समान नागरिक संहिता' (Uniform Civil Code - UCC) लागू करने का निर्देश देता है?",
        "options_en": ["Article 44 (अनुच्छेद 44)", "Article 40", "Article 48A", "Article 50"],
        "options_hi": ["अनुच्छेद 44 (Article 44)", "अनुच्छेद 40", "अनुच्छेद 48A", "अनुच्छेद 50"],
        "correct_idx": 0,
        "exp_en": "Article 44 in Part IV directs the State to endeavor to secure for the citizens a Uniform Civil Code throughout the territory of India.",
        "exp_hi": "अनुच्छेद 44 राज्य के नीति-निर्देशक तत्वों में शामिल है, जो विवाह, तलाक, उत्तराधिकार आदि सिविल मामलों में समान नागरिक संहिता बनाने का निर्देश देता है।",
        "cue_en": "Article 44 = Uniform Civil Code (UCC).",
        "cue_hi": "अनुच्छेद 44 = समान नागरिक संहिता (UCC)।",
        "wrong_en": ["Uniform Civil Code directive.", "Organization of village panchayats.", "Protection of environment and wildlife.", "Separation of judiciary from executive."],
        "wrong_hi": ["समान नागरिक संहिता का प्रावधान।", "ग्राम पंचायतों का गठन।", "पर्यावरण व वन्यजीवों का संरक्षण।", "न्यायपालिका का कार्यपालिका से पृथक्करण।"]
    }
]

# S05-C4d9a5be9 Union Executive: President, PM & Council of Ministers (3 topics)
DATA["S05-C4d9a5be9"] = [
    {
        "name_en": "The President of India: Election, Powers, Ordinance Making (Art 123) & Pardoning Power (Art 72)",
        "name_hi": "भारत के राष्ट्रपति: निर्वाचन मंडल, शक्तियां, अध्यादेश (अनुच्छेद 123) एवं क्षमादान की शक्ति (अनुच्छेद 72)",
        "concepts_en": ["Electoral College (Art 54): Elected members of Lok Sabha, Rajya Sabha, and Legislative Assemblies of States, Delhi & Puducherry; Single Transferable Vote", "Impeachment (Art 61): For 'Violation of the Constitution'; resolution by 1/4th members, passed by 2/3rd majority of total membership of both Houses", "Ordinance making power (Art 123) when Parliament is not in session; must be approved within 6 weeks of reassembly", "Pardoning powers (Art 72): Pardon, Commutation, Remission, Respite, Reprieve; includes court-martial and death sentences"],
        "concepts_hi": ["निर्वाचन मंडल (अनुच्छेद 54): संसद के दोनों सदनों तथा राज्यों व दिल्ली-पुडुचेरी विधानसभाओं के केवल निर्वाचित सदस्य; आनुपातिक प्रतिनिधित्व व एकल संक्रमणीय मत", "महाभियोग (अनुच्छेद 61): केवल 'संविधान के अतिक्रमण' के आधार पर; दोनों सदनों की कुल सदस्य संख्या के 2/3 बहुमत से पारित होना आवश्यक", "अध्यादेश शक्ति (अनुच्छेद 123): संसद के सत्रावसान में आपात विधि निर्माण; संसद के सत्र शुरू होने के 6 सप्ताह के भीतर अनुमोदन अनिवार्य", "क्षमादान शक्तियां (अनुच्छेद 72): क्षमा (Pardon), लघुकरण (Commutation), परिहार (Remission), विराम (Respite), प्रविलंबन (Reprieve); मृत्युदंड व कोर्ट मार्शल में भी"],
        "q_en": "Under which Article of the Constitution of India is the President empowered to promulgate Ordinances during the recess of Parliament?",
        "q_hi": "संसद के दोनों सदनों के सत्रावसान (Recess) की स्थिति में राष्ट्रपति को अध्यादेश (Ordinance) जारी करने की शक्ति किस अनुच्छेद के तहत प्राप्त है?",
        "options_en": ["Article 123 (अनुच्छेद 123)", "Article 72", "Article 110", "Article 213"],
        "options_hi": ["अनुच्छेद 123 (Article 123)", "अनुच्छेद 72", "अनुच्छेद 110", "अनुच्छेद 213"],
        "correct_idx": 0,
        "exp_en": "Article 123 empowers the President to issue Ordinances having the force of an Act of Parliament when either House is not in session and immediate action is required.",
        "exp_hi": "अनुच्छेद 123 के तहत राष्ट्रपति तब अध्यादेश जारी कर सकते हैं जब संसद का कोई एक या दोनों सदन सत्र में न हों और तत्काल कानून बनाना अनिवार्य हो।",
        "cue_en": "Presidential Ordinance = Article 123 (Governor = Art 213).",
        "cue_hi": "राष्ट्रपति का अध्यादेश = अनुच्छेद 123 (राज्यपाल का = अनुच्छेद 213)।",
        "wrong_en": ["Presidential ordinance making power.", "Pardoning power of the President.", "Definition of Money Bills.", "Governor's ordinance making power."],
        "wrong_hi": ["राष्ट्रपति की अध्यादेश शक्ति।", "राष्ट्रपति की क्षमादान शक्ति।", "धन विधेयक की परिभाषा।", "राज्यपाल की अध्यादेश शक्ति।"]
    },
    {
        "name_en": "The Vice-President of India: Qualifications, Election & Role as Rajya Sabha Chairman",
        "name_hi": "भारत के उपराष्ट्रपति: योग्यताएं, निर्वाचन एवं राज्यसभा के पदेन सभापति के रूप में भूमिका",
        "concepts_en": ["Second highest constitutional office (Art 63); qualifications: citizen of India, 35 years old, qualified for election as Rajya Sabha member", "Electoral College (Art 66): Consists of all members of both Houses of Parliament (both elected AND nominated)", "Ex-officio Chairman of Rajya Sabha (Art 64); does not preside when resolution for removal is under consideration", "Acts as President (Art 65) in case of vacancy (death, resignation, removal) for maximum 6 months"],
        "concepts_hi": ["देश का दूसरा सर्वोच्च संवैधानिक पद (अनुच्छेद 63); योग्यता: 35 वर्ष की आयु, राज्यसभा सदस्य बनने योग्य", "निर्वाचन मंडल (अनुच्छेद 66): संसद के दोनों सदनों के सभी सदस्य (निर्वाचित और मनोनीत दोनों भाग लेते हैं; राज्य विधानसभाएं भाग नहीं लेतीं)", "राज्यसभा के पदेन सभापति (अनुच्छेद 64); पद से हटाने के संकल्प के समय अध्यक्षता नहीं करते", "रिक्ति की स्थिति में अधिकतम 6 महीने तक कार्यवाहक राष्ट्रपति के रूप में कार्य (अनुच्छेद 65)"],
        "q_en": "Who constitutes the Electoral College for the election of the Vice-President of India under Article 66?",
        "q_hi": "भारतीय संविधान के अनुच्छेद 66 के अनुसार उपराष्ट्रपति के चुनाव के लिए निर्वाचक मंडल (Electoral College) में कौन शामिल होते हैं?",
        "options_en": ["All members of both Houses of Parliament (both elected and nominated)", "Elected members of Parliament only", "Elected members of Parliament and State Assemblies", "All members of Lok Sabha only"],
        "options_hi": ["संसद के दोनों सदनों के सभी सदस्य (निर्वाचित एवं मनोनीत दोनों)", "केवल संसद के निर्वाचित सदस्य", "संसद एवं राज्य विधानसभाओं के निर्वाचित सदस्य", "केवल लोकसभा के सभी सदस्य"],
        "correct_idx": 0,
        "exp_en": "Under Article 66(1), the Vice-President is elected by an electoral college consisting of the members of both Houses of Parliament (including nominated members). State assemblies do not participate.",
        "exp_hi": "उपराष्ट्रपति के चुनाव में केवल संसद के दोनों सदनों (लोकसभा और राज्यसभा) के सभी सदस्य (निर्वाचित व मनोनीत) मतदान करते हैं। इसमें राज्यों की विधानसभाएं भाग नहीं लेतीं।",
        "cue_en": "Vice-President election = All MPs (Elected + Nominated) only.",
        "cue_hi": "उपराष्ट्रपति चुनाव = संसद के सभी सांसद (निर्वाचित + मनोनीत)।",
        "wrong_en": ["Correct composition under Art 66.", "Excludes nominated members (which is wrong for VP).", "Electoral college for President of India.", "Excludes Rajya Sabha members."],
        "wrong_hi": ["अनुच्छेद 66 के तहत सही निर्वाचक मंडल।", "मनोनीत को छोड़ना गलत है।", "राष्ट्रपति का निर्वाचक मंडल।", "राज्यसभा को छोड़ना गलत है।"]
    },
    {
        "name_en": "Prime Minister & Union Council of Ministers: Collective Responsibility & Art 75",
        "name_hi": "प्रधानमंत्री एवं केंद्रीय मंत्रिपरिषद: सामूहिक उत्तरदायित्व एवं अनुच्छेद 75",
        "concepts_en": ["Prime Minister appointed by President (Art 75(1)); real executive head (de facto) while President is nominal (de jure)", "Council of Ministers collectively responsible to Lok Sabha (Art 75(3)) - 'swim or sink together'", "Ministers hold office during pleasure of the President (Art 75(2) - individual responsibility)", "91st Amendment 2003 capped Council of Ministers at 15% of total Lok Sabha strength (Art 75(1A))"],
        "concepts_hi": ["राष्ट्रपति द्वारा प्रधानमंत्री की नियुक्ति (अनुच्छेद 75(1)); प्रधानमंत्री वास्तविक कार्यपालिका प्रमुख (डी फैक्टो) तथा राष्ट्रपति नाममात्र के प्रमुख (डी ज्यूरे)", "मंत्रिपरिषद सामूहिक रूप से लोकसभा के प्रति उत्तरदायी होती है (अनुच्छेद 75(3)) - 'एक साथ तैरते और एक साथ डूबते हैं'", "व्यक्तिगत रूप से मंत्री राष्ट्रपति के प्रसादपर्यंत पद धारण करते हैं (अनुच्छेद 75(2))", "91वां संशोधन 2003: मंत्रिपरिषद का कुल आकार लोकसभा की कुल सदस्य संख्या के 15% से अधिक नहीं हो सकता (अनुच्छेद 75(1A))"],
        "q_en": "Under Article 75(3) of the Indian Constitution, the Union Council of Ministers is collectively responsible to which institution?",
        "q_hi": "भारतीय संविधान के अनुच्छेद 75(3) के अनुसार केंद्रीय मंत्रिपरिषद सामूहिक रूप से किसके प्रति उत्तरदायी होती है?",
        "options_en": ["The Lok Sabha (House of the People)", "The President of India", "The Parliament as a whole", "The Rajya Sabha"],
        "options_hi": ["लोकसभा (House of the People)", "भारत के राष्ट्रपति", "संपूर्ण संसद", "राज्यसभा"],
        "correct_idx": 0,
        "exp_en": "Article 75(3) unambiguously states that the Council of Ministers shall be collectively responsible to the House of the People (Lok Sabha).",
        "exp_hi": "अनुच्छेद 75(3) के तहत मंत्रिपरिषद सामूहिक रूप से केवल लोकसभा के प्रति उत्तरदायी होती है। यदि लोकसभा में अविश्वास प्रस्ताव पारित हो जाए तो पूरी सरकार को त्यागपत्र देना पड़ता है।",
        "cue_en": "Council of Ministers = Collectively responsible to Lok Sabha (Art 75(3)).",
        "cue_hi": "मंत्रिपरिषद = सामूहिक रूप से लोकसभा के प्रति उत्तरदायी।",
        "wrong_en": ["Sole body for collective responsibility.", "Individually responsible to President.", "Collective responsibility is only to lower house.", "Not responsible to upper house."],
        "wrong_hi": ["सामूहिक उत्तरदायित्व का एकमात्र सदन।", "राष्ट्रपति के प्रति व्यक्तिगत उत्तरदायित्व होता है।", "राज्यसभा के प्रति सामूहिक उत्तरदायित्व नहीं होता।", "गलत सदन।"]
    }
]

# S05-Cc13f58d9 Union Parliament & Integrated Judicial System (4 topics)
DATA["S05-Cc13f58d9"] = [
    {
        "name_en": "Union Parliament: Composition, Presiding Officers & Money Bills (Article 110)",
        "name_hi": "संसद: संरचना, पीठासीन अधिकारी एवं धन विधेयक (अनुच्छेद 110)",
        "concepts_en": ["Parliament consists of President, Rajya Sabha (Council of States, max 250), Lok Sabha (House of People, max 550)", "Speaker of Lok Sabha presides; certifies whether a bill is a Money Bill (Art 110(3) - final decision)", "Money Bill introduced only in Lok Sabha on President's recommendation; Rajya Sabha can only delay for 14 days", "Joint sitting of Parliament (Art 108) summoned by President, presided over by Speaker of Lok Sabha (not for Money Bills or Constitutional Amendments)"],
        "concepts_hi": ["संसद के तीन अंग: राष्ट्रपति, राज्यसभा (अधिकतम 250) और लोकसभा (अधिकतम 550)", "लोकसभा अध्यक्ष सदन की अध्यक्षता करते हैं; किसी विधेयक के धन विधेयक होने का अंतिम प्रमाण पत्र स्पीकर देते हैं (अनुच्छेद 110(3))", "धन विधेयक केवल राष्ट्रपति की पूर्व संस्तुति से लोकसभा में ही पेश होता है; राज्यसभा इसे अधिकतम 14 दिन रोक सकती है", "संसद की संयुक्त बैठक (अनुच्छेद 108): राष्ट्रपति द्वारा आहूत, लोकसभा अध्यक्ष द्वारा अध्यक्षता (धन विधेयक व संविधान संशोधन पर संयुक्त बैठक नहीं होती)"],
        "q_en": "Who holds the final, unchallengeable constitutional authority to decide and certify whether a particular legislative bill is a 'Money Bill' under Article 110?",
        "q_hi": "भारतीय संविधान के अनुच्छेद 110 के तहत कोई विधेयक 'धन विधेयक' (Money Bill) है या नहीं, इसका अंतिम और बाध्यकारी निर्णय देने का अधिकार किसे है?",
        "options_en": ["Speaker of the Lok Sabha (लोकसभा अध्यक्ष)", "President of India", "Finance Minister", "Chairman of the Rajya Sabha"],
        "options_hi": ["लोकसभा अध्यक्ष (Speaker of the Lok Sabha)", "भारत के राष्ट्रपति", "केंद्रीय वित्त मंत्री", "राज्यसभा के सभापति"],
        "correct_idx": 0,
        "exp_en": "Under Article 110(3), if any question arises whether a Bill is a Money Bill or not, the decision of the Speaker of the House of the People thereon shall be final.",
        "exp_hi": "अनुच्छेद 110(3) के अनुसार कोई विधेयक धन विधेयक है या नहीं, इस पर लोकसभा अध्यक्ष का निर्णय अंतिम होता है और इस पर न्यायालय में प्रश्न नहीं उठाया जा सकता।",
        "cue_en": "Money Bill certification = Speaker of Lok Sabha (Art 110).",
        "cue_hi": "धन विधेयक का प्रमाणन = लोकसभा अध्यक्ष (अनुच्छेद 110)।",
        "wrong_en": ["Final authority under Art 110(3).", "Recommends introduction of Money Bill.", "Introduces the Union Budget.", "Has no power to decide on Money Bills."],
        "wrong_hi": ["अनुच्छेद 110(3) के तहत अंतिम प्राधिकारी।", "पेश करने की पूर्व अनुमति देते हैं।", "बजट पेश करते हैं।", "धन विधेयक पर कोई अधिकार नहीं।"]
    },
    {
        "name_en": "Parliamentary Procedures, Motions, Sessions & Key Committees (PAC & Estimates)",
        "name_hi": "संसदीय प्रक्रियाएं, प्रस्ताव, सत्र एवं प्रमुख संसदीय समितियां (लोक लेखा व प्राक्कलन समिति)",
        "concepts_en": ["Three sessions annually: Budget, Monsoon, Winter; maximum gap between sessions cannot exceed 6 months (Art 85)", "Question Hour (first hour) with Starred/Unstarred questions; Zero Hour (Indian procedural innovation since 1962)", "Motions: Adjournment Motion, No-Confidence Motion (requires support of 50 Lok Sabha MPs)", "Public Accounts Committee (PAC): 22 members (15 LS + 7 RS), audits CAG reports, chaired traditionally by opposition leader; Estimates Committee (30 members, all from Lok Sabha)"],
        "concepts_hi": ["वर्ष में तीन सत्र: बजट, मानसून, शीतकालीन सत्र; दो सत्रों के बीच अधिकतम 6 माह से अधिक का अंतर नहीं हो सकता (अनुच्छेद 85)", "प्रश्नकाल (पहला घंटा, तारांकित/अतारांकित प्रश्न); शून्यकाल (1962 से भारतीय संसदीय नवाचार)", "प्रस्ताव: स्थगन प्रस्ताव, अविश्वास प्रस्ताव (लोकसभा के न्यूनतम 50 सदस्यों का समर्थन अनिवार्य)", "लोक लेखा समिति (PAC): 22 सदस्य (15 लोकसभा + 7 राज्यसभा), सीएजी रिपोर्ट की जांच, परंपरा के अनुसार विपक्ष का नेता अध्यक्ष; प्राक्कलन समिति (30 सदस्य, सभी केवल लोकसभा से)"],
        "q_en": "How many total members constitute the Estimates Committee of the Indian Parliament, and from which House are they exclusively drawn?",
        "q_hi": "भारतीय संसद की सबसे बड़ी वित्तीय समिति 'प्राक्कलन समिति' (Estimates Committee) में कुल कितने सदस्य होते हैं और वे किस सदन से चुने जाते हैं?",
        "options_en": ["30 members, exclusively from Lok Sabha", "22 members (15 LS + 7 RS)", "15 members, exclusively from Rajya Sabha", "30 members (20 LS + 10 RS)"],
        "options_hi": ["30 सदस्य, केवल लोकसभा से चुने जाते हैं", "22 सदस्य (15 लोकसभा + 7 राज्यसभा)", "15 सदस्य, केवल राज्यसभा से", "30 सदस्य (20 लोकसभा + 10 राज्यसभा)"],
        "correct_idx": 0,
        "exp_en": "The Estimates Committee has 30 members, all elected annually from the Lok Sabha only. Rajya Sabha has no representation on this committee.",
        "exp_hi": "प्राक्कलन समिति में कुल 30 सदस्य होते हैं और ये सभी केवल लोकसभा से चुने जाते हैं। इसमें राज्यसभा का कोई प्रतिनिधित्व नहीं होता।",
        "cue_en": "Estimates Committee = 30 members (Lok Sabha only).",
        "cue_hi": "प्राक्कलन समिति = 30 सदस्य (केवल लोकसभा)।",
        "wrong_en": ["Correct: 30 members all from Lok Sabha.", "Composition of Public Accounts Committee.", "Incorrect composition.", "Incorrect composition."],
        "wrong_hi": ["प्राक्कलन समिति की सही संरचना।", "लोक लेखा समिति (PAC) की संरचना।", "गलत संरचना।", "गलत संरचना।"]
    },
    {
        "name_en": "The Supreme Court of India: Jurisdiction (Original, Appellate, Advisory) & Judicial Review",
        "name_hi": "भारत का सर्वोच्च न्यायालय: क्षेत्राधिकार (आरंभिक, अपीलीय, परामर्शदात्री) एवं न्यायिक समीक्षा",
        "concepts_en": ["Inaugurated on 28 January 1950 under Article 124; current strength 34 judges (Chief Justice + 33 judges)", "Collegium System for appointment developed through Three Judges Cases (1981, 1993, 1998)", "Original Jurisdiction (Art 131): Inter-state disputes and Centre-State disputes", "Advisory Jurisdiction (Art 143): President can seek opinion of Supreme Court on questions of law/fact; Court of Record (Art 129)"],
        "concepts_hi": ["28 जनवरी 1950 को उद्घाटन (अनुच्छेद 124); वर्तमान स्वीकृत संख्या 34 न्यायाधीश (1 मुख्य न्यायाधीश + 33 अन्य न्यायाधीश)", "कॉलेजियम प्रणाली: न्यायाधीशों के मामलों (1981, 1993, 1998) द्वारा विकसित नियुक्ति व्यवस्था", "आरंभिक क्षेत्राधिकार (अनुच्छेद 131): केंद्र और राज्यों अथवा दो या अधिक राज्यों के बीच विवाद", "परामर्शदात्री क्षेत्राधिकार (अनुच्छेद 143): राष्ट्रपति विधि या तथ्य के प्रश्न पर सर्वोच्च न्यायालय से राय मांग सकते हैं; अभिलेख न्यायालय (अनुच्छेद 129)"],
        "q_en": "Under which Article of the Constitution of India does the Supreme Court exercise its exclusive 'Original Jurisdiction' to adjudicate disputes between the Government of India and one or more States?",
        "q_hi": "भारतीय संविधान के किस अनुच्छेद के तहत भारत सरकार और एक या अधिक राज्यों के बीच विवादों का निपटारा सर्वोच्च न्यायालय के अनन्य 'आरंभिक क्षेत्राधिकार' (Original Jurisdiction) के अंतर्गत आता है?",
        "options_en": ["Article 131 (अनुच्छेद 131)", "Article 136", "Article 143", "Article 132"],
        "options_hi": ["अनुच्छेद 131 (Article 131)", "अनुच्छेद 136", "अनुच्छेद 143", "अनुच्छेद 132"],
        "correct_idx": 0,
        "exp_en": "Article 131 grants original and exclusive jurisdiction to the Supreme Court in any dispute between the Government of India and states or between states themselves.",
        "exp_hi": "अनुच्छेद 131 के तहत केंद्र-राज्य या राज्यों के आपसी विवादों की सीधी सुनवाई केवल सर्वोच्च न्यायालय में ही हो सकती है।",
        "cue_en": "Inter-state federal disputes = Article 131.",
        "cue_hi": "संघीय व अंतर्राज्यीय विवाद = अनुच्छेद 131 (आरंभिक क्षेत्राधिकार)।",
        "wrong_en": ["Exclusive federal original jurisdiction.", "Special Leave Petition (SLP).", "Presidential advisory jurisdiction.", "Appellate jurisdiction in constitutional matters."],
        "wrong_hi": ["अनन्य आरंभिक क्षेत्राधिकार।", "विशेष अनुमति याचिका (SLP)।", "राष्ट्रपति को परामर्श देने की शक्ति।", "संवैधानिक मामलों में अपीलीय क्षेत्राधिकार।"]
    },
    {
        "name_en": "High Courts & Subordinate Judiciary: Appointment, Transfer & Writ Jurisdiction (Article 226)",
        "name_hi": "उच्च न्यायालय एवं अधीनस्थ न्यायपालिका: नियुक्ति, स्थानांतरण एवं रिट क्षेत्राधिकार (अनुच्छेद 226)",
        "concepts_en": ["Articles 214 to 231 cover High Courts; currently 25 High Courts in India (oldest Calcutta HC 1862; newest Andhra Pradesh HC at Amaravati 2019)", "Judges retire at 62 years (compared to 65 for Supreme Court)", "Writ jurisdiction under Article 226 is wider than Art 32 because it covers Fundamental Rights AND any other legal rights", "Subordinate courts (District & Sessions Judge) under administrative superintendence of High Court (Art 227)"],
        "concepts_hi": ["संविधान के अनुच्छेद 214 से 231 में उच्च न्यायालय; वर्तमान में भारत में कुल 25 उच्च न्यायालय हैं (सबसे पुराना कलकत्ता 1862; 25वां अमरावती/आंध्र प्रदेश 2019)", "उच्च न्यायालय के न्यायाधीश 62 वर्ष की आयु में सेवानिवृत्त होते हैं (सर्वोच्च न्यायालय में 65 वर्ष)", "अनुच्छेद 226 के तहत रिट क्षेत्राधिकार अनुच्छेद 32 से अधिक व्यापक है क्योंकि यह मूल अधिकारों के साथ-साथ अन्य विधिक अधिकारों के लिए भी जारी हो सकता है", "अधीनस्थ न्यायपालिका (जिला एवं सत्र न्यायालय) उच्च न्यायालय के अधीक्षण में कार्य करती है (अनुच्छेद 227)"],
        "q_en": "Why is the writ jurisdiction of a High Court under Article 226 considered broader in scope than that of the Supreme Court under Article 32?",
        "q_hi": "अनुच्छेद 226 के तहत उच्च न्यायालय के रिट क्षेत्राधिकार को अनुच्छेद 32 के तहत सर्वोच्च न्यायालय के रिट क्षेत्राधिकार से अधिक व्यापक क्यों माना जाता है?",
        "options_en": ["High Courts can issue writs for Fundamental Rights as well as ordinary legal rights", "High Courts can issue more than five types of writs", "Supreme Court cannot issue Habeas Corpus", "High Court writs apply beyond national territory"],
        "options_hi": ["उच्च न्यायालय मूल अधिकारों के साथ-साथ किसी अन्य सामान्य विधिक अधिकार के प्रवर्तन हेतु भी रिट जारी कर सकते हैं", "उच्च न्यायालय पांच से अधिक प्रकार की रिटें जारी कर सकते हैं", "सर्वोच्च न्यायालय बंदी प्रत्यक्षीकरण जारी नहीं कर सकता", "उच्च न्यायालय की रिटें देश के बाहर भी लागू होती हैं"],
        "correct_idx": 0,
        "exp_en": "While the Supreme Court under Article 32 can issue writs only for enforcing Fundamental Rights, High Courts under Article 226 can issue writs for Fundamental Rights and 'for any other purpose' (ordinary legal rights).",
        "exp_hi": "सर्वोच्च न्यायालय (अनुच्छेद 32) केवल मूल अधिकारों के उल्लंघन पर रिट जारी कर सकता है, जबकि उच्च न्यायालय (अनुच्छेद 226) मूल अधिकारों के साथ-साथ किसी भी विधिक अधिकार के उल्लंघन पर भी रिट जारी कर सकता है।",
        "cue_en": "High Court writ (Art 226) = Fundamental Rights + Any other legal purpose.",
        "cue_hi": "उच्च न्यायालय रिट (अनुच्छेद 226) = मूल अधिकार + अन्य कानूनी अधिकार।",
        "wrong_en": ["Correct reason for broader scope.", "Both issue the same five writs.", "Supreme Court can issue Habeas Corpus.", "Territorial jurisdiction is within the state."],
        "wrong_hi": ["व्यापक होने का सही संवैधानिक कारण।", "दोनों समान पांच प्रकार की रिट जारी करते हैं।", "सर्वोच्च न्यायालय भी बंदी प्रत्यक्षीकरण जारी करता है।", "उच्च न्यायालय का क्षेत्राधिकार राज्य तक सीमित होता है।"]
    }
]

print("Loaded S05 successfully")
