# build_curriculum/group2_s04_part1.py
# S04: Medieval & Modern Indian History (Chapters 1, 2, 3 - 16 topics)

DATA = {}

# S04-C4112654a Early Medieval India, Delhi Sultanate Dynasties (6 topics)
DATA["S04-C4112654a"] = [
    {
        "name_en": "Tripartite Struggle for Kannauj: Gurjara-Pratiharas, Palas & Rashtrakutas",
        "name_hi": "कन्नौज का त्रिपक्षीय संघर्ष: गुर्जर-प्रतिहार, पाल एवं राष्ट्रकूट",
        "concepts_en": ["Centuries-long conflict for control of fertile Gangetic plains", "Gurjara-Pratiharas in west, Palas in Bengal/Bihar, Rashtrakutas in Deccan", "Pratihara ruler Nagabhata II and Vatsaraja", "Ultimate decline of all three dynasties leading to Rajput states"],
        "concepts_hi": ["गंगा के उपजाऊ मैदानों और महोदयश्री (कन्नौज) पर नियंत्रण हेतु 200 वर्षों का संघर्ष", "पश्चिम में गुर्जर-प्रतिहार, पूर्व में पाल और दक्कन में राष्ट्रकूट", "नागभट्ट द्वितीय एवं वत्सराज के अभियान", "तीनों शक्तियों के क्षीण होने पर राजपूत राज्यों का उदय"],
        "q_en": "Which three major Indian dynasties engaged in the famous two-century-long 'Tripartite Struggle' for control of the imperial city of Kannauj?",
        "q_hi": "शाही नगर कन्नौज पर आधिपत्य स्थापित करने हेतु दो शताब्दियों तक चलने वाले 'त्रिपक्षीय संघर्ष' में कौन से तीन राजवंश शामिल थे?",
        "options_en": ["Gurjara-Pratiharas, Palas, and Rashtrakutas", "Cholas, Cheras, and Pandyas", "Chalukyas, Pallavas, and Kadambas", "Delhi Sultans, Mughals, and Marathas"],
        "options_hi": ["गुर्जर-प्रतिहार, पाल एवं राष्ट्रकूट", "चोल, चेर एवं पांड्य", "चालुक्य, पल्लव एवं कदंब", "दिल्ली सुल्तान, मुगल एवं मराठा"],
        "correct_idx": 0,
        "exp_en": "The Tripartite Struggle (8th to 10th century CE) was waged between the Gurjara-Pratiharas of Western India, the Palas of Eastern India, and the Rashtrakutas of the Deccan.",
        "exp_hi": "8वीं से 10वीं शताब्दी के मध्य कन्नौज पर प्रभुत्व के लिए उत्तर भारत के गुर्जर-प्रतिहार, बंगाल के पाल और दक्कन के राष्ट्रकूटों के मध्य त्रिपक्षीय संघर्ष चला।",
        "cue_en": "Tripartite = Pratiharas + Palas + Rashtrakutas.",
        "cue_hi": "त्रिपक्षीय संघर्ष = प्रतिहार + पाल + राष्ट्रकूट।",
        "wrong_en": ["Three powers of Tripartite Struggle.", "Sangam powers of far south.", "Early medieval peninsular rivals.", "Late medieval powers."],
        "wrong_hi": ["त्रिपक्षीय संघर्ष की तीन शक्तियां।", "सुदूर दक्षिण की संगम शक्तियां।", "दक्कन के प्राचीन प्रतिद्वंद्वी।", "उत्तर मध्यकालीन शक्तियां।"]
    },
    {
        "name_en": "Imperial Cholas: Navy, Brihadisvara Temple & Uttaramerur Inscription",
        "name_hi": "शाही चोल साम्राज्य: नौसेना, वृहदेश्वर मंदिर एवं उत्तरमेरूर अभिलेख (स्थानीय स्वशासन)",
        "concepts_en": ["Rajaraja I built Brihadisvara Temple at Thanjavur (1010 CE)", "Rajendra I assumed title 'Gangaikondachola' and sent naval expedition to Srivijaya", "Uttaramerur Inscription of Parantaka I (920 CE) details Grama Sabha elections (Kudavolai system)", "Chola bronze Nataraja sculptures"],
        "concepts_hi": ["राजराज प्रथम ने तंजावुर में भव्य वृहदेश्वर (राजराजेश्वर) मंदिर बनवाया", "राजेंद्र प्रथम ने 'गंगैकोंडचोल' की उपाधि धारण की व श्रीविजय (दक्षिण-पूर्व एशिया) पर सफल नौसैनिक अभियान भेजा", "परांतक प्रथम का उत्तरमेरूर अभिलेख (920 ईस्वी): कुडुवोलाई (लॉटरी) प्रणाली द्वारा ग्राम सभा का चुनाव", "चोल कांस्य नटराज की उत्कृष्ट मूर्तियां"],
        "q_en": "The famous 10th-century Uttaramerur Inscription, providing extraordinary details of democratic village assembly (Sabha) elections, belongs to the reign of which Chola monarch?",
        "q_hi": "लोकतांत्रिक ग्राम सभा (सवा) के चुनाव और योग्यता नियमों का अभूतपूर्व विवरण देने वाला प्रसिद्ध 10वीं शताब्दी का 'उत्तरमेरूर अभिलेख' किस चोल शासक के काल का है?",
        "options_en": ["Parantaka I (परांतक प्रथम)", "Rajaraja I", "Rajendra I", "Kulottunga I"],
        "options_hi": ["परांतक प्रथम (Parantaka I)", "राजराज प्रथम", "राजेंद्र प्रथम", "कुलोत्तुंग प्रथम"],
        "correct_idx": 0,
        "exp_en": "The Uttaramerur inscription in modern Kanchipuram district belongs to Chola King Parantaka I (issued c. 919 and 921 CE), outlining village self-governance via the Kudavolai system.",
        "exp_hi": "तमिलनाडु के कांचीपुरम में स्थित उत्तरमेरूर अभिलेख चोल नरेश परांतक प्रथम के समय का है, जो स्वायत्त ग्रामीण स्वशासन और चुनाव प्रक्रिया का प्रामाणिक दस्तावेज है।",
        "cue_en": "Uttaramerur village assembly = Parantaka I Chola.",
        "cue_hi": "उत्तरमेरूर ग्रामीण स्वशासन अभिलेख = परांतक प्रथम चोल।",
        "wrong_en": ["Issued the Uttaramerur inscriptions.", "Built Thanjavur Brihadisvara temple.", "Conquered Gangetic delta and Srivijaya.", "Abolished tolls (Sungam Tavirtta Chola)."],
        "wrong_hi": ["उत्तरमेरूर अभिलेख जारी किया।", "तंजावुर के वृहदेश्वर मंदिर का निर्माण कराया।", "गंगैकोंडचोलपुरम की स्थापना की।", "चुंगी कर समाप्त करने वाला शासक।"]
    },
    {
        "name_en": "Mahmud of Ghazni, Muhammad Ghori & Battles of Tarain (1191, 1192)",
        "name_hi": "महमूद गजनवी, मुहम्मद गोरी एवं तराइन के ऐतिहासिक युद्ध (1191, 1192)",
        "concepts_en": ["Mahmud of Ghazni 17 expeditions to India (Somnath Temple 1025 CE)", "Al-Biruni accompanied Mahmud and wrote Kitab-ul-Hind", "First Battle of Tarain (1191): Prithviraj Chauhan defeated Muhammad Ghori", "Second Battle of Tarain (1192): Muhammad Ghori defeated Prithviraj, founding Muslim rule in North India"],
        "concepts_hi": ["महमूद गजनवी के भारत पर 17 आक्रमण (1025 ईस्वी में सोमनाथ मंदिर का विध्वंस)", "अल-बरूनी महमूद के साथ भारत आया और 'किताब-उल-हिंद' (तहकीक-ए-हिंद) लिखी", "तराइन का प्रथम युद्ध (1191 ईस्वी): पृथ्वीराज चौहान ने मुहम्मद गोरी को बुरी तरह परास्त किया", "तराइन का द्वितीय युद्ध (1192 ईस्वी): गोरी ने पृथ्वीराज को पराजित कर उत्तर भारत में तुर्क सल्तनत की नींव रखी"],
        "q_en": "In the Second Battle of Tarain (1192 CE), which Rajput ruler of Delhi and Ajmer was defeated by Muhammad Ghori?",
        "q_hi": "1192 ईस्वी में लड़े गए तराइन के दूसरे युद्ध में मुहम्मद गोरी ने दिल्ली और अजमेर के किस प्रतापी राजपूत शासक को पराजित किया था?",
        "options_en": ["Prithviraj Chauhan (Prithviraj III)", "Jaichand of Kannauj", "Rana Kumbha", "Maharana Pratap"],
        "options_hi": ["पृथ्वीराज चौहान (पृथ्वीराज तृतीय)", "कन्नौज के राजा जयचंद", "राणा कुंभा", "महाराणा प्रताप"],
        "correct_idx": 0,
        "exp_en": "Prithviraj Chauhan (Prithviraj III) won the First Battle of Tarain in 1191, but was defeated in the Second Battle in 1192 by Muhammad of Ghor.",
        "exp_hi": "1191 में तराइन के पहले युद्ध में पृथ्वीराज चौहान विजयी रहे, किंतु 1192 के दूसरे युद्ध में मुहम्मद गोरी ने उन्हें पराजित कर दिया।",
        "cue_en": "Second Battle of Tarain 1192 = Prithviraj Chauhan defeated by Ghori.",
        "cue_hi": "तराइन का द्वितीय युद्ध (1192) = पृथ्वीराज चौहान पराजित।",
        "wrong_en": ["Defeated at Second Tarain.", "Defeated at Battle of Chandawar (1194).", "15th-century Mewar king who built Vijay Stambha.", "16th-century Mewar hero of Haldighati."],
        "wrong_hi": ["तराइन के द्वितीय युद्ध में पराजित।", "1194 में चंदावर के युद्ध में गोरी से हारे।", "विजय स्तंभ बनवाने वाले मेवाड़ के राणा।", "हल्दीघाटी के वीर महाराणा।"]
    },
    {
        "name_en": "Slave Dynasty (Mamluks): Qutbuddin Aibak, Iltutmish & Razia Sultana",
        "name_hi": "गुलाम (मामलूक) वंश: कुतुबुद्दीन ऐबक, इल्तुतमिश एवं रजिया सुल्तान",
        "concepts_en": ["Qutbuddin Aibak (Lakh Baksh) founded Delhi Sultanate (1206), started Qutub Minar", "Shamsuddin Iltutmish real founder, instituted Turkan-i-Chahalgani (Group of Forty) and Iqta system", "Silver Tanka and Copper Jital coins introduced by Iltutmish", "Razia Sultana first woman Muslim ruler of Delhi (1236–1240)"],
        "concepts_hi": ["कुतुबुद्दीन ऐबक ('लाखबख्श') ने 1206 में सल्तनत की स्थापना की; कुतुब मीनार का निर्माण शुरू कराया", "शम्सुद्दीन इल्तुतमिश वास्तविक संस्थापक, 'तुर्कान-ए-चिहलगानी' (चालीसा दल) व इक्ता प्रणाली की शुरुआत", "इल्तुतमिश ने शुद्ध अरबी सिक्के चांदी का टंका और तांबे का जीतल चलाए", "रजिया सुल्तान दिल्ली की गद्दी पर बैठने वाली पहली व एकमात्र मुस्लिम महिला शासक (1236-1240)"],
        "q_en": "Who introduced the standardized silver coin 'Tanka' and copper coin 'Jital' into the currency system of the Delhi Sultanate?",
        "q_hi": "दिल्ली सल्तनत की मुद्रा प्रणाली में मानकीकृत चांदी का 'टंका' और तांबे का 'जीतल' किस सुल्तान द्वारा प्रारंभ किया गया था?",
        "options_en": ["Shamsuddin Iltutmish (शम्सुद्दीन इल्तुतमिश)", "Qutbuddin Aibak", "Balban", "Alauddin Khalji"],
        "options_hi": ["शम्सुद्दीन इल्तुतमिश (Shamsuddin Iltutmish)", "कुतुबुद्दीन ऐबक", "गयासुद्दीन बलबन", "अलाउद्दीन खिलजी"],
        "correct_idx": 0,
        "exp_en": "Iltutmish is credited with regularizing Delhi Sultanate currency by introducing the silver Tanka (175 grains) and the copper Jital.",
        "exp_hi": "इल्तुतमिश ने दिल्ली सल्तनत में पहली बार शुद्ध अरबी सिक्का पद्धति लागू करते हुए 175 ग्रेन का चांदी का टंका और तांबे का जीतल सिक्का जारी किया।",
        "cue_en": "Tanka & Jital = Iltutmish.",
        "cue_hi": "टंका और जीतल = इल्तुतमिश।",
        "wrong_en": ["Introduced Tanka and Jital.", "First sultan, died playing Chaugan.", "Destroyed the Chahalgani and introduced Sijdah.", "Introduced market reforms and Dagh."],
        "wrong_hi": ["टंका और जीतल का प्रवर्तक।", "चौगान खेलते समय घोड़े से गिरकर मृत्यु हुई।", "सिजदा व पैबोस प्रथा और लौह-रक्त नीति लागू की।", "बाजार नियंत्रण व दाग-चेहरा लागू किया।"]
    },
    {
        "name_en": "Khalji Dynasty: Alauddin Khalji's Market Reforms, Price Control & Military Expansion",
        "name_hi": "खिलजी वंश: अलाउद्दीन खिलजी के बाजार सुधार, मूल्य नियंत्रण एवं दक्षिण विजय",
        "concepts_en": ["Alauddin Khalji introduced price fixing of grains, cloth, horses via Shahna-i-Mandi", "Dagh (branding of horses) and Chehra (huldah/descriptive rolls of soldiers)", "Malik Kafur led southern expeditions to Devagiri, Warangal, Dwarasamudra, Madurai", "Alai Darwaza architectural masterpiece at Qutub complex"],
        "concepts_hi": ["अलाउद्दीन खिलजी ने आवश्यक वस्तुओं की कीमतें तय कीं; 'शहना-ए-मंडी' की नियुक्ति", "सेना में घोड़ों को दागने की 'दाग' प्रथा एवं सैनिकों का हुलिया दर्ज करने की 'चेहरा' प्रथा", "मलिक काफूर के नेतृत्व में देवगिरि, वारंगल, द्वारसमुद्र और मदुरै तक दक्षिण भारत की सफल विजय", "कुतुब परिसर में अलाई दरवाजा का निर्माण"],
        "q_en": "Under Alauddin Khalji's market control regulations, which designated official was appointed to supervise and regulate the grain market (Mandi)?",
        "q_hi": "अलाउद्दीन खिलजी की बाजार नियंत्रण प्रणाली के अंतर्गत अनाज मंडी की देखरेख और मूल्य नियंत्रण हेतु किस शीर्ष अधिकारी को नियुक्त किया गया था?",
        "options_en": ["Shahna-i-Mandi (शहना-ए-मंडी)", "Diwan-i-Arz", "Barid-i-Mandi", "Munhiyan"],
        "options_hi": ["शहना-ए-मंडी (Shahna-i-Mandi)", "दीवान-ए-अर्ज", "बरीद-ए-मंडी", "मुन्हियां"],
        "correct_idx": 0,
        "exp_en": "Alauddin Khalji placed the grain market under the superintendent known as Shahna-i-Mandi, supported by intelligence officers (Barids) and secret spies (Munhiyans).",
        "exp_hi": "अलाउद्दीन खिलजी ने अनाज बाजार की सर्वोच्च देखरेख के लिए 'शहना-ए-मंडी' नामक अधिकारी नियुक्त किया, जिसकी सहायता बरीद (सूचना अधिकारी) और मुन्हियां (गुप्तचर) करते थे।",
        "cue_en": "Market superintendent = Shahna-i-Mandi.",
        "cue_hi": "बाजार अधीक्षक = शहना-ए-मंडी।",
        "wrong_en": ["Superintendent of market.", "Military minister.", "Official intelligence reporter.", "Secret spy."],
        "wrong_hi": ["मंडी का प्रमुख अधीक्षक अधिकारी।", "सैन्य विभाग का प्रमुख।", "खुफिया रिपोर्टर अधिकारी।", "गुप्त जासूस।"]
    },
    {
        "name_en": "Tughlaq Dynasty: Muhammad bin Tughlaq's Projects & Firoz Shah's Public Works",
        "name_hi": "तुगलक वंश: मुहम्मद बिन तुगलक की पांच योजनाएं एवं फिरोज शाह तुगलक के लोक निर्माण कार्य",
        "concepts_en": ["Muhammad bin Tughlaq visionary schemes: Taxation in Doab, Transfer of capital to Daulatabad (1327), Token currency (copper/brass), Khurasan expedition", "Ibn Battuta (Moroccan traveler, wrote Rihla) appointed Qazi of Delhi", "Firoz Shah Tughlaq established canals, Diwan-i-Khairat, Diwan-i-Bandagan, Firozabad city", "Imposition of Jizya on Brahmins"],
        "concepts_hi": ["मुहम्मद बिन तुगलक की पांच योजनाएं: दोआब में कर वृद्धि, देवगिरि (दौलताबाद) राजधानी परिवर्तन, सांकेतिक मुद्रा का प्रचलन, खुरासान अभियान", "मोरक्को के प्रसिद्ध यात्री इब्न बतूता ('रेहला' के रचयिता) दिल्ली के काजी नियुक्त हुए", "फिरोज शाह तुगलक ने नहरों का जाल बिछाया, दीवान-ए-खैरात व दीवान-ए-बंदगान स्थापित किए", "ब्राह्मणों पर भी जजिया कर लगाया"],
        "q_en": "The famous Moroccan traveler Ibn Battuta, author of the travelogue 'Rihla', visited India during the reign of which Delhi Sultan?",
        "q_hi": "प्रसिद्ध मोरक्कन यात्री इब्न बतूता, जिसने अपनी यात्रा पुस्तक 'रेहला' लिखी, किस दिल्ली सुल्तान के शासनकाल में भारत आया था?",
        "options_en": ["Muhammad bin Tughlaq (मुहम्मद बिन तुगलक)", "Alauddin Khalji", "Firoz Shah Tughlaq", "Sikandar Lodi"],
        "options_hi": ["मुहम्मद बिन तुगलक (Muhammad bin Tughlaq)", "अलाउद्दीन खिलजी", "फिरोज शाह तुगलक", "सिकंदर लोदी"],
        "correct_idx": 0,
        "exp_en": "Ibn Battuta arrived in India in 1333 during Muhammad bin Tughlaq's reign and was appointed as the Chief Qazi of Delhi for eight years.",
        "exp_hi": "इब्न बतूता 1333 ईस्वी में मुहम्मद बिन तुगलक के समय भारत आया; सुल्तान ने उसे 8 वर्षों के लिए दिल्ली का काजी नियुक्त किया और बाद में चीन में अपना दूत बनाकर भेजा।",
        "cue_en": "Ibn Battuta (Rihla) = Muhammad bin Tughlaq (1333).",
        "cue_hi": "इब्न बतूता (रेहला) = मुहम्मद बिन तुगलक।",
        "wrong_en": ["Patron of Ibn Battuta.", "Preceded Ibn Battuta's arrival.", "Cousin and successor of MBT.", "Lodi ruler who founded Agra."],
        "wrong_hi": ["इब्न बतूता का समकालीन सुल्तान।", "इब्न बतूता के आने से पहले का सुल्तान।", "तुगलक का चचेरा भाई व उत्तराधिकारी।", "आगरा की स्थापना करने वाला लोदी शासक।"]
    }
]

# S04-Ccead5806 Mughal Empire: Polity, Economy & Architecture (5 topics)
DATA["S04-Ccead5806"] = [
    {
        "name_en": "Foundations: Babur (Panipat 1526), Humayun & Sur Interregnum (Sher Shah)",
        "name_hi": "मुगल साम्राज्य की स्थापना: बाबर (पानीपत 1526), हुमायूं एवं सूर वंश (शेरशाह सूरी)",
        "concepts_en": ["First Battle of Panipat (21 April 1526): Babur defeated Ibrahim Lodi using Tulghuma tactic & artillery (cannons)", "Battle of Khanwa (1527) against Rana Sanga; Babur wrote Tuzuk-i-Baburi (Baburnama)", "Humayun defeated at Chausa (1539) and Kannauj (1540) by Sher Shah Suri", "Sher Shah Suri administrative reforms: Grand Trunk Road (Sadak-e-Azam), silver Rupiya, postal Dak chowkis"],
        "concepts_hi": ["पानीपत का प्रथम युद्ध (21 अप्रैल 1526): बाबर ने तुलगमा पद्धति व तोपखाने से इब्राहिम लोदी को हराया", "खानवा का युद्ध (1527): राणा सांगा को पराजित किया; तुर्की भाषा में 'तुजुक-ए-बाबरी' लिखी", "शेरशाह सूरी ने हुमायूं को चौसा (1539) और बिलग्राम/कन्नौज (1540) में पराजित किया", "शेरशाह के सुधार: ग्रैंड ट्रंक रोड (सड़क-ए-आजम), शुद्ध चांदी का 'रुपिया' (178 ग्रेन) एवं डाक चौकियों की स्थापना"],
        "q_en": "Who introduced the standardized pure silver coin weighing 178 grains named 'Rupiya', which became the ancestor of modern Indian currency?",
        "q_hi": "178 ग्रेन वजन का मानक शुद्ध चांदी का सिक्का 'रुपिया', जो आधुनिक भारतीय मुद्रा का पूर्वज बना, किस शासक द्वारा शुरू किया गया था?",
        "options_en": ["Sher Shah Suri (शेरशाह सूरी)", "Akbar", "Babur", "Alauddin Khalji"],
        "options_hi": ["शेरशाह सूरी (Sher Shah Suri)", "अकबर", "बाबर", "अलाउद्दीन खिलजी"],
        "correct_idx": 0,
        "exp_en": "Sher Shah Suri reformed currency by issuing the silver Rupiya (178 grains) and copper Dam, along with building the Sadak-e-Azam (Grand Trunk Road).",
        "exp_hi": "शेरशाह सूरी ने 178 ग्रेन का चांदी का 'रुपिया' और तांबे का 'दाम' चलाया; उसने पेशावर से कोलकाता तक सड़क-ए-आजम (जीटी रोड) का निर्माण भी कराया।",
        "cue_en": "Silver Rupiya & GT Road = Sher Shah Suri.",
        "cue_hi": "चांदी का रुपिया और जीटी रोड = शेरशाह सूरी।",
        "wrong_en": ["Issued the original silver Rupiya.", "Continued and expanded the system.", "First Mughal, used Shahrukhi coins.", "Issued Tanka and Jital."],
        "wrong_hi": ["मूल चांदी के रुपिया का जनक।", "प्रणाली को आगे बढ़ाने वाले मुगल।", "शाहरुखी सिक्के चलाने वाले बाबर।", "सल्तनत कालीन सिक्के।"]
    },
    {
        "name_en": "Akbar's Administrative Innovations: Mansabdari System & Dahsala Revenue System",
        "name_hi": "अकबर के प्रशासनिक नवाचार: मनसबदारी व्यवस्था एवं आइन-ए-दहसाला भू-राजस्व प्रणाली",
        "concepts_en": ["Mansabdari system: Dual ranks Zat (personal status/salary) and Sawar (cavalry contingent to maintain)", "Dahsala system (1580) formulated by Raja Todar Mal calculating 10-year average yield", "Classification of land: Polaj (annually cultivated), Parauti, Chachar, Banjar", "Ain-i-Akbari & Akbarnama written by Abul Fazl"],
        "concepts_hi": ["मनसबदारी व्यवस्था: दोहरे पद जात (व्यक्तिगत दर्जा व वेतन) और सवार (सैनिक व घुड़सवार टुकड़ी)", "राजा टोडरमल द्वारा 1580 में तैयार की गई 'दहसाला' भू-राजस्व प्रणाली (10 वर्षों की औसत उपज पर आधारित)", "भूमि का चार वर्गों में वर्गीकरण: पोलज (प्रतिवर्ष खेती), परती, चाचर, बंजर", "अबुल फजल द्वारा रचित 'अकबरनामा' एवं 'आइन-ए-अकबरी'"],
        "q_en": "In Akbar's Mansabdari administrative framework, what did the rank 'Zat' specifically indicate?",
        "q_hi": "अकबर की मनसबदारी व्यवस्था में 'जात' (Zat) पद मुख्य रूप से क्या दर्शाता था?",
        "options_en": ["Personal status and salary of the noble", "Number of cavalry soldiers to be maintained", "Number of horses branded", "Territorial jagir area"],
        "options_hi": ["मनसबदार का व्यक्तिगत दर्जा और उसका वेतन", "रखे जाने वाले घुड़सवारों की संख्या", "दागे गए घोड़ों की संख्या", "आवंटित जागीर का क्षेत्रफल"],
        "correct_idx": 0,
        "exp_en": "In the Mansabdari system, 'Zat' determined the noble's personal position in the imperial hierarchy and fixed his salary, whereas 'Sawar' denoted the cavalry troop quota.",
        "exp_hi": "मनसबदारी प्रणाली में 'जात' से मनसबदार के व्यक्तिगत पद और वेतन का निर्धारण होता था, जबकि 'सवार' से उसके द्वारा रखे जाने वाले घुड़सवार सैनिकों की संख्या तय होती थी।",
        "cue_en": "Zat = Personal rank & pay; Sawar = Cavalry count.",
        "cue_hi": "जात = व्यक्तिगत पद व वेतन; सवार = घुड़सवारों की संख्या।",
        "wrong_en": ["Correct role of Zat.", "Represented by Sawar rank.", "Dagh system feature.", "Jagirdari allocation."],
        "wrong_hi": ["जात पद की सही परिभाषा।", "सवार पद द्वारा निर्धारित होता था।", "दाग प्रथा का हिस्सा।", "जागीर का आवंटन।"]
    },
    {
        "name_en": "Akbar's Religious Policy: Sulh-i-Kul, Ibadat Khana & Din-i-Ilahi",
        "name_hi": "अकबर की धार्मिक नीति: सुलह-ए-कुल, इबादत खाना, महजरनामा एवं दीन-ए-इलाही",
        "concepts_en": ["Abolition of Pilgrim Tax (1563) and Jizya (1564)", "Ibadat Khana (House of Worship) built at Fatehpur Sikri (1575) for interfaith debates", "Mahzarnama (Infallibility Decree, 1579) drafted by Sheikh Mubarak making Akbar supreme religious arbiter", "Sulh-i-Kul (Universal Peace) and Tauhid-i-Ilahi / Din-i-Ilahi (1582)"],
        "concepts_hi": ["तीर्थयात्रा कर (1563) एवं गैर-मुसलमानों पर जजिया कर (1564) की समाप्ति", "फतेहपुर सीकरी में अंतर-धार्मिक संवाद हेतु इबादत खाने का निर्माण (1575)", "शेख मुबारक द्वारा तैयार 'महजरनामा' (1579): अकबर को धार्मिक मामलों में अंतिम मध्यस्थ घोषित किया गया", "सुलह-ए-कुल (सार्वभौमिक शांति) एवं 1582 में 'दीन-ए-इलाही' (तौहीद-ए-इलाही) की घोषणा"],
        "q_en": "In 1575, Emperor Akbar established the 'Ibadat Khana' (House of Worship) for theological debates and interfaith discourses at which capital city?",
        "q_hi": "1575 ईस्वी में सम्राट अकबर ने विभिन्न धर्मों के विद्वानों के साथ धार्मिक विचार-विमर्श हेतु 'इबादत खाना' की स्थापना किस नगर में की थी?",
        "options_en": ["Fatehpur Sikri (फतेहपुर सीकरी)", "Agra", "Delhi", "Lahore"],
        "options_hi": ["फतेहपुर सीकरी (Fatehpur Sikri)", "आगरा", "दिल्ली", "लाहौर"],
        "correct_idx": 0,
        "exp_en": "Akbar built the Ibadat Khana at Fatehpur Sikri in 1575, initially open to Muslim theologians and later expanded in 1578 to scholars of Hinduism, Jainism, Zoroastrianism, and Christianity.",
        "exp_hi": "अकबर ने 1575 में अपनी नई राजधानी फतेहपुर सीकरी में इबादत खाना बनवाया, जिसमें सभी धर्मों के दार्शनिकों के साथ सत्य की खोज पर चर्चा होती थी।",
        "cue_en": "Ibadat Khana = Fatehpur Sikri (1575).",
        "cue_hi": "इबादत खाना = फतेहपुर सीकरी (1575)।",
        "wrong_en": ["Site of Ibadat Khana.", "Earlier Mughal capital.", "Later shifted by Shah Jahan.", "Served as temporary capital."],
        "wrong_hi": ["इबादत खाना का निर्माण स्थल।", "प्रारंभिक राजधानी।", "शाहजहां द्वारा बसाई गई राजधानी।", "अकबर की उत्तर-पश्चिमी राजधानी।"]
    },
    {
        "name_en": "Mughal Architecture: Humayun's Tomb, Fatehpur Sikri, Taj Mahal & Red Fort",
        "name_hi": "मुगल स्थापत्य कला: हुमायूं का मकबरा, फतेहपुर सीकरी, ताजमहल एवं लाल किला",
        "concepts_en": ["Humayun's Tomb (Delhi, Mirak Mirza Ghiyas) - first garden-tomb (Charbagh) and precursor to Taj Mahal", "Fatehpur Sikri: Buland Darwaza (commemorating Gujarat conquest), Panch Mahal, Salim Chishti tomb", "Shah Jahan Golden Age of Architecture: Taj Mahal at Agra (Ustad Ahmad Lahori), Moti Masjid, Red Fort & Jama Masjid in Delhi", "Pietra Dura (Parchin Kari) floral marble inlay technique"],
        "concepts_hi": ["हुमायूं का मकबरा (दिल्ली, मीरक मिर्जा गियास): चारबाग शैली का पहला मकबरा, ताजमहल का अग्रदूत", "फतेहपुर सीकरी: बुलंद दरवाजा (गुजरात विजय की स्मृति में), पंचमहल, सलीम चिश्ती की दरगाह", "शाहजहां का काल स्थापत्य का स्वर्ण युग: ताजमहल (उस्ताद अहमद लाहौरी), मोती मस्जिद, दिल्ली का लाल किला व जामा मस्जिद", "पितरा दूरा (पच्चीकारी): संगमरमर पर रंगीन पत्थरों की जड़ाई कला"],
        "q_en": "Who was the chief architect behind the design and construction of the Taj Mahal in Agra?",
        "q_hi": "आगरा में स्थित विश्व प्रसिद्ध ताजमहल के मुख्य वास्तुकार (Chief Architect) कौन थे?",
        "options_en": ["Ustad Ahmad Lahori (उस्ताद अहमद लाहौरी)", "Mirak Mirza Ghiyas", "Bahauddin", "Inayat Khan"],
        "options_hi": ["उस्ताद अहमद लाहौरी (Ustad Ahmad Lahori)", "मीरक मिर्जा गियास", "बहाउद्दीन", "इनायत खान"],
        "correct_idx": 0,
        "exp_en": "Ustad Ahmad Lahori is widely credited as the chief architect of the Taj Mahal, for which Shah Jahan conferred upon him the title 'Nadir-ul-Asar'.",
        "exp_hi": "शाहजहां के दरबारी इतिहास के अनुसार ताजमहल के प्रधान वास्तुकार उस्ताद अहमद लाहौरी थे, जिन्हें शाहजहां ने 'नादिर-उल-असर' की उपाधि दी थी।",
        "cue_en": "Taj Mahal architect = Ustad Ahmad Lahori.",
        "cue_hi": "ताजमहल के मुख्य वास्तुकार = उस्ताद अहमद लाहौरी।",
        "wrong_en": ["Chief architect of Taj Mahal.", "Architect of Humayun's Tomb.", "Architect of Gol Gumbaz.", "Author of Shah Jahan Nama."],
        "wrong_hi": ["ताजमहल के प्रमुख वास्तुकार।", "हुमायूं के मकबरे के वास्तुकार।", "गोल गुम्बज के वास्तुकार।", "शाहजहांनामा के लेखक।"]
    },
    {
        "name_en": "Aurangzeb's Reign, Deccan Campaigns & Decline of the Mughal Empire",
        "name_hi": "औरंगजेब का शासन, दक्कन के अभियान एवं मुगल साम्राज्य का पतन",
        "concepts_en": ["War of Succession (1658): Defeated Dara Shikoh at Samugarh; titled Alamgir", "Re-imposition of Jizya in 1679; annexation of Bijapur (1686) and Golconda (1687)", "Deccan Ulcer exhausted treasury and military strength for 25 years", "Later Mughals: Bahadur Shah I, Farrukhsiyar, Muhammad Shah 'Rangeela' (Nadir Shah raid 1739)"],
        "concepts_hi": ["उत्तराधिकार का युद्ध (1658): सामूगढ़ में दारा शिकोह को हराकर 'आलमगीर' की उपाधि धारण की", "1679 में जजिया कर पुनः लागू किया; बीजापुर (1686) व गोलकुंडा (1687) का विलय", "'दक्कन का नासूर' (Deccan Ulcer): 25 वर्षों के दक्कन अभियानों ने साम्राज्य का खजाना व शक्ति समाप्त कर दी", "उत्तरवर्ती मुगल: नादिर शाह का दिल्ली पर आक्रमण (1739, मुहम्मद शाह रंगीला का समय) व मयूर सिंहासन की लूट"],
        "q_en": "In which year did Emperor Aurangzeb re-impose the religious poll tax 'Jizya' on non-Muslim subjects, which had earlier been abolished by Akbar in 1564?",
        "q_hi": "मुगल सम्राट औरंगजेब ने गैर-मुस्लिम प्रजा पर 'जजिया कर' किस वर्ष पुनः लागू किया था, जिसे 1564 में अकबर ने समाप्त कर दिया था?",
        "options_en": ["1679 CE", "1658 CE", "1686 CE", "1707 CE"],
        "options_hi": ["1679 ईस्वी", "1658 ईस्वी", "1686 ईस्वी", "1707 ईस्वी"],
        "correct_idx": 0,
        "exp_en": "Aurangzeb re-imposed Jizya in 1679 CE, reversing Akbar's liberal policy and alienating Rajput and other non-Muslim populations.",
        "exp_hi": "औरंगजेब ने 1679 ईस्वी में जजिया कर को फिर से लागू किया, जिसके कारण साम्राज्य में असंतोष बढ़ा।",
        "cue_en": "Jizya re-imposed = 1679 by Aurangzeb.",
        "cue_hi": "जजिया पुनः लागू = 1679 (औरंगजेब)।",
        "wrong_en": ["Year Jizya was re-imposed.", "Accession year of Aurangzeb.", "Annexation of Bijapur.", "Year of Aurangzeb's death."],
        "wrong_hi": ["जजिया कर पुनः लागू होने का वर्ष।", "औरंगजेब का राज्यारोहण वर्ष।", "बीजापुर के विलय का वर्ष।", "औरंगजेब की मृत्यु का वर्ष।"]
    }
]

# S04-C780a1737 Vijayanagara Empire, Marathas & Regional Powers (5 topics)
DATA["S04-C780a1737"] = [
    {
        "name_en": "Vijayanagara Empire: Harihara & Bukka, Four Dynasties & Krishnadeva Raya",
        "name_hi": "विजयनगर साम्राज्य: हरिहर व बुक्का, चार राजवंश एवं कृष्णदेव राय का स्वर्ण काल",
        "concepts_en": ["Founded on Tungabhadra banks (1336) by Harihara I and Bukka I of Sangama dynasty (mentored by Vidyaranya)", "Four dynasties: Sangama, Saluva, Tuluva, Aravidu", "Krishnadeva Raya (Tuluva dynasty, reigned 1509–1529) author of Telugu classic Amuktamalyada", "Ashtadiggajas (eight court poets including Allasani Peddana and Tenali Ramakrishna)"],
        "concepts_hi": ["1336 में तुंगभद्रा नदी के तट पर संत विद्यारण्य के आशीर्वाद से संगम बंधुओं (हरिहर व बुक्का) द्वारा स्थापना", "चार राजवंश: संगम, सालुव, तुलुव एवं आरविडु", "कृष्णदेव राय (तुलुव वंश, 1509-1529): तेलुगु कालजयी ग्रंथ 'आमुक्तमाल्यद' के रचयिता", "दरबार के आठ महान कवि 'अष्टदिग्गज' (अल्लासानी पेद्दना, तेनालीराम आदि)"],
        "q_en": "Emperor Krishnadeva Raya of the Vijayanagara Empire authored the celebrated epic poem 'Amuktamalyada' in which classical language?",
        "q_hi": "विजयनगर साम्राज्य के महान सम्राट कृष्णदेव राय ने अपनी प्रसिद्ध राजनीतिक व धार्मिक रचना 'आमुक्तमाल्यद' किस भाषा में लिखी थी?",
        "options_en": ["Telugu (तेलुगु)", "Sanskrit", "Kannada", "Tamil"],
        "options_hi": ["तेलुगु (Telugu)", "संस्कृत", "कन्नड़", "तमिल"],
        "correct_idx": 0,
        "exp_en": "Krishnadeva Raya composed Amuktamalyada in Telugu, describing the life of Andal and detailing practical statecraft. He also composed Jambavati Kalyanam in Sanskrit.",
        "exp_hi": "कृष्णदेव राय ने तेलुगु भाषा में 'आमुक्तमाल्यद' महाकाव्य लिखा, जिसमें वैष्णव संत आंडाल की कथा और राजनीति का सजीव वर्णन है।",
        "cue_en": "Amuktamalyada = Telugu by Krishnadeva Raya.",
        "cue_hi": "आमुक्तमाल्यद = तेलुगु भाषा (कृष्णदेव राय)।",
        "wrong_en": ["Language of Amuktamalyada.", "He wrote Jambavati Kalyanam in Sanskrit.", "Kannada was regional language.", "Tamil was also in empire."],
        "wrong_hi": ["आमुक्तमाल्यद की भाषा।", "संस्कृत में जाम्बवती कल्याणम लिखा।", "कन्नड़ साम्राज्य की अन्य भाषा थी।", "तमिल भी साम्राज्य में बोली जाती थी।"]
    },
    {
        "name_en": "Battle of Talikota (1565) & Decline of Vijayanagara",
        "name_hi": "तालिकोटा (राक्षस-तांगड़ी) का युद्ध (1565) एवं विजयनगर साम्राज्य का पतन",
        "concepts_en": ["Fought on 23 January 1565 between Vijayanagara (led by Rama Raya) and Deccan Sultanates coalition (Bijapur, Golconda, Ahmadnagar, Bidar)", "Decisive rout of Vijayanagara army; capital city Hampi thoroughly sacked and destroyed", "Shift of remnants to Penukonda and Chandragiri under Tirumala Raya (Aravidu dynasty)", "Hampi ruins rediscovered by Colin Mackenzie in 1800"],
        "concepts_hi": ["23 जनवरी 1565 को विजयनगर (सेनापति रामराय) और दक्कन सल्तनतों (बीजापुर, गोलकुंडा, अहमदनगर, बीदर) के संयुक्त मोर्चे के बीच युद्ध", "विजयनगर की करारी हार; राजधानी हम्पी को जलाकर ध्वस्त कर दिया गया", "तिरूमल राय द्वारा आरविडु वंश के तहत राजधानी पेनुकोंडा व चंद्रगिरि स्थानांतरित", "1800 ईस्वी में कॉलिन मैकेंजी द्वारा हम्पी के खंडहरों का सर्वेक्षण"],
        "q_en": "The historic Battle of Talikota (also known as Rakshasa-Tangadi), which led to the destruction of Hampi, was fought in which year?",
        "q_hi": "विजयनगर साम्राज्य के गौरवशाली पतन का कारण बना ऐतिहासिक 'तालिकोटा का युद्ध' (राक्षस-तांगड़ी का युद्ध) किस वर्ष लड़ा गया था?",
        "options_en": ["1565 CE", "1526 CE", "1556 CE", "1576 CE"],
        "options_hi": ["1565 ईस्वी", "1526 ईस्वी", "1556 ईस्वी", "1576 ईस्वी"],
        "correct_idx": 0,
        "exp_en": "On 23 January 1565, the combined armies of Bijapur, Golconda, Ahmadnagar, and Bidar defeated Rama Raya at Talikota (Rakshasi-Tangadi), leading to the destruction of Hampi.",
        "exp_hi": "23 जनवरी 1565 को तालिकोटा के युद्ध में दक्कन सल्तनतों के संयुक्त मोर्चे ने विजयनगर को परास्त किया, जिसके बाद हम्पी का विध्वंस हुआ।",
        "cue_en": "Battle of Talikota = 1565 CE.",
        "cue_hi": "तालिकोटा का युद्ध = 1565 ईस्वी।",
        "wrong_en": ["Year of Battle of Talikota.", "First Battle of Panipat.", "Second Battle of Panipat.", "Battle of Haldighati."],
        "wrong_hi": ["तालिकोटा युद्ध का वर्ष।", "पानीपत का प्रथम युद्ध।", "पानीपत का द्वितीय युद्ध।", "हल्दीघाटी का युद्ध।"]
    },
    {
        "name_en": "Chhatrapati Shivaji Maharaj: Swarajya, Ashtapradhan Council & Guerilla Warfare",
        "name_hi": "छत्रपति शिवाजी महाराज: हिंदवी स्वराज्य, अष्टप्रधान परिषद एवं गुरिल्ला युद्धनीति",
        "concepts_en": ["Born at Shivneri fort (1630); established Hindavi Swarajya using Ganimi Kava (guerrilla tactics)", "Treaty of Purandar (1665) signed with Raja Jai Singh representing Aurangzeb", "Coronation as Chhatrapati at Raigad fort (1674) by Gaga Bhatt", "Ashtapradhan council: Peshwa (Prime Minister), Amatya (Finance), Sachiv, Senapati, Sumant, etc."],
        "concepts_hi": ["शिवनेरी दुर्ग में जन्म (1630); 'गनीमी कावा' (गुरिल्ला छापामार युद्धनीति) द्वारा हिंदवी स्वराज्य की स्थापना", "1665 में औरंगजेब के सेनापति मिर्जा राजा जयसिंह के साथ पुरंदर की संधि", "1674 में रायगढ़ दुर्ग में काशी के विद्वान गागाभट्ट द्वारा छत्रपति के रूप में राज्याभिषेक", "अष्टप्रधान मंत्रिपरिषद: पेशवा (मुख्य प्रधान), अमात्य (वित्त), सचिव, सेनापति, सुमंत (विदेश मंत्री) आदि"],
        "q_en": "In Chhatrapati Shivaji Maharaj's administrative council of eight ministers (Ashtapradhan), what portfolio was handled by the 'Sumant'?",
        "q_hi": "छत्रपति शिवाजी महाराज की आठ मंत्रियों वाली 'अष्टप्रधान परिषद' में 'सुमंत' (डबीर) किस विभाग के प्रभारी मंत्री थे?",
        "options_en": ["Foreign Affairs / External Relations (विदेश मंत्री)", "Finance and Revenue (अमात्य)", "Commander-in-Chief (सेनापति)", "Royal Correspondence (सचिव)"],
        "options_hi": ["विदेश मंत्री / बाह्य संबंध (Foreign Affairs)", "वित्त एवं राजस्व मंत्री", "प्रधान सेनापति (सर-ए-नौबत)", "राजकीय पत्राचार (सुरनवीस / सचिव)"],
        "correct_idx": 0,
        "exp_en": "In Shivaji's Ashtapradhan, the Sumant (or Dabir) was responsible for foreign affairs and diplomatic correspondence with other states.",
        "exp_hi": "अष्टप्रधान में 'सुमंत' (दबीर) विदेश मंत्री थे, जो अन्य राज्यों के साथ राजनयिक संबंधों और संधियों का कार्यभार संभालते थे।",
        "cue_en": "Sumant = Foreign Minister in Ashtapradhan.",
        "cue_hi": "सुमंत = विदेश मंत्री (अष्टप्रधान)।",
        "wrong_en": ["Handled foreign affairs.", "Portfolio of Amatya.", "Portfolio of Senapati / Sar-i-Naubat.", "Portfolio of Sachiv / Shurunavis."],
        "wrong_hi": ["विदेश मंत्रालय के प्रभारी।", "अमात्य (मजूमदार) का वित्त विभाग।", "सेनापति का कार्यभार।", "सचिव का कार्यभार।"]
    },
    {
        "name_en": "Peshwas, Maratha Confederacy & Third Battle of Panipat (1761)",
        "name_hi": "पेशवा काल, मराठा परिसंघ एवं पानीपत का तीसरा युद्ध (1761)",
        "concepts_en": ["Balaji Vishwanath made Peshwaship hereditary; Baji Rao I ('Fighting Peshwa') expanded Marathas to Delhi", "Maratha Confederacy: Scindias (Gwalior), Holkars (Indore), Gaekwads (Baroda), Bhonsles (Nagpur)", "Third Battle of Panipat (14 January 1761): Ahmad Shah Abdali defeated Sadashivrao Bhau and Vishwasrao", "Taxes: Chauth (25% revenue) and Sardeshmukhi (additional 10%)"],
        "concepts_hi": ["बालाजी विश्वनाथ ने पेशवा पद को वंशानुगत बनाया; बाजीराव प्रथम ने 'अटक से कटक' तक मराठा साम्राज्य का विस्तार किया", "मराठा परिसंघ के प्रमुख घराने: सिंधिया (ग्वालियर), होल्कर (इंदौर), गायकवाड़ (बड़ौदा), भोंसले (नागपुर)", "पानीपत का तीसरा युद्ध (14 जनवरी 1761): अहमद शाह अब्दाली (दुर्रानी) ने सदाशिवराव भाऊ के नेतृत्व वाली मराठा सेना को हराया", "मराठा कर प्रणाली: चौथ (उपज/राजस्व का 1/4 या 25%) एवं सरदेशमुखी (अतिरिक्त 10%)"],
        "q_en": "In the Third Battle of Panipat on 14 January 1761, who commanded the Afghan forces that defeated the Maratha army?",
        "q_hi": "14 जनवरी 1761 को पानीपत के तीसरे युद्ध में मराठा सेना को पराजित करने वाली अफगान सेना का सर्वोच्च सेनापति कौन था?",
        "options_en": ["Ahmad Shah Abdali (अहमद शाह अब्दाली / दुर्रानी)", "Nadir Shah", "Zaman Shah", "Najib-ud-Daulah"],
        "options_hi": ["अहमद शाह अब्दाली (Ahmad Shah Abdali - Durrani)", "नादिर शाह", "जमान शाह", "नजीब-उद-दौला"],
        "correct_idx": 0,
        "exp_en": "Ahmad Shah Durrani (Abdali), supported by Najib-ud-Daulah and Shuja-ud-Daulah, defeated the Maratha confederacy commanded by Sadashivrao Bhau at Panipat in 1761.",
        "exp_hi": "पानीपत के तीसरे युद्ध में अफगान शासक अहमद शाह अब्दाली ने नजीब-उद-दौला और शुजाउद्दौला के सहयोग से मराठा सेना को पराजित किया।",
        "cue_en": "Third Panipat 1761 = Ahmad Shah Abdali vs Marathas.",
        "cue_hi": "पानीपत का तीसरा युद्ध (1761) = अहमद शाह अब्दाली बनाम मराठा।",
        "wrong_en": ["Afghan commander in 1761.", "Invaded Delhi earlier in 1739.", "Son/successor of Abdali.", "Rohilla chieftain ally."],
        "wrong_hi": ["पानीपत में अफगान विजेता।", "1739 में दिल्ली को लूटने वाला ईरानी शासक।", "अब्दाली का उत्तराधिकारी।", "रोहिल्ला सरदार (सहयोगी)।"]
    },
    {
        "name_en": "Regional Kingdoms: Sikh Empire of Maharaja Ranjit Singh & Nawabs of Bengal and Awadh",
        "name_hi": "क्षेत्रीय राज्य: महाराजा रणजीत सिंह का सिख साम्राज्य एवं बंगाल व अवध के नवाब",
        "concepts_en": ["Maharaja Ranjit Singh unified Sukerchakia misl and established Sikh Empire (capital Lahore, 1799)", "Modernized Fauj-i-Khas with European generals (Allard, Ventura); golden covering on Harmandir Sahib", "Nawabs of Bengal: Murshid Quli Khan (shifted capital to Murshidabad), Alivardi Khan", "Nawabs of Awadh: Saadat Khan Burhan-ul-Mulk founded dynasty; Asaf-ud-Daula built Bara Imambara at Lucknow"],
        "concepts_hi": ["महाराजा रणजीत सिंह ने सुकरचकिया मिसल से उठकर 1799 में लाहौर को राजधानी बनाकर सिख साम्राज्य स्थापित किया", "यूरोपीय जनरलों (अलार्ड, वेंतुरा) द्वारा फौज-ए-खास का आधुनिकीकरण; स्वर्ण मंदिर पर स्वर्ण पत्र लगवाया", "बंगाल के नवाब: मुर्शिद कुली खां (मुर्शिदाबाद राजधानी) व अलीवर्दी खां", "अवध के नवाब: सआदत खां बुरहान-उल-मुल्क द्वारा स्थापना; आसफउद्दौला ने लखनऊ में बड़ा इमामबाड़ा बनवाया"],
        "q_en": "Which famous treaty did Maharaja Ranjit Singh sign with the British East India Company (represented by Charles Metcalfe) in 1809, fixing the Sutlej River as the boundary?",
        "q_hi": "महाराजा रणजीत सिंह ने 1809 में ब्रिटिश ईस्ट इंडिया कंपनी (चार्ल्स मेटकाफ) के साथ कौन सी प्रसिद्ध संधि की थी, जिसके तहत सतलुज नदी को दोनों राज्यों की सीमा माना गया?",
        "options_en": ["Treaty of Amritsar (1809)", "Treaty of Lahore", "Treaty of Sugauli", "Treaty of Yandabo"],
        "options_hi": ["अमृतसर की संधि (Treaty of Amritsar - 1809)", "लाहौर की संधि", "सुगौली की संधि", "यांडाबू की संधि"],
        "correct_idx": 0,
        "exp_en": "The Treaty of Amritsar (25 April 1809) between Ranjit Singh and Charles Metcalfe established permanent friendship and recognized the Sutlej as the frontier.",
        "exp_hi": "1809 में रणजीत सिंह और लॉर्ड मिंटो के दूत चार्ल्स मेटकाफ के बीच अमृतसर की संधि हुई, जिसमें सतलुज नदी को सिख साम्राज्य और ब्रिटिश भारत की सीमा स्वीकार किया गया।",
        "cue_en": "Treaty of Amritsar 1809 = Ranjit Singh + British (Sutlej border).",
        "cue_hi": "अमृतसर की संधि (1809) = महाराजा रणजीत सिंह व अंग्रेज (सतलुज सीमा)।",
        "wrong_en": ["Fixed Sutlej border in 1809.", "Signed after First Anglo-Sikh War (1846).", "Anglo-Nepal Treaty (1816).", "Anglo-Burmese Treaty (1826)."],
        "wrong_hi": ["1809 में सतलुज को सीमा तय करने वाली संधि।", "प्रथम आंग्ल-सिख युद्ध के बाद हुई संधि (1846)।", "आंग्ल-नेपाल संधि (1816)।", "आंग्ल-बर्मा संधि (1826)।"]
    }
]

print("Loaded S04 (Chapters 1, 2, 3)")
