# build_curriculum/group4_s12_part1.py
# S12: General Science: Biology & Human Physiology (Chapters 1, 2, 3 - 14 topics)

DATA = {}

# S12-Ce9c56ff6 Cytology, Cell Organelles & Genetics (4 topics)
DATA["S12-Ce9c56ff6"] = [
    {
        "name_en": "Cell Theory, Prokaryotic vs Eukaryotic Cells & Cell Membrane Structure",
        "name_hi": "कोशिका सिद्धांत, प्रोकैरियोटिक बनाम यूकैरियोटिक कोशिकाएं एवं कोशिका झिल्ली",
        "concepts_en": ["Robert Hooke (1665) discovered cells in cork; Antonie van Leeuwenhoek (1674) observed living cells", "Cell Theory formulated by Matthias Schleiden and Theodor Schwann (1839); Rudolf Virchow added 'Omnis cellula-e cellula' (all cells arise from pre-existing cells, 1855)", "Prokaryotic cells (bacteria, blue-green algae): Lack membrane-bound nucleus and organelles; 70S ribosomes", "Eukaryotic cells: True nucleus with nuclear membrane, membrane-bound organelles, 80S ribosomes; Fluid Mosaic Model of cell membrane proposed by Singer and Nicolson (1972)"],
        "concepts_hi": ["रॉबर्ट हुक (1665) ने कॉर्क में मृत कोशिकाएं खोजीं; ल्यूवेनहॉक (1674) ने जीवित कोशिका (जीवाणु) देखी", "कोशिका सिद्धांत: श्लाइडन एवं श्वान (1839); रुडोल्फ विरचो (1855) ने जोड़ा 'ओमनिस सेलुला-ए सेलुला' (नई कोशिकाओं की उत्पत्ति पहले से मौजूद कोशिकाओं से होती है)", "प्रोकैरियोटिक कोशिकाएं (जीवाणु): झिल्लीयुक्त केंद्रक व कोशिकांगों का अभाव; 70S राइबोसोम", "यूकैरियोटिक कोशिकाएं: सुविकसित केंद्रक, झिल्लीदार कोशिकांग, 80S राइबोसोम; सिंगर और निकोलसन का तरल मोजैक मॉडल (Fluid Mosaic Model, 1972)"],
        "q_en": "Who added the revolutionary tenet 'Omnis cellula-e cellula' (all cells arise from pre-existing cells) to the classical Cell Theory in 1855?",
        "q_hi": "1855 में शास्त्रीय कोशिका सिद्धांत में यह महत्वपूर्ण सूत्र 'ओमनिस सेलुला-ए सेलुला' (सभी नई कोशिकाओं का निर्माण पूर्ववर्ती कोशिकाओं से होता है) किसने जोड़ा था?",
        "options_en": ["Rudolf Virchow (रुडोल्फ विरचो)", "Theodor Schwann", "Matthias Schleiden", "Robert Brown"],
        "options_hi": ["रुडोल्फ विरचो (Rudolf Virchow)", "थियोडोर श्वान", "मैथियास श्लाइडन", "रॉबर्ट ब्राउन"],
        "correct_idx": 0,
        "exp_en": "Rudolf Virchow in 1855 expanded cell theory by postulating that new cells develop only by the division of pre-existing cells ('Omnis cellula-e cellula').",
        "exp_hi": "रुडोल्फ विरचो ने 1855 में कोशिका सिद्धांत को पूर्णता प्रदान की और बताया कि कोशिकाएं स्वतः पैदा नहीं होतीं, बल्कि पूर्व-विद्यमान कोशिकाओं के विभाजन से बनती हैं।",
        "cue_en": "Omnis cellula-e cellula = Rudolf Virchow (1855).",
        "cue_hi": "कोशिकाओं की उत्पत्ति पूर्व कोशिकाओं से = रुडोल्फ विरचो।",
        "wrong_en": ["Formulated 'Omnis cellula-e cellula'.", "Co-founder of animal cell theory (1839).", "Co-founder of plant cell theory (1838).", "Discovered the cell nucleus in 1831."],
        "wrong_hi": ["कोशिका विभाजन का सिद्धांत जोड़ा।", "जंतु कोशिका सिद्धांतकार।", "पादप कोशिका सिद्धांतकार।", "1831 में केंद्रक के खोजकर्ता।"]
    },
    {
        "name_en": "Cell Organelles: Mitochondria (Powerhouse), Ribosomes, Lysosomes & Golgi Apparatus",
        "name_hi": "कोशिकांग: माइटोकॉन्ड्रिया (ऊर्जाघर), राइबोसोम, लाइसोसोम (आत्मघाती थैली) एवं गॉल्जी काय",
        "concepts_en": ["Mitochondria: 'Powerhouse of the cell'; produces cellular energy ATP via cellular respiration and Krebs cycle; contains own circular DNA and 70S ribosomes (semi-autonomous)", "Ribosomes: Discovered by George Palade; non-membrane bound 'protein factories' of the cell", "Lysosomes: Discovered by Christian de Duve; contain hydrolytic digestive enzymes operating at acidic pH; known as 'suicidal bags' of the cell", "Golgi Apparatus: Camillo Golgi; packaging, modification, and secretion of proteins and lipids"],
        "concepts_hi": ["माइटोकॉन्ड्रिया: 'कोशिका का ऊर्जाघर' (Powerhouse of the cell); क्रेब्स चक्र द्वारा एटीपी (ATP) के रूप में ऊर्जा उत्पादन; अपना स्वतंत्र डीएनए और 70S राइबोसोम रखता है (अर्ध-स्वायत्त कोशिकांग)", "राइबोसोम: जॉर्ज पैलाडे द्वारा खोज; झिल्लीरहित कण; 'कोशिका की प्रोटीन फैक्ट्री' कहलाते हैं", "लाइसोसोम: क्रिश्चियन डी डुवे द्वारा खोज; अम्लीय माध्यम में सक्रिय पाचक एंजाइम; 'कोशिका की आत्मघाती थैली' (Suicide Bags) कहलाते हैं", "गॉल्जी काय: कैमिलो गॉल्जी; प्रोटीनों की पैकेजिंग, रूपांतरण और स्राव का कार्य"],
        "q_en": "Which membrane-bound organelle, packed with hydrolytic digestive enzymes capable of digesting cellular debris and damaged organelles, is termed the 'Suicidal Bag' of the cell?",
        "q_hi": "पाचक एंजाइमों से भरी वह कौन सी झिल्लीदार कोशिकांग है, जो क्षतिग्रस्त या मृत कोशिका का स्वतः पाचन कर देती है और जिसे 'कोशिका की आत्मघाती थैली' (Suicide Bag) कहा जाता है?",
        "options_en": ["Lysosome (लाइसोसोम)", "Mitochondrion", "Ribosome", "Peroxisome"],
        "options_hi": ["लाइसोसोम (Lysosome)", "माइटोकॉन्ड्रिया", "राइबोसोम", "परॉक्सिसोम"],
        "correct_idx": 0,
        "exp_en": "Lysosomes contain acid hydrolases capable of breaking down all biological macromolecules. When a cell is injured, lysosomes rupture and digest their own host cell.",
        "exp_hi": "लाइसोसोम में शक्तिशाली पाचक हाइड्रोलाइटिक एंजाइम होते हैं; जब कोशिका क्षतिग्रस्त हो जाती है तो लाइसोसोम फट जाते हैं और अपनी ही कोशिका का पाचन कर लेते हैं, इसलिए इन्हें आत्मघाती थैली कहते हैं।",
        "cue_en": "Suicidal bag of cell = Lysosome; Powerhouse = Mitochondria.",
        "cue_hi": "आत्मघाती थैली = लाइसोसोम; पावरहाउस = माइटोकॉन्ड्रिया।",
        "wrong_en": ["Suicidal bag with digestive enzymes.", "Powerhouse generating ATP.", "Protein factory.", "Metabolizes hydrogen peroxide."],
        "wrong_hi": ["आत्मघाती थैली।", "ऊर्जाघर।", "प्रोटीन निर्माण स्थल।", "हाइड्रोजन पेरोक्साइड अपघटक।"]
    },
    {
        "name_en": "Cell Division: Mitosis (Equational) vs Meiosis (Reductional & Crossing Over)",
        "name_hi": "कोशिका विभाजन: समसूत्री विभाजन (Mitosis) बनाम अर्धसूत्री विभाजन (Meiosis)",
        "concepts_en": ["Mitosis: Occurs in somatic cells for growth and tissue repair; produces 2 genetically identical diploid (2n) daughter cells; phases: Prophase, Metaphase (chromosomes align at equatorial plate), Anaphase (sister chromatids separate), Telophase", "Meiosis: Occurs in germ cells to produce gametes (sperm/egg); two divisions yielding 4 genetically diverse haploid (n) daughter cells", "Reductional division occurs in Meiosis I (chromosome number halved)", "Crossing over occurs during Pachytene stage of Prophase I between non-sister chromatids of homologous chromosomes, creating genetic variation (mediated by enzyme Recombinase)"],
        "concepts_hi": ["समसूत्री विभाजन (Mitosis): शारीरिक (कायिक) कोशिकाओं में वृद्धि व मरम्मत हेतु; 2 समान द्विगुणित (2n) संतति कोशिकाएं बनती हैं; मध्यावस्था (Metaphase) में गुणसूत्र मध्य रेखा (इक्वेटर) पर व्यवस्थित होते हैं", "अर्धसूत्री विभाजन (Meiosis): जनन कोशिकाओं में युग्मक (शुक्राणु/अंडाणु) निर्माण हेतु; दो चरणों में 4 अगुणित (n) संतति कोशिकाएं बनती हैं (गुणसूत्र संख्या आधी रह जाती है)", "जीन विनिमय (Crossing Over): अर्धसूत्री-I के प्रोफेज-I की 'पैचीटीन' (Pachytene) अवस्था में समजात गुणसूत्रों के बीच डीएनए का आदान-प्रदान, जिससे आनुवंशिक विविधता उत्पन्न होती है"],
        "q_en": "During which sub-stage of Prophase I in Meiosis does the critical genetic phenomenon of 'Crossing Over' (recombination of genetic material) take place?",
        "q_hi": "अर्धसूत्री कोशिका विभाजन (Meiosis) के प्रोफेज-I की किस उप-अवस्था में समजात गुणसूत्रों के बीच आनुवंशिक पुनर्योजन यानी 'जीन विनिमय' (Crossing Over) की प्रक्रिया संपन्न होती है?",
        "options_en": ["Pachytene (पैचीटीन अवस्था)", "Leptotene", "Zygotene", "Diplotene"],
        "options_hi": ["पैचीटीन अवस्था (Pachytene)", "लेप्टोटीन अवस्था", "जाइगोटीन अवस्था", "डिप्लोटीन अवस्था"],
        "correct_idx": 0,
        "exp_en": "Crossing over occurs during the Pachytene stage of Meiosis I, where non-sister chromatids of homologous chromosomes exchange genetic segments via chiasmata formation.",
        "exp_hi": "अर्धसूत्री विभाजन के प्रोफेज-I की पैचीटीन (Pachytene) उप-अवस्था में रिकॉम्बीनेज एंजाइम की सहायता से समजात गुणसूत्रों के मध्य क्रॉसिंग ओवर होता है, जिससे संतानों में नए गुण आते हैं।",
        "cue_en": "Crossing over occurs in Pachytene.",
        "cue_hi": "जीन विनिमय (क्रॉसिंग ओवर) = पैचीटीन अवस्था।",
        "wrong_en": ["Stage where crossing over occurs.", "Chromosomes condense into threads.", "Homologous chromosomes pair up (synapsis).", "Chiasmata become visible."],
        "wrong_hi": ["क्रॉसिंग ओवर की अवस्था।", "गुणसूत्र धागे जैसे दिखने लगते हैं।", "गुणसूत्रों का युग्मन (सिनैप्सिस) होता है।", "काइस्मेटा दिखाई देते हैं।"]
    },
    {
        "name_en": "Mendelian Genetics, DNA Structure (Watson & Crick) & Central Dogma",
        "name_hi": "मेंडल के आनुवंशिकी नियम, डीएनए की द्विकुंडलिनी संरचना (वाटसन व क्रिक) एवं सेंट्रल डोग्मा",
        "concepts_en": ["Gregor Johann Mendel ('Father of Genetics'): Experiments on garden pea (Pisum sativum); Law of Segregation and Law of Independent Assortment; Monohybrid phenotypic ratio 3:1 (genotypic 1:2:1)", "James Watson and Francis Crick (1953) elucidated DNA Double Helix model (using Rosalind Franklin's X-ray diffraction data)", "DNA nitrogenous bases: Adenine pairs with Thymine (A=T via 2 hydrogen bonds), Guanine pairs with Cytosine (G≡C via 3 hydrogen bonds)", "Central Dogma of Molecular Biology (Francis Crick): DNA -> (Transcription) -> mRNA -> (Translation) -> Protein"],
        "concepts_hi": ["ग्रेगर जॉन मेंडल ('आनुवंशिकी के जनक'): मटर के पौधे (Pisum sativum) पर संकरण प्रयोग; पृथक्करण का नियम एवं स्वतंत्र अपव्यूहन का नियम; एकसंकर अनुपात 3:1", "जेम्स वाटसन एवं फ्रांसिस क्रिक (1953): डीएनए का द्विकुंडलिनी मॉडल (Double Helix); 1962 का नोबेल पुरस्कार", "डीएनए में चार नाइट्रोजन क्षार: एडेनिन और थायमिन के बीच 2 हाइड्रोजन बंध (A=T), ग्वानिन और साइटोसिन के बीच 3 हाइड्रोजन बंध (G≡C)", "आणविक जीव विज्ञान का सेंट्रल डोग्मा: डीएनए -> (अनुलेखन / Transcription) -> आरएनए -> (अनुवाद / Translation) -> प्रोटीन"],
        "q_en": "In the double-helical structure of DNA proposed by Watson and Crick, how many hydrogen bonds pair Guanine (G) specifically with Cytosine (C)?",
        "q_hi": "वाटसन और क्रिक द्वारा प्रतिपादित डीएनए की द्विकुंडलिनी संरचना में ग्वानिन (G) और साइटोसिन (C) आपस में कितने हाइड्रोजन बंधों द्वारा जुड़े होते हैं?",
        "options_en": ["3 hydrogen bonds (तीन हाइड्रोजन बंध)", "2 hydrogen bonds", "1 hydrogen bond", "4 hydrogen bonds"],
        "options_hi": ["3 हाइड्रोजन बंध (Three Hydrogen Bonds)", "2 हाइड्रोजन बंध (यह A और T के बीच होते हैं)", "1 हाइड्रोजन बंध", "4 हाइड्रोजन बंध"],
        "correct_idx": 0,
        "exp_en": "In complementary DNA base pairing, Guanine pairs with Cytosine via three hydrogen bonds (G≡C), making GC-rich DNA regions more thermally stable than AT pairs (which have two hydrogen bonds: A=T).",
        "exp_hi": "डीएनए में ग्वानिन (G) और साइटोसिन (C) के बीच 3 हाइड्रोजन बंध होते हैं, जबकि एडेनिन (A) और थायमिन (T) के बीच 2 हाइड्रोजन बंध होते हैं।",
        "cue_en": "A=T (2 hydrogen bonds); G≡C (3 hydrogen bonds).",
        "cue_hi": "A और T में 2 बंध; G और C में 3 हाइड्रोजन बंध।",
        "wrong_en": ["Number of bonds between G and C.", "Number of bonds between A and T.", "Incorrect number.", "Incorrect number."],
        "wrong_hi": ["G और C के मध्य 3 बंध।", "A और T के मध्य 2 बंध।", "गलत संख्या।", "गलत संख्या।"]
    }
]

# S12-Caa1e76e7 Human Organ Systems: Circulatory, Nervous, Endocrine & Digestive (6 topics)
DATA["S12-Caa1e76e7"] = [
    {
        "name_en": "Human Digestive System: Gastrointestinal Tract, Digestive Enzymes & Liver/Pancreas",
        "name_hi": "मानव पाचन तंत्र: आहार नाल, प्रमुख पाचक एंजाइम एवं यकृत व अग्न्याशय की भूमिका",
        "concepts_en": ["Mouth: Salivary amylase (Ptyalin) digests starch into maltose; Stomach: Gastric juice contains HCl (activates pepsinogen) and Pepsin (digests proteins)", "Small Intestine: Duodenum receives bile (from Liver, emulsifies fats) and pancreatic juice (Trypsin for proteins, Amylase for carbs, Lipase for fats); site of complete digestion and absorption via villi", "Liver: Largest gland of human body; produces bile (stored in Gallbladder); urea synthesis (Ornithine cycle)", "Pancreas: Mixed gland (heterocrine); endocrine islets secrete insulin/glucagon; exocrine acini secrete digestive enzymes"],
        "concepts_hi": ["मुख: लार ग्रंथि से टायलिन (एमाइलेज) एंजाइम जो स्टार्च को माल्टोज शर्करा में तोड़ता है; आमाशय: जठर रस में हाइड्रोक्लोरिक अम्ल (HCl) और पेप्सिन (प्रोटीन पाचक)", "छोटी आंत: ग्रहणी में यकृत से पित्त रस (वसा का इमल्सीकरण) तथा अग्न्याशयी रस (ट्रिप्सिन, एमाइलेज, लाइपेस); भोजन का पूर्ण पाचन और विली (Villi) द्वारा अवशोषण", "यकृत (Liver): मानव शरीर की सबसे बड़ी ग्रंथि; पित्त रस बनाता है (पित्ताशय में जमा होता है); यूरिया का निर्माण करता है", "अग्न्याशय (Pancreas): मिश्रित ग्रंथि; अंतःस्रावी भाग से इंसुलिन व ग्लूकागन तथा बहिःस्रावी भाग से पाचक रस निकलते हैं"],
        "q_en": "Which major digestive secretion produced by the liver contains NO digestive enzymes, yet is indispensable for the emulsification and digestion of dietary fats?",
        "q_hi": "यकृत (Liver) द्वारा निर्मित वह कौन सा पाचक स्राव है जिसमें कोई पाचक एंजाइम नहीं होता, फिर भी वह वसा के इमल्सीकरण और पाचन के लिए अत्यंत अनिवार्य होता है?",
        "options_en": ["Bile Juice (पित्त रस)", "Gastric Juice", "Pancreatic Juice", "Intestinal Juice (Succus Entericus)"],
        "options_hi": ["पित्त रस (Bile Juice)", "जठर रस", "अग्न्याशयी रस", "आंत्रिक रस"],
        "correct_idx": 0,
        "exp_en": "Bile juice, synthesized by liver hepatocytes and stored in the gallbladder, contains bile salts (sodium glycocholate/taurocholate) and pigments (bilirubin/biliverdin) with zero enzymes, performing fat emulsification.",
        "exp_hi": "पित्त रस (Bile) में कोई एंजाइम नहीं होता, किंतु इसमें पाए जाने वाले पित्त लवण बड़ी वसा बूंदों को छोटी बूंदों में तोड़ देते हैं (इमल्सीकरण), जिससे लाइपेस एंजाइम वसा का पाचन कर सके।",
        "cue_en": "Enzyme-free digestive juice = Bile (emulsifies fat).",
        "cue_hi": "एंजाइम-रहित पाचक द्रव = पित्त रस (वसा का इमल्सीकरण)।",
        "wrong_en": ["Contains bile salts, no enzymes.", "Contains pepsin and lipase.", "Contains trypsin, amylase, lipase.", "Contains maltase, sucrase, peptidase."],
        "wrong_hi": ["एंजाइम रहित पाचक रस।", "पेप्सिन एंजाइम रखता है।", "तीन मुख्य पाचक एंजाइम रखता है।", "अनेक आंत्रिक एंजाइम रखता है।"]
    },
    {
        "name_en": "Human Circulatory System: Heart Anatomy, Double Circulation & ABO/Rh Blood Groups",
        "name_hi": "मानव परिसंचरण तंत्र: हृदय की संरचना, दोहरा परिसंचरण एवं एबीओ (ABO) व आरएच (Rh) रक्त समूह",
        "concepts_en": ["Four-chambered heart (2 atria, 2 ventricles); Sinoatrial (SA) node is the natural 'Pacemaker' generating cardiac action potentials (72 bpm)", "Double Circulation: Pulmonary circulation (heart to lungs and back) and Systemic circulation (heart to body and back); William Harvey discovered blood circulation (1628)", "Blood vessels: Arteries carry oxygenated blood under high pressure away from heart (except Pulmonary Artery); Veins carry deoxygenated blood to heart (except Pulmonary Vein)", "ABO Blood Group (Karl Landsteiner 1900): O-negative is Universal Donor (lacks A, B, Rh antigens); AB-positive is Universal Recipient (lacks antibodies in plasma)"],
        "concepts_hi": ["चार कोष्ठकीय हृदय (2 अलिंद, 2 निलय); साइनो-एट्रियल नोड (SA Node) को हृदय का प्राकृतिक 'पेसमेकर' कहा जाता है (धड़कन दर ~72 प्रति मिनट)", "दोहरा परिसंचरण: फुफ्फुसीय परिसंचरण (हृदय से फेफड़े) एवं दैहिक परिसंचरण (हृदय से संपूर्ण शरीर); विलियम हार्वे ने 1628 में रक्त परिसंचरण की खोज की", "धमनियां (Arteries): शुद्ध रक्त ले जाती हैं (अपवाद: फुफ्फुस धमनी अशुद्ध रक्त ले जाती है); शिराएं (Veins): अशुद्ध रक्त लाती हैं (अपवाद: फुफ्फुस शिरा शुद्ध रक्त लाती है)", "रक्त समूह (कार्ल लैंडस्टीनर, 1900): 'O-नेगेटिव' सर्वदाता (Universal Donor) है; 'AB-पॉजिटिव' सर्वग्राही (Universal Recipient) है"],
        "q_en": "Which specialized patch of neuromuscular tissue situated in the right atrium acts as the natural 'Pacemaker' of the human heart by initiating rhythmic electrical impulses?",
        "q_hi": "मानव हृदय के दाएं अलिंद में स्थित वह विशिष्ट ऊतक कौन सा है, जो विद्युत आवेग उत्पन्न कर हृदय की धड़कन प्रारंभ करता है और जिसे 'प्राकृतिक पेसमेकर' कहा जाता है?",
        "options_en": ["Sinoatrial Node (SA Node / साइनो-एट्रियल नोड)", "Atrioventricular Node (AV Node)", "Bundle of His", "Purkinje Fibers"],
        "options_hi": ["साइनो-एट्रियल नोड (SA Node)", "एट्रियो-वेंट्रिकुलर नोड (AV Node)", "हिस का बंडल (Bundle of His)", "पुर्किंजे तंतु (Purkinje Fibers)"],
        "correct_idx": 0,
        "exp_en": "The Sinoatrial (SA) Node in the upper wall of the right atrium spontaneously generates action potentials at ~72 beats per minute, setting the intrinsic rhythm of cardiac contraction.",
        "exp_hi": "दाएं अलिंद में स्थित एसए नोड (SA Node) हृदय की लयबद्ध धड़कन शुरू करता है, इसलिए इसे हृदय का प्राकृतिक पेसमेकर कहा जाता है।",
        "cue_en": "Heart Pacemaker = SA Node.",
        "cue_hi": "हृदय का पेसमेकर = एसए नोड (SA Node)।",
        "wrong_en": ["Natural cardiac pacemaker.", "Relays impulse to ventricles.", "Conducts impulses along septum.", "Distributes impulses through ventricular walls."],
        "wrong_hi": ["प्राकृतिक पेसमेकर।", "आवेगों को निलय में भेजता है।", "पट के साथ आवेग ले जाता है।", "निलय की दीवारों में आवेग फैलाता है।"]
    },
    {
        "name_en": "Human Respiratory System: Gas Exchange, Hemoglobin & Cellular Respiration",
        "name_hi": "मानव श्वसन तंत्र: गैसों का विनिमय, हीमोग्लोबिन एवं कोशिकीय श्वसन",
        "concepts_en": ["Alveoli: Functional structural units of lungs with massive surface area (~80 m²) and thin capillary network for O2/CO2 diffusion", "Hemoglobin (Hb): Iron-containing respiratory metalloprotein in RBCs; each Hb molecule binds up to 4 oxygen molecules forming Oxyhemoglobin", "CO2 transport: 70% as bicarbonate ions (HCO3⁻) in plasma (catalyzed by Carbonic Anhydrase), 20-25% bound to Hb as Carbaminohemoglobin, 7% dissolved in plasma", "Cellular Respiration: Glycolysis (in cytoplasm, anaerobic, net 2 ATP) -> Krebs Cycle (in mitochondrial matrix) -> Electron Transport Chain (inner mitochondrial membrane, generating total 36-38 ATP per glucose)"],
        "concepts_hi": ["कूपिकाएं (Alveoli): फेफड़ों की कार्यात्मक इकाइयां; विशाल सतही क्षेत्रफल (~80 वर्ग मीटर) जहां रक्त और वायु के बीच ऑक्सीजन व CO2 का विनिमय होता है", "हीमोग्लोबिन (Hb): आरबीसी में स्थित लौह-युक्त वर्णक; हीमोग्लोबिन का एक अणु ऑक्सीजन के 4 अणुओं को बांधता है (ऑक्सीहीमोग्लोबिन)", "CO2 का परिवहन: 70% बाईकार्बोनेट आयनों (HCO3⁻) के रूप में प्लाज्मा द्वारा, 20-25% कार्बाअमीनोहीमोग्लोबिन के रूप में, 7% प्लाज्मा में घुलकर", "कोशिकीय श्वसन: ग्लाइकोलाइसिस (कोशिका द्रव्य में, 2 ATP) -> क्रेब्स चक्र (माइटोकॉन्ड्रिया मैट्रिक्स) -> ईटीसी (कुल 36-38 ATP ऊर्जा प्रति ग्लूकोज अणु)"],
        "q_en": "The majority (approximately 70%) of Carbon Dioxide produced during cellular metabolism is transported in human blood in which form?",
        "q_hi": "कोशिकीय उपापचय से उत्पन्न कार्बन डाइऑक्साइड (CO2) का अधिकांश भाग (लगभग 70%) मानव रक्त में किस रूप में परिवहित होता है?",
        "options_en": ["Bicarbonate Ions (HCO3⁻) dissolved in blood plasma", "Carbaminohemoglobin bound to RBCs", "Carbonic acid in arterial walls", "Free dissolved CO2 gas bubbles"],
        "options_hi": ["रक्त प्लाज्मा में बाईकार्बोनेट आयन (HCO3⁻) के रूप में", "कार्बाअमीनोहीमोग्लोबिन के रूप में", "धमनियों में कार्बोनिक अम्ल के रूप में", "मुक्त घुली हुई CO2 गैस के रूप में"],
        "correct_idx": 0,
        "exp_en": "Approximately 70% of CO2 is carried as bicarbonate ions (HCO3⁻) in plasma, generated within RBCs by the ultra-fast enzyme Carbonic Anhydrase.",
        "exp_hi": "कार्बन डाइऑक्साइड का लगभग 70% परिवहन रक्त प्लाज्मा में बाईकार्बोनेट आयनों के रूप में होता है, जो कार्बोनिक एनहाइड्रेज एंजाइम की सहायता से बनता है।",
        "cue_en": "CO2 transport = 70% as Bicarbonate ions in plasma.",
        "cue_hi": "CO2 का मुख्य परिवहन = 70% बाईकार्बोनेट के रूप में।",
        "wrong_en": ["Main transport mechanism (~70%).", "Secondary transport mechanism (~20-25%).", "Transient intermediate, not transport form.", "Minor fraction (~7% dissolved)."],
        "wrong_hi": ["मुख्य परिवहन रूप (70%)।", "द्वितीयक रूप (20-25%)।", "अस्थायी मध्यवर्ती रूप।", "केवल 7% भाग।"]
    },
    {
        "name_en": "Human Excretory System: Kidneys, Nephron Ultrafiltration & Dialysis",
        "name_hi": "मानव उत्सर्जन तंत्र: वृक्क (गुर्दे), नेफ्रॉन द्वारा परा-निस्पंदन एवं हीमोडायलिसिस",
        "concepts_en": ["Kidneys filter nitrogenous waste (Urea produced in liver from ammonia via Ornithine cycle; humans are Ureotelic)", "Nephron is functional microscopic unit (~1 million per kidney); consists of Malpighian corpuscle (Glomerulus + Bowman's capsule) and Renal Tubule (PCT, Loop of Henle, DCT, Collecting duct)", "Urine formation: Ultrafiltration in glomerulus (GFR ~125 mL/min or 180 liters/day), Selective reabsorption in PCT (glucose, amino acids, 99% water reabsorbed), Tubular secretion", "Hemodialysis: Artificial kidney filtering blood across semipermeable membrane when kidneys suffer acute failure"],
        "concepts_hi": ["वृक्क (गुर्दे): यूरिया और नाइट्रोजनयुक्त अपशिष्टों का निष्कासन (मानव यूरियोटेलिक प्राणी है; यकृत में यूरिया बनता है)", "नेफ्रॉन (Nephron): वृक्क की संरचनात्मक व कार्यात्मक इकाई (प्रत्येक गुर्दे में लगभग 10 लाख नेफ्रॉन); बोमन संपुट, ग्लोमेरुलस, हेनले का लूप, दूरस्थ कुंडलित नलिका", "मूत्र निर्माण: परा-निस्पंदन (Glomerular Filtration Rate ~125 मिली/मिनट यानी 180 लीटर/दिन), 99% द्रव का पुनरावशोषण (प्रतिदिन केवल 1.5 लीटर मूत्र उत्सर्जन)", "हीमोडायलिसिस: गुर्दे खराब होने पर कृत्रिम वृक्क मशीन द्वारा अर्ध-पारगम्य झिल्ली के माध्यम से रक्त का शोधन"],
        "q_en": "What is the structural and functional microscopic filtering unit of the human kidney?",
        "q_hi": "मानव गुर्दे (वृक्क) की संरचनात्मक और कार्यात्मक सूक्ष्म निस्यंदन (छानने वाली) इकाई क्या कहलाती है?",
        "options_en": ["Nephron (नेफ्रॉन)", "Neuron (न्यूरॉन)", "Alveolus", "Hepatic Lobule"],
        "options_hi": ["नेफ्रॉन (Nephron)", "न्यूरॉन (Neuron - यह तंत्रिका तंत्र की इकाई है)", "कूपिका (Alveolus - यह फेफड़े की इकाई है)", "यकृत पालिका (Hepatic Lobule)"],
        "correct_idx": 0,
        "exp_en": "The Nephron is the fundamental microscopic filtering unit of the kidney, with each human kidney containing approximately 1 to 1.2 million nephrons.",
        "exp_hi": "नेफ्रॉन (Nephron) वृक्क की मूल निस्यंदन इकाई है जो रक्त से अपशिष्ट पदार्थों और अतिरिक्त जल को छानकर मूत्र बनाती है। (न्यूरॉन मस्तिष्क व तंत्रिका तंत्र की इकाई है)।",
        "cue_en": "Kidney unit = Nephron; Nervous system unit = Neuron.",
        "cue_hi": "गुर्दे की इकाई = नेफ्रॉन; तंत्रिका तंत्र की इकाई = न्यूरॉन।",
        "wrong_en": ["Functional filtering unit of kidney.", "Functional unit of nervous system.", "Functional gas exchange unit of lung.", "Functional unit of liver."],
        "wrong_hi": ["गुर्दे की सूक्ष्म निस्यंदन इकाई।", "तंत्रिका तंत्र की इकाई।", "फेफड़े की श्वसन इकाई।", "यकृत की इकाई।"]
    },
    {
        "name_en": "Human Nervous System: Brain Regions, Reflex Arc & Autonomic Nervous System",
        "name_hi": "मानव तंत्रिका तंत्र: मस्तिष्क के प्रमुख भाग, प्रतिवर्ती चाप (Reflex Arc) एवं स्वायत्त तंत्रिका तंत्र",
        "concepts_en": ["Central Nervous System (Brain + Spinal Cord) and Peripheral Nervous System", "Forebrain: Cerebrum (largest part, intelligence, memory, voluntary actions, sensory integration), Thalamus (relay station), Hypothalamus (regulates body temperature, hunger, thirst, circadian clock, pituitary hormones)", "Midbrain: Visual and auditory reflex centers", "Hindbrain: Cerebellum (controls body posture, equilibrium, motor coordination), Pons, Medulla Oblongata (involuntary centers: heart rate, blood pressure, breathing, vomiting, swallowing)", "Reflex Arc: Fast involuntary automatic response mediated directly through Spinal Cord"],
        "concepts_hi": ["केंद्रीय तंत्रिका तंत्र (मस्तिष्क + मेरुरज्जु) एवं परिधीय तंत्रिका तंत्र", "प्रमस्तिष्क (Cerebrum): मस्तिष्क का सबसे बड़ा भाग; बुद्धि, चेतना, स्मृति और ऐच्छिक गतियों का केंद्र", "हाइपोथैलेमस: शरीर के तापमान का नियंत्रण (थर्मोस्टेट), भूख, प्यास, भावनाएं और पिट्यूटरी ग्रंथि का नियंत्रण", "अनुमस्तिष्क (Cerebellum): शरीर का संतुलन, मुद्रा (Posture) और मांसपेशियों के समन्वय का नियंत्रण (शराब पीने पर यही प्रभावित होता है)", "मेडुला ऑबलांगाटा: अनैच्छिक क्रियाओं का केंद्र (हृदय गति, रक्तचाप, श्वसन, उल्टी, निगलना)", "प्रतिवर्ती क्रिया (Reflex Action): बिना सोचे मेरुरज्जु (Spinal Cord) द्वारा नियंत्रित त्वरित क्रिया"],
        "q_en": "Which major anatomical region of the human brain is primarily responsible for maintaining muscular coordination, posture, and body balance during voluntary movement?",
        "q_hi": "मानव मस्तिष्क का कौन सा भाग ऐच्छिक गतियों के दौरान मांसपेशियों के समन्वय, शारीरिक संतुलन और मुद्रा (Posture) को नियंत्रित करने के लिए मुख्य रूप से उत्तरदायी होता है?",
        "options_en": ["Cerebellum (अनुमस्तिष्क / छोटा दिमाग)", "Cerebrum (प्रमस्तिष्क)", "Medulla Oblongata", "Hypothalamus"],
        "options_hi": ["अनुमस्तिष्क (Cerebellum)", "प्रमस्तिष्क (Cerebrum)", "मेडुला ऑबलांगाटा (Medulla Oblongata)", "हाइपोथैलेमस (Hypothalamus)"],
        "correct_idx": 0,
        "exp_en": "The Cerebellum coordinates voluntary motor movements, precision, timing, and posture/balance. Alcohol suppresses cerebellar function, leading to loss of motor coordination.",
        "exp_hi": "अनुमस्तिष्क (Cerebellum) शरीर का संतुलन, चाल और मांसपेशियों की गति का सटीक समन्वय बनाए रखता है। अधिक शराब पीने पर इसी के असंतुलन से व्यक्ति लड़खड़ाने लगता है।",
        "cue_en": "Body balance & posture = Cerebellum.",
        "cue_hi": "शरीर का संतुलन व समन्वय = अनुमस्तिष्क (सेरिबेलम)।",
        "wrong_en": ["Maintains balance and posture.", "Seats conscious thought, intelligence, memory.", "Regulates involuntary breathing and heart rate.", "Controls body temperature and thirst."],
        "wrong_hi": ["संतुलन का नियंत्रक।", "बुद्धि और सोच का केंद्र।", "अनैच्छिक श्वसन व हृदय गति नियंत्रक।", "तापमान व भूख-प्यास नियंत्रक।"]
    },
    {
        "name_en": "Endocrine System: Pituitary, Thyroid, Pancreas & Adrenal Glands",
        "name_hi": "अंतःस्रावी तंत्र: पीयूष ग्रंथि (मास्टर ग्रंथि), थायरॉयड, अग्न्याशय एवं अधिवृक्क ग्रंथि (आपातकालीन हार्मोन)",
        "concepts_en": ["Ductless endocrine glands secrete chemical messengers (hormones) directly into bloodstream", "Pituitary Gland: 'Master Gland' at base of brain (controlled by Hypothalamus); secretes Growth Hormone (GH - dwarfism vs gigantism), TSH, ACTH, Oxytocin, Vasopressin/ADH (antidiuretic hormone prevents water loss)", "Thyroid Gland: Butterfly-shaped gland in neck; produces Thyroxine (T4) requiring iodine (deficiency causes Goitre); regulates basal metabolic rate (BMR)", "Pancreas: Islets of Langerhans beta-cells secrete Insulin (lowers blood glucose); alpha-cells secrete Glucagon (raises blood glucose); deficiency of insulin causes Diabetes Mellitus", "Adrenal Glands: Adrenal medulla secretes Adrenaline/Epinephrine ('Fight or Flight' emergency hormone)"],
        "concepts_hi": ["नलिकाविहीन अंतःस्रावी ग्रंथियां सीधे रक्त में रासायनिक संदेशवाहक (हार्मोन) छोड़ती हैं", "पीयूष ग्रंथि (Pituitary Gland): 'मास्टर ग्रंथि'; मस्तिष्क के आधार पर स्थित; वृद्धि हार्मोन (GH), टीएसएच, ऑक्सीटोसिन, वैसोप्रेसिन (एंटी-डाईयूरेटिक हार्मोन) का स्राव", "थायरॉयड ग्रंथि: गले में तितली के आकार की; थायरोक्सिन हार्मोन बनाती है जिसके लिए आयोडीन अनिवार्य है (कमी से घेंघा/गलगंड रोग); बीएमआर का नियंत्रण", "अग्न्याशय के लैंगरहेंस के द्वीप: बीटा कोशिकाएं इंसुलिन का स्राव करती हैं (रक्त में शर्करा कम करता है); कमी से मधुमेह (डायबिटीज मेलिटस) रोग होता है", "अधिवृक्क ग्रंथि (Adrenal Gland): एड्रिनल मेड्युला से एड्रिनलिन हार्मोन निकलता है, जिसे 'लड़ो या उड़ो' (Fight or Flight) या आपातकालीन हार्मोन कहा जाता है"],
        "q_en": "Which hormone, secreted by the beta cells of the Islets of Langerhans in the pancreas, is responsible for lowering blood glucose levels by facilitating cellular uptake?",
        "q_hi": "अग्न्याशय में स्थित लैंगरहेंस के द्वीपों की बीटा (β) कोशिकाओं द्वारा कौन सा हार्मोन स्रावित होता है, जो रक्त में ग्लूकोज (शर्करा) के स्तर को नियंत्रित और कम करता है?",
        "options_en": ["Insulin (इंसुलिन)", "Glucagon", "Adrenaline", "Thyroxine"],
        "options_hi": ["इंसुलिन (Insulin)", "ग्लूकागन (Glucagon)", "एड्रिनलिन (Adrenaline)", "थायरोक्सिन (Thyroxine)"],
        "correct_idx": 0,
        "exp_en": "Insulin is a peptide hormone produced by pancreatic beta cells that promotes glucose uptake by muscles and adipose tissue, preventing hyperglycemia.",
        "exp_hi": "इंसुलिन रक्त में ग्लूकोज को ग्लाइकोजन में बदलकर यकृत और मांसपेशियों में संचित करवाता है; इंसुलिन की कमी से रक्त में शर्करा बढ़ जाती है और डायबिटीज रोग हो जाता है।",
        "cue_en": "Pancreatic beta cells = Insulin (lowers blood glucose).",
        "cue_hi": "बीटा कोशिकाएं = इंसुलिन (शर्करा कम करता है)।",
        "wrong_en": ["Lowers blood glucose.", "Secreted by alpha cells, raises blood glucose.", "Emergency fight-or-flight hormone.", "Thyroid hormone controlling metabolic rate."],
        "wrong_hi": ["रक्त शर्करा कम करने वाला।", "अल्फा कोशिकाओं से निकलता है, शर्करा बढ़ाता है।", "आपातकालीन हार्मोन।", "उपापचय नियंत्रक हार्मोन।"]
    }
]

# S12-C7b539aa0 Plant Anatomy, Photosynthesis & Plant Hormones (4 topics)
DATA["S12-C7b539aa0"] = [
    {
        "name_en": "Plant Tissues: Meristematic vs Permanent Complex Tissues (Xylem & Phloem)",
        "name_hi": "पादप ऊतक: विभज्योतक (मेरिस्टेमैटिक) बनाम स्थायी जटिल ऊतक (जाइलम एवं फ्लोएम)",
        "concepts_en": ["Meristematic Tissues: Actively dividing cells; Apical meristem (root/shoot tip growth in length), Lateral meristem / Cambium (growth in girth/diameter), Intercalary meristem", "Permanent Simple Tissues: Parenchyma (storage, photosynthesis in chlorenchyma), Collenchyma (mechanical flexibility, pectin corners), Sclerenchyma (rigid, dead at maturity with lignified walls, e.g., husk of coconut)", "Complex Vascular Tissues: Xylem transports water and dissolved mineral nutrients unidirectionally from roots to leaves (tracheids, vessels, xylem parenchyma, xylem fibers)", "Phloem transports organic food (sucrose) bidirectionally from source (leaves) to sinks (sieve tubes, companion cells, phloem parenchyma, phloem fibers)"],
        "concepts_hi": ["विभज्योतक (Meristematic): निरंतर विभाजित होने वाली कोशिकाएं; शीर्षस्थ (लंबाई में वृद्धि), पार्श्वीय / कैम्बियम (तने की मोटाई/घेरे में वृद्धि), अंतर्वेशी", "सरल स्थायी ऊतक: पैरेन्काइमा (भंडारण, प्रकाश संश्लेषण), कॉलेन्काइमा (लचीलापन व यांत्रिक सहारा), स्क्लेरेन्काइमा (दृढ़ोतक, मृत कोशिकाएं, लिग्निन युक्त; नारियल का छिलका)", "जटिल संवहनी ऊतक: जाइलम (Xylem) जड़ों से जल और खनिजों का ऊपर पत्तियों की ओर एकदिशीय संवहन करता है (वाहिकाएं, वाहिनिकाएं)", "फ्लोएम (Phloem): पत्तियों द्वारा निर्मित भोजन (सुक्रोज) का पौधे के सभी अंगों में द्विदिशीय संवहन करता है (चालनी नलिकाएं, सहचर कोशिकाएं)"],
        "q_en": "Which complex vascular plant tissue conducts water and dissolved mineral nutrients unidirectionally from the roots upward to the stems and leaves?",
        "q_hi": "पादपों में जड़ों द्वारा अवशोषित जल और खनिज लवणों को ऊपर तने और पत्तियों तक एकदिशीय रूप में पहुंचाने वाला संवहनी ऊतक कौन सा है?",
        "options_en": ["Xylem (जाइलम / दारू ऊतक)", "Phloem (फ्लोएम / पोषवाह)", "Collenchyma", "Sclerenchyma"],
        "options_hi": ["जाइलम (Xylem)", "फ्लोएम (Phloem)", "कॉलेन्काइमा", "स्क्लेरेन्काइमा"],
        "correct_idx": 0,
        "exp_en": "Xylem is the specialized conducting tissue that transports water and dissolved inorganic ions upward from roots driven by transpirational pull and root pressure.",
        "exp_hi": "जाइलम ऊतक जड़ों से जल और पोषक तत्वों को पौधे के शीर्ष तक ले जाता है। (फ्लोएम पत्तियों में बने भोजन को पौधे के विभिन्न भागों तक पहुंचाता है)।",
        "cue_en": "Xylem = Water (Jal -> Xylem); Phloem = Food (Phal/Food -> Phloem).",
        "cue_hi": "जल = जाइलम; फल/भोजन = फ्लोएम।",
        "wrong_en": ["Transports water and minerals.", "Transports organic nutrients/sugars.", "Provides mechanical flexibility.", "Provides dead structural strength."],
        "wrong_hi": ["जल व खनिज का संवहन।", "भोजन का संवहन करता है।", "लचीलापन देता है।", "कठोरता प्रदान करता है।"]
    },
    {
        "name_en": "Photosynthesis: Light-Dependent Reactions, Calvin Cycle & Chloroplast Anatomy",
        "name_hi": "प्रकाश संश्लेषण: प्रकाशिक अभिक्रिया, कैल्विन चक्र (अप्रकाशिक) एवं क्लोरोप्लास्ट",
        "concepts_en": ["Overall reaction: 6CO2 + 12H2O + Sunlight -> C6H12O6 + 6O2 + 6H2O; Oxygen released during photosynthesis originates from WATER (photolysis of water), NOT from CO2 (proven by Ruben and Kamen using O-18)", "Chloroplast structure: Grana (thylakoid stacks) and fluid Stroma", "Light Reaction (Photochemical): Occurs in Thylakoid membranes; uses chlorophyll pigments, produces ATP, NADPH, and photolytic O2", "Dark Reaction / Calvin Cycle (Biosynthetic): Occurs in Stroma; enzyme RuBisCO (most abundant enzyme on Earth) fixes CO2 into glucose"],
        "concepts_hi": ["प्रकाश संश्लेषण का समग्र समीकरण: 6CO2 + 12H2O + प्रकाश -> C6H12O6 + 6O2 + 6H2O", "प्रकाश संश्लेषण में निकलने वाली प्राणवायु ऑक्सीजन (O2) जल (H2O) के प्रकाशिक अपघटन से निकलती है, न कि CO2 से (रूबेन व कामेन द्वारा O-18 समस्थानिक से सिद्ध)", "क्लोरोप्लास्ट (हरित लवक): थाइलेकॉइड के चट्टे (ग्रैना) एवं तरल स्ट्रोमा", "प्रकाशिक अभिक्रिया (Light Reaction): ग्रैना (थाइलेकॉइड झिल्ली) में होती है; एटीपी, एनएडीपीएच और ऑक्सीजन बनते हैं", "अप्रकाशिक अभिक्रिया (Calvin Cycle): स्ट्रोमा में होती है; रुबिस्को (RuBisCO) एंजाइम CO2 का स्थिरीकरण कर ग्लूकोज बनाता है"],
        "q_en": "In the biochemical process of oxygenic photosynthesis, from which reactant molecule is molecular oxygen (O2) released into the atmosphere?",
        "q_hi": "पौधों में प्रकाश संश्लेषण की जैव-रासायनिक प्रक्रिया के दौरान वायुमंडल में मुक्त होने वाली ऑक्सीजन (O2) किस अणु के प्रकाशिक अपघटन से प्राप्त होती है?",
        "options_en": ["Water (जल - H2O)", "Carbon Dioxide (CO2)", "Glucose (C6H12O6)", "Chlorophyll"],
        "options_hi": ["जल (Water - H2O)", "कार्बन डाइऑक्साइड (CO2)", "ग्लूकोज (Glucose)", "क्लोरोफिल (पर्णहरित)"],
        "correct_idx": 0,
        "exp_en": "Photolysis of water (splitting of H2O into protons, electrons, and oxygen) driven by Photosystem II in the thylakoid membrane is the true source of all photosynthetic O2.",
        "exp_hi": "प्रकाशिक अभिक्रिया में सूर्य के प्रकाश द्वारा जल के अणुओं का विखंडन (Photolysis of water) होता है, जिससे ऑक्सीजन गैस मुक्त होती है (CO2 से ग्लूकोज बनता है)।",
        "cue_en": "Photosynthetic Oxygen comes from WATER (H2O), NOT from CO2.",
        "cue_hi": "प्रकाश संश्लेषण की ऑक्सीजन जल (H2O) से निकलती है, CO2 से नहीं।",
        "wrong_en": ["Source of oxygen (photolysis of water).", "Source of carbon and oxygen in glucose.", "End product carbohydrate.", "Light-absorbing catalyst."],
        "wrong_hi": ["ऑक्सीजन का वास्तविक स्रोत।", "ग्लूकोज का स्रोत है।", "अंतिम उत्पाद।", "प्रकाश अवशोषक वर्णक।"]
    },
    {
        "name_en": "Transpiration, Stomatal Mechanism & Ascent of Sap (Cohesion-Tension Theory)",
        "name_hi": "वाष्पोत्सर्जन, रंध्रों (स्टोमेटा) की क्रियाविधि एवं रस का आरोहण (संसंजन-तनाव सिद्धांत)",
        "concepts_en": ["Transpiration: Evaporative loss of water as vapor from aerial parts of plant (primarily through microscopic stomata in leaves); called a 'necessary evil' by Curtis", "Stomatal mechanism: Guard cells swell with turgor pressure when K⁺ ions enter, opening stomata; lose turgor and close when K⁺ exits", "Ascent of Sap: Dixon and Joly (1894) Cohesion-Tension-Transpiration Pull Theory explains sap rising hundreds of feet in tall redwood trees", "Water molecules exhibit strong cohesive forces (hydrogen bonding between H2O) and adhesive forces (H2O to xylem walls), maintaining continuous water column under tension"],
        "concepts_hi": ["वाष्पोत्सर्जन (Transpiration): पत्तियों के रंध्रों (स्टोमेटा) द्वारा जल का वाष्प रूप में उड़ना; कर्टिस ने इसे 'एक अनिवार्य बुराई' कहा था", "रंध्रों के खुलने व बंद होने का तंत्र: द्वार कोशिकाओं (Guard cells) में पोटेशियम (K⁺) आयनों के प्रवेश से स्फीति दाब बढ़ता है और रंध्र खुल जाते हैं", "रस का आरोहण (Ascent of Sap): डिक्सन और जॉली का संसंजन-तनाव-वाष्पोत्सर्जन खिंचाव सिद्धांत (Cohesion-Tension Theory) विशाल वृक्षों में जल के 100 मीटर ऊपर चढ़ने की व्याख्या करता है", "जल के अणुओं का आपसी आकर्षण (संसंजन) और जाइलम दीवारों से आकर्षण (आसंजन) एक अटूट जल स्तंभ बनाए रखता है"],
        "q_en": "Which widely accepted physical theory, formulated by Dixon and Joly in 1894, explains the ascent of sap through xylem vessels in tall trees?",
        "q_hi": "डिक्सन और जॉली द्वारा 1894 में प्रतिपादित कौन सा सर्वमान्य सिद्धांत विशाल वृक्षों में जाइलम के माध्यम से जल के ऊपर चढ़ने (रस के आरोहण) की वैज्ञानिक व्याख्या करता है?",
        "options_en": ["Cohesion-Tension-Transpiration Pull Theory (संसंजन-तनाव-वाष्पोत्सर्जन खिंचाव सिद्धांत)", "Root Pressure Theory", "Capillary Action Theory", "Pulsation Theory of J.C. Bose"],
        "options_hi": ["संसंजन-तनाव-वाष्पोत्सर्जन खिंचाव सिद्धांत (Cohesion-Tension Theory)", "मूल दाब सिद्धांत (Root Pressure)", "केशिका क्रिया सिद्धांत", "जे.सी. बोस का स्पंदन सिद्धांत"],
        "correct_idx": 0,
        "exp_en": "Dixon and Joly's Cohesion-Tension Theory demonstrates that transpirational pull creates negative tension transmitted down the continuous cohesive column of water in xylem.",
        "exp_hi": "डिक्सन और जॉली का संसंजन-तनाव सिद्धांत बताता है कि पत्तियों से वाष्पोत्सर्जन होने पर एक जबर्दस्त खिंचाव बल (सक्शन) पैदा होता है, जो जल के अणुओं के संसंजन बल के कारण पूरे जल स्तंभ को ऊपर खींच लेता है।",
        "cue_en": "Ascent of sap = Dixon & Joly Cohesion-Tension Theory.",
        "cue_hi": "रस का आरोहण = डिक्सन-जॉली का संसंजन-तनाव सिद्धांत।",
        "wrong_en": ["Explains ascent of sap in tall trees.", "Can only push water up a few meters.", "Cannot explain rise beyond 1 meter.", "Earlier vital force theory."],
        "wrong_hi": ["विशाल पेड़ों में जल संचरण की सही व्याख्या।", "केवल कुछ मीटर तक जल चढ़ा सकता है।", "1 मीटर से ऊपर नहीं चढ़ा सकता।", "पुराना स्पंदन सिद्धांत।"]
    },
    {
        "name_en": "Plant Hormones (Phytohormones): Auxins, Gibberellins, Cytokinins, Abscisic Acid & Ethylene",
        "name_hi": "पादप हार्मोन (फाइटोहार्मोन): ऑक्सिन, जिबरेलिन, साइटोकाइनिन, एब्सिसिक अम्ल एवं एथिलीन",
        "concepts_en": ["Auxins (IAA): Apical dominance, cell elongation, phototropism (bends towards light), root initiation, parthenocarpy; synthetic 2,4-D used as selective weedicide", "Gibberellins (GA3): Bolting (internodal elongation in rosette plants), breaking seed dormancy, fruit enlargement in seedless grapes", "Cytokinins (Zeatin, Kinetin): Promotes cell division (cytokinesis), delays leaf senescence (Richmond-Lang effect), breaks apical dominance", "Abscisic Acid (ABA): 'Stress hormone'; promotes stomatal closure during drought, induces seed dormancy, accelerates leaf abscission", "Ethylene (C2H4): Only GASEOUS phytohormone; accelerates fruit ripening (climacteric fruits like bananas, mangoes), promotes senescence and abscission"],
        "concepts_hi": ["ऑक्सिन (IAA): शीर्षस्थ प्रभाविता (Apical Dominance), प्रकाशानुवर्तन (प्रकाश की ओर झुकना), जड़ों का विकास; कृत्रिम ऑक्सिन 2,4-D का उपयोग खरपतवारनाशी के रूप में", "जिबरेलिन (GA3): तने के पर्वों की लंबाई बढ़ाना (बोल्टिंग), बीजों की प्रसुप्ति तोड़ना, अंगूर के गुच्छों का आकार बढ़ाना", "साइटोकाइनिन: कोशिका विभाजन (Cytokinesis) को प्रेरित करना, पत्तियों के बुढ़ापे (जीर्णता) को रोकना, पार्श्व कलियों का विकास", "एब्सिसिक अम्ल (ABA): 'तनाव हार्मोन' (Stress Hormone); सूखे में रंध्रों को बंद करना, बीजों को सुप्तावस्था में रखना, पत्तियों को गिराना", "एथिलीन (Ethylene): एकमात्र 'गैसीय पादप हार्मोन'; फलों को प्राकृतिक रूप से पकाना (केला, आम), जीर्णता को बढ़ावा देना"],
        "q_en": "Which phytohormone is unique for existing in a GASEOUS state at room temperature and functions as a master accelerator of fruit ripening?",
        "q_hi": "कमरे के तापमान पर गैसीय अवस्था में पाया जाने वाला एकमात्र पादप हार्मोन कौन सा है, जो फलों को पकाने में मुख्य भूमिका निभाता है?",
        "options_en": ["Ethylene (एथिलीन / C2H4)", "Auxin (IAA)", "Gibberellic Acid", "Abscisic Acid"],
        "options_hi": ["एथिलीन (Ethylene)", "ऑक्सिन (Auxin)", "जिबरेलिन (Gibberellin)", "एब्सिसिक अम्ल (Abscisic Acid)"],
        "correct_idx": 0,
        "exp_en": "Ethylene is the only gaseous plant hormone, regulating fruit ripening, flower fading, and leaf abscission.",
        "exp_hi": "एथिलीन (C2H4) एकमात्र गैसीय हार्मोन है जो कच्चे फलों (जैसे केला, आम, सेब) को पकाने में उत्प्रेरक का काम करता है।",
        "cue_en": "Gaseous fruit-ripening hormone = Ethylene.",
        "cue_hi": "फलों को पकाने वाला गैसीय हार्मोन = एथिलीन।",
        "wrong_en": ["Only gaseous phytohormone.", "Promotes shoot elongation.", "Promotes bolting and stem stretch.", "Drought stress hormone."],
        "wrong_hi": ["गैसीय अवस्था वाला हार्मोन।", "शीर्षस्थ वृद्धि हार्मोन।", "तने की लंबाई का हार्मोन।", "तनाव हार्मोन।"]
    }
]

print("Loaded S12 Part 1 successfully")
