# build_curriculum/group4_s10.py
# S10: General Science: Physics (14 topics across 3 chapters)

DATA = {}

# S10-C0f1997cd Mechanics, Gravitation, Work, Power & Energy (4 topics)
DATA["S10-C0f1997cd"] = [
    {
        "name_en": "Newton's Laws of Motion, Momentum & Rocket Propulsion",
        "name_hi": "न्यूटन के गति के नियम, रेखीय संवेग एवं रॉकेट प्रणोदन का सिद्धांत",
        "concepts_en": ["First Law (Law of Inertia): An object remains at rest or in uniform motion unless acted upon by an external net force", "Second Law: Force equals rate of change of momentum (F = dp/dt = ma)", "Third Law: To every action there is an equal and opposite reaction", "Rocket propulsion and recoil of a gun operate on the conservation of linear momentum"],
        "concepts_hi": ["प्रथम नियम (जड़त्व का नियम): कोई वस्तु तब तक अपनी विरामावस्था या गति की अवस्था में रहती है जब तक उस पर बाह्य बल न लगाया जाए", "द्वितीय नियम: संवेग परिवर्तन की दर लगाए गए बल के समानुपाती होती है (F = ma)", "तृतीय नियम: प्रत्येक क्रिया की सदैव बराबर एवं विपरीत दिशा में प्रतिक्रिया होती है", "रॉकेट प्रक्षेपण और बंदूक का पीछे हटना रेखीय संवेग संरक्षण के नियम पर आधारित है"],
        "q_en": "The upward propulsion and flight of a multi-stage space rocket operates fundamentally on the principle of conservation of which physical quantity?",
        "q_hi": "रॉकेट का अंतरिक्ष में ऊपर की ओर तीव्र प्रक्षेपण किस भौतिक राशि के संरक्षण के सिद्धांत पर कार्य करता है?",
        "options_en": ["Linear Momentum (रेखीय संवेग)", "Kinetic Energy", "Angular Momentum", "Total Mass"],
        "options_hi": ["रेखीय संवेग (Linear Momentum)", "गतिज ऊर्जा", "कोणीय संवेग", "कुल द्रव्यमान"],
        "correct_idx": 0,
        "exp_en": "Rocket propulsion is a classic application of Newton's third law and the law of conservation of linear momentum: backward ejection of exhaust gases propels the rocket forward.",
        "exp_hi": "रॉकेट से पीछे की ओर अत्यधिक तीव्र वेग से निकलने वाली गैसें रॉकेट को आगे की दिशा में संवेग प्रदान करती हैं, जो रेखीय संवेग संरक्षण और क्रिया-प्रतिक्रिया नियम पर आधारित है।",
        "cue_en": "Rocket propulsion = Conservation of Linear Momentum.",
        "cue_hi": "रॉकेट प्रणोदन = रेखीय संवेग संरक्षण।",
        "wrong_en": ["Governing physical principle.", "Energy is converted from chemical to kinetic.", "Applies to rotational systems.", "Mass decreases as fuel burns."],
        "wrong_hi": ["भौतिकी का मूल सिद्धांत।", "ऊर्जा का केवल रूपांतरण होता है।", "घूर्णन गति में लागू होता है।", "ईंधन जलने से द्रव्यमान घटता है।"]
    },
    {
        "name_en": "Universal Gravitation, Acceleration due to Gravity (g) & Escape Velocity",
        "name_hi": "सार्वत्रिक गुरुत्वाकर्षण, गुरुत्वीय त्वरण (g) एवं पलायन वेग",
        "concepts_en": ["Newton's Universal Law of Gravitation: F = G*(m1*m2)/r² (G = 6.674×10⁻¹¹ N m²/kg² determined by Cavendish)", "Acceleration due to gravity (g = 9.8 m/s²): Maximum at poles, minimum at equator; zero at center of Earth", "Weight (W = mg) varies with g, but mass (m) is invariant", "Escape velocity from Earth surface: v_e = √(2gR) ≈ 11.2 km/s (Moon escape velocity is 2.38 km/s, explaining lack of atmosphere)"],
        "concepts_hi": ["न्यूटन का गुरुत्वाकर्षण नियम: F = G*(m1*m2)/r² (सार्वत्रिक नियतांक G = 6.674×10⁻¹¹ N m²/kg², कैवेंडिश द्वारा मापा गया)", "गुरुत्वीय त्वरण (g = 9.8 m/s²): ध्रुवों पर अधिकतम, भूमध्य रेखा पर न्यूनतम, पृथ्वी के केंद्र पर शून्य", "भार (W = mg) स्थान के साथ बदलता है, किंतु द्रव्यमान (m) सदैव स्थिर रहता है", "पृथ्वी से पलायन वेग: v = √(2gR) ≈ 11.2 किमी/सेकंड (चंद्रमा पर पलायन वेग केवल 2.38 किमी/सेकंड है, जिससे वहां वायुमंडल नहीं टिक पाता)"],
        "q_en": "What is the minimum escape velocity required for an object launched from the surface of the Earth to overcome its gravitational field and enter interplanetary space?",
        "q_hi": "पृथ्वी की सतह से किसी वस्तु को अंतरिक्ष में भेजने के लिए आवश्यक न्यूनतम 'पलायन वेग' (Escape Velocity) का मान लगभग कितना होता है?",
        "options_en": ["11.2 km/s (11.2 किमी/सेकंड)", "7.9 km/s", "2.38 km/s", "42.1 km/s"],
        "options_hi": ["11.2 किमी/सेकंड (11.2 km/s)", "7.9 किमी/सेकंड", "2.38 किमी/सेकंड", "42.1 किमी/सेकंड"],
        "correct_idx": 0,
        "exp_en": "Escape velocity from the surface of Earth is calculated as √(2gR) ≈ 11.2 km/s. Orbital velocity for low Earth orbit is approximately 7.9 km/s.",
        "exp_hi": "पृथ्वी की सतह से पलायन वेग 11.2 किमी/सेकंड होता है। यदि किसी वस्तु को इस गति से ऊपर फेंका जाए तो वह पृथ्वी के गुरुत्वाकर्षण क्षेत्र को पार कर जाती है।",
        "cue_en": "Earth escape velocity = 11.2 km/s (Orbital velocity = 7.9 km/s).",
        "cue_hi": "पृथ्वी का पलायन वेग = 11.2 किमी/सेकंड।",
        "wrong_en": ["Earth escape velocity.", "First cosmic / orbital velocity for LEO.", "Escape velocity from Moon.", "Solar System escape velocity from Earth orbit."],
        "wrong_hi": ["पृथ्वी का पलायन वेग।", "कक्षा में स्थापित करने का कक्षीय वेग।", "चंद्रमा का पलायन वेग।", "सौरमंडल से पलायन वेग।"]
    },
    {
        "name_en": "Work-Energy Theorem, Kinetic & Potential Energy Conservation",
        "name_hi": "कार्य-ऊर्जा प्रमेय, गतिज व स्थितिज ऊर्जा एवं यांत्रिक ऊर्जा संरक्षण",
        "concepts_en": ["Work done = Force × Displacement × cos(θ) (measured in Joules); zero work if displacement is perpendicular to force (e.g., satellite in circular orbit)", "Work-Energy Theorem: Net work done on an object equals change in its kinetic energy (W = ΔKE)", "Kinetic Energy: KE = 1/2 m v² (doubling velocity quadruples KE)", "Potential Energy: Gravitational PE = mgh; Conservation of Mechanical Energy: KE + PE = Constant in conservative field"],
        "concepts_hi": ["कार्य = बल × विस्थापन × cos(θ) (मात्रक: जूल); यदि बल और विस्थापन लंबवत हों (θ = 90°) तो किया गया कार्य 'शून्य' होता है (जैसे कुली द्वारा सिर पर बोझ लेकर चलना)", "कार्य-ऊर्जा प्रमेय: किसी वस्तु पर किया गया कुल कार्य उसकी गतिज ऊर्जा में परिवर्तन के बराबर होता है", "गतिज ऊर्जा: KE = 1/2 m v² (यदि वेग को दोगुना कर दिया जाए तो गतिज ऊर्जा चार गुनी हो जाएगी)", "स्थितिज ऊर्जा: PE = mgh; यांत्रिक ऊर्जा संरक्षण: गतिज ऊर्जा + स्थितिज ऊर्जा = नियत"],
        "q_en": "If the velocity of a moving motor vehicle is doubled, by what factor does its kinetic energy increase?",
        "q_hi": "यदि किसी गतिमान वाहन का वेग (गति) दोगुना कर दिया जाए, तो उसकी गतिज ऊर्जा (Kinetic Energy) कितने गुना बढ़ जाएगी?",
        "options_en": ["4 times (चार गुना)", "2 times", "8 times", "16 times"],
        "options_hi": ["4 गुना (Four times)", "2 गुना", "8 गुना", "16 गुना"],
        "correct_idx": 0,
        "exp_en": "Kinetic energy is directly proportional to the square of velocity (KE = 1/2 m v²). Therefore, doubling the velocity (2v) increases KE by (2)² = 4 times.",
        "exp_hi": "गतिज ऊर्जा का सूत्र KE = 1/2 m v² होता है। चूंकि गतिज ऊर्जा वेग के वर्ग के समानुपाती होती है, अतः वेग दोगुना करने पर गतिज ऊर्जा (2)² = 4 गुना हो जाती है।",
        "cue_en": "Doubling velocity quadruples kinetic energy (v² factor).",
        "cue_hi": "वेग दोगुना करने पर गतिज ऊर्जा 4 गुनी हो जाती है।",
        "wrong_en": ["Correct: increases by factor of 4.", "Linear scaling would apply to momentum, not KE.", "Cube factor.", "Fourth power factor."],
        "wrong_hi": ["सही: 4 गुना वृद्धि।", "संवेग 2 गुना होता, गतिज ऊर्जा नहीं।", "घन का संबंध नहीं।", "चतुर्थ घात नहीं।"]
    },
    {
        "name_en": "Friction, Circular Motion & Centripetal vs Centrifugal Force",
        "name_hi": "घर्षण, वृत्तीय गति एवं अभिकेंद्रीय बनाम अपकेंद्री बल",
        "concepts_en": ["Friction opposes relative motion; Static friction > Limiting friction > Kinetic/Sliding friction > Rolling friction (ball bearings minimize friction)", "Centripetal Force: Real inward-directed force compelling an object to follow a curved circular path (F = m v² / r)", "Banking of roads and railway tracks provides necessary centripetal force without relying solely on tire friction", "Centrifugal Force: Apparent pseudo-force directed radially outward in a rotating non-inertial reference frame (used in cream separators, centrifuges, washing machine dryers)"],
        "concepts_hi": ["घर्षण सापेक्ष गति का विरोध करता है; स्थैतिक घर्षण > गतिज घर्षण > लोटनिक (रोलिंग) घर्षण (बॉल बेयरिंग से घर्षण न्यूनतम किया जाता है)", "अभिकेंद्रीय बल (Centripetal Force): केंद्र की ओर लगने वाला वास्तविक बल जो वृत्तीय गति संभव बनाता है (F = m v² / r)", "सड़कों व रेल पटरियों का झुकाव (Banking): अभिकेंद्रीय बल प्रदान करने के लिए मोड़ों पर बाहरी भाग को ऊंचा उठाया जाता है", "अपकेंद्री बल (Centrifugal Force): घूर्णनशील तंत्र में बाहर की ओर आभासी बल (दूध से मक्खन निकालने की मशीन, वाशिंग मशीन का ड्रायर)"],
        "q_en": "The separation of cream from milk in a domestic dairy centrifuge or the spin dryer of a washing machine operates primarily due to which mechanical force?",
        "q_hi": "दूध से मक्खन (क्रीम) अलग करने वाली मथनी या वाशिंग मशीन के कपड़े सुखाने वाले ड्रायर में किस बल का उपयोग किया जाता है?",
        "options_en": ["Centrifugal Force (अपकेंद्री बल)", "Centripetal Force", "Gravitational Force", "Magnetic Force"],
        "options_hi": ["अपकेंद्री बल (Centrifugal Force)", "अभिकेंद्रीय बल (Centripetal Force)", "गुरुत्वाकर्षण बल", "चुंबकीय बल"],
        "correct_idx": 0,
        "exp_en": "In a rotating separator, centrifugal force pushes the denser milk particles radially outward while the lighter fat globules (cream) coalesce near the center.",
        "exp_hi": "घूर्णन के दौरान उत्पन्न अपकेंद्री बल (Centrifugal Force) के कारण भारी द्रव परिधि की ओर फिंक जाता है और कम घनत्व वाला मक्खन केंद्र के पास एकत्र हो जाता है।",
        "cue_en": "Cream separator & Spin dryer = Centrifugal Force.",
        "cue_hi": "मक्खन निकालने वाली मशीन = अपकेंद्री बल।",
        "wrong_en": ["Apparent outward force in centrifuge.", "Inward force maintaining orbit.", "Weak fundamental attraction.", "Operates on magnetic poles."],
        "wrong_hi": ["घूर्णन में बाहर की ओर लगने वाला आभासी बल।", "केंद्र की ओर लगने वाला बल।", "गुरुत्वाकर्षण।", "चुंबकीय बल।"]
    }
]

# S10-Cc1c9f435 Wave Motion, Sound, Optics & Light Reflection/Refraction (4 topics)
DATA["S10-Cc1c9f435"] = [
    {
        "name_en": "Wave Characteristics: Longitudinal vs Transverse & Electromagnetic Waves",
        "name_hi": "तरंग गति की विशेषताएं: अनुदैर्ध्य बनाम अनुप्रस्थ तरंगें एवं विद्युत चुंबकीय स्पेक्ट्रम",
        "concepts_en": ["Transverse waves: Particles oscillate perpendicular to wave propagation (Crests & Troughs; e.g., light, ripples on water; can be polarized)", "Longitudinal waves: Particles oscillate parallel to propagation (Compressions & Rarefactions; e.g., sound; CANNOT be polarized)", "Electromagnetic Spectrum (decreasing wavelength / increasing frequency): Radio -> Microwave -> Infrared -> Visible (VIBGYOR) -> Ultraviolet -> X-rays -> Gamma rays", "Speed of EM waves in vacuum: c ≈ 3 × 10⁸ m/s"],
        "concepts_hi": ["अनुप्रस्थ तरंगें (Transverse): माध्यम के कण तरंग संचरण की दिशा के लंबवत दोलन करते हैं (श्रृंग व गर्त; जैसे प्रकाश तरंगें; इनका ध्रुवण संभव है)", "अनुदैर्ध्य तरंगें (Longitudinal): माध्यम के कण तरंग संचरण के समानांतर दोलन करते हैं (संपीडन व विरलन; जैसे ध्वनि तरंगें; इनका ध्रुवण नहीं हो सकता)", "विद्युत चुंबकीय स्पेक्ट्रम: रेडियो -> सूक्ष्म (माइक्रोवेव) -> अवरक्त (IR) -> दृश्य प्रकाश (VIBGYOR) -> पराबैंगनी (UV) -> एक्स-रे -> गामा किरणें", "निर्वात में प्रकाश की चाल: c ≈ 3 × 10⁸ मीटर/सेकंड"],
        "q_en": "Which wave phenomenon can be exhibited exclusively by transverse waves (such as light), but NEVER by longitudinal waves (such as sound)?",
        "q_hi": "निम्नलिखित में से कौन सी तरंगीय परिघटना केवल अनुप्रस्थ तरंगों (जैसे प्रकाश) द्वारा प्रदर्शित की जा सकती है, किंतु अनुदैर्ध्य तरंगों (जैसे ध्वनि) द्वारा कभी नहीं?",
        "options_en": ["Polarization (ध्रुवण)", "Diffraction", "Interference", "Refraction"],
        "options_hi": ["ध्रुवण (Polarization)", "विवर्तन (Diffraction)", "व्यतिकरण (Interference)", "अपवर्तन (Refraction)"],
        "correct_idx": 0,
        "exp_en": "Polarization is the restriction of wave vibrations to a single plane, a property exclusive to transverse waves because their oscillations are perpendicular to travel.",
        "exp_hi": "ध्रुवण (Polarization) केवल अनुप्रस्थ तरंगों का विशिष्ट गुण है; चूंकि ध्वनि एक अनुदैर्ध्य तरंग है जिसमें दोलन संचरण की दिशा में होते हैं, अतः ध्वनि का ध्रुवण संभव नहीं है।",
        "cue_en": "Polarization occurs in Transverse waves only (Light, NOT Sound).",
        "cue_hi": "केवल अनुप्रस्थ तरंगों में ध्रुवण होता है (प्रकाश में होता है, ध्वनि में नहीं)।",
        "wrong_en": ["Exclusive to transverse waves.", "Occurs in both transverse and longitudinal.", "Occurs in both transverse and longitudinal.", "Occurs in both transverse and longitudinal."],
        "wrong_hi": ["केवल अनुप्रस्थ तरंगों का गुण।", "दोनों में होता है।", "दोनों में होता है।", "दोनों में होता है।"]
    },
    {
        "name_en": "Sound Waves: Speed, Frequency Spectrum (Infrasonic to Ultrasonic) & Doppler Effect",
        "name_hi": "ध्वनि तरंगें: गति, आवृत्ति स्पेक्ट्रम (अपश्रव्य, श्रव्य, पराश्रव्य) एवं डॉपलर प्रभाव",
        "concepts_en": ["Audible range for human ear: 20 Hz to 20,000 Hz (20 kHz)", "Infrasonic (<20 Hz): Produced by earthquakes, volcanic eruptions, elephants, whales", "Ultrasonic (>20,000 Hz): Used by bats for echolocation, SONAR (Sound Navigation and Ranging), ultrasonography, cleaning delicate jewelry", "Speed of sound: Requires material medium (cannot travel in vacuum); fastest in solids (~5000 m/s in steel) > liquids (~1500 m/s in water) > gases (~343 m/s in air at 20°C); increases with temperature and humidity", "Doppler Effect: Apparent change in frequency/pitch when source and observer are in relative motion"],
        "concepts_hi": ["मानव कान की श्रव्य सीमा: 20 हर्ट्ज से 20,000 हर्ट्ज (20 kHz)", "अपश्रव्य तरंगें (Infrasonic): 20 Hz से कम (भूकंप, हाथी, व्हेल)", "पराश्रव्य तरंगें (Ultrasonic): 20,000 Hz से अधिक (चमगादड़, सोनार / SONAR, अल्ट्रासाउंड सोनोग्राफी)", "ध्वनि की चाल: माध्यम अनिवार्य (निर्वात में गमन नहीं कर सकती); ठोस में सर्वाधिक (स्टील में ~5000 मी/से) > जल में (~1500 मी/से) > वायु में (~343 मी/से); तापमान व आर्द्रता बढ़ने पर ध्वनि की चाल बढ़ती है", "डॉपलर प्रभाव: स्रोत और श्रोता की सापेक्ष गति के कारण ध्वनि की आवृत्ति (तारत्व) में होने वाला आभासी परिवर्तन"],
        "q_en": "Through which of the following media does sound propagate with the HIGHEST velocity?",
        "q_hi": "निम्नलिखित में से किस माध्यम में ध्वनि की चाल सर्वाधिक (सबसे तेज) होती है?",
        "options_en": ["Steel / Iron (ठोस इस्पात)", "Water (जल)", "Air (वायु)", "Vacuum (निर्वात)"],
        "options_hi": ["इस्पात / लोहा (Steel)", "जल (Water)", "वायु (Air)", "निर्वात (Vacuum)"],
        "correct_idx": 0,
        "exp_en": "Sound propagates fastest through dense elastic solids where molecular bonds are stiff; in steel it travels at ~5,100 m/s, compared to ~1,480 m/s in water and ~343 m/s in air.",
        "exp_hi": "ध्वनि की चाल माध्यम के प्रत्यास्थता गुणांक पर निर्भर करती है; इस्पात (ठोस) में ध्वनि लगभग 5,100 मीटर/सेकंड की गति से चलती है, जबकि निर्वात में ध्वनि का संचरण शून्य होता है।",
        "cue_en": "Speed of Sound: Solids > Liquids > Gases (Zero in Vacuum).",
        "cue_hi": "ध्वनि की चाल: ठोस > द्रव > गैस (निर्वात में शून्य)।",
        "wrong_en": ["Fastest medium (~5,100 m/s).", "Intermediate velocity (~1,480 m/s).", "Slow velocity (~343 m/s).", "Sound cannot travel in vacuum."],
        "wrong_hi": ["सर्वाधिक गति वाला माध्यम।", "मध्यम गति (~1,480 मी/से)।", "धीमी गति (~343 मी/से)।", "निर्वात में ध्वनि नहीं चल सकती।"]
    },
    {
        "name_en": "Reflection, Refraction, Snell's Law & Total Internal Reflection (TIR)",
        "name_hi": "प्रकाश का परावर्तन, अपवर्तन, स्नेल का नियम एवं पूर्ण आंतरिक परावर्तन (TIR)",
        "concepts_en": ["Laws of Reflection: Angle of incidence = Angle of reflection (i = r)", "Refraction: Bending of light when crossing media boundaries; Snell's Law: n1*sin(i) = n2*sin(r)", "Total Internal Reflection (TIR) conditions: Light must travel from denser to rarer medium AND angle of incidence must exceed Critical Angle (C)", "Applications of TIR: Optical fiber telecommunications, brilliance of cut diamonds, mirages in deserts, medical endoscopes"],
        "concepts_hi": ["परावर्तन के नियम: आपतन कोण = परावर्तन कोण (i = r)", "अपवर्तन: एक माध्यम से दूसरे माध्यम में जाने पर प्रकाश की चाल बदलने से उसका मुड़ना; स्नेल का नियम: sin(i) / sin(r) = नियतांक (अपवर्तनांक)", "पूर्ण आंतरिक परावर्तन (TIR) की दो अनिवार्य शर्तें: प्रकाश सघन माध्यम से विरल माध्यम में जाना चाहिए और आपतन कोण का मान क्रांतिक कोण (Critical Angle) से अधिक होना चाहिए", "TIR के अनुप्रयोग: ऑप्टिकल फाइबर संचार, हीरे की चमक, रेगिस्तान में मरीचिका (Mirage), एंडोस्कोपी"],
        "q_en": "Modern high-speed optical fiber communications transmit data pulses based on which fundamental optical phenomenon?",
        "q_hi": "आधुनिक उच्च गति इंटरनेट ऑप्टिकल फाइबर (प्रकाश तंतु) केबल में डेटा संकेतों का संचरण प्रकाश की किस परिघटना पर आधारित होता है?",
        "options_en": ["Total Internal Reflection (पूर्ण आंतरिक परावर्तन)", "Scattering of Light", "Diffraction of Light", "Double Refraction"],
        "options_hi": ["पूर्ण आंतरिक परावर्तन (Total Internal Reflection)", "प्रकाश का प्रकीर्णन", "प्रकाश का विवर्तन", "द्वि-अपवर्तन"],
        "correct_idx": 0,
        "exp_en": "Optical fibers consist of a glass/plastic core surrounded by cladding with a lower refractive index, trapping light pulses completely inside via repeated Total Internal Reflection (TIR).",
        "exp_hi": "ऑप्टिकल फाइबर के कोर का अपवर्तनांक क्लैडिंग से अधिक रखा जाता है, जिससे प्रकाश किरणें अंदर ही अंदर बार-बार पूर्ण आंतरिक परावर्तन (TIR) करते हुए बिना ऊर्जा क्षय के लंबी दूरी तय करती हैं।",
        "cue_en": "Optical Fiber = Total Internal Reflection (TIR).",
        "cue_hi": "ऑप्टिकल फाइबर = पूर्ण आंतरिक परावर्तन।",
        "wrong_en": ["Underlying principle of optical fibers.", "Explains blue color of sky (Rayleigh).", "Bending around obstacles.", "Birefringence in calcite crystals."],
        "wrong_hi": ["ऑप्टिकल फाइबर का सिद्धांत।", "आकाश के नीले रंग का कारण।", "किनारों से मुड़ना।", "कैल्साइट में दोहरा अपवर्तन।"]
    },
    {
        "name_en": "Lenses, Mirrors, Dispersion of Light & Human Vision Defects",
        "name_hi": "लेंस, दर्पण, प्रकाश का विक्षेपण (वर्ण-विक्षेपण) एवं दृष्टि दोष (मायोपिया, हाइपरमेट्रोपिया)",
        "concepts_en": ["Concave mirror: Converging (used in shaving mirrors, dentist headlamps, solar cookers); Convex mirror: Diverging, always virtual upright diminished image with wide field of view (used as vehicle rear-view mirrors)", "Dispersion: Splitting of white light into spectrum (VIBGYOR) through a prism (Newton 1666); Violet bends most (highest refractive index), Red bends least", "Myopia (Short-sightedness): Image forms in front of retina; corrected by Concave Lens (diverging)", "Hypermetropia (Far-sightedness): Image forms behind retina; corrected by Convex Lens (converging); Presbyopia corrected by Bifocal lenses"],
        "concepts_hi": ["अवतल दर्पण (Concave): अभिसारी (दाढ़ी बनाने का शीशा, दंत चिकित्सक, गाड़ियों की हेडलाइट); उत्तल दर्पण (Convex): अपसारी, सदैव सीधा व छोटा आभासी प्रतिबिंब, विस्तृत दृष्टि क्षेत्र (वाहनों का पश्च-दृश्य दर्पण / Rear-view mirror)", "वर्ण-विक्षेपण (Dispersion): प्रिज्म से गुजरने पर श्वेत प्रकाश का सात रंगों (बैजानीहपीनाला / VIBGYOR) में बंटना; बैंगनी रंग का विचलन सर्वाधिक और लाल रंग का विचलन न्यूनतम होता है", "निकट दृष्टि दोष (Myopia): पास की वस्तु दिखती है, दूर की नहीं; प्रतिबिंब रेटिना से पहले बनता है; 'अवतल लेंस' द्वारा निवारण", "दूर दृष्टि दोष (Hypermetropia): प्रतिबिंब रेटिना के पीछे बनता है; 'उत्तल लेंस' द्वारा निवारण; जरा दृष्टि दोष (Presbyopia) में द्विफोकसी (Bifocal) लेंस"],
        "q_en": "Which corrective optical lens is prescribed to correct Myopia (near-sightedness), where light rays from a distant object focus in front of the retina?",
        "q_hi": "निकट दृष्टि दोष (Myopia) से पीड़ित व्यक्ति, जिसकी आंखों में दूर की वस्तु का प्रतिबिंब रेटिना के आगे बन जाता है, के निवारण हेतु किस प्रकार के लेंस का चश्मा लगाया जाता है?",
        "options_en": ["Concave Lens (अवतल लेंस / अपसारी लेंस)", "Convex Lens (उत्तल लेंस)", "Bifocal Lens", "Cylindrical Lens"],
        "options_hi": ["अवतल लेंस (Concave Lens)", "उत्तल लेंस (Convex Lens)", "द्विफोकसी लेंस (Bifocal Lens)", "बेलनाकार लेंस (Cylindrical Lens)"],
        "correct_idx": 0,
        "exp_en": "A concave (diverging) lens diverges incoming parallel light rays before they enter the eye, allowing them to focus exactly onto the retina to correct Myopia.",
        "exp_hi": "निकट दृष्टि दोष (मायोपिया) में अवतल लेंस (Concave lens) लगाया जाता है जो किरणों को थोड़ा फैला देता है ताकि प्रतिबिंब रेटिना के आगे बनने के बजाय ठीक रेटिना पर बने।",
        "cue_en": "Myopia = Concave lens; Hypermetropia = Convex lens.",
        "cue_hi": "निकट दृष्टि दोष (मायोपिया) = अवतल लेंस; दूर दृष्टि = उत्तल लेंस।",
        "wrong_en": ["Corrects Myopia.", "Corrects Hypermetropia (far-sightedness).", "Corrects Presbyopia in elderly.", "Corrects Astigmatism."],
        "wrong_hi": ["मायोपिया का निवारक।", "दूर दृष्टि दोष का निवारक।", "जरा दृष्टि दोष का निवारक।", "दृष्टिवैषम्य (अबिंदुकता) का निवारक।"]
    }
]

# S10-C64dfa5ec Heat, Thermodynamics, Electromagnetism & Modern Physics (6 topics)
DATA["S10-C64dfa5ec"] = [
    {
        "name_en": "Thermal Expansion, Specific Heat Capacity & Latent Heat of Phase Change",
        "name_hi": "तापीय प्रसार, विशिष्ट ऊष्मा धारिता एवं अवस्था परिवर्तन की गुप्त ऊष्मा",
        "concepts_en": ["Anomalous expansion of water: Contracts when heated from 0°C to 4°C; density of water is MAXIMUM at 4°C (preserves aquatic life under frozen lakes)", "Specific Heat Capacity: Amount of heat required to raise temperature of 1 kg mass by 1°C; Water has exceptionally high specific heat (4,184 J/kg·K), making it ideal coolant in car radiators", "Latent Heat of Fusion (80 cal/g for ice) and Vaporization (540 cal/g for steam)", "Steam causes more severe burns than boiling water at 100°C due to latent heat of vaporization"],
        "concepts_hi": ["जल का असामान्य प्रसार: 0°C से 4°C तक गर्म करने पर जल सिकुड़ता है; 4°C पर जल का घनत्व 'अधिकतम' होता है (सर्दियों में झीलों के जमने पर भी नीचे जलीय जीवन सुरक्षित रहता है)", "विशिष्ट ऊष्मा: 1 किग्रा पदार्थ का तापमान 1°C बढ़ाने हेतु आवश्यक ऊष्मा; जल की विशिष्ट ऊष्मा अत्यधिक उच्च (4,184 J/kg·K) होती है, इसलिए इसका उपयोग इंजन कूलेंट व सिकाई में होता है", "गुप्त ऊष्मा: अवस्था परिवर्तन में बिना तापमान बदले दी जाने वाली ऊष्मा; वाष्पन की गुप्त ऊष्मा (भाप = 540 cal/g)", "100°C के उबलते पानी की तुलना में 100°C की भाप से जलना अधिक कष्टदायी होता है क्योंकि भाप में 540 कैलोरी/ग्राम अतिरिक्त गुप्त ऊष्मा होती है"],
        "q_en": "At what temperature does pure liquid water reach its MAXIMUM density before expanding upon further cooling?",
        "q_hi": "शुद्ध जल का घनत्व किस तापमान पर अधिकतम (Maximum Density) होता है?",
        "options_en": ["4°C (4 डिग्री सेल्सियस)", "0°C", "-4°C", "100°C"],
        "options_hi": ["4°C (Four Degrees Celsius)", "0°C", "-4°C", "100°C"],
        "correct_idx": 0,
        "exp_en": "Due to anomalous expansion caused by hydrogen bonding, water contracts as temperature rises from 0°C to 4°C, attaining maximum density of 1.00 g/cm³ at precisely 4°C (39.2°F).",
        "exp_hi": "जल के असामान्य प्रसार के कारण 4°C पर पानी का आयतन न्यूनतम और उसका घनत्व अधिकतम (1 ग्राम/सेमी³) होता है।",
        "cue_en": "Maximum density of water = 4°C.",
        "cue_hi": "जल का अधिकतम घनत्व = 4°C।",
        "wrong_en": ["Maximum density temperature.", "Freezing point of water.", "Water is solid ice at this point.", "Boiling point at standard pressure."],
        "wrong_hi": ["अधिकतम घनत्व का तापमान।", "जल का हिमांक बिंदु।", "बर्फ अवस्था।", "क्वथनांक बिंदु।"]
    },
    {
        "name_en": "Laws of Thermodynamics: Zeroth, First, Second Laws & Absolute Zero",
        "name_hi": "ऊष्मागतिकी के नियम: शून्यांकी नियम, प्रथम नियम, द्वितीय नियम (एंट्रॉपी) एवं परम शून्य",
        "concepts_en": ["Zeroth Law: Defines concept of temperature (if A is in thermal equilibrium with B, and B with C, then A is in equilibrium with C)", "First Law (Conservation of Energy): Heat added to a system equals increase in internal energy plus work done (dQ = dU + dW)", "Second Law: Heat cannot spontaneously flow from cooler to hotter body without external work (Clausius); no heat engine can convert all absorbed heat into work (Kelvin-Planck); Total Entropy of isolated universe always increases", "Third Law & Absolute Zero: As temperature approaches Absolute Zero (0 Kelvin = -273.15°C), entropy of a pure crystalline substance approaches zero"],
        "concepts_hi": ["शून्यांकी नियम (Zeroth Law): तापमान की अवधारणा देता है (यदि निकाय A व B तथा B व C तापीय साम्यावस्था में हैं, तो A व C भी साम्यावस्था में होंगे)", "प्रथम नियम (ऊर्जा संरक्षण): निकाय को दी गई ऊष्मा आंतरिक ऊर्जा में वृद्धि तथा किए गए कार्य के योग के बराबर होती है (dQ = dU + dW)", "द्वितीय नियम (एंट्रॉपी का नियम): ऊष्मा स्वतः ठंडे पिंड से गर्म पिंड की ओर प्रवाहित नहीं हो सकती (क्लासियस); 100% दक्ष ऊष्मा इंजन संभव नहीं है; ब्रह्मांड की कुल एंट्रॉपी सदैव बढ़ती है", "तृतीय नियम: परम शून्य ताप (0 केल्विन = -273.15°C) पर किसी आदर्श क्रिस्टल की एंट्रॉपी शून्य हो जाती है"],
        "q_en": "What is the theoretical lower limit of thermodynamic temperature, known as 'Absolute Zero', expressed on the Celsius scale?",
        "q_hi": "ऊष्मागतिकी में 'परम शून्य ताप' (Absolute Zero), जिस पर अणुओं की तापीय गति शून्य मानी जाती है, सेल्सियस पैमाने पर कितना होता है?",
        "options_en": ["-273.15°C (माइनस 273.15 डिग्री सेल्सियस)", "-100°C", "0°C", "-459.67°C"],
        "options_hi": ["-273.15°C", "-100°C", "0°C", "-459.67°C (यह फारेनहाइट मान है)"],
        "correct_idx": 0,
        "exp_en": "Absolute zero corresponds to 0 Kelvin or -273.15°C (-459.67°F), at which enthalpy and entropy of a cooled ideal gas reach their minimum values.",
        "exp_hi": "परम शून्य तापमान 0 केल्विन या -273.15°C होता है; यह प्रकृति का न्यूनतम संभव तापमान है जिस पर आणविक गति रुक जाती है।",
        "cue_en": "Absolute Zero = 0 K = -273.15°C.",
        "cue_hi": "परम शून्य = 0 K = -273.15°C।",
        "wrong_en": ["Correct Celsius value for Absolute Zero.", "Sub-zero temperature, not absolute zero.", "Freezing point of water.", "Fahrenheit value, not Celsius."],
        "wrong_hi": ["सेल्सियस में सही मान।", "सामान्य ठंडा तापमान।", "जल का हिमांक।", "फारेनहाइट मान (-459.67°F)।"]
    },
    {
        "name_en": "Coulomb's Law, Electric Current, Ohm's Law & Electric Power",
        "name_hi": "कूलॉम का नियम, विद्युत धारा, ओम का नियम एवं विद्युत शक्ति",
        "concepts_en": ["Coulomb's Law: F = k*(q1*q2)/r² between static charges; electric field and potential", "Electric Current (I = Q/t, unit Ampere); potential difference (V = W/Q, unit Volt)", "Ohm's Law: V = I*R (at constant temperature); Resistance R = ρ*L/A (depends on material resistivity ρ, length L, cross-sectional area A)", "Resistors in series (R_eq = R1 + R2) vs parallel (1/R_eq = 1/R1 + 1/R2; household wiring is in parallel so each appliance receives full voltage)", "Joule's Law of Heating: H = I²*R*t; Electric power P = V*I = I²*R = V²/R (commercial unit: 1 kWh = 1 Unit = 3.6 × 10⁶ Joules)"],
        "concepts_hi": ["कूलॉम का नियम: दो बिंदु आवेशों के बीच आकर्षण/प्रतिकर्षण बल F = k*(q1*q2)/r²", "विद्युत धारा (I = q/t, मात्रक: एम्पियर); विभवांतर (V, मात्रक: वोल्ट)", "ओम का नियम: V = IR (नियत ताप पर); प्रतिरोध R = ρ*L/A (तार की लंबाई बढ़ने पर प्रतिरोध बढ़ता है, मोटाई बढ़ने पर घटता है)", "प्रतिरोधों का संयोजन: श्रेणीक्रम (R = R1 + R2) एवं समानांतर क्रम (1/R = 1/R1 + 1/R2; घरेलू वायरिंग समानांतर क्रम में होती है ताकि सबको 220V समान मिले)", "जूल का ऊष्मीय नियम: H = I²Rt; विद्युत शक्ति P = VI; 1 यूनिट (kWh) = 3.6 × 10⁶ जूल"],
        "q_en": "Why are electrical household domestic appliances and lighting circuits always wired in a PARALLEL arrangement rather than in series?",
        "q_hi": "घरों में विद्युत उपकरण और बल्ब सदैव 'समानांतर क्रम' (Parallel Circuit) में क्यों जोड़े जाते हैं?",
        "options_en": ["Each appliance receives the full supply voltage and operates independently of others", "It minimizes total current drawn from the grid", "It increases total electrical resistance of the house", "It eliminates the need for earthing and fuses"],
        "options_hi": ["प्रत्येक उपकरण को समान पूर्ण वोल्टेज मिलती है और एक के खराब होने पर अन्य बंद नहीं होते", "यह ग्रिड से खींची जाने वाली धारा को कम करता है", "यह घर के कुल प्रतिरोध को बहुत बढ़ा देता है", "यह अर्थिंग की आवश्यकता को समाप्त कर देता है"],
        "correct_idx": 0,
        "exp_en": "In parallel wiring, every appliance is connected across the full 220V mains voltage and can be switched on/off independently without breaking the circuit for other devices.",
        "exp_hi": "समानांतर क्रम में सभी उपकरणों को समान वोल्टेज (220 वोल्ट) प्राप्त होता है तथा प्रत्येक का अपना स्वतंत्र स्विच होता है; एक उपकरण के खराब होने पर बाकी उपकरण सामान्य रूप से कार्य करते रहते हैं।",
        "cue_en": "Household wiring = Parallel (Full voltage + Independent switches).",
        "cue_hi": "घरेलू परिपथ = समानांतर क्रम (समान वोल्टेज व स्वतंत्र संचालन)।",
        "wrong_en": ["Core reasons for parallel domestic circuits.", "Draws required current, not minimizing blindly.", "Parallel wiring reduces total resistance, not increases.", "Fuses and earthing are still mandatory."],
        "wrong_hi": ["समानांतर क्रम का मुख्य लाभ।", "धारा आवश्यकतानुसार मिलती है।", "समानांतर में कुल प्रतिरोध घटता है।", "सुरक्षा उपकरण फिर भी जरूरी होते हैं।"]
    },
    {
        "name_en": "Electromagnetism: Oersted Experiment, Faraday's Induction & Lenz's Law",
        "name_hi": "विद्युत चुंबकत्व: ओर्स्टेड का प्रयोग, फैराडे का विद्युत चुंबकीय प्रेरण एवं लेन्ज का नियम",
        "concepts_en": ["Hans Christian Oersted (1820) discovered that electric current creates a magnetic field (deflected magnetic compass)", "Right-Hand Thumb Rule gives direction of circular magnetic field lines around straight conductor", "Michael Faraday (1831) discovered Electromagnetic Induction: Changing magnetic flux induces electromotive force (EMF) in a coil (basis of electric generators and transformers)", "Lenz's Law (conservation of energy): Direction of induced current always opposes the change in magnetic flux that produces it", "Fleming's Left-Hand Rule (Electric Motors) vs Fleming's Right-Hand Rule (Generators)"],
        "concepts_hi": ["हंस क्रिश्चियन ओर्स्टेड (1820): विद्युत धारा के चुंबकीय प्रभाव की खोज (तार में धारा प्रवाहित करने पर कंपास की सुई में विक्षेप)", "दाहिने हाथ के अंगूठे का नियम: चालक के चारों ओर चुंबकीय क्षेत्र की दिशा दर्शाता है", "माइकल फैराडे (1831): विद्युत चुंबकीय प्रेरण (चुंबकीय फ्लक्स में परिवर्तन से प्रेरित विद्युत वाहक बल/धारा उत्पन्न होना; जनरेटर व ट्रांसफार्मर का सिद्धांत)", "लेन्ज का नियम (ऊर्जा संरक्षण): प्रेरित धारा की दिशा सदैव ऐसी होती है कि वह उस कारण का विरोध करती है जिससे वह स्वयं उत्पन्न हुई है", "फ्लेमिंग का बायां हाथ नियम (विद्युत मोटर) बनाम दायां हाथ नियम (विद्युत जनरेटर)"],
        "q_en": "Which foundational law of electromagnetism states that the direction of an induced current is always such that it opposes the change in magnetic flux producing it?",
        "q_hi": "विद्युत चुंबकत्व का वह कौन सा नियम है जो यह निर्धारित करता है कि 'प्रेरित धारा की दिशा सदैव ऐसी होती है कि वह उसी परिवर्तन (चुंबकीय फ्लक्स में बदलाव) का विरोध करती है जिससे वह उत्पन्न होती है'?",
        "options_en": ["Lenz's Law (लेन्ज का नियम)", "Ohm's Law", "Coulomb's Law", "Ampere's Circuital Law"],
        "options_hi": ["लेन्ज का नियम (Lenz's Law)", "ओम का नियम", "कूलॉम का नियम", "एम्पीयर का परिपथीय नियम"],
        "correct_idx": 0,
        "exp_en": "Lenz's Law, formulated in 1834 by Heinrich Lenz, gives the direction of induced EMF/current and is a direct consequence of the conservation of energy.",
        "exp_hi": "लेन्ज का नियम ऊर्जा संरक्षण के सिद्धांत पर आधारित है; यह बताता है कि प्रेरित धारा चुंबकीय फ्लक्स में परिवर्तन का विरोध करने की दिशा में बहती है।",
        "cue_en": "Direction of induced EMF opposes cause = Lenz's Law.",
        "cue_hi": "प्रेरित धारा विरोध करती है = लेन्ज का नियम।",
        "wrong_en": ["Specifies opposing direction of induced current.", "Relates current and voltage.", "Relates forces between charges.", "Relates magnetic field to enclosed current."],
        "wrong_hi": ["प्रेरित धारा की दिशा का नियम।", "प्रतिरोध का नियम।", "स्थिर विद्युत बल का नियम।", "धारा और चुंबकीय क्षेत्र का संबंध।"]
    },
    {
        "name_en": "Photoelectric Effect: Quantum Nature of Light & Einstein's Photoelectric Equation",
        "name_hi": "प्रकाश-विद्युत प्रभाव: प्रकाश की क्वांटम प्रकृति एवं आइंस्टीन का प्रकाश-विद्युत समीकरण",
        "concepts_en": ["Discovered by Heinrich Hertz (1887), experimentally studied by Hallwachs and Lenard", "Photoelectric Effect: Emission of electrons from a metal surface when irradiated with light of frequency above threshold frequency (ν₀)", "Could not be explained by classical wave theory (kinetic energy depends on frequency, NOT intensity; emission is instantaneous)", "Albert Einstein (1905) explained it using Max Planck's photon quantum theory: E = hν = W₀ + KE_max (W₀ = work function); Einstein was awarded the 1921 Nobel Prize in Physics specifically for this discovery", "Applications: Solar photovoltaic cells, light meters, night-vision photocells"],
        "concepts_hi": ["हेनरिक हर्ट्ज (1887) द्वारा खोजा गया; हॉलवैक्स एवं लेनार्ड द्वारा विस्तृत अध्ययन", "प्रकाश-विद्युत प्रभाव: किसी धातु की सतह पर देहली आवृत्ति (Threshold Frequency) से अधिक आवृत्ति का प्रकाश पड़ने पर इलेक्ट्रॉनों का तुरंत बाहर निकलना", "तरंग सिद्धांत से व्याख्या असंभव थी (इलेक्ट्रॉन की गतिज ऊर्जा प्रकाश की आवृत्ति पर निर्भर करती है, तीव्रता पर नहीं; कोई समय-पश्चता नहीं होती)", "अल्बर्ट आइंस्टीन ने 1905 में प्लांक के क्वांटम सिद्धांत के आधार पर समझाया: hν = W + 1/2 m v² (W = कार्यफलन); आइंस्टीन को 1921 का भौतिकी का नोबेल पुरस्कार इसी खोज हेतु मिला था", "अनुप्रयोग: सोलर पैनल (फोटोवोल्टाइक सेल), फोटोइलेक्ट्रिक सेंसर, प्रकाश मापक"],
        "q_en": "For which seminal scientific achievement was Albert Einstein officially awarded the 1921 Nobel Prize in Physics?",
        "q_hi": "अल्बर्ट आइंस्टीन को वर्ष 1921 का भौतिकी का नोबेल पुरस्कार उनकी किस युगांतरकारी खोज हेतु प्रदान किया गया था?",
        "options_en": ["His explanation of the Law of the Photoelectric Effect (प्रकाश-विद्युत प्रभाव की व्याख्या)", "The Special Theory of Relativity (E = mc²)", "The General Theory of Relativity", "His theory of Brownian Motion"],
        "options_hi": ["प्रकाश-विद्युत प्रभाव के नियम की व्याख्या (Law of the Photoelectric Effect)", "आपेक्षिकता का विशिष्ट सिद्धांत (Special Relativity)", "आपेक्षिकता का सामान्य सिद्धांत (General Relativity)", "ब्राउनियन गति का सिद्धांत"],
        "correct_idx": 0,
        "exp_en": "The Nobel Citation officially honored Einstein 'for his services to Theoretical Physics, and especially for his discovery of the law of the photoelectric effect' using quanta of light.",
        "exp_hi": "आइंस्टीन को नोबेल पुरस्कार उनके सापेक्षता के सिद्धांत के लिए नहीं, बल्कि 1905 में फोटॉन सिद्धांत द्वारा 'प्रकाश-विद्युत प्रभाव' के नियम की सफल व्याख्या करने हेतु दिया गया था।",
        "cue_en": "Einstein's Nobel Prize (1921) = Photoelectric Effect.",
        "cue_hi": "आइंस्टीन को नोबेल पुरस्कार = प्रकाश-विद्युत प्रभाव।",
        "wrong_en": ["Official Nobel award citation.", "1905 theory, not cited by Nobel committee.", "1915 theory, too controversial at the time.", "1905 paper on molecular dimensions."],
        "wrong_hi": ["आधिकारिक नोबेल प्रशस्ति।", "इस पर नोबेल नहीं मिला।", "इस पर नोबेल नहीं मिला।", "अणु आकार का शोध।"]
    },
    {
        "name_en": "Nuclear Physics: Fission, Fusion, Radioactive Decay & Half-Life",
        "name_hi": "नाभिकीय भौतिकी: नाभिकीय विखंडन, नाभिकीय संलयन एवं रेडियोधर्मी क्षय (अर्धायु काल)",
        "concepts_en": ["Nuclear Fission: Heavy nucleus (Uranium-235, Plutonium-239) splits into lighter nuclei when bombarded by thermal neutrons, releasing enormous energy (~200 MeV per fission) and 2-3 fast neutrons (chain reaction); basis of Nuclear Reactors and Atomic Bombs", "Nuclear Reactor components: Moderator (heavy water D2O, graphite) slows fast neutrons; Control rods (cadmium, boron) absorb excess neutrons; Coolant transfers heat", "Nuclear Fusion: Light nuclei (deuterium and tritium) fuse under extreme temperature and pressure to form helium, releasing far greater energy per unit mass; powers the Sun and Stars, basis of Hydrogen Bomb", "Radioactive Decay: Alpha particles (He nuclei), Beta particles (electrons/positrons), Gamma rays (high-energy photons); Half-life (T1/2 = 0.693/λ) is time required for half the radioactive nuclei to disintegrate"],
        "concepts_hi": ["नाभिकीय विखंडन (Fission): धीमे न्यूट्रॉन की टक्कर से भारी नाभिक (U-235) का हल्के नाभिकों (बेरियम व क्रिप्टन) में टूटना, भारी ऊर्जा (~200 MeV) व 2-3 नए न्यूट्रॉन निकलना; परमाणु भट्टी व परमाणु बम का आधार", "परमाणु रिएक्टर के अंग: मंदक (भारी जल D2O, ग्रेफाइट) न्यूट्रॉनों की गति धीमी करता है; नियंत्रक छड़ें (कैडमियम, बोरॉन) न्यूट्रॉनों को अवशोषित करती हैं; शीतलक ऊष्मा निकालता है", "नाभिकीय संलयन (Fusion): अत्यधिक उच्च ताप व दाब पर दो हल्के नाभिक (ड्यूटीरियम + ट्रिटियम) जुड़कर हीलियम बनाते हैं; सूर्य व तारों की असीम ऊर्जा का स्रोत; हाइड्रोजन बम का आधार", "रेडियोधर्मी क्षय: अल्फा (हीलियम नाभिक), बीटा (इलेक्ट्रॉन) और गामा (विद्युत चुंबकीय विकिरण); अर्धायु काल (Half-life): किसी रेडियोधर्मी तत्व के आधे परमाणुओं के विघटन में लगा समय"],
        "q_en": "In a nuclear power reactor, which material is commonly employed as a 'Moderator' to slow down fast neutrons to thermal speeds to sustain a controlled chain reaction?",
        "q_hi": "परमाणु ऊर्जा रिएक्टर में तीव्रगामी न्यूट्रॉनों की गति को धीमा (तापीय न्यूट्रॉन) करने के लिए 'मंदक' (Moderator) के रूप में सामान्यतः किसका उपयोग किया जाता है?",
        "options_en": ["Heavy Water (D2O) or Graphite (भारी जल या ग्रेफाइट)", "Cadmium or Boron rods", "Liquid Sodium", "Lead shielding"],
        "options_hi": ["भारी जल (D2O) या ग्रेफाइट (Heavy Water or Graphite)", "कैडमियम या बोरॉन की छड़ें (यह नियंत्रक छड़ें हैं)", "तरल सोडियम (यह शीतलक है)", "सीसे की ढाल"],
        "correct_idx": 0,
        "exp_en": "Heavy water (deuterium oxide, D2O) and high-purity graphite serve as moderators to slow down fission neutrons without capturing them, facilitating sustained fission of U-235.",
        "exp_hi": "भारी जल (D2O) और ग्रेफाइट का उपयोग मंदक के रूप में न्यूट्रॉनों की गति धीमी करने हेतु किया जाता है। (कैडमियम और बोरॉन की छड़ें न्यूट्रॉनों को सोखने वाले नियंत्रक के रूप में काम आती हैं)।",
        "cue_en": "Nuclear Moderator = Heavy Water (D2O) / Graphite; Control Rods = Cadmium / Boron.",
        "cue_hi": "परमाणु मंदक = भारी जल (D2O) व ग्रेफाइट; नियंत्रक छड़ें = कैडमियम व बोरॉन।",
        "wrong_en": ["Common nuclear moderators.", "Used as control rods (absorbers).", "Used as fast reactor coolant.", "Radiation shielding material."],
        "wrong_hi": ["सही मंदक पदार्थ।", "नियंत्रक छड़ें (न्यूट्रॉन अवशोषक)।", "शीतलक पदार्थ।", "सुरक्षा ढाल।"]
    }
]

print("Loaded S10 successfully")
