# build_curriculum/group3_s07.py
# S07: Indian Economy, Banking & Public Finance (16 topics across 3 chapters)

DATA = {}

# S07-C81cde124 National Income Accounting, GDP & Inflation Metrics (5 topics)
DATA["S07-C81cde124"] = [
    {
        "name_en": "Gross Domestic Product (GDP), GNP, NNP & Factor Cost vs Market Price",
        "name_hi": "सकल घरेलू उत्पाद (जीडीपी), जीएनपी, एनएनपी एवं साधन लागत बनाम बाजार मूल्य",
        "concepts_en": ["GDP is total monetary value of final goods and services produced within domestic territory in a financial year", "GNP = GDP + Net Factor Income from Abroad (NFIA)", "NNP at Factor Cost = National Income (NNP = GNP - Depreciation)", "Market Price = Factor Cost + Net Indirect Taxes (Indirect Taxes - Subsidies)"],
        "concepts_hi": ["जीडीपी: एक वित्तीय वर्ष में देश की घरेलू सीमा के भीतर उत्पादित अंतिम वस्तुओं एवं सेवाओं का कुल मौद्रिक मूल्य", "जीएनपी = जीडीपी + विदेशों से शुद्ध साधन आय (NFIA)", "साधन लागत पर शुद्ध राष्ट्रीय उत्पाद (NNP at Factor Cost) ही वास्तविक 'राष्ट्रीय आय' कहलाती है", "बाजार मूल्य = साधन लागत + शुद्ध अप्रत्यक्ष कर (अप्रत्यक्ष कर - सब्सिडी)"],
        "q_en": "Which national accounting aggregate is officially regarded as the true measure of 'National Income' of a country?",
        "q_hi": "राष्ट्रीय आय लेखांकन में निम्नलिखित में से किसे किसी देश की वास्तविक 'राष्ट्रीय आय' (National Income) माना जाता है?",
        "options_en": ["Net National Product at Factor Cost (NNP at Factor Cost)", "Gross Domestic Product at Market Price (GDP at MP)", "Gross National Product at Factor Cost (GNP at FC)", "Net Domestic Product at Market Price (NDP at MP)"],
        "options_hi": ["साधन लागत पर शुद्ध राष्ट्रीय उत्पाद (NNP at Factor Cost)", "बाजार मूल्य पर सकल घरेलू उत्पाद (GDP at MP)", "साधन लागत पर सकल राष्ट्रीय उत्पाद (GNP at FC)", "बाजार मूल्य पर शुद्ध घरेलू उत्पाद (NDP at MP)"],
        "correct_idx": 0,
        "exp_en": "Net National Product at Factor Cost (NNP at FC) is the official conceptual definition of National Income, representing total earnings accrued to normal residents.",
        "exp_hi": "साधन लागत पर शुद्ध राष्ट्रीय उत्पाद (NNP at FC) को ही अर्थशास्त्र में शुद्ध राष्ट्रीय आय कहा जाता है, जिसमें मूल्यह्रास घटाया गया होता है और उत्पादन के साधनों की आय शामिल होती है।",
        "cue_en": "National Income = NNP at Factor Cost.",
        "cue_hi": "राष्ट्रीय आय = साधन लागत पर एनएनपी (NNP at FC)।",
        "wrong_en": ["Official definition of National Income.", "Measure of domestic production, not national earnings.", "Includes depreciation.", "Domestic measure, not national."],
        "wrong_hi": ["राष्ट्रीय आय की मानक परिभाषा।", "यह घरेलू उत्पादन है, राष्ट्रीय आय नहीं।", "इसमें मूल्यह्रास शामिल रहता है।", "यह घरेलू पैमाना है।"]
    },
    {
        "name_en": "GDP Calculation Approaches: Production, Income & Expenditure Methods",
        "name_hi": "जीडीपी गणना की विधियां: उत्पादन (मूल्य संवर्धन), आय एवं व्यय विधि",
        "concepts_en": ["Production / Gross Value Added (GVA) approach: GVA = Output Value - Intermediate Consumption", "Income approach: Sum of wages (compensation of employees), rent, interest, and profits", "Expenditure approach: GDP = C + I + G + (X - M) [Private Consumption + Investment + Government Spending + Net Exports]", "National Statistical Office (NSO) under MoSPI compiles Indian GDP"],
        "concepts_hi": ["उत्पादन विधि (सकल मूल्य संवर्धन - GVA): GVA = कुल उत्पादन मूल्य - मध्यवर्ती उपभोग", "आय विधि: कर्मचारियों का पारिश्रमिक + किराया + ब्याज + लाभ का कुल योग", "व्यय विधि: GDP = C + I + G + (X - M) [निजी उपभोग + सकल निवेश + सरकारी व्यय + शुद्ध निर्यात]", "सांख्यिकी और कार्यक्रम कार्यान्वयन मंत्रालय (MoSPI) का राष्ट्रीय सांख्यिकी कार्यालय (NSO) जीडीपी आंकड़े जारी करता है"],
        "q_en": "In the Expenditure Method of estimating Gross Domestic Product, what does the formula GDP = C + I + G + (X - M) represent for '(X - M)'?",
        "q_hi": "सकल घरेलू उत्पाद (GDP) की गणना की व्यय विधि में सूत्र GDP = C + I + G + (X - M) में घटक '(X - M)' क्या दर्शाता है?",
        "options_en": ["Net Exports (Total Exports minus Total Imports)", "National Investment minus Foreign Outflows", "Gross Capital Formation", "Government External Borrowings"],
        "options_hi": ["शुद्ध निर्यात (कुल निर्यात में से कुल आयात घटाकर)", "राष्ट्रीय निवेश में से विदेशी बहिर्वाह", "सकल पूंजी निर्माण", "सरकारी विदेशी ऋण"],
        "correct_idx": 0,
        "exp_en": "In the standard expenditure identity, X represents total exports of goods and services, and M represents total imports; thus (X - M) equals Net Exports.",
        "exp_hi": "व्यय विधि में X निर्यात (Exports) और M आयात (Imports) को दर्शाता है; अतः (X - M) देश के शुद्ध निर्यात (Net Exports) का प्रतिनिधित्व करता है।",
        "cue_en": "(X - M) = Net Exports in GDP expenditure formula.",
        "cue_hi": "(X - M) = शुद्ध निर्यात (निर्यात - आयात)।",
        "wrong_en": ["Represents Net Exports.", "Incorrect financial flow.", "Represented by 'I' (Investment).", "Fiscal financing metric."],
        "wrong_hi": ["शुद्ध निर्यात को दर्शाता है।", "गलत वित्तीय प्रवाह।", "यह 'I' (निवेश) द्वारा दर्शाया जाता है।", "राजकोषीय पैमाना।"]
    },
    {
        "name_en": "Inflation Metrics: Consumer Price Index (CPI) vs Wholesale Price Index (WPI)",
        "name_hi": "मुद्रास्फीति के संकेतक: उपभोक्ता मूल्य सूचकांक (CPI) बनाम थोक मूल्य सूचकांक (WPI)",
        "concepts_en": ["CPI (Combined) measures retail price inflation experienced by consumers; base year 2012; food weightage ~45.86%; compiled by NSO", "WPI measures wholesale transaction prices; base year 2011-12; manufactured products weight ~64.23%; does NOT include services; compiled by DPIIT", "RBI adopted CPI (Combined) as nominal anchor for monetary policy following Urjit Patel Committee (2014)", "Core inflation excludes volatile food and fuel prices"],
        "concepts_hi": ["उपभोक्ता मूल्य सूचकांक (CPI): खुदरा स्तर पर उपभोक्ताओं द्वारा वहन की जाने वाली मुद्रास्फीति; आधार वर्ष 2012; खाद्य पदार्थों का भार लगभग 45.86%; NSO द्वारा जारी", "थोक मूल्य सूचकांक (WPI): थोक स्तर पर वस्तुओं के मूल्यों में परिवर्तन; आधार वर्ष 2011-12; इसमें सेवाएं (Services) शामिल नहीं होतीं; DPIIT द्वारा जारी", "उर्जित पटेल समिति (2014) की सिफारिश पर आरबीआई ने अपनी मौद्रिक नीति हेतु CPI को आधिकारिक पैमाना बनाया", "कोर मुद्रास्फीति: अस्थिर खाद्य और ईंधन की कीमतों को हटाकर निकाली गई मुद्रास्फीति"],
        "q_en": "Which inflation index was adopted by the Reserve Bank of India in 2014 as the primary headline measure for monetary policy and inflation targeting?",
        "q_hi": "भारतीय रिज़र्व बैंक (RBI) ने 2014 में अपनी मौद्रिक नीति और मुद्रास्फीति लक्ष्य निर्धारण हेतु प्राथमिक आधिकारिक सूचकांक के रूप में किसे अपनाया था?",
        "options_en": ["Consumer Price Index - Combined (CPI-C)", "Wholesale Price Index (WPI)", "Gross Domestic Product Deflator", "Index of Industrial Production (IIP)"],
        "options_hi": ["उपभोक्ता मूल्य सूचकांक - संयुक्त (CPI-Combined)", "थोक मूल्य सूचकांक (WPI)", "जीडीपी डिफ्लेटर (GDP Deflator)", "औद्योगिक उत्पादन सूचकांक (IIP)"],
        "correct_idx": 0,
        "exp_en": "Following the Urjit Patel Committee recommendations in 2014, the RBI switched from WPI to CPI (Combined) as its key gauge to guide policy interest rate decisions.",
        "exp_hi": "उर्जित पटेल समिति की संस्तुति पर 2014 से आरबीआई ने डब्ल्यूपीआई के स्थान पर सीपीआई (संयुक्त) को मौद्रिक नीति का मुख्य आधार बनाया क्योंकि यह आम उपभोक्ता पर पड़ने वाले प्रभाव को दर्शाता है।",
        "cue_en": "RBI inflation anchor = CPI (Combined).",
        "cue_hi": "आरबीआई का मुद्रास्फीति पैमाना = सीपीआई (CPI-Combined)।",
        "wrong_en": ["Primary inflation metric used by RBI.", "Former anchor, excludes services.", "Implicit broader measure, released quarterly.", "Measures industrial physical output."],
        "wrong_hi": ["आरबीआई का प्रमुख सूचकांक।", "पूर्व में प्रयुक्त होता था, सेवाएं शामिल नहीं।", "त्रैमासिक व्यापक सूचक।", "औद्योगिक उत्पादन का पैमाना।"]
    },
    {
        "name_en": "Types of Inflation: Demand-Pull, Cost-Push, Stagflation & Deflation",
        "name_hi": "मुद्रास्फीति के प्रकार: मांग-प्रेरित, लागत-जन्य, स्टैगफ्लेशन (मंदीयुक्त स्फीति) एवं अवस्फीति",
        "concepts_en": ["Demand-Pull Inflation: Aggregate demand exceeds aggregate supply ('too much money chasing too few goods')", "Cost-Push Inflation: Caused by supply-side shocks, rise in raw material/wage costs, oil price spikes", "Stagflation: Toxic combination of stagnant economic growth, high unemployment, and high inflation", "Phillips Curve inverse relationship between inflation and unemployment (breaks down during stagflation)"],
        "concepts_hi": ["मांग-प्रेरित मुद्रास्फीति (Demand-Pull): समग्र मांग का समग्र आपूर्ति से अधिक होना ('कम वस्तुओं के पीछे बहुत अधिक धन का भागना')", "लागत-जन्य मुद्रास्फीति (Cost-Push): उत्पादन लागत, मजदूरी या कच्चे माल (कच्चा तेल आदि) की कीमतों में वृद्धि से उत्पन्न", "स्टैगफ्लेशन (मंदीयुक्त स्फीति): आर्थिक संवृद्धि में ठहराव, उच्च बेरोजगारी और उच्च मुद्रास्फीति की एक साथ उपस्थिति", "फिलिप्स वक्र (Phillips Curve): मुद्रास्फीति और बेरोजगारी के बीच व्युत्क्रम संबंध (स्टैगफ्लेशन में यह संबंध टूट जाता है)"],
        "q_en": "An unusual economic condition characterized by stagnant economic growth, elevated unemployment, and simultaneously persistently high inflation is termed:",
        "q_hi": "अर्थव्यवस्था की वह असामान्य और चिंताजनक स्थिति क्या कहलाती है, जिसमें आर्थिक संवृद्धि में ठहराव, उच्च बेरोजगारी और साथ ही उच्च मुद्रास्फीति एक साथ विद्यमान होती है?",
        "options_en": ["Stagflation (स्टैगफ्लेशन / मंदीयुक्त स्फीति)", "Hyperinflation", "Deflation", "Reflation"],
        "options_hi": ["स्टैगफ्लेशन / मंदीयुक्त स्फीति (Stagflation)", "अति-मुद्रास्फीति (Hyperinflation)", "अवस्फीति (Deflation)", "रिफ्लेशन (Reflation)"],
        "correct_idx": 0,
        "exp_en": "Stagflation is an economic paradox combining stagnant output (slow GDP growth), high unemployment, and rising inflation, famously witnessed during the 1970s oil shocks.",
        "exp_hi": "स्टैगफ्लेशन (Stagnation + Inflation) मंदी और मुद्रास्फीति का ऐसा विषम मिश्रण है जिसमें अर्थव्यवस्था धीमी पड़ती है, बेरोजगारी बढ़ती है और कीमतें भी लगातार बढ़ती रहती हैं।",
        "cue_en": "Stagnant growth + High inflation + Unemployment = Stagflation.",
        "cue_hi": "धीमी संवृद्धि + उच्च बेरोजगारी + उच्च मुद्रास्फीति = स्टैगफ्लेशन।",
        "wrong_en": ["Correct term for the dual malaise.", "Extremely rapid out-of-control inflation.", "Sustained decrease in general price level.", "Stimulated recovery from recession."],
        "wrong_hi": ["दोहरी आर्थिक समस्या की सही परिभाषा।", "अनियंत्रित तीव्र गति से बढ़ती महंगाई।", "कीमतों में लगातार गिरावट।", "मंदी से उबरने हेतु कृत्रिम विस्तार।"]
    },
    {
        "name_en": "Human Development Index (HDI), Multidimensional Poverty Index (MPI) & Gini Coefficient",
        "name_hi": "मानव विकास सूचकांक (HDI), बहुआयामी गरीबी सूचकांक (MPI) एवं गिनी गुणांक",
        "concepts_en": ["HDI developed in 1990 by Mahbub ul Haq and Amartya Sen (published by UNDP); three dimensions: Health (Life Expectancy at birth), Education (Mean and Expected years of schooling), Standard of Living (GNI per capita PPP)", "Gini Coefficient measures income inequality (0 = perfect equality, 1 = perfect inequality); derived from Lorenz Curve", "Multidimensional Poverty Index (MPI) developed by OPHI and UNDP; evaluates 10 indicators across health, education, living standards; NITI Aayog publishes India National MPI"],
        "concepts_hi": ["मानव विकास सूचकांक (HDI): 1990 में महबूब उल हक और अमर्त्य सेन द्वारा विकसित (UNDP द्वारा प्रकाशित); तीन आयाम: स्वास्थ्य (जीवन प्रत्याशा), शिक्षा (स्कूली शिक्षा के औसत व अपेक्षित वर्ष), जीवन स्तर (प्रति व्यक्ति GNI)", "गिनी गुणांक (Gini Coefficient): आय असमानता का मापक (0 = पूर्ण समानता, 1 = पूर्ण असमानता); लोरेंज वक्र से निकाला जाता है", "बहुआयामी गरीबी सूचकांक (MPI): ऑक्सफोर्ड (OPHI) व UNDP द्वारा विकसित; स्वास्थ्य, शिक्षा व जीवन स्तर के 10 संकेतकों पर आधारित; नीति आयोग राष्ट्रीय MPI जारी करता है"],
        "q_en": "Which graphical curve depicts the cumulative percentage of national income earned by cumulative percentages of the population, used to calculate the Gini Coefficient?",
        "q_hi": "जनसंख्या के संचयी प्रतिशत और उसके द्वारा प्राप्त राष्ट्रीय आय के संचयी प्रतिशत के बीच संबंध दर्शाने वाला कौन सा वक्र 'गिनी गुणांक' की गणना का आधार बनता है?",
        "options_en": ["Lorenz Curve (लोरेंज वक्र)", "Phillips Curve", "Kuznets Curve", "Laffer Curve"],
        "options_hi": ["लोरेंज वक्र (Lorenz Curve)", "फिलिप्स वक्र (Phillips Curve)", "कुजनेट्स वक्र (Kuznets Curve)", "लाफर वक्र (Laffer Curve)"],
        "correct_idx": 0,
        "exp_en": "The Lorenz Curve (developed by Max O. Lorenz in 1905) graphically illustrates income distribution inequality, with the deviation from the 45-degree line of perfect equality yielding the Gini Coefficient.",
        "exp_hi": "लोरेंज वक्र आय या संपत्ति के वितरण की असमानता को रेखांकित करता है; पूर्ण समानता रेखा (45 डिग्री) और लोरेंज वक्र के बीच का क्षेत्रफल गिनी गुणांक निर्धारित करता है।",
        "cue_en": "Income inequality curve = Lorenz Curve (Gini Coefficient).",
        "cue_hi": "आय असमानता का वक्र = लोरेंज वक्र (गिनी गुणांक)।",
        "wrong_en": ["Illustrates income distribution.", "Relates inflation and unemployment.", "Relates economic growth and environmental inequality.", "Relates tax rates and tax revenue."],
        "wrong_hi": ["आय असमानता का चित्रण करता है।", "मुद्रास्फीति और बेरोजगारी का संबंध।", "संवृद्धि और असमानता का संबंध।", "कर की दर और कर राजस्व का संबंध।"]
    }
]

# S07-Cef3bcdf8 Reserve Bank of India, Monetary Policy & Banking Architecture (6 topics)
DATA["S07-Cef3bcdf8"] = [
    {
        "name_en": "Reserve Bank of India: History, Hilton Young Commission & Statutory Functions",
        "name_hi": "भारतीय रिज़र्व बैंक: इतिहास, हिल्टन यंग आयोग एवं सांविधिक कार्य",
        "concepts_en": ["Established on 1 April 1935 under Reserve Bank of India Act 1934 on recommendations of Hilton Young Commission (Royal Commission on Indian Currency and Finance 1926)", "Initially private shareholders' bank; nationalized on 1 January 1949", "Sir Osborne Smith first Governor (1935–37); C.D. Deshmukh first Indian Governor (1943–49)", "Central bank functions: Issuer of currency notes (except ₹1 coin/note issued by Ministry of Finance), banker to governments and banks, lender of last resort, manager of foreign exchange (FEMA 1999)"],
        "concepts_hi": ["हिल्टन यंग आयोग (1926) की सिफारिश पर आरबीआई अधिनियम 1934 के तहत 1 अप्रैल 1935 को स्थापना", "प्रारंभ में निजी बैंक था; 1 जनवरी 1949 को इसका राष्ट्रीयकरण हुआ", "सर ओसबोर्न स्मिथ पहले गवर्नर (1935-37); सी.डी. देशमुख पहले भारतीय गवर्नर (1943-49)", "आरबीआई के कार्य: नोट निर्गमन (₹1 के नोट/सिक्के को छोड़कर जो वित्त मंत्रालय जारी करता है), बैंकों का बैंक, सरकार का बैंकर, अंतिम ऋणदाता, विदेशी मुद्रा भंडार का प्रबंधक (FEMA)"],
        "q_en": "Who served as the very first Indian Governor of the Reserve Bank of India, appointed in 1943 during the British Raj and continuing past Independence?",
        "q_hi": "1943 में नियुक्त होने वाले तथा स्वतंत्रता के समय पद पर बने रहने वाले भारतीय रिज़र्व बैंक के पहले भारतीय गवर्नर कौन थे?",
        "options_en": ["Sir Chintaman Dwarakanath (C.D.) Deshmukh", "Sir Osborne Smith", "Sir James Braid Taylor", "Dr. Manmohan Singh"],
        "options_hi": ["सी.डी. देशमुख (Sir C.D. Deshmukh)", "सर ओसबोर्न स्मिथ", "सर जेम्स टेलर", "डॉ. मनमोहन सिंह"],
        "correct_idx": 0,
        "exp_en": "Sir C.D. Deshmukh was appointed Governor of the RBI on 11 August 1943, becoming the first Indian to hold the office and overseeing its nationalization in 1949.",
        "exp_hi": "सर सी.डी. देशमुख 1943 में आरबीआई के गवर्नर बने और वे पहले भारतीय थे जिन्होंने इस पद को संभाला। बाद में वे स्वतंत्र भारत के वित्त मंत्री भी बने।",
        "cue_en": "First Indian RBI Governor = C.D. Deshmukh.",
        "cue_hi": "आरबीआई के पहले भारतीय गवर्नर = सी.डी. देशमुख।",
        "wrong_en": ["First Indian RBI Governor.", "First overall Governor (British).", "Second Governor of RBI.", "Governor of RBI (1982–1985)."],
        "wrong_hi": ["आरबीआई के पहले भारतीय गवर्नर।", "आरबीआई के पहले ब्रिटिश गवर्नर।", "दूसरे गवर्नर।", "आरबीआई गवर्नर (1982-85)।"]
    },
    {
        "name_en": "Monetary Policy Committee (MPC) & Flexible Inflation Targeting Framework",
        "name_hi": "मौद्रिक नीति समिति (MPC) एवं लचीला मुद्रास्फीति लक्ष्यीकरण ढांचा (4% ± 2%)",
        "concepts_en": ["Statutory 6-member committee constituted under Section 45ZB of RBI Act 1934 (amended by Finance Act 2016)", "Composition: 3 RBI officials (Governor as ex-officio Chairperson, Deputy Governor in-charge of MP, one officer) + 3 external members appointed by Central Government for 4 years", "RBI Governor has casting vote in case of tie", "Statutory inflation target set by Government in consultation with RBI: 4% Consumer Price Index (CPI) with tolerance band of +/- 2% (2% to 6%)"],
        "concepts_hi": ["आरबीआई अधिनियम 1934 की धारा 45ZB के तहत गठित 6 सदस्यीय सांविधिक समिति", "संरचना: 3 आरबीआई अधिकारी (गवर्नर पदेन अध्यक्ष, डिप्टी गवर्नर, एक अन्य अधिकारी) + केंद्र सरकार द्वारा 4 वर्ष हेतु नियुक्त 3 बाहरी विशेषज्ञ", "मत बराबर होने की स्थिति में आरबीआई गवर्नर को निर्णायक मत (Casting Vote) देने का अधिकार", "वैधानिक मुद्रास्फीति लक्ष्य: उपभोक्ता मूल्य सूचकांक (CPI) 4% (± 2% का सहनशीलता बैंड, अर्थात 2% से 6%)"],
        "q_en": "What is the statutory medium-term Consumer Price Index (CPI) inflation target, along with its tolerance band, mandated for the Monetary Policy Committee (MPC) in India?",
        "q_hi": "भारत की मौद्रिक नीति समिति (MPC) के लिए सरकार द्वारा निर्धारित सांविधिक मध्यम-अवधि मुद्रास्फीति लक्ष्य और उसका सहनशीलता बैंड (Tolerance Band) क्या है?",
        "options_en": ["4% with a tolerance band of +/- 2% (2% to 6%)", "5% with a tolerance band of +/- 1%", "3% with a tolerance band of +/- 1.5%", "6% with a tolerance band of +/- 2%"],
        "options_hi": ["4% (सहनशीलता बैंड ± 2%, यानी 2% से 6%)", "5% (सहनशीलता बैंड ± 1%)", "3% (सहनशीलता बैंड ± 1.5%)", "6% (सहनशीलता बैंड ± 2%)"],
        "correct_idx": 0,
        "exp_en": "Under the Flexible Inflation Targeting framework, the inflation target is 4% CPI headline inflation with an upper tolerance limit of 6% and a lower tolerance limit of 2%.",
        "exp_hi": "भारत सरकार ने आरबीआई के परामर्श से मुद्रास्फीति का लक्ष्य 4% तय किया है, जिसकी ऊपरी सीमा 6% और निचली सीमा 2% निर्धारित है।",
        "cue_en": "Inflation Target = 4% +/- 2% (2% to 6%).",
        "cue_hi": "मुद्रास्फीति लक्ष्य = 4% ± 2% (2% से 6%)।",
        "wrong_en": ["Statutory inflation target.", "Incorrect parameters.", "Incorrect parameters.", "Upper limit, not base target."],
        "wrong_hi": ["सांविधिक मुद्रास्फीति लक्ष्य।", "गलत मान।", "गलत मान।", "यह ऊपरी सीमा है, आधार लक्ष्य नहीं।"]
    },
    {
        "name_en": "Quantitative Monetary Instruments: Repo Rate, Reverse Repo, SDF, MSF, CRR & SLR",
        "name_hi": "मात्रात्मक मौद्रिक उपकरण: रेपो दर, रिवर्स रेपो, एसडीएफ, एमएसएफ, सीआरआर एवं एसएलआर",
        "concepts_en": ["Repo Rate: Policy interest rate at which RBI lends short-term liquidity to commercial banks against government securities", "Standing Deposit Facility (SDF): Introduced in 2022 under Section 17 of RBI Act; allows RBI to absorb collateral-free liquidity (floor of Liquidity Adjustment Facility corridor)", "Marginal Standing Facility (MSF): Penal rate for emergency overnight borrowing (ceiling of LAF corridor)", "Cash Reserve Ratio (CRR): Percentage of Net Demand and Time Liabilities (NDTL) banks must park as cash with RBI", "Statutory Liquidity Ratio (SLR): Percentage of NDTL banks must maintain in liquid assets (gold, cash, approved government securities)"],
        "concepts_hi": ["रेपो दर (Repo Rate): वह नीतिगत ब्याज दर जिस पर आरबीआई प्रतिभूतियों के बदले वाणिज्यिक बैंकों को अल्पकालिक ऋण देता है", "स्टैंडिंग डिपॉजिट फैसिलिटी (SDF): 2022 में शुरू किया गया नया तंत्र; बिना किसी जमानत के बैंकों से अतिरिक्त तरलता सोखने का उपकरण (LAF का निचला स्तर)", "मार्जिनल स्टैंडिंग फैसिलिटी (MSF): आपातकालीन ओवरनाइट उधारी दर (LAF का ऊपरी स्तर)", "नकद आरक्षित अनुपात (CRR): बैंकों को अपनी कुल जमा (NDTL) का एक निश्चित प्रतिशत नकद रूप में आरबीआई के पास रखना होता है (इस पर कोई ब्याज नहीं मिलता)", "सांविधिक तरलता अनुपात (SLR): बैंकों को अपनी NDTL का एक निश्चित हिस्सा सरकारी प्रतिभूतियों, सोने या नकदी के रूप में अपने पास रखना अनिवार्य"],
        "q_en": "Which liquidity management instrument was operationalized by the RBI in April 2022 to absorb surplus liquidity from commercial banks without providing any government securities as collateral?",
        "q_hi": "आरबीआई ने अप्रैल 2022 में बैंकों से बिना किसी सरकारी प्रतिभूति को गिरवी रखे अतिरिक्त तरलता सोखने के लिए किस नए मौद्रिक उपकरण को लागू किया?",
        "options_en": ["Standing Deposit Facility (SDF / स्थायी जमा सुविधा)", "Marginal Standing Facility (MSF)", "Market Stabilization Scheme (MSS)", "Cash Reserve Ratio (CRR)"],
        "options_hi": ["स्थायी जमा सुविधा (Standing Deposit Facility - SDF)", "सीमांत स्थायी सुविधा (MSF)", "बाजार स्थिरीकरण योजना (MSS)", "नकद आरक्षित अनुपात (CRR)"],
        "correct_idx": 0,
        "exp_en": "The Standing Deposit Facility (SDF) was instituted in April 2022 under amended Section 17 of the RBI Act, strengthening liquidity absorption without tying up government bonds.",
        "exp_hi": "अप्रैल 2022 में आरबीआई ने एसडीएफ (SDF) लागू किया, जो बिना किसी जमानत (कोलैटरल) के बैंकों से अतिरिक्त नकदी जमा करने की सुविधा देता है और रिवर्स रेपो से अधिक प्रभावी है।",
        "cue_en": "Collateral-free absorption = Standing Deposit Facility (SDF).",
        "cue_hi": "बिना प्रतिभूति तरलता सोखने वाला उपकरण = SDF।",
        "wrong_en": ["Collateral-free absorption facility.", "Emergency borrowing window (ceiling).", "Bond-issuing sterilization tool.", "Unremunerated cash reserve."],
        "wrong_hi": ["बिना जमानत नकदी सोखने का नया उपकरण।", "आपातकालीन उधारी खिड़की।", "बांड आधारित योजना।", "नकद आरक्षित अनुपात।"]
    },
    {
        "name_en": "Commercial Banking Structure & Resolution of Non-Performing Assets (NPAs, IBC 2016)",
        "name_hi": "वाणिज्यिक बैंकिंग संरचना एवं गैर-निष्पादित परिसंपत्तियों (NPAs) का समाधान (IBC 2016)",
        "concepts_en": ["Scheduled Commercial Banks (included in Second Schedule of RBI Act 1934): Public Sector Banks, Private Sector Banks, Foreign Banks", "Non-Performing Asset (NPA): Loan where principal or interest overdue for more than 90 days (classified as Sub-standard, Doubtful, Loss assets)", "Insolvency and Bankruptcy Code (IBC) 2016: Unified framework for time-bound resolution (180 days + 90 days extension); National Company Law Tribunal (NCLT) is adjudicating authority for corporates", "National Asset Reconstruction Company Limited (NARCL / 'Bad Bank')"],
        "concepts_hi": ["अनुसूचित वाणिज्यिक बैंक (आरबीआई अधिनियम 1934 की दूसरी अनुसूची में शामिल): सार्वजनिक क्षेत्र के बैंक, निजी बैंक, विदेशी बैंक", "एनपीए (Non-Performing Asset): ऐसा ऋण जिस पर मूलधन या ब्याज 90 दिनों से अधिक समय तक बकाया रहे (वर्गीकरण: अवमानक, संदिग्ध, हानि परिसंपत्ति)", "दिवाला और दिवालियापन संहिता (IBC) 2016: 180 दिन (+90 दिन विस्तार) की समयसीमा में दिवाला समाधान; राष्ट्रीय कंपनी विधि अधिकरण (NCLT) न्यायिक प्राधिकरण", "नेशनल एसेट रिकंस्ट्रक्शन कंपनी लिमिटेड (NARCL / 'बैड बैंक')"],
        "q_en": "Under standard RBI prudential banking norms, an advance or loan account is classified as a Non-Performing Asset (NPA) when interest or principal remains overdue for a period exceeding:",
        "q_hi": "आरबीआई के मानक नियमों के अनुसार किसी ऋण खाते को गैर-निष्पादित परिसंपत्ति (NPA) तब घोषित किया जाता है जब उस पर मूलधन या ब्याज कितने दिनों से अधिक समय तक बकाया रहता है?",
        "options_en": ["90 days (90 दिन)", "60 days", "180 days", "365 days"],
        "options_hi": ["90 दिन (90 days)", "60 दिन", "180 दिन", "365 दिन"],
        "correct_idx": 0,
        "exp_en": "Under RBI guidelines, an asset becomes non-performing when it ceases to generate income, officially triggered when interest or installment remains overdue for more than 90 days.",
        "exp_hi": "आरबीआई के दिशा-निर्देशों के अनुसार यदि किसी वाणिज्यिक ऋण की किस्त या ब्याज लगातार 90 दिनों से अधिक समय तक अदा न किया जाए, तो उसे एनपीए (NPA) घोषित कर दिया जाता है।",
        "cue_en": "NPA classification threshold = Overdue > 90 days.",
        "cue_hi": "एनपीए घोषित करने की अवधि = 90 दिन से अधिक बकाया।",
        "wrong_en": ["Standard threshold for NPA classification.", "Special Mention Account-1 (SMA-1) threshold.", "Former threshold under older norms.", "Threshold for loss/doubtful classification."],
        "wrong_hi": ["एनपीए का मानक समय।", "एसएमए-1 (SMA-1) का समय।", "पुराना मानक।", "संदिग्ध परिसंपत्ति का पैमाना।"]
    },
    {
        "name_en": "Priority Sector Lending (PSL) & Regional Rural Banks (RRBs)",
        "name_hi": "प्राथमिकता प्राप्त क्षेत्र को ऋण (PSL) एवं क्षेत्रीय ग्रामीण बैंक (RRBs)",
        "concepts_en": ["PSL targets mandated by RBI: Domestic commercial banks must allocate 40% of Adjusted Net Bank Credit (ANBC) to priority sectors (Agriculture, MSMEs, Export Credit, Education, Housing, Social Infrastructure, Renewable Energy, Weaker Sections)", "RRBs and Small Finance Banks must allocate 75% of ANBC to priority sectors", "Regional Rural Banks (RRBs) established under RRB Act 1976 on recommendations of Narasimham Working Group (Prathama Bank first RRB, sponsored by Syndicate Bank on 2 Oct 1975)", "RRB shareholding structure: 50% Central Govt, 15% State Govt, 35% Sponsor Bank"],
        "concepts_hi": ["आरबीआई द्वारा अनिवार्य प्राथमिकता प्राप्त क्षेत्र ऋण (PSL): घरेलू वाणिज्यिक बैंकों को अपने समायोजित निवल बैंक ऋण (ANBC) का 40% प्राथमिक क्षेत्रों (कृषि, एमएसएमई, निर्यात, शिक्षा, आवास, नवीकरणीय ऊर्जा, कमजोर वर्ग) को देना अनिवार्य", "क्षेत्रीय ग्रामीण बैंकों (RRBs) और लघु वित्त बैंकों (SFBs) के लिए यह लक्ष्य 75% है", "क्षेत्रीय ग्रामीण बैंक (RRBs): नरसिम्हम कार्य समूह की सिफारिश पर 2 अक्टूबर 1975 को प्रथम बैंक (मुरादाबाद, सिंडिकेट बैंक द्वारा प्रायोजित) स्थापित", "आरआरबी का शेयरधारिता ढांचा: केंद्र सरकार 50%, राज्य सरकार 15%, प्रायोजक बैंक 35%"],
        "q_en": "In the ownership equity structure of Regional Rural Banks (RRBs) in India, what percentage of capital is held by the Central Government, State Government, and Sponsor Bank respectively?",
        "q_hi": "भारत में क्षेत्रीय ग्रामीण बैंकों (RRBs) की शेयर पूंजी में केंद्र सरकार, संबंधित राज्य सरकार और प्रायोजक बैंक (Sponsor Bank) की हिस्सेदारी का सही अनुपात क्या है?",
        "options_en": ["50% Central Government, 15% State Government, 35% Sponsor Bank", "40% Central Government, 30% State Government, 30% Sponsor Bank", "51% Central Government, 24% State Government, 25% Sponsor Bank", "33% each among the three entities"],
        "options_hi": ["50% केंद्र सरकार, 15% राज्य सरकार, 35% प्रायोजक बैंक", "40% केंद्र सरकार, 30% राज्य सरकार, 30% प्रायोजक बैंक", "51% केंद्र सरकार, 24% राज्य सरकार, 25% प्रायोजक बैंक", "तीनों की 33.3% बराबर हिस्सेदारी"],
        "correct_idx": 0,
        "exp_en": "Under the Regional Rural Banks Act 1976, the issued capital of an RRB is held by the Central Government (50%), the Sponsor Bank (35%), and the concerned State Government (15%).",
        "exp_hi": "आरआरबी अधिनियम 1976 के अनुसार प्रत्येक क्षेत्रीय ग्रामीण बैंक की पूंजी में केंद्र सरकार की 50%, प्रायोजक बैंक की 35% और राज्य सरकार की 15% हिस्सेदारी होती है।",
        "cue_en": "RRB ownership = 50 : 15 : 35 (Centre : State : Sponsor).",
        "cue_hi": "आरआरबी पूंजी अनुपात = 50 (केंद्र) : 15 (राज्य) : 35 (प्रायोजक बैंक)।",
        "wrong_en": ["Statutory equity ratio.", "Incorrect ratio.", "Incorrect ratio.", "Incorrect ratio."],
        "wrong_hi": ["कानूनी रूप से निर्धारित अनुपात।", "गलत अनुपात।", "गलत अनुपात।", "गलत अनुपात।"]
    },
    {
        "name_en": "Differentiated Banks: Small Finance Banks, Payments Banks & Financial Inclusion (PMJDY)",
        "name_hi": "विभेदित बैंक: लघु वित्त बैंक (SFBs), पेमेंट्स बैंक एवं वित्तीय समावेशन (PMJDY)",
        "concepts_en": ["Nachiket Mor Committee (2014) recommended niche/differentiated banking licenses", "Payments Banks: Can accept demand deposits up to ₹2 lakh per individual; CANNOT issue credit cards and CANNOT lend money (Airtel Payments Bank first)", "Small Finance Banks: Basic banking services of acceptance of deposits and lending to unserved sections (at least 50% loans must be up to ₹25 lakh)", "Pradhan Mantri Jan Dhan Yojana (PMJDY) launched 28 August 2014: Zero-balance basic savings accounts, RuPay debit card, overdraft facility"],
        "concepts_hi": ["नचिकेत मोर समिति (2014) की सिफारिश पर विभेदित बैंकिंग (Niche Banking) लाइसेंस की शुरुआत", "पेमेंट्स बैंक (Payments Banks): प्रति व्यक्ति ₹2 लाख तक मांग जमा स्वीकार कर सकते हैं; ऋण (लोन) नहीं दे सकते और क्रेडिट कार्ड जारी नहीं कर सकते (एयरटेल पेमेंट्स बैंक पहला बैंक था)", "लघु वित्त बैंक (Small Finance Banks): छोटे किसानों, सूक्ष्म उद्यमों को ऋण व जमा सुविधाएं (कम से कम 50% ऋण ₹25 लाख से कम होने चाहिए)", "प्रधानमंत्री जन धन योजना (PMJDY - 28 अगस्त 2014): जीरो बैलेंस खाता, रुपे डेबिट कार्ड, दुर्घटना बीमा व ओवरड्राफ्ट सुविधा"],
        "q_en": "Under RBI guidelines, which of the following activities is strictly prohibited for Payments Banks in India?",
        "q_hi": "आरबीआई के दिशा-निर्देशों के अनुसार भारत में पेमेंट्स बैंकों (Payments Banks) के लिए निम्नलिखित में से कौन सी गतिविधि पूर्णतः प्रतिबंधित है?",
        "options_en": ["Lending money and issuing credit cards (ऋण देना एवं क्रेडिट कार्ड जारी करना)", "Accepting demand deposits up to ₹2,00,000", "Issuing ATM / debit cards", "Offering remittance and utility payment services"],
        "options_hi": ["ऋण (लोन) देना एवं क्रेडिट कार्ड जारी करना", "₹2,00,000 तक की मांग जमा स्वीकार करना", "एटीएम / डेबिट कार्ड जारी करना", "धन प्रेषण और बिल भुगतान सेवाएं प्रदान करना"],
        "correct_idx": 0,
        "exp_en": "Payments banks can accept savings and current deposits up to ₹2 lakh and offer remittances/debit cards, but they are expressly prohibited from lending money or issuing credit cards.",
        "exp_hi": "पेमेंट्स बैंक बचत खाता खोल सकते हैं, डेबिट कार्ड दे सकते हैं, किंतु वे किसी भी प्रकार का कर्ज (लोन) नहीं दे सकते और न ही क्रेडिट कार्ड जारी कर सकते हैं।",
        "cue_en": "Payments Banks = NO loans, NO credit cards.",
        "cue_hi": "पेमेंट्स बैंक = न कोई लोन, न कोई क्रेडिट कार्ड।",
        "wrong_en": ["Strictly prohibited for payments banks.", "Permitted up to ₹2 lakh limit.", "Permitted (debit cards allowed).", "Permitted core function."],
        "wrong_hi": ["पेमेंट्स बैंकों के लिए पूर्णतः प्रतिबंधित।", "₹2 लाख तक जमा ले सकते हैं।", "डेबिट कार्ड जारी कर सकते हैं।", "यह उनका मुख्य कार्य है।"]
    }
]

# S07-Cd8d761ef Union Budget, Fiscal Policy, Taxation & GST (5 topics)
DATA["S07-Cd8d761ef"] = [
    {
        "name_en": "Union Budget Framework: Revenue Deficit, Fiscal Deficit & Primary Deficit",
        "name_hi": "केंद्रीय बजट की संरचना: राजस्व घाटा, राजकोषीय घाटा एवं प्राथमिक घाटा",
        "concepts_en": ["Article 112 refers to Union Budget as 'Annual Financial Statement'", "Consolidated Fund of India (Art 266(1)), Contingency Fund (Art 267), Public Account (Art 266(2))", "Fiscal Deficit = Total Expenditure - Total Receipts (excluding borrowings) = Total Government Borrowings", "Primary Deficit = Fiscal Deficit - Interest Payments", "Revenue Deficit = Revenue Expenditure - Revenue Receipts"],
        "concepts_hi": ["अनुच्छेद 112 में बजट को 'वार्षिक वित्तीय विवरण' (Annual Financial Statement) कहा गया है", "भारत की संचित निधि (अनुच्छेद 266(1)), आकस्मिकता निधि (अनुच्छेद 267), लोक लेखा (अनुच्छेद 266(2))", "राजकोषीय घाटा (Fiscal Deficit) = कुल व्यय - कुल प्राप्तियां (उधारियों को छोड़कर) = सरकार का कुल नया ऋण", "प्राथमिक घाटा (Primary Deficit) = राजकोषीय घाटा - ब्याज भुगतान", "राजस्व घाटा = राजस्व व्यय - राजस्व प्राप्तियां"],
        "q_en": "In public finance, what does the 'Primary Deficit' specifically measure when calculated from the Union Budget?",
        "q_hi": "सार्वजनिक वित्त में जब केंद्रीय बजट का 'प्राथमिक घाटा' (Primary Deficit) निकाला जाता है, तो वह वास्तव में क्या दर्शाता है?",
        "options_en": ["Fiscal Deficit minus Interest Payments (राजकोषीय घाटा ऋण ब्याज भुगतान)", "Total Revenue minus Total Expenditure", "Budget Deficit plus Market Borrowings", "Revenue Deficit minus Capital Outlay"],
        "options_hi": ["राजकोषीय घाटा - ब्याज भुगतान (Fiscal Deficit minus Interest Payments)", "कुल राजस्व - कुल व्यय", "बजट घाटा + बाजार उधारी", "राजस्व घाटा - पूंजीगत व्यय"],
        "correct_idx": 0,
        "exp_en": "Primary Deficit equals Fiscal Deficit minus interest liabilities paid on past borrowings, showing the government's borrowing needs purely for current year expenditures.",
        "exp_hi": "प्राथमिक घाटा = राजकोषीय घाटा - ब्याज अदायगी। यह दर्शाता है कि पुराने कर्जों के ब्याज को हटाकर सरकार को वर्तमान वित्तीय वर्ष के खर्चों के लिए कितना नया कर्ज लेना पड़ रहा है।",
        "cue_en": "Primary Deficit = Fiscal Deficit - Interest Payments.",
        "cue_hi": "प्राथमिक घाटा = राजकोषीय घाटा - ब्याज भुगतान।",
        "wrong_en": ["Formula for Primary Deficit.", "Measures overall surplus/deficit.", "Incorrect formulation.", "Incorrect formulation."],
        "wrong_hi": ["प्राथमिक घाटे का सही सूत्र।", "कुल घाटा दर्शाता है।", "गलत सूत्र।", "गलत सूत्र।"]
    },
    {
        "name_en": "Direct Taxation Architecture: Income Tax, Corporate Tax & STT",
        "name_hi": "प्रत्यक्ष कराधान प्रणाली: आयकर, निगम कर एवं प्रतिभूति लेनदेन कर (STT)",
        "concepts_en": ["Direct Tax: Incident and impact fall on same entity; administered by Central Board of Direct Taxes (CBDT)", "Corporate Tax (Corporation Tax): Levied on net income/profit of domestic and foreign companies", "Securities Transaction Tax (STT) levied on purchase/sale of listed equities and mutual fund units", "Progressive taxation principle"],
        "concepts_hi": ["प्रत्यक्ष कर (Direct Tax): कराघात (Impact) और करापात (Incidence) एक ही व्यक्ति/संस्था पर पड़ता है; केंद्रीय प्रत्यक्ष कर बोर्ड (CBDT) द्वारा प्रशासित", "निगम कर (Corporate Tax): कंपनियों के शुद्ध लाभ पर लगाया जाने वाला कर (केंद्र सरकार के राजस्व का प्रमुख स्रोत)", "प्रतिभूति लेनदेन कर (STT): शेयर बाजार में प्रतिभूतियों की खरीद-बिक्री पर लगाया जाता है", "प्रगामी कराधान प्रणाली (आय बढ़ने पर कर की दर बढ़ना)"],
        "q_en": "Which premier statutory authority, operating under the Department of Revenue in the Ministry of Finance, administers direct taxes in India?",
        "q_hi": "वित्त मंत्रालय के राजस्व विभाग के अंतर्गत भारत में प्रत्यक्ष करों (आयकर, निगम कर आदि) के प्रशासन और नीतियों हेतु कौन सा शीर्ष वैधानिक प्राधिकरण कार्यरत है?",
        "options_en": ["Central Board of Direct Taxes (CBDT)", "Central Board of Indirect Taxes and Customs (CBIC)", "Enforcement Directorate (ED)", "Insolvency and Bankruptcy Board of India (IBBI)"],
        "options_hi": ["केंद्रीय प्रत्यक्ष कर बोर्ड (CBDT)", "केंद्रीय अप्रत्यक्ष कर एवं सीमा शुल्क बोर्ड (CBIC)", "प्रवर्तन निदेशालय (ED)", "भारतीय दिवाला और शोधन अक्षमता बोर्ड (IBBI)"],
        "correct_idx": 0,
        "exp_en": "The Central Board of Direct Taxes (CBDT), constituted under the Central Boards of Revenue Act 1963, provides inputs for policy and planning and administers direct taxes.",
        "exp_hi": "केंद्रीय प्रत्यक्ष कर बोर्ड (CBDT) केंद्रीय राजस्व बोर्ड अधिनियम 1963 के तहत प्रत्यक्ष करों के निर्धारण, वसूली और नीति-निर्माण का कार्य करता है।",
        "cue_en": "Direct taxes authority = CBDT (Indirect = CBIC).",
        "cue_hi": "प्रत्यक्ष कर प्राधिकरण = सीबीडीटी (CBDT)।",
        "wrong_en": ["Administers direct taxes.", "Administers GST and customs (indirect taxes).", "Investigates money laundering and FEMA violations.", "Regulates bankruptcy professionals."],
        "wrong_hi": ["प्रत्यक्ष करों का शीर्ष बोर्ड।", "अप्रत्यक्ष करों व जीएसटी का बोर्ड।", "मनी लॉन्ड्रिंग की जांच करने वाला।", "दिवाला पेशेवरों का नियामक।"]
    },
    {
        "name_en": "Goods and Services Tax (GST): 101st Amendment, Structure & GST Council (Article 279A)",
        "name_hi": "वस्तु एवं सेवा कर (जीएसटी): 101वां संविधान संशोधन, कर स्लैब एवं जीएसटी परिषद (अनुच्छेद 279A)",
        "concepts_en": ["101st Constitutional Amendment Act 2016 introduced destination-based consumption tax from 1 July 2017 ('One Nation, One Tax')", "Subsumed 17 central and state indirect taxes (Excise, Service Tax, VAT, Octroi, Luxury Tax)", "Dual GST model: CGST, SGST/UTGST, and IGST (inter-state transactions)", "GST Council (Art 279A) chaired by Union Finance Minister; voting power: Centre has 1/3rd, all States combined have 2/3rd; decisions require 3/4th (75%) majority"],
        "concepts_hi": ["101वां संविधान संशोधन 2016: 1 जुलाई 2017 से गंतव्य-आधारित उपभोग कर प्रणाली लागू ('एक राष्ट्र, एक कर')", "17 केंद्रीय और राज्य स्तरीय अप्रत्यक्ष करों (उत्पाद शुल्क, सेवा कर, वैट, चुंगी आदि) का विलय", "दोहरा जीएसटी मॉडल: सीजीएसटी (CGST), एसजीएसटी (SGST) एवं आईजीएसटी (IGST - अंतर्राज्यीय व्यापार पर)", "जीएसटी परिषद (अनुच्छेद 279A): केंद्रीय वित्त मंत्री अध्यक्ष; मतदान भार: केंद्र का 1/3, सभी राज्यों का कुल 2/3; निर्णय हेतु 3/4 (75%) बहुमत अनिवार्य"],
        "q_en": "Under Article 279A of the Indian Constitution, what weighted voting share do the Central Government and State Governments possess in the GST Council respectively?",
        "q_hi": "संविधान के अनुच्छेद 279A के अनुसार जीएसटी परिषद (GST Council) में केंद्र सरकार और राज्य सरकारों का मतदान भार (Voting Weightage) क्रमशः कितना निर्धारित है?",
        "options_en": ["Central Government: One-third (1/3); State Governments: Two-thirds (2/3)", "Central Government: One-half (1/2); State Governments: One-half (1/2)", "Central Government: Two-thirds (2/3); State Governments: One-third (1/3)", "Equal vote for every member present and voting"],
        "options_hi": ["केंद्र सरकार: एक-तिहाई (1/3); राज्य सरकारें: दो-तिहाई (2/3)", "केंद्र सरकार: आधा (1/2); राज्य सरकारें: आधा (1/2)", "केंद्र सरकार: दो-तिहाई (2/3); राज्य सरकारें: एक-तिहाई (1/3)", "प्रत्येक उपस्थित सदस्य का समान एक मत"],
        "correct_idx": 0,
        "exp_en": "In the GST Council, the vote of the Central Government has a weightage of one-third of total votes cast, and the votes of all State Governments taken together have a weightage of two-thirds.",
        "exp_hi": "जीएसटी परिषद में केंद्र सरकार का मत-भार कुल मतों का 1/3 होता है और सभी राज्यों का संयुक्त मत-भार 2/3 होता है। किसी भी प्रस्ताव को पारित होने के लिए 75% (3/4) बहुमत चाहिए होता है।",
        "cue_en": "GST Council voting = Centre 1/3rd, States 2/3rd (75% to pass).",
        "cue_hi": "जीएसटी परिषद मतदान = केंद्र 1/3, राज्य 2/3 (पास होने के लिए 75%)।",
        "wrong_en": ["Statutory voting weightage.", "Incorrect proportion.", "Reversed proportion.", "Weighted system applies, not simple individual."],
        "wrong_hi": ["संवैधानिक रूप से सही भार।", "गलत अनुपात।", "उल्टा अनुपात।", "समान मत नहीं, भारित मत होता है।"]
    },
    {
        "name_en": "Fiscal Responsibility and Budget Management (FRBM) Act 2003 & NK Singh Committee",
        "name_hi": "राजकोषीय उत्तरदायित्व एवं बजट प्रबंधन (FRBM) अधिनियम 2003 व एन.के. सिंह समिति",
        "concepts_en": ["Enacted in 2003 to institutionalize financial discipline and reduce fiscal deficit", "Mandates presentation of Medium-Term Fiscal Policy Statement, Fiscal Policy Strategy Statement, and Macroeconomic Framework Statement with Budget", "NK Singh Review Committee (2017) recommended targeting Debt-to-GDP ratio (60% combined: 40% Centre, 20% States) and 3% Fiscal Deficit target", "Escape clause allows fiscal deviation up to 0.5% of GDP for national security, war, calamities, structural collapse"],
        "concepts_hi": ["2003 में वित्तीय अनुशासन सुनिश्चित करने और राजकोषीय घाटे को नियंत्रित करने हेतु पारित", "बजट के साथ मध्यम-अवधि राजकोषीय नीति विवरण, राजकोषीय नीति रणनीति विवरण और व्यापक-आर्थिक रूपरेखा विवरण प्रस्तुत करना अनिवार्य", "एन.के. सिंह समिति (2017) ने ऋण-जीडीपी अनुपात 60% (केंद्र 40%, राज्य 20%) और 3% राजकोषीय घाटे का लक्ष्य सुझाया", "'एस्केप क्लॉज' (Escape Clause): युद्ध, राष्ट्रीय सुरक्षा, गंभीर प्राकृतिक आपदा या संरचनात्मक सुधारों के समय 0.5% तक विचलन की अनुमति"],
        "q_en": "What combined public Debt-to-GDP ratio (for Centre and States combined) was recommended as the target by the N.K. Singh FRBM Review Committee in 2017?",
        "q_hi": "2017 में एन.के. सिंह की अध्यक्षता वाली एफआरबीएम (FRBM) समीक्षा समिति ने केंद्र और राज्यों के लिए संयुक्त रूप से कितने प्रतिशत ऋण-जीडीपी अनुपात (Debt-to-GDP ratio) का लक्ष्य सुझाया था?",
        "options_en": ["60% of GDP (40% for Centre and 20% for States)", "50% of GDP (30% Centre and 20% States)", "70% of GDP (45% Centre and 25% States)", "40% of GDP (25% Centre and 15% States)"],
        "options_hi": ["जीडीपी का 60% (केंद्र हेतु 40% और राज्यों हेतु 20%)", "जीडीपी का 50%", "जीडीपी का 70%", "जीडीपी का 40%"],
        "correct_idx": 0,
        "exp_en": "The N.K. Singh Committee recommended a debt-to-GDP ratio of 60% for the general government by 2022-23, comprising 40% for the Central Government and 20% for State Governments.",
        "exp_hi": "एन.के. सिंह समिति ने राजकोषीय स्थिरता के लिए कुल सार्वजनिक ऋण को जीडीपी के 60% तक सीमित करने की सिफारिश की थी (केंद्र सरकार 40% और राज्य सरकारें 20%)।",
        "cue_en": "FRBM Debt target = 60% of GDP (40% Centre + 20% States).",
        "cue_hi": "एफआरबीएम ऋण लक्ष्य = 60% (40% केंद्र + 20% राज्य)।",
        "wrong_en": ["Recommended combined debt target.", "Incorrect target.", "Current elevated level, not target.", "Incorrect target."],
        "wrong_hi": ["समिति द्वारा अनुशंसित लक्ष्य।", "गलत अनुपात।", "वर्तमान में उच्च स्तर, लक्ष्य नहीं।", "गलत मान।"]
    },
    {
        "name_en": "External Sector: Balance of Payments, Current Account Deficit & Foreign Direct Investment (FDI)",
        "name_hi": "बाह्य क्षेत्र: भुगतान संतुलन (BoP), चालू खाता घाटा (CAD) एवं प्रत्यक्ष विदेशी निवेश (FDI)",
        "concepts_en": ["Balance of Payments (BoP) systematically records all economic transactions between residents and rest of the world (Current Account + Capital Account + Errors/Omissions = Change in Forex)", "Current Account covers trade in goods (merchandise), trade in services (invisibles), and unilateral transfers (remittances)", "Current Account Deficit (CAD) occurs when value of imports of goods/services exceeds exports", "Foreign Direct Investment (FDI - long term, active management) vs Foreign Portfolio Investment (FPI - hot money in secondary securities market)"],
        "concepts_hi": ["भुगतान संतुलन (BoP): किसी देश के निवासियों और शेष विश्व के बीच एक वर्ष के समस्त आर्थिक लेन-देन का व्यवस्थित लेखा-जोखा (चालू खाता + पूंजी खाता)", "चालू खाता (Current Account): दृश्य व्यापार (वस्तुएं), अदृश्य व्यापार (सेवाएं) तथा एकतरफा अंतरण (विदेशों से भेजा गया धन/रेमिटेंस)", "चालू खाता घाटा (CAD): जब वस्तुओं व सेवाओं का आयात उनके निर्यात से अधिक हो जाता है", "प्रत्यक्ष विदेशी निवेश (FDI - दीर्घकालिक, परिसंपत्तियों में सीधा निवेश) बनाम विदेशी पोर्टफोलियो निवेश (FPI - शेयर बाजार में अल्पकालिक निवेश / हॉट मनी)"],
        "q_en": "Remittances sent home by non-resident Indian citizens working abroad are categorized under which component of India's Balance of Payments (BoP)?",
        "q_hi": "विदेशों में काम करने वाले अनिवासी भारतीयों (NRIs) द्वारा स्वदेश भेजी जाने वाली धनराशि (Remittances) को भारत के भुगतान संतुलन (BoP) के किस खाते में दर्ज किया जाता है?",
        "options_en": ["Current Account - Invisibles (Unilateral Transfers)", "Capital Account - External Commercial Borrowings", "Capital Account - Foreign Direct Investment", "Financial Derivatives Account"],
        "options_hi": ["चालू खाता - अदृश्य मदें (एकतरफा अंतरण / Unilateral Transfers)", "पूंजी खाता - विदेशी वाणिज्यिक उधारी (ECB)", "पूंजी खाता - प्रत्यक्ष विदेशी निवेश (FDI)", "वित्तीय डेरिवेटिव खाता"],
        "correct_idx": 0,
        "exp_en": "Private remittances from abroad represent unrequited or unilateral transfers, classified under the invisibles component of the Current Account in the Balance of Payments.",
        "exp_hi": "विदेशी कामगारों द्वारा घर भेजा गया धन (Remittances) चालू खाते की अदृश्य मदों के अंतर्गत 'एकतरफा अंतरण' (बिना किसी सेवा या वस्तु की प्रतिपूर्ति के) के रूप में दर्ज होता है।",
        "cue_en": "Remittances = Current Account (Invisibles / Unilateral Transfers).",
        "cue_hi": "रेमिटेंस (विदेशी धन प्रेषण) = चालू खाता (अदृश्य / अंतरण)।",
        "wrong_en": ["Correct classification in BoP.", "Commercial loan liability in Capital Account.", "Equity investment in Capital Account.", "Derivatives trading account."],
        "wrong_hi": ["भुगतान संतुलन में सही प्रविष्टि।", "पूंजी खाते का ऋण।", "पूंजी खाते का निवेश।", "डेरिवेटिव खाता।"]
    }
]

print("Loaded S07 successfully")
