# build_curriculum/group1_s03.py
# S03: Ancient Indian History & Archaeology (30 topics across 5 chapters)

DATA = {}

# S03-Cf57dd5c3 Prehistoric Periods & Indus Valley Civilization (6 topics)
DATA["S03-Cf57dd5c3"] = [
    {
        "name_en": "Prehistoric Rock Art & Paleolithic to Neolithic Sites (Bhimbetka, Burzahom)",
        "name_hi": "प्रागैतिहासिक शैलचित्र एवं पुरापाषाण से नवपाषाण स्थल (भीमबेटका, बुर्जहोम)",
        "concepts_en": ["Bhimbetka rock shelters (Madhya Pradesh, V.S. Wakankar 1957)", "Burzahom pit dwellings and dog burials in Kashmir", "Mehrgarh early agricultural settlement in Balochistan", "Acheulian handaxes and microliths"],
        "concepts_hi": ["भीमबेटका शैलचित्र (मध्य प्रदेश, वी.एस. वाकणकर 1957)", "कश्मीर में बुर्जहोम के गर्त आवास (Pit-dwellings) व श्वान शवाधान", "मेहरगढ़ (बलूचिस्तान) में प्राचीनतम कृषि साक्ष्य", "एश्यूलियन कुल्हाड़ियां व माइक्रोलिथ"],
        "q_en": "The famous UNESCO World Heritage site of Bhimbetka, renowned for its prehistoric rock shelters and cave paintings, is located in which Indian state?",
        "q_hi": "प्रागैतिहासिक शैलचित्रों एवं गुफाओं के लिए प्रसिद्ध यूनेस्को विश्व धरोहर स्थल 'भीमबेटका' भारत के किस राज्य में स्थित है?",
        "options_en": ["Madhya Pradesh (Raisen district)", "Rajasthan", "Maharashtra", "Uttar Pradesh"],
        "options_hi": ["मध्य प्रदेश (रायसेन जिला)", "राजस्थान", "महाराष्ट्र", "उत्तर प्रदेश"],
        "correct_idx": 0,
        "exp_en": "Bhimbetka rock shelters in Raisen district of Madhya Pradesh exhibit the earliest traces of human life on the Indian subcontinent with paintings from Upper Paleolithic to Mesolithic periods.",
        "exp_hi": "मध्य प्रदेश के रायसेन जिले में विंध्य पहाड़ियों की तलहटी में स्थित भीमबेटका के शैलचित्र उच्च पुरापाषाण और मध्यपाषाण काल के मानव जीवन को दर्शाते हैं।",
        "cue_en": "Bhimbetka = Madhya Pradesh (discovered by V.S. Wakankar).",
        "cue_hi": "भीमबेटका = मध्य प्रदेश (वाकणकर द्वारा 1957 में खोजा गया)।",
        "wrong_en": ["Raisen district, MP.", "Known for Bagor and Kalibangan.", "Known for Ajanta and Ellora.", "Known for Belan valley."],
        "wrong_hi": ["मध्य प्रदेश का रायसेन जिला।", "बागोर और कालीबंगा हेतु प्रसिद्ध।", "अजंता और एलोरा हेतु प्रसिद्ध।", "बेलन घाटी हेतु प्रसिद्ध।"]
    },
    {
        "name_en": "Indus Valley Civilization: Urban Planning, Great Bath & Drainage System",
        "name_hi": "सिंधु घाटी सभ्यता: नगर नियोजन, विशाल स्नानागार एवं जल निकासी",
        "concepts_en": ["Grid layout (Chessboard system)", "Citadel and Lower Town division", "Burnt bricks with standardized 4:2:1 ratio", "Covered underground drainage with inspection holes"],
        "concepts_hi": ["ग्रिड प्रणाली (चेसबोर्ड पैटर्न) पर आधारित सड़कें", "दुर्ग (Citadel) और निचला नगर का विभाजन", "4:2:1 अनुपात की पकी ईंटों का प्रयोग", "ढकी हुई भूमिगत जल निकासी प्रणाली"],
        "q_en": "The standardized ratio of length, breadth, and thickness observed in burnt bricks of the Mature Harappan period is:",
        "q_hi": "परिपक्व हड़प्पा काल में प्रयुक्त पकी ईंटों की लंबाई, चौड़ाई और मोटाई का मानक अनुपात क्या था?",
        "options_en": ["4 : 2 : 1", "3 : 2 : 1", "5 : 3 : 1", "4 : 3 : 2"],
        "options_hi": ["4 : 2 : 1", "3 : 2 : 1", "5 : 3 : 1", "4 : 3 : 2"],
        "correct_idx": 0,
        "exp_en": "Harappan bricks across major sites maintained a highly standardized dimensional ratio of 4:2:1 (length : breadth : thickness), typically 28 × 14 × 7 cm.",
        "exp_hi": "हड़प्पा सभ्यता के विभिन्न स्थलों पर ईंटों का एक अत्यधिक मानकीकृत अनुपात 4:2:1 (लंबाई : चौड़ाई : मोटाई) पाया गया है।",
        "cue_en": "Harappan brick ratio = 4:2:1.",
        "cue_hi": "हड़प्पा की ईंटों का अनुपात = 4 : 2 : 1।",
        "wrong_en": ["Standard Harappan ratio.", "Incorrect proportion.", "Incorrect proportion.", "Incorrect proportion."],
        "wrong_hi": ["हड़प्पा का मानक अनुपात।", "गलत अनुपात।", "गलत अनुपात।", "गलत अनुपात।"]
    },
    {
        "name_en": "Mohenjo-daro & Harappa: Great Bath, Granaries & Bronze Artifacts",
        "name_hi": "मोहनजोदड़ो एवं हड़प्पा: विशाल स्नानागार, अन्नागार एवं कांस्य शिल्प",
        "concepts_en": ["Great Bath at Mohenjo-daro lined with bitumen/gypsum", "Bronze Dancing Girl made with lost-wax technique (cire perdue)", "Pashupati seal and Priest-King bust", "R.D. Banerjee discovered Mohenjo-daro (1922)"],
        "concepts_hi": ["मोहनजोदड़ो का विशाल स्नानागार जिप्सम व बिटुमेन से जलरोधी", "लुप्त मोम तकनीक (लॉस्ट-वैक्स) से निर्मित कांस्य नर्तकी", "पशुपति मुहर एवं दाढ़ी वाले पुरोहित राजा की मूर्ति", "आर.डी. बनर्जी द्वारा 1922 में मोहनजोदड़ो की खोज"],
        "q_en": "The famous bronze figurine of the 'Dancing Girl' was unearthed from which Indus Valley site?",
        "q_hi": "सिंधु घाटी सभ्यता की प्रसिद्ध कांस्य प्रतिमा 'नर्तकी' (Dancing Girl) किस स्थल से प्राप्त हुई थी?",
        "options_en": ["Mohenjo-daro (मोहनजोदड़ो)", "Harappa", "Kalibangan", "Lothal"],
        "options_hi": ["मोहनजोदड़ो (Mohenjo-daro)", "हड़प्पा", "कालीबंगा", "लोथल"],
        "correct_idx": 0,
        "exp_en": "The bronze 'Dancing Girl' was discovered in 1926 by Ernest Mackay at Mohenjo-daro in Sindh, Pakistan.",
        "exp_hi": "कांस्य से बनी नर्तकी की प्रसिद्ध मूर्ति 1926 में अर्नेस्ट मैके द्वारा सिंध में मोहनजोदड़ो से खोजी गई थी।",
        "cue_en": "Dancing Girl & Great Bath = Mohenjo-daro.",
        "cue_hi": "नर्तकी की कांस्य मूर्ति व विशाल स्नानागार = मोहनजोदड़ो।",
        "wrong_en": ["Unearthed at Mohenjo-daro.", "Yielded red sandstone torso.", "Yielded plowed fields and fire altars.", "Yielded dockyard and bead factory."],
        "wrong_hi": ["मोहनजोदड़ो से प्राप्त।", "हड़प्पा से लाल बलुआ पत्थर का धड़ मिला।", "कालीबंगा से जुते हुए खेत मिले।", "लोथल से गोदीबाड़ा मिला।"]
    },
    {
        "name_en": "Lothal, Kalibangan, Dholavira & Rakhigarhi: Special Architectural Features",
        "name_hi": "लोथल, कालीबंगा, धोलावीरा एवं राखीगढ़ी: विशिष्ट पुरातात्विक विशेषताएं",
        "concepts_en": ["Lothal dockyard on Bhogava river in Gujarat", "Kalibangan ploughed field and fire altars in Rajasthan", "Dholavira tripartite city layout and water harvesting reservoirs", "Rakhigarhi largest Harappan site in Haryana"],
        "concepts_hi": ["गुजरात में भोगवा नदी पर लोथल का गोदीबाड़ा (डॉकयार्ड)", "राजस्थान के कालीबंगा में जुते हुए खेत व अग्निकुंड", "धोलावीरा का त्रि-स्तरीय नगर नियोजन व जल संचयन प्रणाली", "हरियाणा में राखीगढ़ी सबसे बड़ा हड़प्पा स्थल"],
        "q_en": "Which Harappan city in Gujarat features a unique tripartite division (Citadel, Middle Town, Lower Town) and a sophisticated water reservoir system?",
        "q_hi": "गुजरात का कौन सा हड़प्पा कालीन नगर तीन भागों (दुर्ग, मध्यम नगर एवं निचला नगर) में विभाजित था तथा अपनी उत्कृष्ट जल संचयन प्रणाली के लिए जाना जाता है?",
        "options_en": ["Dholavira (धोलावीरा)", "Lothal", "Surkotada", "Banawali"],
        "options_hi": ["धोलावीरा (Dholavira)", "लोथल", "सुरकोटदा", "बनावली"],
        "correct_idx": 0,
        "exp_en": "Dholavira in the Rann of Kutch (Gujarat) is unique for its three distinct fortified sections and an elaborate network of water management reservoirs.",
        "exp_hi": "कच्छ के रण (गुजरात) में स्थित धोलावीरा तीन भागों (दुर्ग, मध्यम नगर, निचला नगर) में बंटा था और इसमें विशाल शैलकृत जलाशय स्थित थे।",
        "cue_en": "Dholavira = 3 parts + Water reservoirs.",
        "cue_hi": "धोलावीरा = 3 नगर भाग + विशाल जलाशय।",
        "wrong_en": ["Tripartite layout and reservoirs.", "Famous for dockyard, not 3-tier.", "Known for horse bone remains.", "Known for clay plough replica."],
        "wrong_hi": ["तीन भागों में बंटा नगर और जल प्रणाली।", "गोदीबाड़ा हेतु प्रसिद्ध, 3 भागों में नहीं।", "घोड़े की हड्डियों के अवशेष मिले।", "मिट्टी का बना हल मिला।"]
    },
    {
        "name_en": "Harappan Script, Seals, Weights, Measures & Craft Production",
        "name_hi": "हड़प्पा लिपि, मुहरें, बांट, माप एवं शिल्प उत्पादन",
        "concepts_en": ["Steatite seals featuring unicorn, bull, elephant", "Boustrophedon script (undeciphered pictographic)", "Chert binary and decimal weight system (1:2:4:8:16:32...)", "Chanhudaro center for bead making"],
        "concepts_hi": ["सेलखड़ी (स्टीएटाइट) की मुहरें जिन पर एकश्रृंगी, बैल आदि अंकित", "बोस्ट्रोफेडन लिपि (अपठित चित्रात्मक)", "चर्ट पत्थर के द्विआधारी और दशमलव बांट (1:2:4:8:16:32...)", "चन्हूदड़ो मनका बनाने का प्रमुख शिल्प केंद्र"],
        "q_en": "The writing system of the Indus Valley Civilization was primarily written in which style, alternating right-to-left and left-to-right in successive lines?",
        "q_hi": "सिंधु घाटी सभ्यता की चित्रात्मक लिपि मुख्य रूप से किस शैली में लिखी जाती थी, जो क्रमिक पंक्तियों में दाएं से बाएं और फिर बाएं से दाएं चलती थी?",
        "options_en": ["Boustrophedon (बोस्ट्रोफेडन शैली)", "Brahmi script", "Kharosthi script", "Cuneiform script"],
        "options_hi": ["बोस्ट्रोफेडन शैली (Boustrophedon)", "ब्राह्मी लिपि", "खरोष्ठी लिपि", "कीलाक्षर लिपि (Cuneiform)"],
        "correct_idx": 0,
        "exp_en": "Harappan inscriptions were written in Boustrophedon style (as the ox turns during plowing), starting right to left and returning left to right.",
        "exp_hi": "हड़प्पा की लिपि मुख्य रूप से बोस्ट्रोफेडन (सर्पिलाकार) शैली में लिखी जाती थी, जिसमें पहली पंक्ति दाएं से बाएं और दूसरी पंक्ति बाएं से दाएं लिखी जाती थी।",
        "cue_en": "Boustrophedon = Harappan bidirectional script.",
        "cue_hi": "बोस्ट्रोफेडन = दाएं-बाएं-दाएं क्रमिक लेखन शैली।",
        "wrong_en": ["Correct bidirectional style.", "Ancient Indian script written left-to-right.", "Northwestern script written right-to-left.", "Mesopotamian wedge-shaped writing."],
        "wrong_hi": ["हड़प्पा की क्रमिक लेखन शैली।", "बाएं से दाएं लिखी जाने वाली भारतीय लिपि।", "दाएं से बाएं लिखी जाने वाली पश्चिमोत्तर लिपि।", "मेसोपोटामिया की कीलाकार लिपि।"]
    },
    {
        "name_en": "Decline Theories of the Indus Valley Civilization",
        "name_hi": "सिंधु घाटी सभ्यता के पतन के सिद्धांत",
        "concepts_en": ["Aryan invasion theory (Mortimer Wheeler, now rejected)", "Ecological degradation & drying of Saraswati/Ghaggar-Hakra", "Tectonic disturbances and course changes of Indus", "Late Harappan phase (c. 1900–1300 BCE)"],
        "concepts_hi": ["आर्य आक्रमण सिद्धांत (मार्टिमर व्हीलर, अब अमान्य)", "पारिस्थितिक असंतुलन एवं घग्गर-हाकरा/सरस्वती नदी का सूखना", "विवर्तनिक हलचलें व सिंधु नदी के मार्ग में परिवर्तन", "उत्तर हड़प्पा काल (लगभग 1900-1300 ई.पू.)"],
        "q_en": "Which British archaeologist famously proposed the 'Aryan Invasion Theory' for the fall of the Indus Civilization, citing Rigvedic Indra as 'Purandara'?",
        "q_hi": "किस ब्रिटिश पुरातत्वविद् ने ऋग्वेद में इंद्र को 'पुरंदर' कहे जाने के आधार पर हड़प्पा सभ्यता के पतन के लिए 'आर्य आक्रमण सिद्धांत' का प्रतिपादन किया था?",
        "options_en": ["Sir Mortimer Wheeler", "John Marshall", "Alexander Cunningham", "George Dales"],
        "options_hi": ["सर मार्टिमर व्हीलर (Sir Mortimer Wheeler)", "जॉन मार्शल", "अलेक्जेंडर कनिंघम", "जॉर्ज डेल्स"],
        "correct_idx": 0,
        "exp_en": "Sir Mortimer Wheeler in 1946 proposed the theory that Aryan invaders destroyed Harappan cities, citing skeletal finds at Mohenjo-daro, a theory now refuted by modern archaeological evidence.",
        "exp_hi": "मार्टिमर व्हीलर ने 1946 में आर्य आक्रमण का सिद्धांत दिया था, जिसे आधुनिक पुरातात्विक अनुसंधानों द्वारा खारिज कर दिया गया है।",
        "cue_en": "Mortimer Wheeler = Proposed Aryan invasion decline theory.",
        "cue_hi": "मार्टिमर व्हीलर = आर्य आक्रमण सिद्धांत।",
        "wrong_en": ["Proposed the Aryan invasion thesis.", "Announced discovery of IVC in 1924.", "First Director-General of ASI.", "Argued against massacres."],
        "wrong_hi": ["आर्य आक्रमण सिद्धांत का प्रतिपादक।", "1924 में सभ्यता की खोज की आधिकारिक घोषणा की।", "एएसआई के पहले महानिदेशक।", "आक्रमण सिद्धांत का खंडन करने वाले।"]
    }
]

# S03-C6d03bcc2 Vedic Period, Upanishads & Mahajanapadas (6 topics)
DATA["S03-C6d03bcc2"] = [
    {
        "name_en": "Rigvedic Society, Tribes (Janas), Sabha & Samiti",
        "name_hi": "ऋग्वैदिक समाज, जन (कबीले), सभा एवं समिति",
        "concepts_en": ["Pastoral society centered on cattle (Gavishthi)", "Tribal assemblies: Sabha (elders) and Samiti (general folk)", "Rajan (tribal chieftain) aided by Purohita and Senani", "Battle of the Ten Kings (Dasarajna) on Parushni river"],
        "concepts_hi": ["गोधन पर आधारित पशुचारी समाज (गविष्टि)", "कबीलाई संस्थाएं: सभा (प्रबुद्ध जन) और समिति (आम जन)", "राजन (जन का मुखिया) पुरोहित व सेनानी की सहायता से शासित", "परुष्णी (रावी) नदी तट पर दशराज्ञ युद्ध"],
        "q_en": "The famous 'Battle of the Ten Kings' (Dasarajna Yuddha) mentioned in the Seventh Mandala of the Rigveda was fought on the banks of which river?",
        "q_hi": "ऋग्वेद के सातवें मंडल में वर्णित प्रसिद्ध 'दशराज्ञ युद्ध' (दस राजाओं का युद्ध) किस नदी के तट पर लड़ा गया था?",
        "options_en": ["Parushni (modern Ravi river)", "Asikni (Chenab)", "Vitasta (Jhelum)", "Shatudri (Sutlej)"],
        "options_hi": ["परुष्णी (आधुनिक रावी नदी)", "असिक्नी (चेनाब)", "वितस्ता (झेलम)", "शतद्रु (सतलुज)"],
        "correct_idx": 0,
        "exp_en": "The Dasarajna battle was fought on the banks of Parushni (modern Ravi), where King Sudas of the Bharata tribe defeated a confederacy of ten tribes.",
        "exp_hi": "दशराज्ञ युद्ध परुष्णी (रावी) नदी के तट पर लड़ा गया था, जिसमें भारत जन के राजा सुदास ने दस राजाओं के संघ को पराजित किया था।",
        "cue_en": "Dasarajna = Parushni (Ravi).",
        "cue_hi": "दशराज्ञ युद्ध = परुष्णी (रावी नदी)।",
        "wrong_en": ["Site of the Ten Kings Battle.", "Vedic name for Chenab.", "Vedic name for Jhelum.", "Vedic name for Sutlej."],
        "wrong_hi": ["दशराज्ञ युद्ध का स्थल।", "चेनाब का वैदिक नाम।", "झेलम का वैदिक नाम।", "सतलुज का वैदिक नाम।"]
    },
    {
        "name_en": "Later Vedic Period: Painted Grey Ware, Varna System & Sacrificial Rituals",
        "name_hi": "उत्तर वैदिक काल: चित्रित धूसर मृदभांड, वर्ण व्यवस्था एवं महायज्ञ",
        "concepts_en": ["Painted Grey Ware (PGW) culture & iron implements (Syama Ayas)", "Rigid fourfold Varna hierarchy (Brahmana, Kshatriya, Vaishya, Shudra)", "Ashramas (Brahmacharya, Grihastha, Vanaprastha, Sannyasa)", "Royal sacrifices: Ashvamedha, Rajasuya, Vajapeya"],
        "concepts_hi": ["चित्रित धूसर मृदभांड (PGW) एवं लोहे का प्रयोग (श्याम अयस)", "जन्म आधारित चार वर्ण (ब्राह्मण, क्षत्रिय, वैश्य, शूद्र)", "चार आश्रम (ब्रह्मचर्य, गृहस्थ, वानप्रस्थ, संन्यास)", "महायज्ञ: अश्वमेध, राजसूय, वाजपेय"],
        "q_en": "In which ancient text do we find the earliest mention of the four Ashramas (stages of life) together?",
        "q_hi": "चारों आश्रमों (ब्रह्मचर्य, गृहस्थ, वानप्रस्थ, संन्यास) का सर्वप्रथम संयुक्त उल्लेख किस प्राचीन उपनिषद में मिलता है?",
        "options_en": ["Jabala Upanishad (जाबाल उपनिषद)", "Chandogya Upanishad", "Mundaka Upanishad", "Kathopanishad"],
        "options_hi": ["जाबाल उपनिषद (Jabala Upanishad)", "छांदोग्य उपनिषद", "मुंडक उपनिषद", "कठोपनिषद"],
        "correct_idx": 0,
        "exp_en": "The Jabala Upanishad provides the earliest explicit reference to all four Ashramas together. Chandogya Upanishad mentions only the first three.",
        "exp_hi": "जाबाल उपनिषद में पहली बार चारों आश्रमों का एक साथ स्पष्ट उल्लेख मिलता है। छांदोग्य उपनिषद में केवल तीन आश्रमों का उल्लेख है।",
        "cue_en": "4 Ashramas = Jabala Upanishad.",
        "cue_hi": "चारों आश्रम = जाबाल उपनिषद।",
        "wrong_en": ["Mentions all four Ashramas.", "Mentions only first three Ashramas.", "Contains Satyameva Jayate.", "Contains Nachiketa-Yama dialogue."],
        "wrong_hi": ["चारों आश्रमों का उल्लेख।", "केवल तीन आश्रमों का उल्लेख।", "सत्यमेव जयते का स्रोत।", "नचिकेता-यम संवाद का स्रोत।"]
    },
    {
        "name_en": "Vedic Literature: Four Vedas, Brahmanas, Aranyakas & Upanishads",
        "name_hi": "वैदिक साहित्य: चार वेद, ब्राह्मण ग्रंथ, आरण्यक एवं उपनिषद (वेदांत)",
        "concepts_en": ["Rigveda (1,028 suktas), Samaveda (music), Yajurveda (rituals), Atharvaveda (charms)", "Brahmanas explain ritual mechanics (Satapatha Brahmana)", "Aranyakas forest treatises", "108 Upanishads develop Vedanta philosophy (Brahman & Atman)"],
        "concepts_hi": ["ऋग्वेद (1028 सूक्त), सामवेद (संगीत), यजुर्वेद (कर्मकांड), अथर्ववेद (औषधि व मंत्र)", "ब्राह्मण ग्रंथ कर्मकांड की व्याख्या करते हैं (शतपथ ब्राह्मण)", "आरण्यक रहस्यवादी वन पुस्तकें", "108 उपनिषद वेदांत दर्शन (ब्रह्म एवं आत्मा) का प्रतिपादन करते हैं"],
        "q_en": "Which Veda is regarded as the primary musical foundation of Indian classical music and melody?",
        "q_hi": "भारतीय शास्त्रीय संगीत और गायन का प्राथमिक मूल स्रोत किस वेद को माना जाता है?",
        "options_en": ["Samaveda (सामवेद)", "Rigveda", "Yajurveda", "Atharvaveda"],
        "options_hi": ["सामवेद (Samaveda)", "ऋग्वेद", "यजुर्वेद", "अथर्ववेद"],
        "correct_idx": 0,
        "exp_en": "The Samaveda consists of verses largely taken from the Rigveda set to melody and musical scales for chanting during Somayaga rituals.",
        "exp_hi": "सामवेद को भारतीय संगीत का जनक माना जाता है; इसके अधिकांश मंत्र ऋग्वेद से लेकर गेय रूप में संकलित किए गए हैं।",
        "cue_en": "Sama = Song / Music.",
        "cue_hi": "साम = गान / संगीत का वेद।",
        "wrong_en": ["Root of Indian music.", "Oldest collection of hymns.", "Veda of sacrificial formulas.", "Veda of magic, medicine and spells."],
        "wrong_hi": ["भारतीय संगीत का जनक।", "सबसे प्राचीन ऋचाओं का संकलन।", "यज्ञीय कर्मकांडों का वेद।", "औषधि, तंत्र-मंत्र का वेद।"]
    },
    {
        "name_en": "Rise of 16 Mahajanapadas & Magadha Hegemony (Haryanka, Shishunaga, Nanda)",
        "name_hi": "16 महाजनपदों का उदय एवं मगध का उत्कर्ष (हर्यंक, शिशुनाग, नंद वंश)",
        "concepts_en": ["Anguttara Nikaya lists 16 Mahajanapadas in 6th century BCE", "Magadha strategic advantages: iron mines of Rajgir, fertile Ganga plains, elephants", "Bimbisara and Ajatashatru (Haryanka dynasty)", "Mahapadma Nanda 'Ekarat' establishes vast empire"],
        "concepts_hi": ["अंगुत्तर निकाय (बौद्ध ग्रंथ) में 16 महाजनपदों की सूची", "मगध की सामरिक अनुकूलता: लोहे की खानें, उपजाऊ भूमि, हाथी", "बिंबिसार एवं अजातशत्रु (हर्यंक वंश)", "महापद्मनंद ('एकराट्') द्वारा विशाल साम्राज्य की स्थापना"],
        "q_en": "In which Buddhist text is the canonical list of the 16 Great Kingdoms (Mahajanapadas) of ancient India first recorded?",
        "q_hi": "प्राचीन भारत के 16 महाजनपदों की प्रामाणिक सूची सर्वप्रथम किस बौद्ध ग्रंथ में मिलती है?",
        "options_en": ["Anguttara Nikaya (अंगुत्तर निकाय)", "Digha Nikaya", "Vinaya Pitaka", "Mahavamsa"],
        "options_hi": ["अंगुत्तर निकाय (Anguttara Nikaya)", "दीघ निकाय", "विनय पिटक", "महावंश"],
        "correct_idx": 0,
        "exp_en": "The Anguttara Nikaya of the Sutta Pitaka contains the primary list of the 16 Mahajanapadas existing during the time of Gautama Buddha.",
        "exp_hi": "सुत्तपिटक के अंगुत्तर निकाय में भगवान बुद्ध के समकालीन 16 महाजनपदों की प्रामाणिक सूची का उल्लेख मिलता है।",
        "cue_en": "16 Mahajanapadas = Anguttara Nikaya (also Bhagavati Sutra in Jainism).",
        "cue_hi": "16 महाजनपद = अंगुत्तर निकाय (एवं जैन भगवती सूत्र)।",
        "wrong_en": ["Canonical Buddhist list of 16 Mahajanapadas.", "Contains long discourses.", "Monastic rules for Sangha.", "Sri Lankan chronicle."],
        "wrong_hi": ["16 महाजनपदों का उल्लेख।", "बुद्ध के लंबे उपदेशों का संग्रह।", "बौद्ध भिक्षुओं के आचार नियम।", "श्रीलंका का ऐतिहासिक वृत्तांत।"]
    },
    {
        "name_en": "Persian Invasions (Darius I) & Alexander's Campaign in Punjab (326 BCE)",
        "name_hi": "ईरानी आक्रमण (डेरियस प्रथम) एवं सिकंदर का पंजाब अभियान (326 ई.पू.)",
        "concepts_en": ["Achaemenid invasion: Cyrus & Darius I (Bahistun & Persepolis inscriptions)", "Introduction of Kharosthi script from Aramaic", "Alexander the Great crosses Indus (326 BCE)", "Battle of Hydaspes (Jhelum) against King Porus"],
        "concepts_hi": ["हखामनी आक्रमण: साइरस व डेरियस प्रथम (बेहिस्तून व पर्सीपोलिस अभिलेख)", "अरामाइक से खरोष्ठी लिपि का आगमन", "सिकंदर का सिंधु नदी पार करना (326 ई.पू.)", "राजा पोरस के विरुद्ध झेलम (हाइडैस्पीज) का युद्ध"],
        "q_en": "The famous Battle of the Hydaspes in 326 BCE was fought between Alexander the Great and which Indian monarch?",
        "q_hi": "326 ई.पू. में झेलम नदी के तट पर प्रसिद्ध 'हाइडैस्पीज का युद्ध' सिकंदर और किस भारतीय शासक के बीच लड़ा गया था?",
        "options_en": ["King Porus (राजा पोरस / पुरु)", "Chandragupta Maurya", "Ambhi of Taxila", "Dhana Nanda"],
        "options_hi": ["राजा पोरस / पुरु (King Porus)", "चंद्रगुप्त मौर्य", "तक्षशिला का आम्भी", "धनानंद"],
        "correct_idx": 0,
        "exp_en": "Alexander fought King Porus in 326 BCE along the Hydaspes (Jhelum) river in Punjab. Porus fought bravely and was reinstated as a client ruler.",
        "exp_hi": "326 ई.पू. में सिकंदर और पंजाब के शासक पोरस के बीच झेलम (हाइडैस्पीज) नदी के किनारे भीषण युद्ध हुआ, जिसमें पोरस की वीरता देखकर सिकंदर ने उसका राज्य लौटा दिया।",
        "cue_en": "Battle of Hydaspes (Jhelum) = Alexander vs Porus (326 BCE).",
        "cue_hi": "हाइडैस्पीज (झेलम) का युद्ध = सिकंदर बनाम पोरस (326 ई.पू.)।",
        "wrong_en": ["Fought Alexander at Hydaspes.", "Rose to power shortly after Alexander left.", "Surrendered without fighting Alexander.", "Nanda ruler ruling Magadha in east."],
        "wrong_hi": ["सिकंदर से लड़ने वाले वीर शासक।", "सिकंदर के जाने के बाद शासक बने।", "सिकंदर के सामने बिना लड़े आत्मसमर्पण किया।", "मगध के नंद वंश के शासक।"]
    },
    {
        "name_en": "Second Urbanization & Iron Metallurgy in the Middle Ganga Valley",
        "name_hi": "द्वितीय नगरीकरण एवं मध्य गंगा घाटी में लौह धातु विज्ञान",
        "concepts_en": ["Second urbanization emergence (6th century BCE)", "Iron axes cleared dense monsoon forests of Bihar/UP", "Surplus agricultural production supported cities & monetization", "Punch-marked coins (Karshapana)"],
        "concepts_hi": ["छठी शताब्दी ई.पू. में द्वितीय नगरीकरण का उदय", "लोहे की कुल्हाड़ियों से गंगा के घने जंगलों की कटाई", "अधिशेष कृषि उत्पादन से व्यापार व शहरों का विकास", "आहत सिक्के (पंचमार्क सिक्के / कार्षापण) का प्रचलन"],
        "q_en": "What were the earliest metal coins issued in ancient India, characterized by symbols stamped onto silver or copper pieces, called?",
        "q_hi": "प्राचीन भारत में चांदी या तांबे के टुकड़ों पर विभिन्न प्रतीकों को ठप्पा मारकर जारी किए गए सबसे पहले सिक्कों को क्या कहा जाता था?",
        "options_en": ["Punch-marked coins (आहत सिक्के / कार्षापण)", "Dinar", "Jital", "Dam"],
        "options_hi": ["आहत सिक्के / कार्षापण (Punch-marked coins)", "दीनार", "जीतल", "दाम"],
        "correct_idx": 0,
        "exp_en": "Punch-marked coins (Karshapanas or Puranas), primarily made of silver or copper, represent India's earliest coinage dating back to the 6th century BCE.",
        "exp_hi": "छठी शताब्दी ई.पू. में चांदी और तांबे पर ठप्पा मारकर बनाए गए सिक्के 'आहत सिक्के' या 'कार्षापण' कहलाते हैं; ये भारत की सबसे प्राचीन मुद्रा हैं।",
        "cue_en": "Earliest Indian coins = Punch-marked coins (Karshapana).",
        "cue_hi": "भारत के प्राचीनतम सिक्के = आहत सिक्के (कार्षापण)।",
        "wrong_en": ["Earliest coinage in India.", "Gold coins of Guptas/Romans.", "Copper coin of Delhi Sultanate.", "Copper coin of Sher Shah Suri."],
        "wrong_hi": ["भारत के पहले सिक्के।", "गुप्तों व रोमनों के सोने के सिक्के।", "दिल्ली सल्तनत का तांबे का सिक्का।", "शेरशाह सूरी का तांबे का सिक्का।"]
    }
]

print("Loaded S03 (Chapters 1 & 2)")
