# build_curriculum/group2_s04_part2.py
# S04: Medieval & Modern Indian History (Chapters 4, 5, 6 - 16 topics)

DATA = {}

# S04-C511c1907 Advent of Europeans, British Expansion & Battles (5 topics)
DATA["S04-C511c1907"] = [
    {
        "name_en": "Arrival of European Trading Companies: Portuguese, Dutch, English, Danes & French",
        "name_hi": "यूरोपीय व्यापारिक कंपनियों का आगमन: पुर्तगाली, डच, अंग्रेज, डेन एवं फ्रांसीसी",
        "concepts_en": ["Vasco da Gama reached Calicut (May 1498) welcomed by Zamorin; Francisco de Almeida's Blue Water Policy", "Alfonso de Albuquerque conquered Goa (1510) from Sultan of Bijapur", "Dutch founded factory at Masulipatnam (1605); English East India Company founded 1600 (Charter of Queen Elizabeth I)", "Battle of Bedara (1759) defeated Dutch; Battle of Wandiwash (1760) Eyre Coote defeated French (Lally)"],
        "concepts_hi": ["वास्कोडिगामा 1498 में कालीकट पहुंचा (राजा जमोरिन द्वारा स्वागत); अलमीडा की 'ब्लू वॉटर पॉलिसी' (शांत जल नीति)", "अल्बुकर्क ने 1510 में बीजापुर के सुल्तान से गोवा छीना", "डचों की पहली फैक्ट्री मसूलीपट्टनम (1605); अंग्रेजी ईस्ट इंडिया कंपनी की स्थापना 1600 में महारानी एलिजाबेथ के चार्टर द्वारा", "बेदारा का युद्ध (1759) में डच पराजित; वांडीवाश का युद्ध (1760) में सर आयर कूट ने फ्रांसीसी सेना को परास्त किया"],
        "q_en": "In the decisive Battle of Wandiwash (1760) during the Third Carnatic War, which British general defeated the French forces led by Count de Lally?",
        "q_hi": "तृतीय कर्नाटक युद्ध के दौरान 1760 के निर्णायक 'वांडीवाश के युद्ध' में किस ब्रिटिश सेनापति ने काउंट डी लाली के नेतृत्व वाली फ्रांसीसी सेना को पराजित किया था?",
        "options_en": ["Sir Eyre Coote (सर आयर कूट)", "Robert Clive", "Hector Munro", "Arthur Wellesley"],
        "options_hi": ["सर आयर कूट (Sir Eyre Coote)", "रॉबर्ट क्लाइव", "हेक्टर मुनरो", "आर्थर वेलेस्ली"],
        "correct_idx": 0,
        "exp_en": "In January 1760, British forces under Sir Eyre Coote decisively defeated the French under Count de Lally at Wandiwash, effectively ending French imperial ambitions in India.",
        "exp_hi": "1760 में वांडीवाश के मैदान में ब्रिटिश जनरल सर आयर कूट ने फ्रांसीसी सेनापति लाली को पूरी तरह परास्त किया, जिसने भारत में फ्रांसीसी साम्राज्य का अंत कर दिया।",
        "cue_en": "Battle of Wandiwash (1760) = Eyre Coote defeats French.",
        "cue_hi": "वांडीवाश का युद्ध (1760) = आयर कूट ने फ्रांसीसियों को हराया।",
        "wrong_en": ["Victorious British commander at Wandiwash.", "Victor at Plassey (1757).", "Victor at Buxar (1764).", "Victor at Assaye (1803)."],
        "wrong_hi": ["वांडीवाश में ब्रिटिश विजेता सेनापति।", "प्लासी का विजेता।", "बक्सर का विजेता सेनापति।", "असाए के युद्ध का विजेता।"]
    },
    {
        "name_en": "Battle of Plassey (1757), Battle of Buxar (1764) & Treaty of Allahabad (1765)",
        "name_hi": "प्लासी का युद्ध (1757), बक्सर का युद्ध (1764) एवं इलाहाबाद की संधि (1765)",
        "concepts_en": ["Battle of Plassey (23 June 1757): Robert Clive defeated Siraj-ud-Daulah due to treachery of Mir Jafar, Rai Durlabh & Jagat Seth", "Battle of Buxar (22 October 1764): Hector Munro defeated joint forces of Mir Qasim, Shuja-ud-Daulah (Awadh) & Shah Alam II (Mughal Emperor)", "Treaty of Allahabad (1765): Robert Clive secured Diwani rights (revenue collection) of Bengal, Bihar, and Orissa for East India Company", "Dual Government in Bengal (1765–1772) introduced by Clive"],
        "concepts_hi": ["प्लासी का युद्ध (23 जून 1757): मीर जाफर, राय दुर्लभ व जगत सेठ के विश्वासघात से रॉबर्ट क्लाइव ने सिराजुद्दौला को हराया", "बक्सर का युद्ध (22 अक्टूबर 1764): हेक्टर मुनरो ने मीर कासिम, शुजाउद्दौला (अवध) एवं शाह आलम द्वितीय (मुगल सम्राट) के संयुक्त मोर्चे को पराजित किया", "इलाहाबाद की संधि (1765): क्लाइव ने मुगल सम्राट से बंगाल, बिहार और ओडिशा की 'दीवानी' (राजस्व अधिकार) प्राप्त की", "क्लाइव द्वारा बंगाल में द्वैध शासन प्रणाली (1765-1772) की स्थापना"],
        "q_en": "By which historic treaty of August 1765 did Mughal Emperor Shah Alam II grant the permanent 'Diwani' rights of Bengal, Bihar, and Orissa to the English East India Company?",
        "q_hi": "अगस्त 1765 की किस ऐतिहासिक संधि द्वारा मुगल सम्राट शाह आलम द्वितीय ने ईस्ट इंडिया कंपनी को बंगाल, बिहार और ओडिशा की 'दीवानी' (राजस्व वसूली अधिकार) प्रदान की थी?",
        "options_en": ["Treaty of Allahabad (1765)", "Treaty of Alinagar", "Treaty of Purandar", "Treaty of Bassein"],
        "options_hi": ["इलाहाबाद की संधि (Treaty of Allahabad - 1765)", "अलीनगर की संधि", "पुरंदर की संधि", "बेसिन की संधि"],
        "correct_idx": 0,
        "exp_en": "Following the Battle of Buxar, Robert Clive concluded the Treaty of Allahabad in 1765, by which Shah Alam II granted the fiscal Diwani of Bengal, Bihar, and Orissa to the Company.",
        "exp_hi": "बक्सर के युद्ध के बाद 1765 में क्लाइव और मुगल सम्राट शाह आलम द्वितीय के बीच इलाहाबाद की संधि हुई, जिसने कंपनी को भारत का वास्तविक राजनीतिक व आर्थिक शासक बना दिया।",
        "cue_en": "Diwani rights 1765 = Treaty of Allahabad.",
        "cue_hi": "दीवानी अधिकार (1765) = इलाहाबाद की संधि।",
        "wrong_en": ["Granted Diwani of Bengal, Bihar, Orissa.", "Signed between Siraj-ud-Daulah and Clive (1757).", "Signed between Shivaji and Jai Singh (1665).", "Signed between Baji Rao II and Wellesley (1802)."],
        "wrong_hi": ["बंगाल-बिहार-ओडिशा की दीवानी की संधि।", "सिराजुद्दौला और क्लाइव के बीच 1757 की संधि।", "शिवाजी और जयसिंह की 1665 की संधि।", "बाजीराव द्वितीय और वेलेस्ली की 1802 की संधि।"]
    },
    {
        "name_en": "Anglo-Mysore Wars: Hyder Ali, Tipu Sultan & the Fall of Srirangapatna (1799)",
        "name_hi": "आंग्ल-मैसूर युद्ध: हैदर अली, टीपू सुल्तान एवं श्रीरंगपट्टनम का पतन (1799)",
        "concepts_en": ["Four Anglo-Mysore Wars (1767–1799)", "First War (1767–69): Treaty of Madras; Second War (1780–84): Treaty of Mangalore (Eyre Coote defeated Hyder Ali at Porto Novo)", "Third War (1790–92): Treaty of Seringapatam under Cornwallis; Tipu ceded half his territory", "Fourth War (1799): Lord Wellesley attacked Mysore; Tipu Sultan ('Tiger of Mysore') died defending Srirangapatna fort (4 May 1799)"],
        "concepts_hi": ["चार आंग्ल-मैसूर युद्ध (1767-1799)", "प्रथम युद्ध (1767-69): मद्रास की संधि; द्वितीय युद्ध (1780-84): मंगलौर की संधि (हैदर अली की मृत्यु, पोर्टो नोवो का युद्ध)", "तृतीय युद्ध (1790-92): कॉर्नवालिस के समय श्रीरंगपट्टनम की संधि (टीपू को आधा राज्य खोना पड़ा)", "चतुर्थ युद्ध (1799): लॉर्ड वेलेस्ली का आक्रमण; टीपू सुल्तान ('मैसूर का शेर') 4 मई 1799 को श्रीरंगपट्टनम के दुर्ग की रक्षा करते हुए वीरगति को प्राप्त हुए"],
        "q_en": "Tipu Sultan, the ruler of Mysore, died fighting the British East India Company forces during which Anglo-Mysore War in 1799?",
        "q_hi": "मैसूर के शासक टीपू सुल्तान 1799 में किस आंग्ल-मैसूर युद्ध के दौरान श्रीरंगपट्टनम के दुर्ग की रक्षा करते हुए वीरगति को प्राप्त हुए?",
        "options_en": ["Fourth Anglo-Mysore War (1799)", "First Anglo-Mysore War", "Second Anglo-Mysore War", "Third Anglo-Mysore War"],
        "options_hi": ["चतुर्थ आंग्ल-मैसूर युद्ध (1799)", "प्रथम आंग्ल-मैसूर युद्ध", "द्वितीय आंग्ल-मैसूर युद्ध", "तृतीय आंग्ल-मैसूर युद्ध"],
        "correct_idx": 0,
        "exp_en": "Tipu Sultan fell on 4 May 1799 during the Fourth Anglo-Mysore War, when British troops led by General George Harris and Arthur Wellesley breached Srirangapatna.",
        "exp_hi": "4 मई 1799 को चौथे आंग्ल-मैसूर युद्ध में वेलेस्ली की सेना से लड़ते हुए टीपू सुल्तान श्रीरंगपट्टनम में शहीद हुए, जिसके बाद वाडियार वंश को गद्दी सौंपी गई।",
        "cue_en": "Tipu Sultan fell = Fourth Anglo-Mysore War (1799).",
        "cue_hi": "टीपू सुल्तान की शहादत = चतुर्थ आंग्ल-मैसूर युद्ध (1799)।",
        "wrong_en": ["Fall of Srirangapatna & death of Tipu.", "Hyder Ali dictated Treaty of Madras.", "Hyder Ali died of cancer in 1782.", "Concluded with Treaty of Seringapatam (1792)."],
        "wrong_hi": ["श्रीरंगपट्टनम का पतन व टीपू की मृत्यु।", "हैदर अली ने मद्रास की संधि कराई।", "हैदर अली की 1782 में मृत्यु।", "1792 की श्रीरंगपट्टनम की संधि से समाप्त।"]
    },
    {
        "name_en": "British Expansionist Policies: Subsidiary Alliance System & Doctrine of Lapse",
        "name_hi": "ब्रिटिश विस्तारवादी नीतियां: सहायक संधि प्रणाली (वेलेस्ली) एवं हड़प नीति (डलहौजी)",
        "concepts_en": ["Subsidiary Alliance (Lord Wellesley, 1798): Indian rulers accepted British resident, disbanded own army, paid for Company troops; Nizam of Hyderabad first to sign (1798), followed by Mysore, Tanjore, Awadh, Peshwa (Bassein 1802)", "Doctrine of Lapse (Lord Dalhousie, 1848): Annexed states where ruler died without natural male heir; Satara (1848) first, then Jaitpur, Sambalpur, Baghat, Udaipur, Jhansi (1853), Nagpur (1854)", "Awadh annexed on grounds of misgovernance (1856) on Outram's report"],
        "concepts_hi": ["सहायक संधि (लॉर्ड वेलेस्ली, 1798): भारतीय शासक ब्रिटिश रेजीडेंट रखेंगे और विदेशी संबंध त्यागेंगे; हैदराबाद का निजाम सबसे पहले शामिल (1798), फिर मैसूर, तंजौर, अवध, मराठा", "हड़प नीति / व्यपगत का सिद्धांत (लॉर्ड डलहौजी, 1848): दत्तक पुत्र को उत्तराधिकारी मानने से इनकार; सबसे पहले सतारा (1848) का विलय, फिर जैतपुर, संबलपुर, बघाट, उदयपुर, झांसी (1853), नागपुर (1854)", "अवध का विलय 1856 में आउट्रम रिपोर्ट के आधार पर 'कुशासन' का आरोप लगाकर किया गया"],
        "q_en": "Which princely state was the very first to be annexed by Lord Dalhousie under the controversial 'Doctrine of Lapse' in 1848?",
        "q_hi": "लॉर्ड डलहौजी द्वारा 1848 में लागू की गई 'हड़प नीति' (Doctrine of Lapse / व्यपगत सिद्धांत) के तहत सबसे पहले किस भारतीय रियासत का विलय किया गया था?",
        "options_en": ["Satara (सतारा - 1848)", "Jhansi (1853)", "Nagpur (1854)", "Sambalpur (1849)"],
        "options_hi": ["सतारा (Satara - 1848)", "झांसी (1853)", "नागपुर (1854)", "संबलपुर (1849)"],
        "correct_idx": 0,
        "exp_en": "Satara in Maharashtra was the first state annexed under the Doctrine of Lapse in 1848 when its ruler Appa Sahib died without a biological male heir.",
        "exp_hi": "लॉर्ड डलहौजी ने व्यपगत के सिद्धांत के तहत 1848 में सबसे पहले महाराष्ट्र के सतारा का विलय किया। इसके बाद जैतपुर, संबलपुर, बघाट, उदयपुर, झांसी और नागपुर का विलय हुआ।",
        "cue_en": "Doctrine of Lapse first = Satara (1848).",
        "cue_hi": "हड़प नीति के तहत पहला विलय = सतारा (1848)।",
        "wrong_en": ["First state annexed (1848).", "Annexed in 1853 (Rani Lakshmibai).", "Annexed in 1854.", "Annexed in 1849."],
        "wrong_hi": ["1848 में सबसे पहले विलीन।", "1853 में रानी लक्ष्मीबाई की रियासत।", "1854 में विलीन बड़ी रियासत।", "1849 में विलीन।"]
    },
    {
        "name_en": "Colonial Land Revenue Systems: Permanent Settlement, Ryotwari & Mahalwari",
        "name_hi": "औपनिवेशिक भू-राजस्व प्रणालियां: स्थायी बंदोबस्त, रैयतवाड़ी एवं महालवाड़ी",
        "concepts_en": ["Permanent Settlement (Zamindari System, 1793): Lord Cornwallis in Bengal, Bihar, Orissa; Zamindars made landlords with fixed 10/11th to Company and 1/11th to Zamindar; Sunset Law", "Ryotwari System (1820): Thomas Munro and Alexander Read in Madras and Bombay Presidencies; direct settlement with peasant (Ryot)", "Mahalwari System (1822): Holt Mackenzie and Robert Merttins Bird in Gangetic Valley, NWFP, Punjab; settlement with village community (Mahal)"],
        "concepts_hi": ["स्थायी बंदोबस्त (जमींदारी प्रथा, 1793): लॉर्ड कॉर्नवालिस द्वारा बंगाल, बिहार, ओडिशा में; जमींदारों को भूमि का स्वामी माना गया; 10/11 भाग कंपनी का व 1/11 भाग जमींदार का; 'सूर्यास्त कानून' (Sunset Law)", "रैयतवाड़ी व्यवस्था (1820): थॉमस मुनरो एवं कैप्टन रीड द्वारा मद्रास व बंबई में; किसान (रैयत) से सीधा राजस्व समझौता", "महालवाड़ी व्यवस्था (1822): हॉल्ट मैकेंजी व मार्टिन्स बर्ड द्वारा संयुक्त प्रांत, पंजाब, मध्य प्रांत में; पूरे गांव/महाल के साथ सामूहिक समझौता"],
        "q_en": "Who formulated and introduced the Ryotwari land revenue system in the Madras Presidency in 1820?",
        "q_hi": "1820 में मद्रास प्रेसीडेंसी में किसानों के साथ प्रत्यक्ष राजस्व बंदोबस्त करने वाली 'रैयतवाड़ी व्यवस्था' किसने लागू की थी?",
        "options_en": ["Sir Thomas Munro (सर थॉमस मुनरो)", "Lord Cornwallis", "Holt Mackenzie", "Warren Hastings"],
        "options_hi": ["सर थॉमस मुनरो (Sir Thomas Munro)", "लॉर्ड कॉर्नवालिस", "हॉल्ट मैकेंजी", "वॉरेन हेस्टिंग्स"],
        "correct_idx": 0,
        "exp_en": "Sir Thomas Munro, Governor of Madras, implemented the Ryotwari system in 1820, establishing direct revenue relations with individual cultivators (Ryots).",
        "exp_hi": "मद्रास के गवर्नर थॉमस मुनरो ने 1820 में रैयतवाड़ी व्यवस्था लागू की, जिसमें बिचौलियों (जमींदारों) को हटाकर सीधे किसानों से राजस्व वसूली तय की गई।",
        "cue_en": "Ryotwari = Thomas Munro (Madras 1820).",
        "cue_hi": "रैयतवाड़ी = थॉमस मुनरो (मद्रास)।",
        "wrong_en": ["Introduced Ryotwari in Madras.", "Introduced Permanent Settlement (1793).", "Formulated Mahalwari concept.", "Introduced Izaredari five-year farming system."],
        "wrong_hi": ["मद्रास में रैयतवाड़ी के जनक।", "स्थायी बंदोबस्त के जनक।", "महालवाड़ी के प्रवर्तक।", "इजारेदारी व्यवस्था के जनक।"]
    }
]

# S04-C2a69d8ec Revolt of 1857 & Socio-Religious Reformers (6 topics)
DATA["S04-C2a69d8ec"] = [
    {
        "name_en": "Revolt of 1857: Outbreak at Meerut, Causes & Key Centers of Resistance",
        "name_hi": "1857 का विद्रोह: मेरठ में विस्फोट, प्रमुख कारण एवं विद्रोह के मुख्य केंद्र",
        "concepts_en": ["Enfield rifle greased cartridge controversy (cow & pig fat); Mangal Pandey mutinied at Barrackpore (29 March 1857)", "Meerut outbreak on 10 May 1857; march to Delhi and proclamation of Bahadur Shah Zafar as Shahenshah-e-Hindustan", "Delhi: General Bakht Khan; Kanpur: Nana Saheb & Tatya Tope; Lucknow: Begum Hazrat Mahal; Bareilly: Khan Bahadur Khan", "Bihar (Arrah): 80-year-old Kunwar Singh; Jhansi: Rani Lakshmibai"],
        "concepts_hi": ["एनफील्ड राइफल के चर्बी वाले कारतूस (गाय व सूअर की चर्बी); बैरकपुर छावनी में मंगल पांडे का विद्रोह (29 मार्च 1857)", "10 मई 1857 को मेरठ में खुला विद्रोह; दिल्ली कूच कर अंतिम मुगल बादशाह बहादुर शाह जफर को 'शहंशाह-ए-हिंदुस्तान' घोषित किया", "दिल्ली: जनरल बख्त खान; कानपुर: नाना साहेब व तात्या टोपे; लखनऊ: बेगम हजरत महल; बरेली: खान बहादुर खान", "बिहार (जगदीशपुर): 80 वर्षीय वीर कुंवर सिंह; झांसी: वीरांगना रानी लक्ष्मीबाई"],
        "q_en": "Who led the 1857 revolt against the British in Jagdishpur, Bihar, demonstrating legendary military prowess despite being over 75 years old?",
        "q_hi": "1857 के स्वतंत्रता संग्राम में 75 वर्ष से अधिक की आयु में भी बिहार के जगदीशपुर (आरा) में अंग्रेजों के छक्के छुड़ाने वाले प्रमुख नायक कौन थे?",
        "options_en": ["Kunwar Singh (वीर कुंवर सिंह)", "Nana Saheb", "Tatya Tope", "Maulvi Liaquat Ali"],
        "options_hi": ["वीर कुंवर सिंह (Kunwar Singh - Jagdishpur)", "नाना साहेब", "तात्या टोपे", "मौलवी लियाकत अली"],
        "correct_idx": 0,
        "exp_en": "Veer Kunwar Singh of the Ujjainiya clan of Jagdishpur (Bhojpur, Bihar) was the undisputed leader of the 1857 revolt in Bihar, defeating several British commanders until his death in 1858.",
        "exp_hi": "जगदीशपुर के जमींदार वीर कुंवर सिंह ने बिहार में 1857 के विद्रोह का नेतृत्व किया और अदम्य साहस का परिचय देते हुए अंग्रेजों को कई युद्धों में पराजित किया।",
        "cue_en": "1857 Bihar leader = Veer Kunwar Singh (Jagdishpur).",
        "cue_hi": "1857 बिहार के नायक = वीर कुंवर सिंह (जगदीशपुर)।",
        "wrong_en": ["Leader of revolt in Bihar.", "Led revolt in Kanpur.", "General of Nana Saheb and Rani of Jhansi.", "Led revolt in Allahabad."],
        "wrong_hi": ["बिहार के प्रमुख विद्रोही नेता।", "कानपुर में विद्रोह के नेता।", "मराठा सेनापति (ग्वालियर/झांसी)।", "इलाहाबाद में विद्रोह के नेता।"]
    },
    {
        "name_en": "Government of India Act 1858 & Queen Victoria's Proclamation",
        "name_hi": "भारत सरकार अधिनियम 1858 एवं महारानी विक्टोरिया का घोषणापत्र",
        "concepts_en": ["Act for the Better Government of India (August 1858)", "Abolition of British East India Company rule; power transferred directly to the British Crown", "Abolition of Board of Control and Court of Directors; office of Secretary of State for India with 15-member council created", "Governor-General received title of Viceroy (Lord Canning first Viceroy); Queen's Proclamation read on 1 November 1858 at Allahabad"],
        "concepts_hi": ["भारत शासन अधिनियम 1858 ('एक्ट फॉर द बेटर गवर्नमेंट ऑफ इंडिया')", "ईस्ट इंडिया कंपनी का शासन समाप्त; भारत का शासन सीधे ब्रिटिश ताज (क्राउन) के अधीन", "बोर्ड ऑफ कंट्रोल व कोर्ट ऑफ डायरेक्टर्स समाप्त; 'भारत सचिव' (Secretary of State) पद व 15 सदस्यीय परिषद का गठन", "गवर्नर जनरल को 'वायसराय' की उपाधि (लॉर्ड कैनिंग पहले वायसराय); 1 नवंबर 1858 को इलाहाबाद दरबार में महारानी का घोषणापत्र पढ़ा गया"],
        "q_en": "Who became the first Viceroy of India under the Government of India Act 1858?",
        "q_hi": "1858 के भारत शासन अधिनियम के तहत भारत के पहले 'वायसराय' कौन बने?",
        "options_en": ["Lord Canning (लॉर्ड कैनिंग)", "Lord Dalhousie", "Lord Elgin", "Lord Lawrence"],
        "options_hi": ["लॉर्ड कैनिंग (Lord Canning)", "लॉर्ड डलहौजी", "लॉर्ड एल्गिन", "लॉर्ड लॉरेंस"],
        "correct_idx": 0,
        "exp_en": "Lord Canning, who was Governor-General during the 1857 revolt, became the first Viceroy and Governor-General of India representing the British Crown in November 1858.",
        "exp_hi": "1857 के विद्रोह के समय भारत के गवर्नर जनरल लॉर्ड कैनिंग थे, जिन्हें 1858 के अधिनियम के बाद भारत का पहला वायसराय बनाया गया।",
        "cue_en": "First Viceroy = Lord Canning (1858).",
        "cue_hi": "पहले वायसराय = लॉर्ड कैनिंग (1858)।",
        "wrong_en": ["First Viceroy of India.", "Preceding Governor-General (1848–56).", "Succeeded Canning in 1862.", "Succeeded Elgin in 1864."],
        "wrong_hi": ["भारत के प्रथम वायसराय।", "डलहौजी पूर्व गवर्नर जनरल थे।", "कैनिंग के बाद आने वाले वायसराय।", "1864 के वायसराय।"]
    },
    {
        "name_en": "Raja Ram Mohan Roy, Brahmo Samaj & Social Reforms (Abolition of Sati 1829)",
        "name_hi": "राजा राममोहन राय, ब्रह्म समाज एवं सती प्रथा का उन्मूलन (1829)",
        "concepts_en": ["Raja Ram Mohan Roy called 'Father of Indian Renaissance' and 'Maker of Modern India'", "Authored Gift to Monotheists (Tuhfat-ul-Muwahhidin, 1803) and Precepts of Jesus (1820)", "Founded Atmiya Sabha (1815) and Brahmo Sabha / Brahmo Samaj (1828)", "Abolition of Sati Regulation XVII of 1829 enacted by Lord William Bentinck"],
        "concepts_hi": ["राजा राममोहन राय को 'भारतीय पुनर्जागरण का जनक' व 'आधुनिक भारत का निर्माता' कहा जाता है", "फारसी में 'तुहफत-उल-मुवाहिद्दीन' (एकेश्वरवादियों को उपहार) एवं 'प्रिसेप्ट्स ऑफ जीसस' लिखी", "आत्मीय सभा (1815) एवं ब्रह्म समाज (1828) की स्थापना की", "लॉर्ड विलियम बेंटिंक द्वारा 1829 के नियम XVII के तहत सती प्रथा को गैरकानूनी व दंडनीय घोषित कराया"],
        "q_en": "Under which Governor-General was the historic regulation legally banning and penalizing the practice of Sati passed in December 1829, spearheaded by Raja Ram Mohan Roy?",
        "q_hi": "दिसंबर 1829 में राजा राममोहन राय के अथक प्रयासों से किस गवर्नर जनरल के कार्यकाल में सती प्रथा को कानून बनाकर समाप्त और दंडनीय घोषित किया गया?",
        "options_en": ["Lord William Bentinck (लॉर्ड विलियम बेंटिंक)", "Lord Dalhousie", "Lord Wellesley", "Lord Amherst"],
        "options_hi": ["लॉर्ड विलियम बेंटिंक (Lord William Bentinck)", "लॉर्ड डलहौजी", "लॉर्ड वेलेस्ली", "लॉर्ड एमहर्स्ट"],
        "correct_idx": 0,
        "exp_en": "Lord William Bentinck enacted Regulation XVII on 4 December 1829, making the practice of Sati illegal and punishable as culpable homicide.",
        "exp_hi": "लॉर्ड विलियम बेंटिंक ने 4 दिसंबर 1829 को बंगाल सती नियमन पारित कर सती प्रथा को अपराध घोषित किया, जिसे बाद में मद्रास और बंबई में भी लागू किया गया।",
        "cue_en": "Abolition of Sati 1829 = Bentinck + Ram Mohan Roy.",
        "cue_hi": "सती प्रथा निषेध (1829) = बेंटिंक + राजा राममोहन राय।",
        "wrong_en": ["Passed the 1829 Sati regulation.", "Passed Widow Remarriage Act (1856).", "Pioneered Subsidiary Alliance.", "Governor-General before Bentinck."],
        "wrong_hi": ["1829 में सती प्रथा निषेध कानून पारित किया।", "1856 में विधवा पुनर्विवाह कानून बनाया।", "सहायक संधि के जनक।", "बेंटिंक से ठीक पहले के गवर्नर जनरल।"]
    },
    {
        "name_en": "Ishwar Chandra Vidyasagar & Hindu Widows' Remarriage Act (1856)",
        "name_hi": "ईश्वर चंद्र विद्यासागर एवं हिंदू विधवा पुनर्विवाह अधिनियम (1856)",
        "concepts_en": ["Principal of Sanskrit College, Calcutta; championed women's education and widow rehabilitation", "Cited ancient Vedic and Smriti scriptures to legitimize widow remarriage", "Hindu Widows' Remarriage Act XV of 1856 drafted under Dalhousie and passed under Canning (July 1856)", "Established Bethune College (first higher education institute for women in Asia, 1849)"],
        "concepts_hi": ["कोलकाता के संस्कृत कॉलेज के प्राचार्य; महिला शिक्षा और विधवाओं के उद्धार के महान समर्थक", "पाराशर स्मृति के श्लोकों का हवाला देकर विधवा पुनर्विवाह को धार्मिक रूप से न्यायसंगत सिद्ध किया", "हिंदू विधवा पुनर्विवाह अधिनियम 1856 (अधिनियम XV) लॉर्ड कैनिंग के समय जुलाई 1856 में पारित हुआ", "बेथ्यून स्कूल/कॉलेज (1849) की स्थापना में जॉन ड्रिंकवाटर बेथ्यून का सहयोग किया"],
        "q_en": "The Hindu Widows' Remarriage Act (Act XV of 1856) was officially passed during the tenure of which Governor-General, primarily due to the tireless crusades of Ishwar Chandra Vidyasagar?",
        "q_hi": "ईश्वर चंद्र विद्यासागर के अथक प्रयासों के फलस्वरूप हिंदू विधवा पुनर्विवाह अधिनियम (अधिनियम XV, 1856) किस गवर्नर जनरल के कार्यकाल में आधिकारिक रूप से पारित हुआ था?",
        "options_en": ["Lord Canning (लॉर्ड कैनिंग - जुलाई 1856)", "Lord Dalhousie", "Lord William Bentinck", "Lord Ripon"],
        "options_hi": ["लॉर्ड कैनिंग (Lord Canning - 1856)", "लॉर्ड डलहौजी", "लॉर्ड विलियम बेंटिंक", "लॉर्ड रिपन"],
        "correct_idx": 0,
        "exp_en": "Although drafted under Lord Dalhousie, the Hindu Widows' Remarriage Act XV was officially passed on 26 July 1856 during the governor-generalship of Lord Canning.",
        "exp_hi": "यद्यपि इसका मसौदा डलहौजी के समय तैयार हुआ था, किंतु यह अधिनियम 26 जुलाई 1856 को लॉर्ड कैनिंग के कार्यकाल में पारित हुआ।",
        "cue_en": "Widow Remarriage Act = July 1856 (Canning) + Vidyasagar.",
        "cue_hi": "विधवा पुनर्विवाह अधिनियम = 1856 (कैनिंग) + ईश्वर चंद्र विद्यासागर।",
        "wrong_en": ["Governor-General who passed the Act in July 1856.", "Drafted the bill before leaving India in early 1856.", "Passed Sati regulation in 1829.", "Known for Local Self-Government (1882)."],
        "wrong_hi": ["जुलाई 1856 में कानून पारित करने वाले।", "प्रारूप तैयार किया किंतु पद छोड़ चुके थे।", "1829 में सती कानून बनाया।", "स्थानीय स्वशासन के जनक।"]
    },
    {
        "name_en": "Jyotirao Phule (Satyashodhak Samaj) & Swami Dayananda Saraswati (Arya Samaj)",
        "name_hi": "ज्योतिराव फुले (सत्यशोधक समाज) एवं स्वामी दयानंद सरस्वती (आर्य समाज)",
        "concepts_en": ["Jyotirao Phule founded Satyashodhak Samaj (1873) in Pune; authored Gulamgiri (1873) dedicated to American abolitionists", "Opened first school for girls at Bhide Wada (1848) with wife Savitribai Phule", "Swami Dayananda Saraswati founded Arya Samaj (1875) in Bombay; slogan 'Go Back to the Vedas'", "Authored Satyarth Prakash (1875) in Hindi; introduced Shuddhi movement and DAV schools"],
        "concepts_hi": ["महात्मा ज्योतिराव फुले ने 1873 में पुणे में 'सत्यशोधक समाज' की स्थापना की; 'गुलामगिरी' पुस्तक लिखी", "पत्नी सावित्रीबाई फुले के साथ 1848 में पुणे में बालिकाओं के लिए भारत का पहला विद्यालय खोला", "स्वामी दयानंद सरस्वती ने 1875 में बंबई में 'आर्य समाज' की स्थापना की; 'वेदों की ओर लौटो' का नारा दिया", "हिंदी में कालजयी ग्रंथ 'सत्यार्थ प्रकाश' लिखा; शुद्धि आंदोलन एवं डीएवी स्कूलों की श्रृंखला प्रारंभ की"],
        "q_en": "Who authored the radical anti-caste treatise 'Gulamgiri' (Slavery) in 1873, dedicating it to the abolitionist movement in the United States?",
        "q_hi": "1873 में जातिगत उत्पीड़न के विरुद्ध प्रसिद्ध क्रांतिकारी ग्रंथ 'गुलामगिरी' की रचना किसने की थी, जिसे अमेरिकी दासता-विरोधी आंदोलनकारियों को समर्पित किया गया था?",
        "options_en": ["Jyotirao Phule (महात्मा ज्योतिराव फुले)", "Dr. B.R. Ambedkar", "Swami Dayananda Saraswati", "E.V. Ramasamy Periyar"],
        "options_hi": ["महात्मा ज्योतिराव फुले (Jyotirao Phule)", "डॉ. बी.आर. अम्बेडकर", "स्वामी दयानंद सरस्वती", "ई.वी. रामासामी पेरियार"],
        "correct_idx": 0,
        "exp_en": "Mahatma Jyotirao Phule published Gulamgiri in Marathi in 1873, drawing parallels between the oppression of Shudras/Ati-Shudras in India and African American slaves in the US.",
        "exp_hi": "महात्मा ज्योतिराव फुले ने 1873 में 'गुलामगिरी' लिखी और इसे अमेरिका के उन अश्वेत दासों की मुक्ति के लिए लड़ने वाले आंदोलनकारियों को समर्पित किया।",
        "cue_en": "Gulamgiri & Satyashodhak Samaj = Jyotirao Phule.",
        "cue_hi": "गुलामगिरी व सत्यशोधक समाज = ज्योतिराव फुले।",
        "wrong_en": ["Author of Gulamgiri (1873).", "Author of Annihilation of Caste (1936).", "Author of Satyarth Prakash (1875).", "Founder of Self-Respect Movement (1925)."],
        "wrong_hi": ["गुलामगिरी के लेखक।", "एनिहिलेशन ऑफ कास्ट के लेखक।", "सत्यार्थ प्रकाश के लेखक।", "आत्मसम्मान आंदोलन के प्रणेता।"]
    },
    {
        "name_en": "Swami Vivekananda, Ramakrishna Mission & Theosophical Movement",
        "name_hi": "स्वामी विवेकानंद, रामकृष्ण मिशन एवं थियोसोफिकल सोसाइटी",
        "concepts_en": ["Swami Vivekananda (Narendranath Datta) disciple of Ramakrishna Paramahamsa", "Historic address at Parliament of Religions in Chicago (11 September 1893) begins 'Sisters and Brothers of America'", "Founded Ramakrishna Mission (1 May 1897) at Belur Math near Kolkata; practical Vedanta (Daridra Narayana)", "Theosophical Society founded by Madam Blavatsky & Col. Olcott (New York 1875, moved to Adyar 1882); Annie Besant founded Central Hindu College at Varanasi (1898)"],
        "concepts_hi": ["स्वामी विवेकानंद (नरेंद्रनाथ दत्त) रामकृष्ण परमहंस के शिष्य", "11 सितंबर 1893 को शिकागो विश्व धर्म संसद में ऐतिहासिक भाषण: 'अमेरिकी भाइयो और बहनो'", "1 मई 1897 को बेलूर मठ में रामकृष्ण मिशन की स्थापना; 'दरिद्र नारायण' की सेवा को ही ईश्वर सेवा बताया", "थियोसोफिकल सोसाइटी: मैडम ब्लावात्स्की व कर्नल अल्काट (1875 न्यूयॉर्क, 1882 अडयार); एनी बेसेंट ने 1898 में बनारस में सेंट्रल हिंदू कॉलेज स्थापित किया"],
        "q_en": "In which city did Swami Vivekananda deliver his legendary speech at the Parliament of the World's Religions on 11 September 1893?",
        "q_hi": "स्वामी विवेकानंद ने 11 सितंबर 1893 को विश्व धर्म संसद में अपना ऐतिहासिक भाषण किस शहर में दिया था?",
        "options_en": ["Chicago, United States (शिकागो)", "New York", "London", "Paris"],
        "options_hi": ["शिकागो (Chicago, United States)", "न्यूयॉर्क", "लंदन", "पेरिस"],
        "correct_idx": 0,
        "exp_en": "Swami Vivekananda represented Hinduism at the World's Parliament of Religions held in Chicago in September 1893, winning global acclaim for Hindu philosophy.",
        "exp_hi": "स्वामी विवेकानंद ने सितंबर 1893 में शिकागो (अमेरिका) में आयोजित विश्व धर्म संसद में भारत और सनातन दर्शन का प्रतिनिधित्व किया था।",
        "cue_en": "Vivekananda speech = Chicago (1893).",
        "cue_hi": "विवेकानंद का विश्व प्रसिद्ध भाषण = शिकागो (1893)।",
        "wrong_en": ["Venue of 1893 Parliament of Religions.", "Founded Vedanta Society in NY (1894).", "Addressed gatherings in London.", "Addressed Congress of Religions in Paris (1900)."],
        "wrong_hi": ["1893 की धर्म संसद का आयोजन स्थल।", "1894 में वेदांत सोसाइटी की स्थापना की।", "लंदन में व्याख्यान दिए।", "1900 में पेरिस धर्म कांग्रेस में बोले।"]
    }
]

# S04-Cacadfdde Indian National Movement & Independence (1885–1947) (5 topics)
DATA["S04-Cacadfdde"] = [
    {
        "name_en": "Formation of Indian National Congress (1885) & Moderate Phase",
        "name_hi": "भारतीय राष्ट्रीय कांग्रेस की स्थापना (1885) एवं उदारवादी (नरमपंथी) चरण",
        "concepts_en": ["INC founded by Allan Octavian Hume (retired ICS officer) in December 1885", "First session held at Gokuldas Tejpal Sanskrit College, Bombay, attended by 72 delegates; W.C. Bonnerjee first President", "Moderate leaders: Dadabhai Naoroji ('Grand Old Man of India'), Gopal Krishna Gokhale, Pherozeshah Mehta, Surendranath Banerjee", "Drain of Wealth Theory articulated by Dadabhai Naoroji in Poverty and Un-British Rule in India (1901)"],
        "concepts_hi": ["सेवानिवृत्त ब्रिटिश अधिकारी ए.ओ. ह्यूम द्वारा दिसंबर 1885 में कांग्रेस की स्थापना", "पहला अधिवेशन गोकुलदास तेजपाल संस्कृत कॉलेज, बंबई में; 72 प्रतिनिधियों ने भाग लिया; व्योमेश चंद्र बनर्जी पहले अध्यक्ष", "उदारवादी नेता: दादाभाई नौरोजी ('भारत के वयोवृद्ध पुरुष'), गोपाल कृष्ण गोखले, फिरोजशाह मेहता, सुरेंद्रनाथ बनर्जी", "दादाभाई नौरोजी द्वारा 'धन की निकासी का सिद्धांत' (Drain of Wealth Theory) का प्रतिपादन"],
        "q_en": "Who presided over the historic inaugural session of the Indian National Congress held in Bombay in December 1885?",
        "q_hi": "दिसंबर 1885 में बंबई में आयोजित भारतीय राष्ट्रीय कांग्रेस के पहले ऐतिहासिक अधिवेशन की अध्यक्षता किसने की थी?",
        "options_en": ["Womesh Chandra Bonnerjee (व्योमेश चंद्र बनर्जी)", "Dadabhai Naoroji", "A.O. Hume", "Badruddin Tyabji"],
        "options_hi": ["व्योमेश चंद्र बनर्जी (W.C. Bonnerjee)", "दादाभाई नौरोजी", "ए.ओ. ह्यूम", "बदरुद्दीन तैयबजी"],
        "correct_idx": 0,
        "exp_en": "Womesh Chandra Bonnerjee was elected president of the first session of the INC in Bombay on 28 December 1885, attended by 72 delegates.",
        "exp_hi": "28 दिसंबर 1885 को बंबई में कांग्रेस के प्रथम अधिवेशन के अध्यक्ष व्योमेश चंद्र बनर्जी बने, जिसमें देश भर से 72 प्रतिनिधियों ने भाग लिया।",
        "cue_en": "First Congress President = W.C. Bonnerjee (Bombay 1885).",
        "cue_hi": "कांग्रेस के पहले अध्यक्ष = व्योमेश चंद्र बनर्जी (1885)।",
        "wrong_en": ["First President of INC.", "President of second session (Calcutta 1886).", "General Secretary and founder.", "First Muslim President (Madras 1887)."],
        "wrong_hi": ["कांग्रेस के पहले अध्यक्ष।", "1886 के दूसरे अधिवेशन के अध्यक्ष।", "संस्थापक व पहले महासचिव।", "1887 के तीसरे अधिवेशन के पहले मुस्लिम अध्यक्ष।"]
    },
    {
        "name_en": "Partition of Bengal (1905), Swadeshi Movement & Surat Split (1907)",
        "name_hi": "बंगाल का विभाजन (1905), स्वदेशी आंदोलन एवं सूरत का विभाजन (1907)",
        "concepts_en": ["Lord Curzon announced Partition of Bengal on 16 October 1905 (observed as Raksha Bandhan day / Day of Mourning)", "Swadeshi & Boycott Movement launched at Calcutta Town Hall (7 August 1905); Rabindranath Tagore composed Amar Shonar Bangla", "Lal-Bal-Pal (Lala Lajpat Rai, Bal Gangadhar Tilak, Bipin Chandra Pal) and Aurobindo Ghose led Extemists", "Surat Split (1907): Congress divided into Moderates (led by Rash Behari Ghosh) and Extremists (Tilak)"],
        "concepts_hi": ["लॉर्ड कर्जन ने 16 अक्टूबर 1905 को बंगाल का विभाजन लागू किया (शोक दिवस व रक्षाबंधन दिवस के रूप में मनाया गया)", "7 अगस्त 1905 को कलकत्ता टाउन हॉल से स्वदेशी एवं बहिष्कार आंदोलन का औपचारिक ऐलान; टैगोर ने 'आमार सोनार बांग्ला' रचा", "लाल-बाल-पाल (लाला लाजपत राय, बाल गंगाधर तिलक, बिपिन चंद्र पाल) और अरविंद घोष ने गरम दल का नेतृत्व किया", "सूरत विभाजन (1907): रासबिहारी घोष की अध्यक्षता वाले अधिवेशन में कांग्रेस नरम और गरम दल में विभाजित हुई"],
        "q_en": "Who was the Viceroy of India who ordered and executed the controversial Partition of Bengal in October 1905?",
        "q_hi": "अक्टूबर 1905 में बंगाल के विभाजन का कुख्यात आदेश किस ब्रिटिश वायसराय द्वारा जारी और लागू किया गया था?",
        "options_en": ["Lord Curzon (लॉर्ड कर्जन)", "Lord Minto II", "Lord Hardinge II", "Lord Chelmsford"],
        "options_hi": ["लॉर्ड कर्जन (Lord Curzon)", "लॉर्ड मिंटो द्वितीय", "लॉर्ड हार्डिंग द्वितीय", "लॉर्ड चेम्सफोर्ड"],
        "correct_idx": 0,
        "exp_en": "Lord Curzon partitioned Bengal in 1905 ostensibly for administrative convenience but primarily to divide the politically active Bengali intelligentsia along religious lines.",
        "exp_hi": "लॉर्ड कर्जन ने फूट डालो और राज करो की नीति के तहत 1905 में बंगाल का विभाजन किया, जिसके विरोध में राष्ट्रव्यापी स्वदेशी आंदोलन छिड़ गया।",
        "cue_en": "Partition of Bengal 1905 = Lord Curzon.",
        "cue_hi": "बंगाल विभाजन (1905) = लॉर्ड कर्जन।",
        "wrong_en": ["Executed Partition in 1905.", "Succeeded Curzon (Morley-Minto Reforms 1909).", "Annulled Partition in Delhi Durbar (1911).", "Viceroy during Rowlatt Act (1919)."],
        "wrong_hi": ["1905 में विभाजन लागू करने वाले।", "मार्ले-मिंटो सुधार (1909) वाले वायसराय।", "1911 में दिल्ली दरबार में विभाजन रद्द करने वाले।", "रोलेट एक्ट के समय वायसराय।"]
    },
    {
        "name_en": "Mahatma Gandhi's Early Satyagrahas: Champaran (1917), Ahmedabad & Kheda (1918)",
        "name_hi": "महात्मा गांधी के आरंभिक सत्याग्रह: चंपारण (1917), अहमदाबाद मिल मजदूर एवं खेड़ा (1918)",
        "concepts_en": ["Gandhi returned to India from South Africa on 9 January 1915 (Pravasi Bharatiya Divas)", "Champaran Satyagraha (Bihar, 1917): First Civil Disobedience in India; Rajkumar Shukla invited Gandhi to protest Tinkathia system (compulsory 3/20 indigo cultivation)", "Ahmedabad Mill Strike (1918): First Hunger Strike by Gandhi demanding 35% plague bonus; Anusuya Sarabhai", "Kheda Satyagraha (1918): First Non-Cooperation movement; revenue exemption due to crop failure with Vallabhbhai Patel"],
        "concepts_hi": ["9 जनवरी 1915 को गांधीजी दक्षिण अफ्रीका से भारत लौटे (प्रवासी भारतीय दिवस)", "चंपारण सत्याग्रह (बिहार, 1917): भारत में पहला सविनय अवज्ञा आंदोलन; राजकुमार शुक्ल के बुलावे पर तिनकठिया प्रथा (3/20 भाग पर नील की खेती) के विरुद्ध सफल संघर्ष", "अहमदाबाद मिल हड़ताल (1918): गांधीजी की पहली भूख हड़ताल; 35% प्लेग बोनस की मांग", "खेड़ा सत्याग्रह (1918): पहला असहयोग आंदोलन; फसल नष्ट होने पर लगान माफी हेतु सरदार वल्लभभाई पटेल के साथ संघर्ष"],
        "q_en": "Against which exploitative agricultural arrangement requiring farmers to cultivate indigo on 3/20th of their land was Gandhi's historic Champaran Satyagraha of 1917 launched?",
        "q_hi": "गांधीजी का भारत में पहला सफल 'चंपारण सत्याग्रह' (1917) किस शोषणकारी कृषि व्यवस्था के विरुद्ध किया गया था, जिसमें जमीन के 3/20 भाग पर नील उगाना अनिवार्य था?",
        "options_en": ["Tinkathia System (तिनकठिया पद्धति)", "Ryotwari System", "Zabti System", "Izaredari System"],
        "options_hi": ["तिनकठिया पद्धति (Tinkathia System)", "रैयतवाड़ी पद्धति", "जब्ती प्रणाली", "इजारेदारी प्रथा"],
        "correct_idx": 0,
        "exp_en": "The Tinkathia system legally forced Bihari peasants to grow indigo on 3 out of every 20 kathas of their land. Gandhi investigated and secured its abolition.",
        "exp_hi": "चंपारण में यूरोपीय बागान मालिकों ने किसानों पर तिनकठिया प्रथा (20 कट्ठा में 3 कट्ठा पर नील की खेती) थोप रखी थी, जिसे गांधीजी के पहले सत्याग्रह ने समाप्त कराया।",
        "cue_en": "Champaran 1917 = Tinkathia system (3/20 indigo).",
        "cue_hi": "चंपारण सत्याग्रह (1917) = तिनकठिया प्रथा (3/20 भाग पर नील)।",
        "wrong_en": ["3/20 indigo requirement.", "British southern land tenure.", "Mughal revenue assessment.", "Revenue auction contract."],
        "wrong_hi": ["नील की अनिवार्य खेती का नियम।", "दक्षिण भारत का राजस्व बंदोबस्त।", "मुगल कालीन राजस्व प्रणाली।", "ठेकेदारी पर आधारित राजस्व।"]
    },
    {
        "name_en": "Non-Cooperation Movement (1920–22), Khilafat & Chauri Chaura Incident",
        "name_hi": "असहयोग आंदोलन (1920-22), खिलाफत आंदोलन एवं चौरी-चौरा की घटना",
        "concepts_en": ["Rowlatt Act (Black Act, 1919) and Jallianwala Bagh Massacre (13 April 1919) ordered by General Dyer; Rabindranath Tagore renounced Knighthood", "Khilafat Committee formed by Ali Brothers (Shaukat Ali and Mohammad Ali)", "Special session at Calcutta (Sept 1920) and Nagpur Congress (Dec 1920) approved Non-Cooperation resolution", "Chauri Chaura incident (Gorakhpur, UP, 4 February 1922) led Gandhi to abruptly suspend movement on 12 February 1922 at Bardoli"],
        "concepts_hi": ["रोलेट एक्ट ('बिना वकील, बिना अपील, बिना दलील') एवं जलियांवाला बाग नरसंहार (13 अप्रैल 1919); टैगोर ने 'नाइटहुड' उपाधि त्यागी", "खिलाफत आंदोलन: अली बंधुओं (शौकत अली व मोहम्मद अली) द्वारा तुर्की के खलीफा के समर्थन में आंदोलन", "नागपुर कांग्रेस अधिवेशन (दिसंबर 1920) में असहयोग का ऐतिहासिक प्रस्ताव पारित", "चौरी-चौरा कांड (गोरखपुर, 4 फरवरी 1922): थाने को जलाए जाने की हिंसक घटना के बाद गांधीजी ने 12 फरवरी 1922 को बारदोली में आंदोलन वापस ले लिया"],
        "q_en": "Following the violent clash at which police station in Gorakhpur district of Uttar Pradesh in February 1922 did Mahatma Gandhi call off the Non-Cooperation Movement?",
        "q_hi": "फरवरी 1922 में उत्तर प्रदेश के गोरखपुर जिले के किस थाने में हुई हिंसक घटना के कारण महात्मा गांधी ने असहयोग आंदोलन को अचानक वापस ले लिया था?",
        "options_en": ["Chauri Chaura (चौरी-चौरा)", "Kakori", "Kalyanpur", "Bardoli"],
        "options_hi": ["चौरी-चौरा (Chauri Chaura)", "काकोरी", "कल्याणपुर", "बारदोली"],
        "correct_idx": 0,
        "exp_en": "On 4 February 1922, a crowd burned down the police station at Chauri Chaura, killing 22 policemen. Distressed by violence, Gandhi called off the movement at Bardoli on 12 February.",
        "exp_hi": "4 फरवरी 1922 को चौरी-चौरा में उत्तेजित भीड़ ने थाने में आग लगा दी जिसमें 22 पुलिसकर्मी मारे गए; अहिंसा के सिद्धांत का उल्लंघन देखकर गांधीजी ने आंदोलन स्थगित कर दिया।",
        "cue_en": "Non-Cooperation withdrawn due to Chauri Chaura (1922).",
        "cue_hi": "असहयोग आंदोलन स्थगित = चौरी-चौरा कांड (1922)।",
        "wrong_en": ["Site of violent clash in 1922.", "Site of famous train action (1925).", "Railway junction near Kanpur.", "Site of CWC resolution withdrawing movement."],
        "wrong_hi": ["1922 की हिंसक घटना का स्थल।", "1925 के ट्रेन एक्शन का स्थल।", "कानपुर के निकट का कस्बा।", "जहां कार्यसमिति ने स्थगन प्रस्ताव पारित किया।"]
    },
    {
        "name_en": "Civil Disobedience Movement (Dandi March 1930) to Independence (1947)",
        "name_hi": "सविनय अवज्ञा आंदोलन (दांडी मार्च 1930) से भारत की स्वतंत्रता (1947)",
        "concepts_en": ["Lahore Congress (1929) under Jawaharlal Nehru adopted Poorna Swaraj (Complete Independence) resolution", "Dandi Salt March: Sabarmati to Dandi (12 March to 6 April 1930, 240 miles with 78 followers); broke Salt Law", "Gandhi-Irwin Pact (1931) and Second Round Table Conference; Poona Pact (1932) between Gandhi and Dr. Ambedkar", "Quit India Movement (8 August 1942) with 'Do or Die' mantra; Cabinet Mission Plan (1946) & Mountbatten Plan (3 June 1947) leading to Independence on 15 August 1947"],
        "concepts_hi": ["लाहौर कांग्रेस अधिवेशन (1929, जवाहरलाल नेहरू की अध्यक्षता) में 'पूर्ण स्वराज' का ऐतिहासिक प्रस्ताव पारित", "दांडी नमक सत्याग्रह: साबरमती से दांडी (12 मार्च से 6 अप्रैल 1930, 240 मील, 78 अनुयायी); नमक कानून तोड़ा", "गांधी-इरविन समझौता (1931) व द्वितीय गोलमेज सम्मेलन; गांधीजी व डॉ. अम्बेडकर के बीच पूना पैक्ट (1932)", "भारत छोड़ो आंदोलन (8 अगस्त 1942, 'करो या मरो' का नारा); कैबिनेट मिशन (1946) एवं माउंटबेटन योजना (3 जून 1947) से 15 अगस्त 1947 को स्वतंत्रता"],
        "q_en": "From which ashram did Mahatma Gandhi commence his historic 240-mile Salt March to Dandi on 12 March 1930?",
        "q_hi": "महात्मा गांधी ने 12 मार्च 1930 को 78 सत्याग्रहियों के साथ अपनी ऐतिहासिक 240 मील की दांडी नमक यात्रा किस आश्रम से प्रारंभ की थी?",
        "options_en": ["Sabarmati Ashram, Ahmedabad (साबरमती आश्रम)", "Sevagram Ashram, Wardha", "Phoenix Settlement, Durban", "Tolstoy Farm, Johannesburg"],
        "options_hi": ["साबरमती आश्रम, अहमदाबाद (Sabarmati Ashram)", "सेवाग्राम आश्रम, वर्धा", "फीनिक्स आश्रम, डरबन", "टॉलस्टॉय फार्म, जोहान्सबर्ग"],
        "correct_idx": 0,
        "exp_en": "Gandhi began the Dandi March on 12 March 1930 from Sabarmati Ashram in Ahmedabad, reaching Dandi on the Arabian Sea coast on 6 April 1930 to manufacture salt.",
        "exp_hi": "गांधीजी ने 12 मार्च 1930 को साबरमती आश्रम (अहमदाबाद) से दांडी यात्रा शुरू की और 6 अप्रैल 1930 को दांडी पहुंचकर समुद्र तट पर नमक बनाकर कानून तोड़ा।",
        "cue_en": "Dandi March: Sabarmati Ashram to Dandi (12 March – 6 April 1930).",
        "cue_hi": "दांडी यात्रा: साबरमती आश्रम से दांडी (12 मार्च से 6 अप्रैल 1930)।",
        "wrong_en": ["Starting point of Dandi March.", "Founded later in Maharashtra in 1936.", "Founded in South Africa in 1904.", "Founded in South Africa in 1910."],
        "wrong_hi": ["दांडी मार्च का प्रस्थान स्थल।", "1936 में महाराष्ट्र में स्थापित आश्रम।", "दक्षिण अफ्रीका में 1904 का आश्रम।", "दक्षिण अफ्रीका में 1910 का आश्रम।"]
    }
]

print("Loaded S04 (Chapters 4, 5, 6)")
