# build_curriculum/group2_s06.py
# S06: Governance, Panchayati Raj & Union Administration (17 topics across 4 chapters)

DATA = {}

# S06-C4397a951 Panchayati Raj System (Part IX, 73rd Amendment) (4 topics)
DATA["S06-C4397a951"] = [
    {
        "name_en": "Evolution of Panchayati Raj: Balwant Rai Mehta, Ashok Mehta & L.M. Singhvi Committees",
        "name_hi": "पंचायती राज का विकास: बलवंत राय मेहता, अशोक मेहता एवं एल.एम. सिंघवी समितियां",
        "concepts_en": ["Balwant Rai Mehta Committee (1957) recommended 3-tier Panchayati Raj system; first inaugurated at Nagaur, Rajasthan on 2 October 1959 by Nehru", "Ashok Mehta Committee (1977) recommended 2-tier system (Mandal Panchayat & Zila Parishad) and political party participation", "G.V.K. Rao Committee (1985) called PRIs 'grass without roots'", "L.M. Singhvi Committee (1986) recommended constitutional recognition for Panchayats"],
        "concepts_hi": ["बलवंत राय मेहता समिति (1957) ने त्रि-स्तरीय पंचायती राज की सिफारिश की; 2 अक्टूबर 1959 को राजस्थान के नागौर में नेहरू द्वारा उद्घाटन", "अशोक मेहता समिति (1977) ने द्वि-स्तरीय प्रणाली (मंडल पंचायत व जिला परिषद) की सिफारिश की", "जी.वी.के. राव समिति (1985) ने बिना जड़ की घास (grass without roots) कहा", "एल.एम. सिंघवी समिति (1986) ने पंचायतों को संवैधानिक दर्जा देने की पहली मजबूत सिफारिश की"],
        "q_en": "In which district and state of India was the democratic Panchayati Raj system inaugurated for the very first time on 2 October 1959 by Prime Minister Jawaharlal Nehru?",
        "q_hi": "2 अक्टूबर 1959 को प्रधानमंत्री जवाहरलाल नेहरू द्वारा भारत में सर्वप्रथम त्रि-स्तरीय पंचायती राज व्यवस्था का उद्घाटन किस जिले और राज्य में किया गया था?",
        "options_en": ["Nagaur, Rajasthan (नागौर, राजस्थान)", "Shadnagar, Andhra Pradesh", "Belgaum, Karnataka", "Varanasi, Uttar Pradesh"],
        "options_hi": ["नागौर, राजस्थान (Nagaur, Rajasthan)", "शादनगर, आंध्र प्रदेश", "बेलगाम, कर्नाटक", "वाराणसी, उत्तर प्रदेश"],
        "correct_idx": 0,
        "exp_en": "On 2 October 1959, Jawaharlal Nehru inaugurated the first Panchayati Raj institution at Nagaur, Rajasthan, followed shortly by Andhra Pradesh.",
        "exp_hi": "2 अक्टूबर 1959 को गांधी जयंती के अवसर पर राजस्थान के नागौर जिले में पहली ग्राम पंचायत का उद्घाटन हुआ, जिसके बाद आंध्र प्रदेश ने इसे अपनाया।",
        "cue_en": "First Panchayat = Nagaur, Rajasthan (2 Oct 1959).",
        "cue_hi": "पहली पंचायती राज व्यवस्था = नागौर, राजस्थान (2 अक्टूबर 1959)।",
        "wrong_en": ["First site of Panchayati Raj.", "Second state to adopt (late 1959).", "Site of 1924 Congress session.", "Eastern UP district."],
        "wrong_hi": ["पंचायती राज का पहला स्थल।", "दूसरा अपनाने वाला राज्य (आंध्र प्रदेश)।", "1924 कांग्रेस अधिवेशन स्थल।", "पूर्वी उत्तर प्रदेश का जिला।"]
    },
    {
        "name_en": "73rd Constitutional Amendment Act 1992 & Eleventh Schedule (29 Functional Items)",
        "name_hi": "73वां संविधान संशोधन अधिनियम 1992 एवं 11वीं अनुसूची (29 कार्यात्मक विषय)",
        "concepts_en": ["Passed in Dec 1992, enforced on 24 April 1993 (celebrated as National Panchayati Raj Day)", "Inserted Part IX ('The Panchayats', Articles 243 to 243-O) and Eleventh Schedule containing 29 subjects", "Mandatory provisions: Gram Sabha (Art 243A), 3-tier structure, 5-year tenure (Art 243E), State Finance Commission (Art 243-I), State Election Commission (Art 243K)", "Minimum 1/3rd (33%) reservation for women (Art 243D)"],
        "concepts_hi": ["दिसंबर 1992 में पारित, 24 अप्रैल 1993 से प्रभावी (राष्ट्रीय पंचायती राज दिवस)", "संविधान में भाग IX ('पंचायतें', अनुच्छेद 243 से 243-O) एवं 29 विषयों वाली 11वीं अनुसूची जोड़ी गई", "अनिवार्य प्रावधान: ग्राम सभा (243A), त्रि-स्तरीय ढांचा, 5 वर्ष का कार्यकाल (243E), राज्य वित्त आयोग (243-I), राज्य चुनाव आयोग (243K)", "महिलाओं के लिए न्यूनतम 1/3 (33%) आरक्षण का संवैधानिक प्रावधान (अनुच्छेद 243D)"],
        "q_en": "How many functional items/matters are listed under the Eleventh Schedule of the Constitution of India, placed within the purview of Panchayats by the 73rd Amendment?",
        "q_hi": "73वें संविधान संशोधन द्वारा भारतीय संविधान की 11वीं अनुसूची में पंचायतों के कार्यक्षेत्र के अंतर्गत कुल कितने विषयों की सूची दी गई है?",
        "options_en": ["29 subjects (29 विषय)", "18 subjects", "22 subjects", "12 subjects"],
        "options_hi": ["29 विषय (29 Functional Items)", "18 विषय", "22 विषय", "12 विषय"],
        "correct_idx": 0,
        "exp_en": "The Eleventh Schedule contains 29 functional items (such as agriculture, minor irrigation, animal husbandry, drinking water, roads) devolved to Panchayats.",
        "exp_hi": "संविधान की 11वीं अनुसूची में कुल 29 विषय हैं जिन पर पंचायतों को विधि बनाने और विकास योजनाएं लागू करने का अधिकार दिया गया है (नगर पालिकाओं के लिए 12वीं अनुसूची में 18 विषय हैं)।",
        "cue_en": "11th Schedule (Panchayats) = 29 subjects; 12th Schedule (Municipalities) = 18.",
        "cue_hi": "11वीं अनुसूची (पंचायत) = 29 विषय; 12वीं अनुसूची (नगर पालिका) = 18 विषय।",
        "wrong_en": ["Subjects under 11th Schedule.", "Subjects under 12th Schedule (Municipalities).", "Languages in 8th Schedule.", "Total schedules in Constitution."],
        "wrong_hi": ["11वीं अनुसूची के विषय।", "12वीं अनुसूची (नगर पालिका) के विषय।", "8वीं अनुसूची की भाषाएं।", "संविधान की कुल अनुसूचियां।"]
    },
    {
        "name_en": "Three-Tier Structure: Gram Panchayat, Panchayat Samiti & Zila Parishad",
        "name_hi": "त्रि-स्तरीय ढांचा: ग्राम पंचायत, पंचायत समिति एवं जिला परिषद",
        "concepts_en": ["Village level: Gram Panchayat headed by Sarpanch/Pradhan; Gram Sabha is electorate comprising all registered voters", "Intermediate / Block level: Panchayat Samiti / Janpad Panchayat headed by Block Pramukh, with Block Development Officer (BDO) as executive officer", "District level: Zila Parishad headed by District President, with District Collector / Chief Executive Officer (CEO)", "States with population below 20 lakhs may dispense with intermediate tier (Art 243B)"],
        "concepts_hi": ["ग्राम स्तर: ग्राम पंचायत (प्रधान/सरपंच); ग्राम सभा में गांव के सभी पंजीकृत मतदाता सदस्य होते हैं", "मध्यवर्ती / ब्लॉक स्तर: पंचायत समिति / जनपद पंचायत (अध्यक्ष ब्लॉक प्रमुख; प्रशासनिक प्रमुख खंड विकास अधिकारी - BDO)", "जिला स्तर: जिला परिषद (जिला पंचायत अध्यक्ष; प्रशासनिक प्रमुख मुख्य कार्यकारी अधिकारी - CEO / IAS)", "20 लाख से कम जनसंख्या वाले राज्यों को मध्यवर्ती स्तर न बनाने की छूट (अनुच्छेद 243B)"],
        "q_en": "Under Article 243A of the Indian Constitution, the 'Gram Sabha' consists of which group of individuals in a village?",
        "q_hi": "भारतीय संविधान के अनुच्छेद 243A के अनुसार 'ग्राम सभा' में गांव के कौन से व्यक्ति शामिल होते हैं?",
        "options_en": ["All persons registered in the electoral rolls relating to a village within the Panchayat area", "All adult residents above 18 years regardless of registration", "All heads of families residing in the village", "Elected ward members of the Gram Panchayat only"],
        "options_hi": ["पंचायत क्षेत्र के अंतर्गत गांव की मतदाता सूची में पंजीकृत सभी व्यक्ति", "गांव के सभी 18 वर्ष से ऊपर के निवासी चाहे वे पंजीकृत हों या न हों", "गांव में रहने वाले सभी परिवारों के मुखिया", "केवल ग्राम पंचायत के निर्वाचित वार्ड सदस्य"],
        "correct_idx": 0,
        "exp_en": "Article 243(b) defines Gram Sabha as a body consisting of persons registered in the electoral rolls relating to a village comprised within the area of Panchayat.",
        "exp_hi": "ग्राम सभा गांव के उन सभी व्यक्तियों का निकाय है जिनके नाम उस ग्राम पंचायत क्षेत्र की मतदाता सूची में दर्ज होते हैं। यह प्रत्यक्ष लोकतंत्र का सबसे जीवंत उदाहरण है।",
        "cue_en": "Gram Sabha = All registered voters of the village.",
        "cue_hi": "ग्राम सभा = गांव के सभी पंजीकृत मतदाता।",
        "wrong_en": ["Correct constitutional definition.", "Must be registered in electoral rolls.", "Not limited to heads of families.", "That is the Gram Panchayat, not Gram Sabha."],
        "wrong_hi": ["संवैधानिक परिभाषा।", "मतदाता सूची में नाम होना अनिवार्य है।", "केवल परिवार के मुखिया नहीं होते।", "यह ग्राम पंचायत है, ग्राम सभा नहीं।"]
    },
    {
        "name_en": "PESA Act 1996 (Panchayats Extension to Scheduled Areas) & Tribal Self-Rule",
        "name_hi": "पेसा अधिनियम 1996 (अनुसूचित क्षेत्रों पर पंचायतों का विस्तार) एवं जनजातीय स्वशासन",
        "concepts_en": ["Enacted on recommendations of Dileep Singh Bhuria Committee (1995)", "Extends Part IX provisions to Fifth Schedule areas across 10 states (AP, Telangana, Jharkhand, Gujarat, HP, MP, Maharashtra, Odisha, Rajasthan, Chhattisgarh)", "Empowers Gram Sabha to safeguard tribal traditions, customary law, minor forest produce (MFP) ownership", "Mandatory consultation before land acquisition or mineral mining leases"],
        "concepts_hi": ["दिलीप सिंह भूरिया समिति (1995) की सिफारिश पर 24 दिसंबर 1996 को संसद द्वारा पारित", "10 राज्यों के 5वीं अनुसूची के जनजातीय क्षेत्रों में भाग IX का विस्तार", "ग्राम सभा को परंपराओं, रूढ़िजन्य विधियों एवं लघु वनोपज (MFP) के स्वामित्व के पूर्ण अधिकार", "भूमि अधिग्रहण या लघु खनिजों के खनन पट्टे देने से पहले ग्राम सभा से अनिवार्य परामर्श"],
        "q_en": "The Provisions of the Panchayats (Extension to the Scheduled Areas) Act, 1996 (PESA) was enacted on the recommendations of which expert committee?",
        "q_hi": "अनुसूचित क्षेत्रों में जनजातीय स्वशासन की रक्षा हेतु 'पेसा अधिनियम 1996' (PESA Act) किस समिति की सिफारिशों के आधार पर संसद द्वारा पारित किया गया था?",
        "options_en": ["Dileep Singh Bhuria Committee (दिलीप सिंह भूरिया समिति)", "L.M. Singhvi Committee", "Ashok Mehta Committee", "Sarkaria Commission"],
        "options_hi": ["दिलीप सिंह भूरिया समिति (Dileep Singh Bhuria Committee)", "एल.एम. सिंघवी समिति", "अशोक मेहता समिति", "सरकारिया आयोग"],
        "correct_idx": 0,
        "exp_en": "The Bhuria Committee appointed in 1994 submitted its recommendations in 1995, leading to the enactment of the PESA Act on 24 December 1996.",
        "exp_hi": "1995 में दिलीप सिंह भूरिया समिति की रिपोर्ट के आधार पर पेसा कानून बनाया गया, जिसने आदिवासी क्षेत्रों में ग्राम सभा को स्वशासन और प्राकृतिक संसाधनों का रक्षक बनाया।",
        "cue_en": "PESA Act 1996 = Bhuria Committee.",
        "cue_hi": "पेसा कानून 1996 = भूरिया समिति।",
        "wrong_en": ["Recommended PESA legislation.", "Recommended constitutional status for Panchayats.", "Recommended 2-tier Panchayati Raj.", "Commission on Centre-State relations."],
        "wrong_hi": ["पेसा कानून की सिफारिश करने वाली समिति।", "पंचायतों को संवैधानिक दर्जे की सिफारिश।", "द्वि-स्तरीय व्यवस्था की सिफारिश।", "केंद्र-राज्य संबंध आयोग।"]
    }
]

# S06-C5c3ba939 Municipalities & Urban Local Bodies (Part IXA, 74th Amendment) (4 topics)
DATA["S06-C5c3ba939"] = [
    {
        "name_en": "74th Constitutional Amendment Act 1992 & Twelfth Schedule (18 Functions)",
        "name_hi": "74वां संविधान संशोधन अधिनियम 1992 एवं 12वीं अनुसूची (18 नगरीय कार्य)",
        "concepts_en": ["Enforced on 1 June 1993, inserted Part IXA ('The Municipalities', Articles 243P to 243ZG)", "Twelfth Schedule lists 18 functional items (urban planning, regulation of land use, water supply, public health, fire services)", "Three types of municipalities: Nagar Panchayat (transitional), Municipal Council (smaller urban area), Municipal Corporation (larger urban area)", "Ward Committees for wards having population of 3 lakhs or more (Art 243S)"],
        "concepts_hi": ["1 जून 1993 से लागू; संविधान में भाग IXA ('नगरपालिकाएं', अनुच्छेद 243P से 243ZG) जोड़ा गया", "12वीं अनुसूची में नगर निकायों को 18 कार्य सौंपे गए (शहरी नियोजन, भूमि उपयोग, जलापूर्ति, जनस्वास्थ्य, अग्निशमन)", "तीन प्रकार के नगरीय निकाय: नगर पंचायत (संक्रमणकालीन क्षेत्र), नगर पालिका परिषद (लघु शहरी क्षेत्र), नगर निगम (वृहद शहरी क्षेत्र)", "3 लाख या अधिक आबादी वाले वार्डों हेतु वार्ड समितियों का गठन (अनुच्छेद 243S)"],
        "q_en": "How many municipal functions and powers are enumerated under the Twelfth Schedule of the Indian Constitution introduced by the 74th Amendment?",
        "q_hi": "74वें संविधान संशोधन द्वारा भारतीय संविधान में जोड़ी गई 12वीं अनुसूची में शहरी स्थानीय निकायों (नगर पालिकाओं) के लिए कितने कार्यात्मक विषय सूचीबद्ध हैं?",
        "options_en": ["18 functions (18 विषय)", "29 functions", "12 functions", "21 functions"],
        "options_hi": ["18 विषय (18 Functions)", "29 विषय", "12 विषय", "21 विषय"],
        "correct_idx": 0,
        "exp_en": "The Twelfth Schedule added by the 74th Constitutional Amendment Act 1992 lists 18 municipal functional items devolved to Urban Local Bodies.",
        "exp_hi": "12वीं अनुसूची में कुल 18 विषय शामिल हैं, जिनमें नगर नियोजन, सड़कों व पुलों का निर्माण, सार्वजनिक स्वास्थ्य और ठोस अपशिष्ट प्रबंधन शामिल हैं।",
        "cue_en": "Twelfth Schedule (Municipalities) = 18 items.",
        "cue_hi": "12वीं अनुसूची (नगरपालिकाएं) = 18 विषय।",
        "wrong_en": ["Listed in Twelfth Schedule.", "Listed in Eleventh Schedule (Panchayats).", "Number of schedules.", "Incorrect count."],
        "wrong_hi": ["12वीं अनुसूची के विषय।", "11वीं अनुसूची (पंचायतों) के 29 विषय।", "कुल अनुसूचियों की संख्या।", "गलत संख्या।"]
    },
    {
        "name_en": "Urban Local Bodies: Municipal Corporations, Councils & Nagar Panchayats",
        "name_hi": "शहरी स्थानीय निकायों के प्रकार: नगर निगम, नगर पालिका परिषद एवं नगर पंचायत",
        "concepts_en": ["First Municipal Corporation in India established at Madras (1688), followed by Bombay and Calcutta (1726)", "Lord Ripon's Resolution of 1882 called Magna Carta of Local Self-Government (Ripon is 'Father of Local Self-Government in India')", "Municipal Corporation: Political head is Mayor; administrative head is Municipal Commissioner (IAS officer appointed by State)", "Cantonment Boards administered under Ministry of Defence (Cantonments Act 2006)"],
        "concepts_hi": ["भारत का पहला नगर निगम 1688 में मद्रास में स्थापित हुआ, जिसके बाद बंबई और कलकत्ता (1726) में बने", "लॉर्ड रिपन का 1882 का प्रस्ताव स्थानीय स्वशासन का 'मैग्नाकार्टा' माना जाता है (रिपन 'भारत में स्थानीय स्वशासन के जनक')", "नगर निगम: राजनीतिक प्रमुख 'महापौर' (मेयर) होता है; प्रशासनिक प्रमुख राज्य सरकार द्वारा नियुक्त 'नगर निगम आयुक्त' (IAS) होता है", "छावनी बोर्ड (Cantonment Boards) रक्षा मंत्रालय के सीधे नियंत्रण में प्रशासित होते हैं"],
        "q_en": "Where was the very first Municipal Corporation in India established by the British East India Company in the year 1688?",
        "q_hi": "ब्रिटिश ईस्ट इंडिया कंपनी द्वारा वर्ष 1688 में भारत के पहले नगर निगम (Municipal Corporation) की स्थापना कहां की गई थी?",
        "options_en": ["Madras (मद्रास - 1688)", "Bombay", "Calcutta", "Delhi"],
        "options_hi": ["मद्रास (Madras - Chennai)", "बंबई (Mumbai)", "कलकत्ता (Kolkata)", "दिल्ली"],
        "correct_idx": 0,
        "exp_en": "The Municipal Corporation of Madras was established by a royal charter issued by King James II in December 1687, formally functioning from 29 September 1688.",
        "exp_hi": "भारत का सबसे पहला नगर निगम 1688 में मद्रास (चेन्नई) में स्थापित किया गया था।",
        "cue_en": "First Municipal Corporation = Madras (1688).",
        "cue_hi": "पहला नगर निगम = मद्रास (1688)।",
        "wrong_en": ["First corporation in India (1688).", "Established in 1726.", "Established in 1726.", "Established in 1958."],
        "wrong_hi": ["पहला नगर निगम (1688)।", "1726 में स्थापित।", "1726 में स्थापित।", "1958 में स्थापित।"]
    },
    {
        "name_en": "Urban Governance: Mayor, Municipal Commissioner & District Planning Committee (Art 243ZD)",
        "name_hi": "शहरी शासन व्यवस्था: महापौर, नगर निगम आयुक्त एवं जिला योजना समिति (अनुच्छेद 243ZD)",
        "concepts_en": ["District Planning Committee (Art 243ZD): Consolidates plans prepared by Panchayats and Municipalities in the district; 4/5th members elected by and from elected members of Zila Parishad and Municipalities", "Metropolitan Planning Committee (Art 243ZE) for areas with population of 10 lakhs or more; 2/3rd members elected", "Separation of deliberative wing (Council headed by Mayor) and executive wing (Municipal Commissioner)", "State Finance Commission reviews financial position of Municipalities every 5 years (Art 243Y)"],
        "concepts_hi": ["जिला योजना समिति (अनुच्छेद 243ZD): जिले में पंचायतों और नगर पालिकाओं द्वारा तैयार योजनाओं को समेकित करती है; 4/5 सदस्य जिला पंचायत व नगर पालिकाओं के निर्वाचित सदस्यों में से चुने जाते हैं", "महानगर योजना समिति (अनुच्छेद 243ZE): 10 लाख से अधिक आबादी वाले महानगरीय क्षेत्रों हेतु; 2/3 सदस्य निर्वाचित", "विचार-विमर्श शाखा (मेयर की अध्यक्षता वाली परिषद) और कार्यपालक शाखा (नगर आयुक्त) का पृथक्करण", "राज्य वित्त आयोग (अनुच्छेद 243Y) हर 5 वर्ष में नगर पालिकाओं की वित्तीय स्थिति की समीक्षा करता है"],
        "q_en": "Under Article 243ZD of the Constitution, what fraction of members of the District Planning Committee (DPC) must be elected by and from the elected members of the district Panchayat and Municipalities?",
        "q_hi": "भारतीय संविधान के अनुच्छेद 243ZD के अनुसार जिला योजना समिति (DPC) के कुल सदस्यों का कितना भाग जिला पंचायत एवं नगर पालिकाओं के निर्वाचित सदस्यों द्वारा अपने में से चुना जाना अनिवार्य है?",
        "options_en": ["Four-fifths (4/5)", "Two-thirds (2/3)", "Three-fourths (3/4)", "Half (1/2)"],
        "options_hi": ["चार-पंचमांश (Four-fifths - 4/5)", "दो-तिहाई (2/3)", "तीन-चौथाई (3/4)", "आधा (1/2)"],
        "correct_idx": 0,
        "exp_en": "Under Article 243ZD(2)(b), not less than four-fifths (80%) of the total members of the District Planning Committee must be elected from the elected members of the Zila Parishad and Municipalities.",
        "exp_hi": "अनुच्छेद 243ZD के अनुसार जिला योजना समिति के कम से कम 4/5 (80%) सदस्य जिले की ग्रामीण पंचायतों और नगर पालिकाओं के निर्वाचित सदस्यों में से उनकी आबादी के अनुपात में चुने जाते हैं।",
        "cue_en": "District Planning Committee = 4/5th elected members.",
        "cue_hi": "जिला योजना समिति = 4/5 सदस्य निर्वाचित।",
        "wrong_en": ["Required proportion under Art 243ZD.", "Proportion for Metropolitan Planning Committee (Art 243ZE).", "Common legislative fraction.", "Incorrect proportion."],
        "wrong_hi": ["अनुच्छेद 243ZD के अनुसार सही अनुपात।", "महानगर योजना समिति (243ZE) का 2/3 अनुपात।", "गलत अनुपात।", "गलत अनुपात।"]
    },
    {
        "name_en": "Urban Renewal Missions: Smart Cities Mission, AMRUT & Swachh Bharat Urban",
        "name_hi": "शहरी पुनरुद्धार मिशन: स्मार्ट सिटीज मिशन, अमृत (AMRUT) एवं स्वच्छ भारत मिशन (नगरीय)",
        "concepts_en": ["Smart Cities Mission launched in June 2015 to develop 100 citizen-friendly, sustainable cities via Special Purpose Vehicles (SPVs) and Integrated Command & Control Centres (ICCC)", "AMRUT (Atal Mission for Rejuvenation and Urban Transformation) focused on water supply, sewerage, and stormwater drainage in 500 cities", "Swachh Bharat Mission (Urban) achieving Open Defecation Free (ODF) status and solid waste processing", "Pradhan Mantri Awas Yojana (Urban) housing for all"],
        "concepts_hi": ["स्मार्ट सिटीज मिशन (जून 2015): 100 शहरों को एसपीवी (SPV) और एकीकृत कमान एवं नियंत्रण केंद्रों (ICCC) के जरिए आधुनिक बनाना", "अमृत (AMRUT) योजना: 500 शहरों में बुनियादी नागरिक सुविधाएं जैसे नल से जलापूर्ति, सीवरेज नेटवर्क और हरित क्षेत्र विकसित करना", "स्वच्छ भारत मिशन (नगरीय): खुले में शौच से मुक्ति (ODF, ODF+) एवं वैज्ञानिक ठोस अपशिष्ट प्रबंधन", "प्रधानमंत्री आवास योजना (शहरी): सभी पात्र शहरी परिवारों को पक्के मकान उपलब्ध कराना"],
        "q_en": "What central technology platform serves as the nerve center for monitoring traffic, municipal services, security, and civic grievances in cities developed under the Smart Cities Mission?",
        "q_hi": "स्मार्ट सिटी मिशन के तहत शहरों में यातायात, सुरक्षा, नागरिक सेवाओं एवं आपदा प्रबंधन की चौबीसों घंटे निगरानी करने वाले तंत्र को क्या कहा जाता है?",
        "options_en": ["Integrated Command and Control Centre (ICCC)", "Central Municipal Network (CMN)", "Urban Operations Bureau (UOB)", "Smart Citizen Hub (SCH)"],
        "options_hi": ["एकीकृत कमान एवं नियंत्रण केंद्र (ICCC)", "केंद्रीय नगर निगम नेटवर्क (CMN)", "शहरी संचालन ब्यूरो (UOB)", "स्मार्ट नागरिक हब (SCH)"],
        "correct_idx": 0,
        "exp_en": "Integrated Command and Control Centres (ICCCs) act as the brain and nervous system of smart cities, integrating sensors, CCTV, solid waste management, and traffic systems.",
        "exp_hi": "स्मार्ट सिटीज में आईसीसीसी (ICCC) केंद्रीय नियंत्रण कक्ष के रूप में कार्य करता है, जो शहर के विभिन्न विभागों और डिजिटल सेंसरों के डेटा को एक मंच पर जोड़ता है।",
        "cue_en": "Smart Cities brain = Integrated Command and Control Centre (ICCC).",
        "cue_hi": "स्मार्ट सिटी का नियंत्रण तंत्र = ICCC।",
        "wrong_en": ["Correct nerve center for smart cities.", "Fictitious term.", "Fictitious term.", "Fictitious term."],
        "wrong_hi": ["स्मार्ट सिटी का सही नियंत्रण केंद्र।", "काल्पनिक नाम।", "काल्पनिक नाम।", "काल्पनिक नाम।"]
    }
]

# S06-Cbd122131 Administration of Union Territories & Special Areas (7 topics)
DATA["S06-Cbd122131"] = [
    {
        "name_en": "Administration of Union Territories: Articles 239 to 241 & Lieutenant Governors",
        "name_hi": "केंद्र शासित प्रदेशों का प्रशासन: अनुच्छेद 239 से 241 एवं उपराज्यपाल (LG)",
        "concepts_en": ["Part VIII of Constitution (Articles 239 to 241); administered directly by President through an Administrator or Lieutenant Governor (LG)", "Currently 8 Union Territories in India (Delhi, Puducherry, J&K have legislative assemblies)", "President can make regulations for peace, progress, and good government under Article 240 (Andaman, Lakshadweep, Dadra & Nagar Haveli and Daman & Diu, Ladakh)", "Parliament can establish High Courts for UTs or extend jurisdiction of existing High Court under Article 241 (Delhi has own High Court since 1966)"],
        "concepts_hi": ["संविधान का भाग VIII (अनुच्छेद 239 से 241); राष्ट्रपति द्वारा नियुक्त प्रशासक या उपराज्यपाल (LG) के माध्यम से प्रत्यक्ष प्रशासन", "भारत में वर्तमान में 8 केंद्र शासित प्रदेश (दिल्ली, पुडुचेरी और जम्मू-कश्मीर में अपनी विधानसभाएं हैं)", "अनुच्छेद 240 के तहत राष्ट्रपति को शांति, प्रगति व सुशासन हेतु विनियम बनाने की विशेष शक्ति", "अनुच्छेद 241 के तहत संसद किसी यूटी हेतु पृथक उच्च न्यायालय स्थापित कर सकती है (दिल्ली का 1966 से अपना उच्च न्यायालय है)"],
        "q_en": "Which is the only Union Territory in India that possesses its own independent High Court established by Parliament under Article 241 (since 1966)?",
        "q_hi": "भारत का एकमात्र केंद्र शासित प्रदेश कौन सा है जिसका अपना स्वतंत्र उच्च न्यायालय (High Court) 1966 से कार्यरत है?",
        "options_en": ["National Capital Territory of Delhi (दिल्ली)", "Puducherry", "Chandigarh", "Jammu and Kashmir"],
        "options_hi": ["राष्ट्रीय राजधानी क्षेत्र दिल्ली (NCT of Delhi)", "पुडुचेरी (मद्रास HC के अधीन)", "चंडीगढ़ (पंजाब-हरियाणा HC)", "जम्मू एवं कश्मीर (लद्दाख के साथ साझा)"],
        "correct_idx": 0,
        "exp_en": "Delhi is the only Union Territory with its own High Court, established in 1966. (Jammu & Kashmir High Court is shared with the UT of Ladakh).",
        "exp_hi": "दिल्ली एकमात्र ऐसा केंद्र शासित प्रदेश है जिसका अपना स्वतंत्र उच्च न्यायालय (1966 में स्थापित) है। पुडुचेरी मद्रास उच्च न्यायालय के अधीन है और चंडीगढ़ पंजाब व हरियाणा उच्च न्यायालय के अधीन है।",
        "cue_en": "Only UT with exclusive High Court = Delhi (1966).",
        "cue_hi": "एकमात्र यूटी जिसका अपना हाईकोर्ट है = दिल्ली (1966)।",
        "wrong_en": ["Only UT with exclusive High Court.", "Under jurisdiction of Madras High Court.", "Shared by Punjab and Haryana.", "Shared between J&K and Ladakh."],
        "wrong_hi": ["दिल्ली का अपना स्वतंत्र उच्च न्यायालय है।", "मद्रास उच्च न्यायालय के अधिकार क्षेत्र में।", "पंजाब और हरियाणा के साथ साझा।", "लद्दाख के साथ साझा उच्च न्यायालय।"]
    },
    {
        "name_en": "Special Constitutional Provisions for Delhi: Article 239AA & NCT Administration",
        "name_hi": "दिल्ली हेतु विशेष संवैधानिक प्रावधान: अनुच्छेद 239AA एवं राष्ट्रीय राजधानी क्षेत्र प्रशासन",
        "concepts_en": ["Inserted by 69th Constitutional Amendment Act 1991 (based on S. Balakrishnan Committee)", "Designated Union Territory of Delhi as 'National Capital Territory of Delhi' (NCT) with Legislative Assembly and Council of Ministers", "Legislative Assembly can legislate on State List and Concurrent List EXCEPT three subjects: Public Order, Police, and Land (Entry 1, 2, 18 of State List)", "Size of Council of Ministers capped at 10% of Assembly strength (Chief Minister + 6 Ministers = 7 total)"],
        "concepts_hi": ["69वें संविधान संशोधन अधिनियम 1991 (एस. बालकृष्णन समिति की रिपोर्ट पर आधारित) द्वारा अनुच्छेद 239AA जोड़ा गया", "दिल्ली को 'राष्ट्रीय राजधानी क्षेत्र' (NCT) का विशेष दर्जा तथा 70 सदस्यीय विधानसभा व मंत्रिपरिषद दी गई", "विधानसभा राज्य सूची और समवर्ती सूची के विषयों पर कानून बना सकती है, सिवाय तीन विषयों के: लोक व्यवस्था (Public Order), पुलिस (Police) और भूमि (Land)", "मंत्रिपरिषद का आकार विधानसभा की कुल सदस्य संख्या का 10% (मुख्यमंत्री सहित अधिकतम 7 मंत्री) निर्धारित है"],
        "q_en": "Under Article 239AA of the Constitution, the Legislative Assembly of the National Capital Territory of Delhi CANNOT make laws with respect to which three subjects of the State List?",
        "q_hi": "अनुच्छेद 239AA के तहत राष्ट्रीय राजधानी क्षेत्र दिल्ली की विधानसभा राज्य सूची के किन तीन विषयों पर कानून नहीं बना सकती?",
        "options_en": ["Public Order, Police, and Land (लोक व्यवस्था, पुलिस और भूमि)", "Public Health, Sanitation, and Education", "Agriculture, Forests, and Fisheries", "Local Government, Prisons, and Transport"],
        "options_hi": ["लोक व्यवस्था, पुलिस और भूमि (Public Order, Police, and Land)", "जनस्वास्थ्य, स्वच्छता और शिक्षा", "कृषि, वन और मत्स्य पालन", "स्थानीय शासन, जेल और परिवहन"],
        "correct_idx": 0,
        "exp_en": "Article 239AA(3)(a) excludes Public Order (Entry 1), Police (Entry 2), and Land (Entry 18) of the State List from the legislative competence of the Delhi Assembly.",
        "exp_hi": "अनुच्छेद 239AA स्पष्ट करता है कि राज्य सूची की प्रविष्टि 1 (लोक व्यवस्था), प्रविष्टि 2 (पुलिस) और प्रविष्टि 18 (भूमि) केंद्र सरकार के अधीन रहेंगे, जिन पर दिल्ली विधानसभा कानून नहीं बना सकती।",
        "cue_en": "Delhi Assembly exclusions = Public Order, Police, Land (Entries 1, 2, 18).",
        "cue_hi": "दिल्ली विधानसभा के अपवर्जित विषय = लोक व्यवस्था, पुलिस और भूमि।",
        "wrong_en": ["Three excluded subjects.", "Fully within competence of Delhi Assembly.", "Fully within competence of Delhi Assembly.", "Fully within competence of Delhi Assembly."],
        "wrong_hi": ["तीन विषय जो केंद्र के पास हैं।", "दिल्ली विधानसभा के अधिकार में हैं।", "दिल्ली विधानसभा के अधिकार में हैं।", "दिल्ली विधानसभा के अधिकार में हैं।"]
    },
    {
        "name_en": "Fifth Schedule Areas: Tribal Advisory Councils & Governor's Legislative Powers",
        "name_hi": "पांचवीं अनुसूची के क्षेत्र: जनजाति सलाहकार परिषद (TAC) एवं राज्यपाल की विधायी शक्तियां",
        "concepts_en": ["Article 244(1) applies to administration of Scheduled Areas and Scheduled Tribes in 10 states (excluding Assam, Meghalaya, Tripura, Mizoram)", "President declares an area as Scheduled Area (can alter boundaries in consultation with Governor)", "Governor has extraordinary legislative power: can direct an Act of Parliament/State Legislature shall not apply or apply with modifications", "Tribal Advisory Council (TAC) of up to 20 members (at least 3/4th representatives of STs in State Assembly)"],
        "concepts_hi": ["अनुच्छेद 244(1): 10 राज्यों में अनुसूचित क्षेत्रों और अनुसूचित जनजातियों का प्रशासन (असम, मेघालय, त्रिपुरा, मिजोरम को छोड़कर)", "राष्ट्रपति किसी भी क्षेत्र को अनुसूचित क्षेत्र घोषित कर सकते हैं", "राज्यपाल की असाधारण विधायी शक्ति: संसद या विधानसभा के किसी कानून को लागू न करने या संशोधित रूप में लागू करने का निर्देश दे सकते हैं", "जनजाति सलाहकार परिषद (TAC): अधिकतम 20 सदस्य, जिनमें से कम से कम 3/4 सदस्य राज्य विधानसभा में अनुसूचित जनजाति के विधायक होते हैं"],
        "q_en": "Who has the constitutional authority under the Fifth Schedule to declare an area as a 'Scheduled Area' or to increase or alter its boundaries?",
        "q_hi": "भारतीय संविधान की 5वीं अनुसूची के अंतर्गत किसी भी क्षेत्र को 'अनुसूचित क्षेत्र' घोषित करने अथवा उसकी सीमाओं में परिवर्तन करने की शक्ति किसे प्राप्त है?",
        "options_en": ["The President of India (भारत के राष्ट्रपति)", "The Governor of the State", "The Parliament by law", "The Union Tribal Affairs Minister"],
        "options_hi": ["भारत के राष्ट्रपति (The President of India)", "संबंधित राज्य के राज्यपाल", "संसद द्वारा कानून बनाकर", "केंद्रीय जनजातीय कार्य मंत्री"],
        "correct_idx": 0,
        "exp_en": "Paragraph 6 of the Fifth Schedule vests the power to declare any area to be a Scheduled Area, or alter its boundaries, exclusively in the President of India.",
        "exp_hi": "5वीं अनुसूची के पैरा 6 के अनुसार किसी भी क्षेत्र को अनुसूचित क्षेत्र घोषित करने या समाप्त करने का अनन्य अधिकार भारत के राष्ट्रपति को है।",
        "cue_en": "Declare Scheduled Area = President of India.",
        "cue_hi": "अनुसूचित क्षेत्र घोषित करना = राष्ट्रपति।",
        "wrong_en": ["Presidential constitutional power.", "Governor submits reports and administers.", "Parliament alters state boundaries under Art 3.", "Cabinet minister, not sovereign authority."],
        "wrong_hi": ["राष्ट्रपति की शक्ति।", "राज्यपाल वार्षिक रिपोर्ट देते हैं और प्रशासन चलाते हैं।", "संसद राज्यों की सीमा बदलती है।", "मंत्रालय के पास यह संवैधानिक शक्ति नहीं है।"]
    },
    {
        "name_en": "Sixth Schedule: Autonomous District Councils (ADCs) in Assam, Meghalaya, Tripura & Mizoram",
        "name_hi": "छठी अनुसूची: असम, मेघालय, त्रिपुरा एवं मिजोरम में स्वायत्त जिला परिषदें (ADCs)",
        "concepts_en": ["Article 244(2) and Article 275(1) apply specifically to the 4 northeastern tribal states ('AMTM': Assam, Meghalaya, Tripura, Mizoram)", "Creation of Autonomous District Councils (ADCs) and Regional Councils with substantial legislative, judicial, and financial autonomy", "ADC composition: Maximum 30 members (26 elected by adult franchise + 4 nominated by Governor for 5-year term)", "Can make laws on land, forests, canal water, shifting cultivation, marriage, customs; Governor's assent required"],
        "concepts_hi": ["अनुच्छेद 244(2) एवं 275(1): पूर्वोत्तर के चार जनजातीय राज्यों ('असम, मेघालय, त्रिपुरा, मिजोरम' - AMTM) पर लागू", "स्वायत्त जिला परिषदों (ADCs) और क्षेत्रीय परिषदों का गठन, जिन्हें विधायी, न्यायिक व वित्तीय स्वायत्तता प्राप्त है", "परिषद की संरचना: अधिकतम 30 सदस्य (26 वयस्क मताधिकार से निर्वाचित + 4 राज्यपाल द्वारा मनोनीत; 5 वर्ष का कार्यकाल)", "भूमि, वन, कृषि, विवाह, उत्तराधिकार और रीति-रिवाजों पर कानून बनाने की शक्ति; राज्यपाल की सहमति अनिवार्य"],
        "q_en": "Which four North-Eastern states are governed by the special tribal autonomy provisions of the Sixth Schedule of the Indian Constitution?",
        "q_hi": "भारतीय संविधान की छठी अनुसूची में किन चार पूर्वोत्तर राज्यों के जनजातीय क्षेत्रों के लिए स्वायत्त जिला परिषदों (ADCs) का विशेष प्रावधान किया गया है?",
        "options_en": ["Assam, Meghalaya, Tripura, and Mizoram (AMTM)", "Assam, Nagaland, Manipur, and Mizoram", "Arunachal Pradesh, Nagaland, Manipur, and Mizoram", "Meghalaya, Manipur, Tripura, and Sikkim"],
        "options_hi": ["असम, मेघालय, त्रिपुरा और मिजोरम (AMTM)", "असम, नागालैंड, मणिपुर और मिजोरम", "अरुणाचल प्रदेश, नागालैंड, मणिपुर और मिजोरम", "मेघालय, मणिपुर, त्रिपुरा और सिक्किम"],
        "correct_idx": 0,
        "exp_en": "The Sixth Schedule specifically applies to the tribal areas in the four states of Assam, Meghalaya, Tripura, and Mizoram (acronym AMTM).",
        "exp_hi": "छठी अनुसूची केवल चार राज्यों पर लागू होती है: असम, मेघालय, त्रिपुरा और मिजोरम (AMTM)। नागालैंड, मणिपुर और अरुणाचल इसमें शामिल नहीं हैं।",
        "cue_en": "Sixth Schedule states = AMTM (Assam, Meghalaya, Tripura, Mizoram).",
        "cue_hi": "छठी अनुसूची के 4 राज्य = असम, मेघालय, त्रिपुरा, मिजोरम (AMTM)।",
        "wrong_en": ["The four Sixth Schedule states.", "Nagaland and Manipur not in 6th Schedule.", "Arunachal, Nagaland, Manipur not in 6th Schedule.", "Manipur and Sikkim not in 6th Schedule."],
        "wrong_hi": ["छठी अनुसूची के सही 4 राज्य।", "नागालैंड और मणिपुर 6वीं अनुसूची में नहीं हैं।", "ये राज्य इसमें शामिल नहीं हैं।", "सिक्किम व मणिपुर शामिल नहीं हैं।"]
    },
    {
        "name_en": "Special Provisions for States: Article 371 Series (371A Nagaland, 371J Karnataka)",
        "name_hi": "राज्यों हेतु विशेष प्रावधान: अनुच्छेद 371 श्रृंखला (371A नागालैंड, 371J कर्नाटक आदि)",
        "concepts_en": ["Part XXI (Temporary, Transitional and Special Provisions); Article 371 (Maharashtra and Gujarat development boards)", "Article 371A (Nagaland): Parliament acts regarding Naga customary law, religious practices, and land ownership do not apply unless state assembly decides", "Article 371B (Assam), 371C (Manipur), 371D & 371E (Andhra Pradesh), 371F (Sikkim - 36th Amendment 1975)", "Article 371G (Mizoram), 371H (Arunachal Pradesh), 371-I (Goa), Article 371J (Kalyana-Karnataka region - 98th Amendment 2012)"],
        "concepts_hi": ["संविधान का भाग XXI: अनुच्छेद 371 (महाराष्ट्र के विदर्भ व मराठवाड़ा तथा गुजरात के सौराष्ट्र व कच्छ हेतु विकास बोर्ड)", "अनुच्छेद 371A (नागालैंड): नागा धार्मिक व सामाजिक परंपराओं, रूढ़िजन्य कानूनों और भूमि अधिकारों पर संसद का कोई कानून तब तक लागू नहीं होगा जब तक राज्य विधानसभा सहमति न दे", "अनुच्छेद 371B (असम), 371C (मणिपुर), 371D (आंध्र प्रदेश), 371F (सिक्किम - 36वां संशोधन 1975)", "अनुच्छेद 371G (मिजोरम), 371H (अरुणाचल प्रदेश), 371-I (गोवा), अनुच्छेद 371J (कल्याण-कर्नाटक / हैदराबाद-कर्नाटक क्षेत्र - 98वां संशोधन 2012)"],
        "q_en": "Which Article of the Constitution of India provides extraordinary protection to Nagaland, requiring that Acts of Parliament regarding Naga religious or social practices and land ownership require the state assembly's approval to apply?",
        "q_hi": "भारतीय संविधान का कौन सा अनुच्छेद नागालैंड को विशेष दर्जा देता है, जिसके अनुसार नागा प्रथाओं, रीति-रिवाजों और भूमि हस्तांतरण पर संसद का कोई कानून राज्य विधानसभा के अनुमोदन के बिना लागू नहीं हो सकता?",
        "options_en": ["Article 371A (अनुच्छेद 371A)", "Article 371F", "Article 371J", "Article 371G"],
        "options_hi": ["अनुच्छेद 371A (Article 371A - Nagaland)", "अनुच्छेद 371F (Sikkim)", "अनुच्छेद 371J (Karnataka)", "अनुच्छेद 371G (Mizoram)"],
        "correct_idx": 0,
        "exp_en": "Article 371A, inserted by the 13th Constitutional Amendment Act 1962, guarantees that no Act of Parliament concerning religious/social practices, customary law, or land ownership applies to Nagaland unless approved by its Legislative Assembly.",
        "exp_hi": "13वें संशोधन अधिनियम 1962 द्वारा जोड़ा गया अनुच्छेद 371A नागालैंड के लोगों की विशिष्ट सांस्कृतिक पहचान, प्रथागत कानून और भूमि अधिकारों को संवैधानिक संरक्षण प्रदान करता है।",
        "cue_en": "Article 371A = Nagaland special autonomy.",
        "cue_hi": "अनुच्छेद 371A = नागालैंड को विशेष प्रावधान।",
        "wrong_en": ["Protects Nagaland customary laws.", "Special provisions for Sikkim.", "Special provisions for Kalyana-Karnataka.", "Special provisions for Mizoram."],
        "wrong_hi": ["नागालैंड का विशेष संरक्षण।", "सिक्किम हेतु विशेष प्रावधान।", "कल्याण-कर्नाटक हेतु विशेष प्रावधान।", "मिजोरम हेतु विशेष प्रावधान।"]
    },
    {
        "name_en": "Inter-State Council (Article 263) & Zonal Councils (States Reorganisation Act 1956)",
        "name_hi": "अंतर्राज्यीय परिषद (अनुच्छेद 263) एवं क्षेत्रीय परिषदें (राज्य पुनर्गठन अधिनियम 1956)",
        "concepts_en": ["Inter-State Council (Article 263): Constitutional body established by Presidential Order in May 1990 on Sarkaria Commission recommendations", "Chaired by Prime Minister; members include Chief Ministers of all States and UTs with assemblies, administrators of other UTs, and 6 Union Cabinet Ministers", "Zonal Councils: Statutory bodies created under States Reorganisation Act 1956 (Northern, Central, Eastern, Western, Southern); Union Home Minister is common chairman", "North-Eastern Council (NEC) established separately under North Eastern Council Act 1971 (8 states including Sikkim)"],
        "concepts_hi": ["अंतर्राज्यीय परिषद (अनुच्छेद 263): सरकारिया आयोग की सिफारिश पर मई 1990 में राष्ट्रपति के आदेश द्वारा गठित संवैधानिक निकाय", "अध्यक्ष प्रधानमंत्री होते हैं; सभी राज्यों व विधानसभा वाले यूटी के मुख्यमंत्री, अन्य यूटी के प्रशासक और 6 कैबिनेट मंत्री सदस्य होते हैं", "क्षेत्रीय परिषदें (Zonal Councils): राज्य पुनर्गठन अधिनियम 1956 के तहत गठित सांविधिक निकाय (उत्तरी, मध्य, पूर्वी, पश्चिमी, दक्षिणी); केंद्रीय गृह मंत्री सभी के साझा अध्यक्ष होते हैं", "पूर्वोत्तर परिषद (NEC): पूर्वोत्तर परिषद अधिनियम 1971 के तहत गठित (सिक्किम सहित 8 राज्य शामिल)"],
        "q_en": "Who serves as the permanent Chairman of the five statutory Zonal Councils established under the States Reorganisation Act of 1956?",
        "q_hi": "राज्य पुनर्गठन अधिनियम 1956 के तहत स्थापित पांचों सांविधिक क्षेत्रीय परिषदों (Zonal Councils) का पदेन अध्यक्ष कौन होता है?",
        "options_en": ["Union Home Minister (केंद्रीय गृह मंत्री)", "Prime Minister of India", "President of India", "Chief Ministers of member states on rotation"],
        "options_hi": ["केंद्रीय गृह मंत्री (Union Home Minister)", "भारत के प्रधानमंत्री", "भारत के राष्ट्रपति", "सदस्य राज्यों के मुख्यमंत्री (रोटेशन पर)"],
        "correct_idx": 0,
        "exp_en": "Under Section 16 of the States Reorganisation Act 1956, the Union Home Minister is the common Chairman of all five Zonal Councils, while Chief Ministers act as Vice-Chairmen on annual rotation.",
        "exp_hi": "पांचों क्षेत्रीय परिषदों के अध्यक्ष केंद्रीय गृह मंत्री होते हैं। संबंधित राज्यों के मुख्यमंत्री रोटेशन के आधार पर एक वर्ष के लिए उपाध्यक्ष बनते हैं। (अंतर्राज्यीय परिषद के अध्यक्ष प्रधानमंत्री होते हैं)।",
        "cue_en": "Zonal Councils Chairman = Union Home Minister (Inter-State Council = PM).",
        "cue_hi": "क्षेत्रीय परिषदों के अध्यक्ष = केंद्रीय गृह मंत्री (अंतर्राज्यीय परिषद के = प्रधानमंत्री)।",
        "wrong_en": ["Chairman of all Zonal Councils.", "Chairman of Inter-State Council (Art 263).", "Appoints administrators.", "Act as Vice-Chairmen on rotation."],
        "wrong_hi": ["सभी क्षेत्रीय परिषदों के साझा अध्यक्ष।", "अंतर्राज्यीय परिषद के अध्यक्ष होते हैं।", "संवैधानिक प्रमुख।", "रोटेशन पर उपाध्यक्ष बनते हैं।"]
    },
    {
        "name_en": "Finance Commission of India (Article 280): Tax Devolution & Horizontal Criteria",
        "name_hi": "भारत का वित्त आयोग (अनुच्छेद 280): करों का विभाजन एवं क्षैतिज वितरण के मानदंड",
        "concepts_en": ["Quasi-judicial constitutional body constituted by President every five years (or earlier) under Article 280", "Composition: Chairman + 4 other members appointed by President (qualifications prescribed by Parliament in Finance Commission Act 1951)", "Functions: Recommends distribution of net tax proceeds between Centre and States (Vertical devolution) and among States (Horizontal devolution); grants-in-aid (Art 275)", "Measures to augment Consolidated Fund of States to supplement resources of Panchayats and Municipalities"],
        "concepts_hi": ["अर्ध-न्यायिक संवैधानिक निकाय; राष्ट्रपति द्वारा प्रत्येक पांचवें वर्ष (या पूर्व) अनुच्छेद 280 के तहत गठित", "संरचना: 1 अध्यक्ष + 4 अन्य सदस्य (वित्त आयोग अधिनियम 1951 द्वारा निर्धारित योग्यताएं)", "कार्य: केंद्र और राज्यों के बीच शुद्ध कर आगमों के वितरण (वर्टिकल डिवोल्यूशन) और राज्यों के बीच आवंटन (हॉरिजॉन्टल डिवोल्यूशन) की सिफारिश; सहायता अनुदान (अनुच्छेद 275)", "पंचायतों और नगर पालिकाओं के संसाधनों की पूर्ति हेतु राज्य की संचित निधि में वृद्धि के उपाय सुझाना"],
        "q_en": "Under Article 280 of the Constitution of India, who possesses the constitutional mandate to constitute the Finance Commission every five years?",
        "q_hi": "भारतीय संविधान के अनुच्छेद 280 के तहत प्रत्येक पांच वर्ष की समाप्ति पर या उससे पहले 'वित्त आयोग' का गठन करने का संवैधानिक अधिकार किसे प्राप्त है?",
        "options_en": ["The President of India (भारत के राष्ट्रपति)", "The Union Finance Minister", "The Parliament of India", "The NITI Aayog"],
        "options_hi": ["भारत के राष्ट्रपति (The President of India)", "केंद्रीय वित्त मंत्री", "भारत की संसद", "नीति आयोग"],
        "correct_idx": 0,
        "exp_en": "Article 280(1) states that the President shall, within two years from commencement and thereafter at the expiration of every fifth year, constitute a Finance Commission.",
        "exp_hi": "अनुच्छेद 280(1) के तहत राष्ट्रपति प्रत्येक पांचवें वर्ष या जब भी वे आवश्यक समझें, एक वित्त आयोग का गठन करते हैं जिसमें एक अध्यक्ष और चार अन्य सदस्य होते हैं।",
        "cue_en": "Finance Commission constituted by = President (Art 280).",
        "cue_hi": "वित्त आयोग का गठन = राष्ट्रपति (अनुच्छेद 280)।",
        "wrong_en": ["Constitutes the Finance Commission.", "Presents Union Budget, receives report.", "Prescribes qualifications by law.", "Policy think tank, replaced Planning Commission."],
        "wrong_hi": ["वित्त आयोग का गठन करते हैं।", "रिपोर्ट प्राप्त करते हैं और संसद में रखते हैं।", "सदस्यों की अर्हताएं तय करती है।", "नीतिगत थिंक टैंक है।"]
    }
]

# S06-C22b72712 Constitutional & Statutory Bodies, Tribunals & CAG (2 topics)
DATA["S06-C22b72712"] = [
    {
        "name_en": "Comptroller and Auditor General of India (CAG, Article 148): Guardian of the Public Purse",
        "name_hi": "भारत के नियंत्रक एवं महालेखापरीक्षक (CAG, अनुच्छेद 148): सार्वजनिक धन का संरक्षक",
        "concepts_en": ["Dr. Ambedkar called CAG 'the most important officer under the Constitution of India'", "Appointed by President under Article 148; tenure 6 years or up to 65 years of age; removed on same grounds and manner as Supreme Court judge", "Ineligible for further office under Government of India or State after retirement (Art 148(4))", "Audits all expenditure from Consolidated Fund of India, States, and UTs; submits three audit reports to President under Article 151 (laid before Parliament and examined by PAC)"],
        "concepts_hi": ["डॉ. अम्बेडकर ने सीएजी को 'भारतीय संविधान के तहत सबसे महत्वपूर्ण अधिकारी' बताया था", "अनुच्छेद 148 के तहत राष्ट्रपति द्वारा नियुक्ति; कार्यकाल 6 वर्ष या 65 वर्ष की आयु (जो भी पहले हो); सुप्रीम कोर्ट के जज की तरह ही हटाया जा सकता है", "सेवानिवृत्ति के बाद भारत सरकार या राज्य सरकार के अधीन कोई अन्य पद धारण नहीं कर सकते (अनुच्छेद 148(4))", "भारत और राज्यों की संचित निधि से किए गए सभी व्यय की लेखापरीक्षा; अनुच्छेद 151 के तहत राष्ट्रपति को रिपोर्ट प्रस्तुत करते हैं, जिसकी जांच संसद की लोक लेखा समिति (PAC) करती है"],
        "q_en": "What is the official tenure of office of the Comptroller and Auditor General of India (CAG) under the CAG (DPC) Act, 1971?",
        "q_hi": "सीएजी (कर्तव्य, शक्तियां एवं सेवा शर्तें) अधिनियम 1971 के अनुसार भारत के नियंत्रक एवं महालेखापरीक्षक (CAG) का आधिकारिक कार्यकाल कितना होता है?",
        "options_en": ["6 years or up to the age of 65 years, whichever is earlier", "5 years or up to the age of 65 years, whichever is earlier", "6 years or up to the age of 62 years, whichever is earlier", "5 years or up to the age of 70 years, whichever is earlier"],
        "options_hi": ["6 वर्ष या 65 वर्ष की आयु, जो भी पहले हो", "5 वर्ष या 65 वर्ष की आयु, जो भी पहले हो", "6 वर्ष या 62 वर्ष की आयु, जो भी पहले हो", "5 वर्ष या 70 वर्ष की आयु, जो भी पहले हो"],
        "correct_idx": 0,
        "exp_en": "The CAG holds office for a term of 6 years or until attaining the age of 65 years, whichever occurs earlier, ensuring independence from executive influence.",
        "exp_hi": "सीएजी का कार्यकाल 6 वर्ष अथवा 65 वर्ष की आयु प्राप्त करने तक (जो भी पहले पूरा हो) होता है।",
        "cue_en": "CAG tenure = 6 years or 65 years of age.",
        "cue_hi": "सीएजी कार्यकाल = 6 वर्ष या 65 वर्ष की आयु।",
        "wrong_en": ["Correct statutory tenure.", "Tenure of Chief Election Commissioner is also 6/65, not 5.", "62 years is for High Court judges.", "Incorrect tenure."],
        "wrong_hi": ["सही वैधानिक कार्यकाल।", "5 वर्ष नहीं होता।", "62 वर्ष उच्च न्यायालय के जजों की आयु है।", "गलत कार्यकाल।"]
    },
    {
        "name_en": "Constitutional Watchdogs & Statutory Bodies: Election Commission, UPSC & NHRC",
        "name_hi": "संवैधानिक एवं संविधिक निकाय: निर्वाचन आयोग (अनुच्छेद 324), यूपीएससी (अनुच्छेद 315) एवं राष्ट्रीय मानवाधिकार आयोग (NHRC)",
        "concepts_en": ["Election Commission of India (Article 324): Multi-member body (Chief Election Commissioner + 2 ECs) conducting elections to Parliament, State Legislatures, President, and VP", "UPSC (Articles 315 to 323): Conducts civil services examinations and advises President on disciplinary matters (tenure 6 years or 65 years)", "National Human Rights Commission (NHRC): Statutory body created under Protection of Human Rights Act 1993; chaired by retired CJI or Supreme Court judge", "NITI Aayog: Non-constitutional, non-statutory think tank formed on 1 Jan 2015 replacing Planning Commission"],
        "concepts_hi": ["भारत का निर्वाचन आयोग (अनुच्छेद 324): तीन सदस्यीय निकाय (मुख्य चुनाव आयुक्त + 2 चुनाव आयुक्त) जो संसद, विधानमंडल, राष्ट्रपति और उपराष्ट्रपति के चुनाव कराता है", "संघ लोक सेवा आयोग (अनुच्छेद 315 से 323): अखिल भारतीय व केंद्रीय सेवाओं की भर्ती और अनुशासनात्मक परामर्श (कार्यकाल 6 वर्ष या 65 वर्ष)", "राष्ट्रीय मानवाधिकार आयोग (NHRC): मानवाधिकार संरक्षण अधिनियम 1993 के तहत स्थापित सांविधिक निकाय; अध्यक्ष पूर्व मुख्य न्यायाधीश या सुप्रीम कोर्ट के जज होते हैं", "नीति आयोग: 1 जनवरी 2015 को योजना आयोग के स्थान पर स्थापित गैर-संवैधानिक व गैर-सांविधिक नीतिगत थिंक टैंक"],
        "q_en": "Under Article 324 of the Constitution of India, the superintendence, direction, and control of elections to which of the following offices is NOT vested in the Election Commission of India?",
        "q_hi": "भारतीय संविधान के अनुच्छेद 324 के अनुसार निम्नलिखित में से किस निकाय के चुनावों का संचालन भारत के निर्वाचन आयोग (ECI) के अधिकार क्षेत्र में नहीं आता?",
        "options_en": ["Panchayats and Municipalities in the States (पंचायतों और नगर पालिकाओं के चुनाव)", "The Parliament (Lok Sabha & Rajya Sabha)", "The State Legislative Assemblies & Councils", "The Offices of President and Vice-President"],
        "options_hi": ["राज्यों की पंचायतों और नगर पालिकाओं के चुनाव", "संसद (लोकसभा एवं राज्यसभा)", "राज्य विधानसभाएं एवं विधान परिषदें", "राष्ट्रपति एवं उपराष्ट्रपति का पद"],
        "correct_idx": 0,
        "exp_en": "Elections to Panchayats and Municipalities are conducted exclusively by State Election Commissions under Articles 243K and 243ZA, not by the Election Commission of India.",
        "exp_hi": "पंचायतों और नगर पालिकाओं के चुनाव कराने का दायित्व संबंधित 'राज्य निर्वाचन आयोग' (अनुच्छेद 243K व 243ZA) का होता है, भारत के निर्वाचन आयोग (ECI) का नहीं।",
        "cue_en": "Local body elections = State Election Commission, NOT Election Commission of India.",
        "cue_hi": "पंचायतों के चुनाव = राज्य निर्वाचन आयोग (ECI नहीं)।",
        "wrong_en": ["Conducted by State Election Commissions.", "Conducted by Election Commission of India.", "Conducted by Election Commission of India.", "Conducted by Election Commission of India."],
        "wrong_hi": ["राज्य चुनाव आयोग द्वारा कराए जाते हैं।", "भारत निर्वाचन आयोग कराता है।", "भारत निर्वाचन आयोग कराता है।", "भारत निर्वाचन आयोग कराता है।"]
    }
]

print("Loaded S06 successfully")
