# build_curriculum/group3_s08.py
# S08: World Geography & Physical Landforms (18 topics across 3 chapters)

DATA = {}

# S08-C9270c63f Interior of Earth, Plate Tectonics & Volcanism (7 topics)
DATA["S08-C9270c63f"] = [
    {
        "name_en": "Interior Structure of the Earth: Crust, Mantle, Asthenosphere & Core",
        "name_hi": "पृथ्वी की आंतरिक संरचना: भूपर्पटी (क्रस्ट), मेंटल, दुर्बलता मंडल (एस्थेनोस्फीयर) एवं क्रोड",
        "concepts_en": ["Crust: Continental (SIAL - Silica & Aluminium, 30-50 km thick) and Oceanic (SIMA - Silica & Magnesium, 5-10 km thick)", "Mantle: Extends to 2,900 km depth; upper mantle contains semi-molten Asthenosphere (source of magma)", "Core: Outer Core (liquid iron-nickel generates geomagnetic dynamo) and Inner Core (solid iron-nickel under extreme pressure)", "Temperature increases ~1°C per 32 meters depth"],
        "concepts_hi": ["भूपर्पटी (Crust): महाद्वीपीय (सियाल - सिलिका व एल्युमीनियम) एवं महासागरीय (सीमा - सिलिका व मैग्नीशियम)", "मेंटल (Mantle): 2,900 किमी गहराई तक; ऊपरी मेंटल में अर्ध-पिघला 'दुर्बलता मंडल' (Asthenosphere), जो मैग्मा का मुख्य स्रोत है", "क्रोड (Core / निफे): बाह्य क्रोड (तरल लोहा-निकल, जो पृथ्वी का चुंबकीय क्षेत्र बनाता है) एवं आंतरिक क्रोड (ठोस)", "गहराई के साथ तापमान में वृद्धि (लगभग 32 मीटर पर 1°C)"],
        "q_en": "The upper semi-molten layer of the Earth's mantle, located between roughly 100 km and 400 km depth upon which tectonic plates float, is known as the:",
        "q_hi": "पृथ्वी के मेंटल का लगभग 100 से 400 किमी की गहराई में स्थित वह अर्ध-पिघला (प्लास्टिक) स्तर क्या कहलाता है, जिस पर विवर्तनिक प्लेटें तैरती हैं?",
        "options_en": ["Asthenosphere (दुर्बलता मंडल / एस्थेनोस्फीयर)", "Lithosphere", "Mesosphere", "Barysphere"],
        "options_hi": ["दुर्बलता मंडल / एस्थेनोस्फीयर (Asthenosphere)", "स्थल मंडल (Lithosphere)", "मध्य मंडल (Mesosphere)", "गुरु मंडल (Barysphere)"],
        "correct_idx": 0,
        "exp_en": "The Asthenosphere (from Greek asthenes, meaning weak) is the ductile, mechanically weak zone of the upper mantle on which the rigid lithospheric plates glide.",
        "exp_hi": "दुर्बलता मंडल (Asthenosphere) ऊपरी मेंटल का अत्यधिक तप्त एवं प्लास्टिक जैसा कमजोर भाग है; इसी के ऊपर पृथ्वी की दृढ़ स्थलमंडलीय प्लेटें गतिशील रहती हैं।",
        "cue_en": "Weak semi-molten mantle layer = Asthenosphere.",
        "cue_hi": "दुर्बल प्लास्टिक मेंटल स्तर = एस्थेनोस्फीयर।",
        "wrong_en": ["Semi-molten ductile mantle layer.", "Rigid crust and uppermost mantle.", "Deeper lower mantle zone.", "Central dense core region."],
        "wrong_hi": ["अर्ध-पिघला दुर्बल मेंटल।", "दृढ़ क्रस्ट और ऊपरी मेंटल का ऊपरी भाग।", "गहरा निचला मेंटल।", "पृथ्वी का केंद्रीय क्रोड।"]
    },
    {
        "name_en": "Seismic Discontinuities: Mohorovicic, Gutenberg & Lehmann Transitions",
        "name_hi": "भूगर्भिक असंबद्धताएं (Discontinuities): मोहोरोविसिक, गुटेनबर्ग एवं लेहमन असंबद्धता",
        "concepts_en": ["Conrad Discontinuity: Between upper crust and lower crust", "Mohorovicic Discontinuity (Moho): Boundary separating the Earth's crust from the mantle", "Repetti Discontinuity: Between upper mantle and lower mantle", "Gutenberg Discontinuity: Separates mantle from liquid outer core (at ~2,900 km depth)", "Lehmann Discontinuity: Boundary between liquid outer core and solid inner core (at ~5,150 km)"],
        "concepts_hi": ["कॉनराड असंबद्धता: ऊपरी क्रस्ट और निचले क्रस्ट के मध्य", "मोहोरोविसिक असंबद्धता (मोहो): भूपर्पटी (क्रस्ट) और मेंटल के बीच की सीमा", "रेपेटी असंबद्धता: ऊपरी मेंटल और निचले मेंटल के मध्य", "गुटेनबर्ग असंबद्धता: मेंटल और बाह्य तरल क्रोड के बीच (~2,900 किमी गहराई पर)", "लेहमन असंबद्धता: बाह्य तरल क्रोड और आंतरिक ठोस क्रोड के मध्य (~5,150 किमी पर)"],
        "q_en": "Which seismic discontinuity marks the sharp transitional boundary separating the Earth's crust from the underlying mantle?",
        "q_hi": "पृथ्वी की भूपर्पटी (Crust) और उसके नीचे स्थित मेंटल (Mantle) को एक-दूसरे से अलग करने वाली भूगर्भिक असंबद्धता कौन सी है?",
        "options_en": ["Mohorovicic Discontinuity (मोहो असंबद्धता)", "Gutenberg Discontinuity", "Conrad Discontinuity", "Lehmann Discontinuity"],
        "options_hi": ["मोहोरोविसिक असंबद्धता / मोहो (Mohorovicic Discontinuity)", "गुटेनबर्ग असंबद्धता", "कॉनराड असंबद्धता", "लेहमन असंबद्धता"],
        "correct_idx": 0,
        "exp_en": "Discovered by Croatian seismologist Andrija Mohorovicic in 1909, the Moho discontinuity separates the crust from the mantle where seismic P-wave velocity jumps abruptly.",
        "exp_hi": "मोहोरोविसिक (मोहो) असंबद्धता क्रस्ट और मेंटल के बीच स्थित है; यहां घनत्व में अचानक वृद्धि होने से भूकंपीय तरंगों की गति अचानक बढ़ जाती है।",
        "cue_en": "Crust-Mantle boundary = Moho Discontinuity.",
        "cue_hi": "क्रस्ट और मेंटल की सीमा = मोहो असंबद्धता।",
        "wrong_en": ["Separates crust from mantle.", "Separates mantle from outer core (2,900 km).", "Separates upper and lower crust.", "Separates outer and inner core."],
        "wrong_hi": ["क्रस्ट और मेंटल के बीच।", "मेंटल और बाह्य क्रोड के बीच।", "ऊपरी और निचले क्रस्ट के बीच।", "बाह्य और आंतरिक क्रोड के बीच।"]
    },
    {
        "name_en": "Continental Drift Theory (Alfred Wegener) & Sea Floor Spreading (Harry Hess)",
        "name_hi": "महाद्वीपीय विस्थापन सिद्धांत (अल्फ्रेड वेगनर) एवं सागर नितल प्रसरण (हैरी हेस)",
        "concepts_en": ["Alfred Wegener proposed Continental Drift in 1912: Supercontinent Pangaea surrounded by superocean Panthalassa", "Pangaea broke into Laurasia (Angaraland) in north and Gondwanaland in south, separated by Tethys Sea", "Evidence: 'Jigsaw-fit' of South America and Africa, Glossopteris fossil flora, Mesosaurus reptile fossils, Tillite glacial deposits", "Harry Hess proposed Sea Floor Spreading (1960): Mid-Oceanic Ridges create new basaltic crust; magnetic striping/paleomagnetism"],
        "concepts_hi": ["अल्फ्रेड वेगनर ने 1912 में महाद्वीपीय विस्थापन सिद्धांत दिया: विशाल महाद्वीप पेंजिया और विशाल महासागर पैंथालासा", "पेंजिया का विखंडन: उत्तर में लौरेशिया (अंगारालैंड) और दक्षिण में गोंडवानालैंड, बीच में टेथिस सागर", "प्रमाण: दक्षिण अमेरिका और अफ्रीका का 'जिग-सॉ फिट' (तटों का मेल), ग्लोसोप्टेरिस जीवाश्म, मेसोसॉरस जीवाश्म, हिमानी टिलाइट जमाव", "हैरी हेस (1960) का सागर नितल प्रसरण सिद्धांत: मध्य महासागरीय कटक पर नए बेसाल्टिक क्रस्ट का निर्माण"],
        "q_en": "According to Alfred Wegener's Continental Drift Theory, the ancient southern supercontinent formed after the initial split of Pangaea was named:",
        "q_hi": "अल्फ्रेड वेगनर के महाद्वीपीय विस्थापन सिद्धांत के अनुसार पेंजिया के आरंभिक विखंडन के पश्चात बने दक्षिणी विशाल भूभाग को क्या नाम दिया गया था?",
        "options_en": ["Gondwanaland (गोंडवानालैंड)", "Laurasia", "Panthalassa", "Rodinia"],
        "options_hi": ["गोंडवानालैंड (Gondwanaland)", "लौरेशिया (अंगारालैंड)", "पैंथालासा (Panthalassa)", "रोडिनिया (Rodinia)"],
        "correct_idx": 0,
        "exp_en": "Pangaea fractured into Laurasia (North America, Europe, Asia) in the north and Gondwanaland (South America, Africa, Peninsular India, Australia, Antarctica) in the south.",
        "exp_hi": "पेंजिया के दो टुकड़े हुए: उत्तरी भाग लौरेशिया (अंगारालैंड) कहलाया और दक्षिणी भाग गोंडवानालैंड कहलाया, जिसमें भारत, अफ्रीका, दक्षिण अमेरिका, ऑस्ट्रेलिया और अंटार्कटिका शामिल थे।",
        "cue_en": "Pangaea split = Laurasia (North) + Gondwanaland (South).",
        "cue_hi": "पेंजिया का विभाजन = लौरेशिया (उत्तर) + गोंडवानालैंड (दक्षिण)।",
        "wrong_en": ["Southern supercontinent.", "Northern supercontinent.", "The primeval global superocean.", "Pre-Pangaean Proterozoic supercontinent."],
        "wrong_hi": ["दक्षिणी विशाल भूभाग।", "उत्तरी विशाल भूभाग।", "प्राचीन विशाल महासागर।", "पेंजिया से भी पूर्व का प्राचीन भूखंड।"]
    },
    {
        "name_en": "Plate Tectonics: Convergent, Divergent & Transform Plate Boundaries",
        "name_hi": "प्लेट विवर्तनिकी: अभिसारी, अपसारी एवं संरक्षी (रूपांतरण) प्लेट सीमाएं",
        "concepts_en": ["Tuzo Wilson coined 'plate'; Dan McKenzie, Robert Parker and W.J. Morgan formulated Plate Tectonics (1967)", "Divergent Boundaries (Constructive): Plates pull apart, creating rift valleys and mid-ocean ridges (Mid-Atlantic Ridge, East African Rift)", "Convergent Boundaries (Destructive): Plates collide; Oceanic-Continental creates volcanic arcs and trenches; Continental-Continental forms fold mountains (Himalayas)", "Transform Boundaries (Conservative): Plates slide past horizontally; no crust created or destroyed; San Andreas Fault in California"],
        "concepts_hi": ["तुजो विल्सन ने 'प्लेट' शब्द दिया; मैकेंजी, पार्कर और मॉर्गन (1967) द्वारा प्लेट विवर्तनिकी सिद्धांत का प्रतिपादन", "अपसारी सीमाएं (रचनात्मक): प्लेटें एक-दूसरे से दूर जाती हैं; नए क्रस्ट का निर्माण (मध्य-अटलांटिक कटक, पूर्वी अफ्रीकी भ्रंश घाटी)", "अभिसारी सीमाएं (विनाशात्मक): प्लेटें टकराती हैं; भारी प्लेट का क्षेपण (Subduction); वलित पर्वतों का निर्माण (भारतीय व यूरेशियाई प्लेट के टकराव से हिमालय)", "रूपांतरण सीमाएं (संरक्षी): प्लेटें एक-दूसरे के समानांतर फिसलती हैं; न क्रस्ट बनता है न नष्ट होता है (कैलिफोर्निया का सैन एंड्रियास फॉल्ट)"],
        "q_en": "The towering Himalayan mountain range was formed by which type of plate tectonic boundary interaction?",
        "q_hi": "हिमालय पर्वत श्रृंखला का निर्माण किस प्रकार की विवर्तनिक प्लेट सीमा (Plate Tectonic Boundary) की परस्पर क्रिया के फलस्वरूप हुआ है?",
        "options_en": ["Continent-Continent Convergent Boundary (महाद्वीपीय-महाद्वीपीय अभिसारी सीमा)", "Oceanic-Oceanic Divergent Boundary", "Transform Conservative Boundary", "Oceanic-Continent Subduction Boundary"],
        "options_hi": ["महाद्वीपीय-महाद्वीपीय अभिसारी सीमा (Continent-Continent Convergent)", "महासागरीय-महासागरीय अपसारी सीमा", "रूपांतरण संरक्षी सीमा", "महासागरीय-महाद्वीपीय क्षेपण सीमा"],
        "correct_idx": 0,
        "exp_en": "The Himalayas were formed by the continent-continent collision between the Indian Plate and the Eurasian Plate, thrusting the sediments of the Tethys geosyncline into massive fold mountains.",
        "exp_hi": "हिमालय का निर्माण भारतीय प्लेट और यूरेशियाई प्लेट के अभिसरण (आमने-सामने की टक्कर) से हुआ, जिससे टेथिस सागर के अवसाद ऊपर उठकर मोड़दार पर्वत बन गए।",
        "cue_en": "Himalayas = Continental-Continental Convergence (India + Eurasia).",
        "cue_hi": "हिमालय = महाद्वीपीय-महाद्वीपीय अभिसरण।",
        "wrong_en": ["Collision of two continental plates.", "Creates mid-oceanic ridges.", "Generates strike-slip earthquakes like San Andreas.", "Creates volcanic island arcs like Andes/Japan."],
        "wrong_hi": ["दो महाद्वीपीय प्लेटों का टकराव।", "मध्य महासागरीय कटक बनाता है।", "सैन एंड्रियास जैसे भ्रंश बनाता है।", "ज्वालामुखी चाप बनाता है।"]
    },
    {
        "name_en": "Earthquakes: Focus, Epicenter, Primary (P) & Secondary (S) Seismic Waves",
        "name_hi": "भूकंप: मूल (फोकस/हाइपोसेंटर), अधिकेंद्र (एपिसेंटर) एवं प्राथमिक (P) व द्वितीयक (S) तरंगें",
        "concepts_en": ["Focus (Hypocenter): Point inside earth where seismic energy is released", "Epicenter: Point on earth's surface vertically above the focus (experiences first shaking)", "P-waves (Primary/Compressional): Longitudinal waves, fastest, can travel through solids, liquids, and gases", "S-waves (Secondary/Shear): Transverse waves, travel ONLY through solids (cannot travel through outer core liquid, creating shadow zone >105°)", "Measurement: Richter Scale (measures magnitude/energy logarithmically) vs Mercalli Scale (measures intensity/damage)"],
        "concepts_hi": ["भूकंप मूल (Focus / Hypocenter): भूगर्भ में वह बिंदु जहां से भूकंपीय ऊर्जा मुक्त होती है", "अधिकेंद्र (Epicenter): भू-सतह पर स्थित वह बिंदु जो भूकंप मूल के ठीक लंबवत ऊपर होता है", "प्राथमिक तरंगें (P-waves): अनुदैर्ध्य तरंगें, सबसे तेज, ठोस, द्रव और गैस तीनों माध्यमों में चल सकती हैं", "द्वितीयक तरंगें (S-waves): अनुप्रस्थ तरंगें, केवल ठोस माध्यम में संचरित होती हैं (बाह्य तरल क्रोड में प्रवेश नहीं कर पातीं)", "मापन: रिक्टर पैमाना (ऊर्जा/परिमाण का लघुगणकीय मापक) बनाम मर्केली पैमाना (तीव्रता/विनाश का मापक)"],
        "q_en": "Which type of seismic wave travels exclusively through solid media and cannot propagate through liquid or molten layers like the Earth's outer core?",
        "q_hi": "कौन सी भूकंपीय तरंगें केवल ठोस माध्यम में संचरित होती हैं और पृथ्वी के बाह्य क्रोड जैसे तरल या पिघले हुए माध्यम से नहीं गुजर सकतीं?",
        "options_en": ["Secondary Waves (S-waves / द्वितीयक तरंगें)", "Primary Waves (P-waves)", "Rayleigh Waves", "Love Waves"],
        "options_hi": ["द्वितीयक तरंगें / एस-तरंगें (Secondary / S-waves)", "प्राथमिक तरंगें / पी-तरंगें (P-waves)", "रेले तरंगें (Rayleigh waves)", "लव तरंगें (Love waves)"],
        "correct_idx": 0,
        "exp_en": "S-waves are transverse shear waves that can only propagate through solids. Their absence beyond 105 degrees proved that the Earth's outer core is in a molten/liquid state.",
        "exp_hi": "एस-तरंगें (S-waves) केवल ठोस पदार्थों में ही गति कर सकती हैं। बाह्य क्रोड में इनके लुप्त हो जाने से ही यह सिद्ध हुआ कि पृथ्वी का बाह्य क्रोड तरल अवस्था में है।",
        "cue_en": "S-waves = Solids only (cannot cross liquid outer core).",
        "cue_hi": "एस-तरंगें = केवल ठोस में संचरित।",
        "wrong_en": ["Propagate only in solids.", "Travel through solids, liquids, gases.", "Surface wave with elliptical motion.", "Surface wave with horizontal transverse motion."],
        "wrong_hi": ["केवल ठोस में गति करती हैं।", "ठोस, द्रव, गैस तीनों में चलती हैं।", "धरातलीय तरंगें।", "धरातलीय तरंगें।"]
    },
    {
        "name_en": "Volcanism: Shield Volcanoes, Composite Cones & Pacific Ring of Fire",
        "name_hi": "ज्वालामुखी: शील्ड ज्वालामुखी, मिश्रित शंकु (कंपोजिट) एवं प्रशांत महासागरीय अग्नि-वलय",
        "concepts_en": ["Shield Volcanoes: Low viscosity basaltic lava, gentle slopes (Mauna Loa, Kilauea in Hawaii)", "Composite / Stratovolcanoes: High viscosity andesitic/felsic lava, pyroclastic explosions, steep slopes (Mt. Fuji, Mt. Vesuvius, Mt. St. Helens)", "Caldera: Collapsed volcanic depression formed after explosive emptying of magma chamber", "Pacific Ring of Fire: Subduction zones around Pacific basin hosting >75% of world's active volcanoes and 90% of earthquakes"],
        "concepts_hi": ["शील्ड ज्वालामुखी: कम श्यानता (गाढ़ेपन) वाला बेसाल्टिक लावा, मंद ढाल (हवाई के मौना लोआ व किलाउएया)", "मिश्रित ज्वालामुखी (स्ट्रैटोवोलकैनो): अत्यधिक चिपचिपा गाढ़ा लावा, विस्फोटक उद्गार, खड़ी ढाल (माउंट फूजी, माउंट वेसुवियस)", "काल्डेरा (Caldera): विस्फोट के बाद ज्वालामुखी शंकु के धंसने से बना विशाल गर्त", "प्रशांत महासागरीय अग्नि-वलय (Ring of Fire): प्रशांत बेसिन के चारों ओर क्षेपण क्षेत्र, जहां विश्व के 75% से अधिक सक्रिय ज्वालामुखी स्थित हैं"],
        "q_en": "Which horseshoe-shaped seismically active zone encircling the Pacific Ocean basin accounts for approximately 75% of the world's active volcanoes?",
        "q_hi": "प्रशांत महासागर को घेरने वाली घोड़े की नाल के आकार की वह सक्रिय विवर्तनिक पेटी क्या कहलाती है, जहां विश्व के लगभग 75% सक्रिय ज्वालामुखी स्थित हैं?",
        "options_en": ["Pacific Ring of Fire (प्रशांत महासागरीय अग्नि-वलय)", "Mid-Atlantic Ridge", "Alpide Seismic Belt", "East African Rift System"],
        "options_hi": ["प्रशांत महासागरीय अग्नि-वलय (Pacific Ring of Fire)", "मध्य-अटलांटिक कटक", "अल्पाइन-हिमालयी भूकंपीय पेटी", "पूर्वी अफ्रीकी भ्रंश प्रणाली"],
        "correct_idx": 0,
        "exp_en": "The Pacific Ring of Fire (Circum-Pacific Belt) is a 40,000 km horseshoe-shaped basin of oceanic trenches and volcanic arcs hosting over 450 active and dormant volcanoes.",
        "exp_hi": "प्रशांत अग्नि-वलय (Ring of Fire) प्रशांत महासागरीय प्लेट के चारों ओर स्थित सबडक्शन जोन है, जहां विश्व के अधिकांश ज्वालामुखी और भूकंप आते हैं।",
        "cue_en": "Ring of Fire = 75% of active volcanoes (Pacific rim).",
        "cue_hi": "रिंग ऑफ फायर = 75% सक्रिय ज्वालामुखी (प्रशांत महासागर)।",
        "wrong_en": ["Zone of 75% of world's volcanoes.", "Divergent boundary in Atlantic.", "Continental collision belt across Eurasia.", "Divergent continental rift zone."],
        "wrong_hi": ["75% ज्वालामुखियों का क्षेत्र।", "अटलांटिक में अपसारी सीमा।", "यूरेशिया में महाद्वीपीय टक्कर पेटी।", "अफ्रीका की भ्रंश घाटी।"]
    },
    {
        "name_en": "Weathering, Mass Wasting & Fluvial/Glacial Landforms",
        "name_hi": "अपक्षय, वृहद संचलन एवं नदीय/हिमानी स्थलरूप (Landforms)",
        "concepts_en": ["Physical weathering (frost wedging, thermal expansion) vs Chemical weathering (carbonation, oxidation, hydration in karst limestone)", "Mass wasting: Landslides, mudflows, soil creep driven by gravity", "Fluvial erosional features: V-shaped valleys, gorges, waterfalls; Depositional: Meanders, oxbow lakes, floodplains, deltas", "Glacial features: Cirques (corries), arêtes, U-shaped valleys, hanging valleys, moraines, drumlins"],
        "concepts_hi": ["भौतिक अपक्षय (तुषार विखंडन, तापीय प्रसार) बनाम रासायनिक अपक्षय (कार्बोनेटीकरण, चूना पत्थर वाले कार्स्ट क्षेत्र)", "वृहद संचलन (Mass Wasting): गुरुत्वाकर्षण द्वारा मलबा गिरना, भूस्खलन, मडफ्लो", "नदीय स्थलरूप: अपरदनात्मक (V-आकार की घाटी, गॉर्ज, जलप्रपात); निक्षेपात्मक (विसर्प, गोखुर झील/Ox-bow lake, डेल्टा)", "हिमानी स्थलरूप: सर्क (Cirque), अरेत, U-आकार की घाटी, लटकती घाटी, हिमोढ़ (Moraines)"],
        "q_en": "A crescent-shaped lake formed when a meandering river erodes through the narrow neck of a loop is known as an:",
        "q_hi": "जब कोई विसर्पी नदी मोड़ के संकीर्ण भाग को काटकर सीधा मार्ग बना लेती है, तो पीछे छूटी हुई अर्द्धचंद्राकार झील को क्या कहा जाता है?",
        "options_en": ["Oxbow lake (गोखुर झील)", "Cirque lake (Tarn)", "Playa lake", "Crater lake"],
        "options_hi": ["गोखुर झील / छाड़न झील (Oxbow Lake)", "सर्क झील / टार्न", "प्लाया झील", "क्रेटर झील"],
        "correct_idx": 0,
        "exp_en": "An oxbow lake is a curved lake formed when a wide meander of a river is cut off, creating a free-standing body of water shaped like an oxbow or horse's hoof.",
        "exp_hi": "नदी विसर्प के अत्यधिक घुमावदार होने पर जब बाढ़ के समय नदी सीधे बहने लगती है, तो पुराना घुमावदार मार्ग मुख्य धारा से कटकर 'गोखुर झील' बन जाता है।",
        "cue_en": "Abandoned river meander = Oxbow lake (गोखुर झील).",
        "cue_hi": "नदी विसर्प से बनी झील = गोखुर झील।",
        "wrong_en": ["Formed by river meander cutoff.", "Glacial bowl lake.", "Ephemeral desert basin lake.", "Volcanic caldera lake."],
        "wrong_hi": ["नदी विसर्प के कटने से निर्मित।", "हिमानी सर्क में बनी झील।", "मरुस्थलीय मौसमी झील।", "ज्वालामुखी मुख में बनी झील।"]
    }
]

# S08-Cde0152f9 Oceanography: Relief, Currents, Salinity & Tides (3 topics)
DATA["S08-Cde0152f9"] = [
    {
        "name_en": "Ocean Floor Topography: Continental Shelf, Slope, Abyssal Plain & Trenches",
        "name_hi": "महासागरीय नितल के उच्चावच: महाद्वीपीय मग्नतट, मग्नढाल, गहरे सागरीय मैदान एवं गर्त",
        "concepts_en": ["Continental Shelf: Gently sloping seaward extension (average gradient 1° or less); shallow (depth <200 m); richest fishing grounds and offshore petroleum", "Continental Slope: Steeper gradient (2° to 5°), connects shelf to deep ocean basin; submarine canyons", "Abyssal Plains: Extensive flat plains covering 40% of ocean floor at depths of 3,000–6,000 m", "Oceanic Trenches: Deepest narrow depressions formed by subduction; Mariana Trench (Challenger Deep ~10,994 m) in Pacific Ocean"],
        "concepts_hi": ["महाद्वीपीय मग्नतट (Shelf): तट से सटा मंद ढाल (1° से कम); उथला भाग (<200 मी); सर्वाधिक मत्स्य भंडार और अपतटीय पेट्रोलियम भंडार (जैसे बॉम्बे हाई)", "महाद्वीपीय मग्नढाल (Slope): तीव्र ढाल (2° से 5°); अंतःसागरीय कैनियन स्थित होते हैं", "अगाध सागरीय मैदान (Abyssal Plain): 3,000 से 6,000 मीटर गहराई पर सबसे विस्तृत चपटे मैदान", "महासागरीय गर्त (Trenches): प्लेटों के सबडक्शन से बने सबसे गहरे स्थान; प्रशांत महासागर का मेरियाना गर्त (चैलेंजर डीप ~10,994 मी) विश्व का सबसे गहरा बिंदु"],
        "q_en": "Which major division of the ocean floor is economically the richest, hosting the world's most productive commercial fishing grounds and offshore petroleum reserves?",
        "q_hi": "महासागरीय नितल का कौन सा भाग आर्थिक रूप से सर्वाधिक संपन्न है, जहां विश्व के प्रमुख मत्स्यन क्षेत्र और अपतटीय खनिज तेल भंडार पाए जाते हैं?",
        "options_en": ["Continental Shelf (महाद्वीपीय मग्नतट)", "Continental Slope", "Abyssal Plain", "Oceanic Trench"],
        "options_hi": ["महाद्वीपीय मग्नतट (Continental Shelf)", "महाद्वीपीय मग्नढाल (Continental Slope)", "गंभीर सागरीय मैदान (Abyssal Plain)", "महासागरीय गर्त (Oceanic Trench)"],
        "correct_idx": 0,
        "exp_en": "Continental Shelves, receiving abundant sunlight and terrestrial river nutrients, support major fisheries (Dogger Bank, Grand Banks) and yield massive offshore hydrocarbon deposits.",
        "exp_hi": "महाद्वीपीय मग्नतट उथले होते हैं जहां सूर्य का प्रकाश तल तक पहुंचता है और प्लवक प्रचुर मात्रा में पनपते हैं; यही क्षेत्र मत्स्य पालन और पेट्रोलियम उत्खनन के प्रमुख केंद्र हैं।",
        "cue_en": "Richest ocean zone (fish & oil) = Continental Shelf.",
        "cue_hi": "मछली और खनिज तेल का समृद्ध क्षेत्र = महाद्वीपीय मग्नतट।",
        "wrong_en": ["Richest zone for fish and oil.", "Steep drop-off zone.", "Deep flat ocean floor.", "Deepest subduction trenches."],
        "wrong_hi": ["मत्स्यन व तेल हेतु संपन्नतम भाग।", "गहराई में तीव्र ढाल।", "गहरा समतल मैदान।", "अत्यधिक गहरे गर्त।"]
    },
    {
        "name_en": "Ocean Currents: Warm and Cold Circulation Systems & Gyres",
        "name_hi": "महासागरीय धाराएं: गर्म एवं ठंडी जलधाराएं, चक्राकार प्रवाह (Gyres) एवं सारगासो सागर",
        "concepts_en": ["Driven by planetary winds, Coriolis force, density differences, and continental shapes", "North Atlantic Gyre: Gulf Stream (warm) meets Labrador Current (cold) near Newfoundland (dense fog, Grand Banks fishing grounds)", "Sargasso Sea: Calm, seaweed-covered calm water region trapped within North Atlantic gyre (only sea without a land coast)", "Major Cold Currents: Humboldt/Peru, Benguela, California, Canaries, Oyashio", "Major Warm Currents: Kuroshio, Gulf Stream, Brazilian Current, Agulhas Current"],
        "concepts_hi": ["प्रचलित पवनों, कोरिऑलिस बल, तापमान व घनत्व भिन्नता द्वारा संचालित", "उत्तरी अटलांटिक चक्र: गर्म गल्फ स्ट्रीम और ठंडी लैब्राडोर धारा का न्यूफाउंडलैंड के पास मिलन (घना कोहरा, ग्रैंड बैंक्स मत्स्य क्षेत्र)", "सारगासो सागर (Sargasso Sea): उत्तरी अटलांटिक की चार धाराओं से घिरा शांत क्षेत्र; बिना किसी तट रेखा वाला विश्व का एकमात्र सागर", "प्रमुख ठंडी धाराएं: पेरू (हम्बोल्ट), बेंगूएला, कैलिफोर्निया, कनारी, ओयाशियो", "प्रमुख गर्म धाराएं: क्यूरोशियो, गल्फ स्ट्रीम, ब्राजील धारा, अगुलहास"],
        "q_en": "Which famous water body is the only sea on Earth that possesses no land boundary, being entirely defined by four circulating oceanic currents?",
        "q_hi": "पृथ्वी पर स्थित वह एकमात्र सागर कौन सा है जिसकी कोई स्थलीय तटरेखा नहीं है और जो चारों ओर से महासागरीय जलधाराओं के चक्र द्वारा घिरा हुआ है?",
        "options_en": ["Sargasso Sea (सारगासो सागर)", "Coral Sea", "Tasman Sea", "Bering Sea"],
        "options_hi": ["सारगासो सागर (Sargasso Sea)", "कोरल सागर", "तस्मान सागर", "बेरिंग सागर"],
        "correct_idx": 0,
        "exp_en": "The Sargasso Sea in the North Atlantic is bounded solely by ocean currents (Gulf Stream, North Atlantic Current, Canary Current, North Equatorial Current) and has no coastline.",
        "exp_hi": "सारगासो सागर उत्तरी अटलांटिक महासागर में स्थित है, जिसके चारों ओर महासागरीय धाराएं बहती हैं और इसके बीच में 'सारगासम' नामक तैरने वाली समुद्री घास पाई जाती है।",
        "cue_en": "Sea without land boundary = Sargasso Sea.",
        "cue_hi": "तटरहित सागर = सारगासो सागर।",
        "wrong_en": ["Bounded only by oceanic currents.", "Bounded by Australia and islands.", "Bounded by Australia and New Zealand.", "Bounded by Alaska and Russia."],
        "wrong_hi": ["केवल धाराओं से घिरा सागर।", "ऑस्ट्रेलिया के पास स्थित।", "ऑस्ट्रेलिया-न्यूजीलैंड के बीच।", "अलास्का और रूस के बीच।"]
    },
    {
        "name_en": "Ocean Salinity, Temperature Profiles & Tides (Spring and Neap Tides)",
        "name_hi": "महासागरीय लवणता, तापमान परिच्छेदिका एवं ज्वार-भाटा (वृहद व लघु ज्वार)",
        "concepts_en": ["Average global ocean salinity is 35 parts per thousand (ppt or ‰); Lake Van (Turkey, 330‰) and Dead Sea (~240‰) highest", "Thermocline: Boundary layer between warm surface water and cold deep ocean where temperature drops rapidly", "Tides caused by gravitational pull of Moon and Sun; Spring Tides (Syzygy - New Moon and Full Moon when Sun, Moon, Earth align) produce highest amplitude", "Neap Tides (Quadrature - 1st and 3rd quarters when Moon and Sun are at right angles) produce lowest amplitude"],
        "concepts_hi": ["महासागरों की औसत लवणता 35 प्रति हजार (35‰) होती है; तुर्की की वान झील (330‰) व मृत सागर सर्वाधिक लवणीय", "थर्मोक्लाइन (Thermocline): सतह के गर्म जल और गहरे ठंडे जल के बीच का संक्रमण स्तर जहां तापमान तेजी से गिरता है", "ज्वार-भाटा: सूर्य और चंद्रमा के गुरुत्वाकर्षण खिंचाव से उत्पन्न", "वृहद ज्वार (Spring Tides): अमावस्या और पूर्णिमा (सिजिगी/युति-वियुति) को जब सूर्य, पृथ्वी और चंद्रमा एक सीध में होते हैं", "लघु ज्वार (Neap Tides): शुक्ल व कृष्ण पक्ष की सप्तमी-अष्टमी को जब सूर्य और चंद्रमा समकोण (90°) पर होते हैं"],
        "q_en": "During which lunar phases do 'Spring Tides' (exceptionally high tides) occur due to the alignment of the Sun, Moon, and Earth in a straight line (Syzygy)?",
        "q_hi": "सूर्य, चंद्रमा और पृथ्वी के एक सीधी रेखा में होने (सिजिगी) के कारण अत्यधिक ऊंचे 'वृहद ज्वार' (Spring Tides) किन तिथियों को आते हैं?",
        "options_en": ["New Moon and Full Moon (अमावस्या एवं पूर्णिमा)", "First and Third Quarter Moons", "Equinoxes only", "Solar eclipses only"],
        "options_hi": ["अमावस्या एवं पूर्णिमा (New Moon and Full Moon)", "शुक्ल व कृष्ण पक्ष की अष्टमी", "केवल विषुव के दिनों में", "केवल सूर्य ग्रहण के दिन"],
        "correct_idx": 0,
        "exp_en": "Spring tides occur twice each lunar month during Full Moon and New Moon when the gravitational attractions of the Sun and Moon reinforce one another.",
        "exp_hi": "अमावस्या और पूर्णिमा के दिन सूर्य, पृथ्वी और चंद्रमा एक सीध में होते हैं, जिससे उनका संयुक्त गुरुत्वाकर्षण बल सर्वाधिक ऊंचा ज्वार (वृहद ज्वार) उत्पन्न करता है।",
        "cue_en": "Spring Tides = New Moon & Full Moon (Syzygy).",
        "cue_hi": "वृहद ज्वार = अमावस्या और पूर्णिमा।",
        "wrong_en": ["Phases producing spring tides.", "Phases producing neap tides.", "Occurs twice a year.", "Specific eclipse event."],
        "wrong_hi": ["वृहद ज्वार की तिथियां।", "लघु ज्वार की तिथियां।", "साल में दो बार विषुव।", "ग्रहण विशिष्ट घटना।"]
    }
]

# S08-C062cef1d Atmosphere, Pressure Belts, Winds & Climate Zones (8 topics)
DATA["S08-C062cef1d"] = [
    {
        "name_en": "Atmospheric Layers: Troposphere, Stratosphere, Mesosphere & Thermosphere",
        "name_hi": "वायुमंडल की परतें: क्षोभमंडल, समतापमंडल (ओजोन परत), मध्यमंडल एवं तापमंडल",
        "concepts_en": ["Troposphere: Lowest layer (8 km at poles to 18 km at equator); contains all weather phenomena (clouds, storms); normal lapse rate (-6.5°C per 1,000 m)", "Stratosphere: Extends to 50 km; temperature increases with altitude; contains Ozone Layer (O3 at 15-35 km absorbing UV rays); ideal for flying jets", "Mesosphere: Extends to 80 km; coldest layer (-100°C); meteors burn up here", "Thermosphere / Ionosphere: Radio wave reflection (Kennelly-Heaviside layer), Auroras (Borealis & Australis)"],
        "concepts_hi": ["क्षोभमंडल (Troposphere): सबसे निचली परत (ध्रुवों पर 8 किमी, भूमध्य रेखा पर 18 किमी); मौसम संबंधी सभी घटनाएं (बादल, वर्षा, तूफान) यहीं घटती हैं; सामान्य ह्रास दर (-6.5°C प्रति 1000 मी)", "समतापमंडल (Stratosphere): 50 किमी तक; तापमान बढ़ता है; ओजोन परत (15-35 किमी) पराबैंगनी किरणों को सोखती है; जेट विमानों के उड़ने हेतु आदर्श", "मध्यमंडल (Mesosphere): 80 किमी तक; सबसे ठंडा स्तर (-100°C); उल्कापिंड यहीं जलकर नष्ट होते हैं", "तापमंडल / आयनमंडल (Ionosphere): रेडियो तरंगों को परावर्तित करता है; ध्रुवीय ज्योति (ऑरोरा) यहीं दिखाई देती है"],
        "q_en": "In which atmospheric layer is the protective Ozone Layer situated, and where jet aircraft prefer to fly due to absence of convective turbulence?",
        "q_hi": "वायुमंडल की किस परत में पराबैंगनी किरणों से रक्षा करने वाली 'ओजोन परत' स्थित है और बादलों के अभाव के कारण जेट विमान उड़ान भरना पसंद करते हैं?",
        "options_en": ["Stratosphere (समतापमंडल)", "Troposphere", "Mesosphere", "Thermosphere"],
        "options_hi": ["समतापमंडल (Stratosphere)", "क्षोभमंडल (Troposphere)", "मध्यमंडल (Mesosphere)", "तापमंडल (Thermosphere)"],
        "correct_idx": 0,
        "exp_en": "The stratosphere houses the ozone layer (Ozonosphere) and provides smooth flying conditions free of turbulent weather found in the troposphere.",
        "exp_hi": "समतापमंडल में ओजोन परत स्थित होती है जो हानिकारक यूवी किरणों को अवशोषित करती है; इस मंडल में मौसमी विक्षोभ न होने से हवाई जहाज उड़ाने की आदर्श दशाएं मिलती हैं।",
        "cue_en": "Ozone layer & Jet flights = Stratosphere.",
        "cue_hi": "ओजोन परत व जेट विमान = समतापमंडल।",
        "wrong_en": ["Houses ozone layer.", "Lowest weather-active layer.", "Coldest layer where meteors burn.", "Ionized layer reflecting radio waves."],
        "wrong_hi": ["ओजोन परत का मंडल।", "मौसम सक्रिय निचला मंडल।", "सबसे ठंडा मंडल।", "रेडियो तरंगों वाला आयनमंडल।"]
    },
    {
        "name_en": "Atmospheric Insolation, Heat Budget & Temperature Inversion",
        "name_hi": "सूर्यातप (Insolation), पृथ्वी का ऊष्मा बजट एवं तापमान का व्युत्क्रमण",
        "concepts_en": ["Insolation: Incoming solar radiation received in short wavelengths", "Terrestrial Radiation: Earth radiates heat in long infrared wavelengths", "Albedo: Fraction of solar energy reflected back to space without heating (Earth average albedo ~30-35%; fresh snow has highest albedo ~80-90%)", "Temperature Inversion: Condition where temperature increases with height (common in winter valleys under calm, clear skies, causing smog)"],
        "concepts_hi": ["सूर्यातप (Insolation): पृथ्वी को प्राप्त होने वाली लघु तरंगीय सौर विकिरण", "भौमिक विकिरण (Terrestrial Radiation): पृथ्वी द्वारा अंतरिक्ष में छोड़ी जाने वाली दीर्घ तरंगीय ऊष्मा", "एल्बिडो (Albedo): सौर ऊर्जा का वह अंश जो बिना गर्म किए वापस परावर्तित हो जाता है (पृथ्वी का औसत ~30-35%; ताजी बर्फ का सर्वाधिक ~80-90%)", "तापमान व्युत्क्रमण: सामान्य नियम के विपरीत ऊंचाई बढ़ने पर तापमान का बढ़ना (सर्दियों की रातों में घाटियों में कोहरा व स्मॉग बनना)"],
        "q_en": "The proportion of incoming solar radiation reflected back into space from the Earth's surface and atmosphere without contributing to heating is called:",
        "q_hi": "पृथ्वी की सतह और वायुमंडल द्वारा बिना अवशोषित किए अंतरिक्ष में वापस परावर्तित कर दी जाने वाली सौर विकिरण की मात्रा को क्या कहा जाता है?",
        "options_en": ["Albedo (एल्बिडो / परावर्तन अनुपात)", "Insolation", "Solar Constant", "Advection"],
        "options_hi": ["एल्बिडो (Albedo)", "सूर्यातप (Insolation)", "सौर स्थिरांक (Solar Constant)", "अभिवहन (Advection)"],
        "correct_idx": 0,
        "exp_en": "Albedo is the reflectivity of a surface, expressing the ratio of reflected to incident light. Fresh snow has the highest albedo on Earth.",
        "exp_hi": "एल्बिडो किसी सतह की परावर्तन क्षमता है; पृथ्वी का औसत एल्बिडो लगभग 35% है और ताजी बर्फ सबसे अधिक परावर्तक (80-90%) होती है।",
        "cue_en": "Reflected solar radiation = Albedo.",
        "cue_hi": "परावर्तित सौर विकिरण = एल्बिडो।",
        "wrong_en": ["Measure of reflectivity.", "Incoming solar radiation.", "Energy received at top of atmosphere (1.94 cal/cm²/min).", "Horizontal transfer of heat by wind."],
        "wrong_hi": ["परावर्तन का मापक।", "आने वाली सौर ऊर्जा।", "वायुमंडल के शीर्ष पर ऊर्जा मान।", "पवन द्वारा ऊष्मा का क्षैतिज संचरण।"]
    },
    {
        "name_en": "Planetary Pressure Belts: Doldrums, Subtropical Highs & Polar Highs",
        "name_hi": "वैश्विक वायुदाब पेटियां: डोलड्रम (शांत कटिबंध), उपोष्ण उच्च दाब (अश्व अक्षांश) एवं ध्रुवीय उच्च",
        "concepts_en": ["Equatorial Low Pressure Belt (Doldrums, 5°N to 5°S): Thermally induced calm zone, rising convective air currents", "Subtropical High Pressure Belts (Horse Latitudes, 30° to 35° N/S): Dynamically induced sinking air, dry deserts located here", "Subpolar Low Pressure Belts (60° to 65° N/S): Dynamically induced cyclonic storms", "Polar Highs (90° N/S): Thermally induced extreme cold descending air"],
        "concepts_hi": ["भूमध्यरेखीय निम्न दाब पेटी (डोलड्रम, 5° उत्तर से 5° दक्षिण): ताप-जन्य शांत क्षेत्र, हवाओं का संवहनीय आरोहण", "उपोष्ण उच्च दाब पेटी (अश्व अक्षांश / Horse Latitudes, 30° से 35° उत्तर/दक्षिण): गति-जन्य अवरोही वायु, विश्व के अधिकांश गर्म मरुस्थल यहीं स्थित", "उपध्रुवीय निम्न दाब पेटी (60° से 65°): गति-जन्य चक्रवाती क्षेत्र", "ध्रुवीय उच्च दाब पेटी (90°): ताप-जन्य अत्यधिक ठंडी भारी वायु"],
        "q_en": "The calm subtropical high-pressure oceanic belts located between approximately 30° and 35° North and South latitudes are historically known as:",
        "q_hi": "लगभग 30° से 35° उत्तरी एवं दक्षिणी अक्षांशों के मध्य स्थित उपोष्ण कटिबंधीय उच्च वायुदाब की शांत पेटियों को ऐतिहासिक रूप से क्या कहा जाता है?",
        "options_en": ["Horse Latitudes (अश्व अक्षांश)", "Doldrums", "Roaring Forties", "Furious Fifties"],
        "options_hi": ["अश्व अक्षांश (Horse Latitudes)", "डोलड्रम (Doldrums)", "चीखती साठा / गरजती चालीसा", "प्रचंड पचासा"],
        "correct_idx": 0,
        "exp_en": "The Horse Latitudes are subtropical regions of high pressure and calm winds at 30°–35° N/S, where Spanish ships carrying horses often threw them overboard when becalmed.",
        "exp_hi": "30° से 35° अक्षांशों को 'अश्व अक्षांश' कहा जाता है क्योंकि पाल वाले जहाजों के शांत हवा में फंस जाने पर नाविक वजन कम करने के लिए घोड़ों को समुद्र में फेंक देते थे।",
        "cue_en": "30°-35° Subtropical High = Horse Latitudes.",
        "cue_hi": "30°-35° उपोष्ण उच्च दाब = अश्व अक्षांश।",
        "wrong_en": ["Subtropical high pressure zones.", "Equatorial low pressure calm belt.", "Westerly winds at 40° South.", "Westerly winds at 50° South."],
        "wrong_hi": ["उपोष्ण उच्च दाब क्षेत्र।", "भूमध्यरेखीय शांत पेटी।", "40° दक्षिणी अक्षांश की पछुआ हवाएं।", "50° दक्षिणी अक्षांश की हवाएं।"]
    },
    {
        "name_en": "Global Wind Systems: Trade Winds, Westerlies & Polar Easterlies",
        "name_hi": "स्थायी पवन प्रणालियां: व्यापारिक पवनें (सनमार्गी), पछुआ पवनें एवं ध्रुवीय पूर्वी पवनें",
        "concepts_en": ["Coriolis Force (Ferrel's Law): Deflects moving air to the right in Northern Hemisphere and left in Southern Hemisphere", "Trade Winds (Easterlies): Blow from Subtropical Highs to Equatorial Low; Northeast Trades in North, Southeast Trades in South", "Westerlies: Blow from Subtropical Highs to Subpolar Lows; uninterrupted in Southern Hemisphere oceans ('Roaring Forties', 'Furious Fifties', 'Shrieking Sixties')", "Polar Easterlies: Cold dry winds blowing from Polar Highs"],
        "concepts_hi": ["कोरिऑलिस बल (फेरेल का नियम): गतिमान हवाओं को उत्तरी गोलार्ध में दाईं ओर और दक्षिणी गोलार्ध में बाईं ओर मोड़ देता है", "व्यापारिक पवनें (Trade Winds): उपोष्ण उच्च दाब से भूमध्यरेखीय निम्न दाब की ओर; उत्तर-पूर्व व दक्षिण-पूर्व व्यापारिक पवनें", "पछुआ पवनें (Westerlies): उपोष्ण उच्च दाब से उपध्रुवीय निम्न दाब की ओर; दक्षिणी गोलार्ध में खुले समुद्रों के कारण प्रचंड रूप ('गरजती चालीसा', 'प्रचंड पचासा', 'चीखती साठा')", "ध्रुवीय पूर्वी पवनें: ध्रुवों से बहने वाली ठंडी हवाएं"],
        "q_en": "According to Ferrel's Law, wind and moving objects are deflected in which direction in the Northern Hemisphere due to the Earth's rotation (Coriolis Effect)?",
        "q_hi": "फेरेल के नियम और कोरिऑलिस प्रभाव के अनुसार पृथ्वी के घूर्णन के कारण उत्तरी गोलार्ध में गतिमान पवनें किस दिशा में विक्षेपित (मुड़) जाती हैं?",
        "options_en": ["Towards their right (अपनी दाईं ओर)", "Towards their left", "Directly towards the poles", "Directly towards the equator"],
        "options_hi": ["अपनी दाईं ओर (Towards the Right)", "अपनी बाईं ओर (Towards the Left)", "सीधे ध्रुवों की ओर", "सीधे भूमध्य रेखा की ओर"],
        "correct_idx": 0,
        "exp_en": "Ferrel's Law states that Coriolis force deflects any moving fluid to the right of its path in the Northern Hemisphere, and to the left in the Southern Hemisphere.",
        "exp_hi": "फेरेल के नियम के अनुसार कोरिऑलिस बल के प्रभाव से उत्तरी गोलार्ध में बहने वाली सभी हवाएं अपनी गति की दिशा से 'दाईं ओर' तथा दक्षिणी गोलार्ध में 'बाईं ओर' मुड़ जाती हैं।",
        "cue_en": "Coriolis deflection = Right in North, Left in South.",
        "cue_hi": "कोरिऑलिस विक्षेपण = उत्तर में दाईं ओर, दक्षिण में बाईं ओर।",
        "wrong_en": ["Deflection direction in Northern Hemisphere.", "Deflection direction in Southern Hemisphere.", "Unaffected trajectory.", "Unaffected trajectory."],
        "wrong_hi": ["उत्तरी गोलार्ध में विक्षेपण की दिशा।", "दक्षिणी गोलार्ध में विक्षेपण की दिशा।", "सीधा मार्ग नहीं होता।", "सीधा मार्ग नहीं होता।"]
    },
    {
        "name_en": "Jet Streams: Subtropical Westerly & Polar Front Jet Streams",
        "name_hi": "जेट स्ट्रीम: उपोष्ण पछुआ जेट एवं ध्रुवीय वाताग्री जेट धाराएं",
        "concepts_en": ["Narrow bands of high-velocity meandering westerly winds in upper troposphere (9–14 km altitude)", "Speeds exceed 150–400 km/h; discovered during WWII by military aviators", "Polar Front Jet Stream (strongest, associated with mid-latitude cold fronts) and Subtropical Westerly Jet Stream", "Influence on Indian Monsoon: Withdrawal of westerly jet north of Himalayas allows onset of Southwest Monsoon"],
        "concepts_hi": ["ऊपरी क्षोभमंडल में 9 से 14 किमी की ऊंचाई पर संकीर्ण पट्टी में पश्चिम से पूर्व तीव्र गति से चलने वाली पवनें", "गति 150 से 400 किमी/घंटा से अधिक; द्वितीय विश्व युद्ध के दौरान खोज", "ध्रुवीय वाताग्र जेट स्ट्रीम एवं उपोष्ण पछुआ जेट स्ट्रीम", "भारतीय मानसून पर प्रभाव: तिब्बत के पठार के ऊपर पछुआ जेट का उत्तर की ओर खिसकना दक्षिण-पश्चिम मानसून के आगमन का मार्ग प्रशस्त करता है"],
        "q_en": "In which layer of the Earth's atmosphere do high-altitude, fast-flowing meandering air currents known as 'Jet Streams' predominantly circulate?",
        "q_hi": "अत्यधिक तीव्र गति से चलने वाली संकीर्ण विसर्पी वायु धाराएं 'जेट स्ट्रीम' मुख्य रूप से वायुमंडल के किस स्तर में प्रवाहित होती हैं?",
        "options_en": ["Upper Troposphere / Tropopause", "Stratosphere", "Mesosphere", "Exosphere"],
        "options_hi": ["ऊपरी क्षोभमंडल / क्षोभसीमा (Upper Troposphere / Tropopause)", "समतापमंडल", "मध्यमंडल", "बहिर्मंडल"],
        "correct_idx": 0,
        "exp_en": "Jet streams are fast-moving ribbons of wind circulating near the tropopause (the transition between troposphere and stratosphere) at altitudes of 9 to 14 km.",
        "exp_hi": "जेट स्ट्रीम क्षोभसीमा (क्षोभमंडल की ऊपरी सीमा, 9-14 किमी ऊंचाई) के पास पश्चिम से पूर्व दिशा में विशाल लहरदार (रॉसबी तरंगों) के रूप में बहती हैं।",
        "cue_en": "Jet Streams = Upper Troposphere (Tropopause).",
        "cue_hi": "जेट स्ट्रीम = ऊपरी क्षोभमंडल (क्षोभसीमा)।",
        "wrong_en": ["Atmospheric level of jet streams.", "Layer above tropopause.", "Cold middle layer.", "Outer fringes of atmosphere."],
        "wrong_hi": ["जेट स्ट्रीम का प्रवाह क्षेत्र।", "ऊपर का शांत मंडल।", "मध्यमंडल।", "बाह्य वायुमंडल।"]
    },
    {
        "name_en": "Cyclones: Tropical Cyclones vs Temperate Mid-Latitude Cyclones",
        "name_hi": "चक्रवात: उष्णकटिबंधीय चक्रवात बनाम शीतोष्ण कटिबंधीय चक्रवात",
        "concepts_en": ["Tropical Cyclones: Form over warm ocean waters (sea surface temp >27°C); driven by latent heat of condensation; calm 'Eye' at center surrounded by Eye Wall; called Typhoons (China/Japan), Hurricanes (Atlantic), Cyclones (Indian Ocean), Willy-willies (Australia)", "Temperate / Frontal Cyclones: Form along polar fronts where warm and cold air masses collide; cover massive areas; can form over land and water", "Coriolis force is zero at equator, hence tropical cyclones NEVER form between 0° and 5° latitudes"],
        "concepts_hi": ["उष्णकटिबंधीय चक्रवात: गर्म महासागरीय जल (>27°C) पर उत्पन्न; संघनन की गुप्त ऊष्मा से ऊर्जा प्राप्त; केंद्र में शांत 'चक्षु' (Eye) और उसके चारों ओर विनाशकारी 'आई वॉल'; नाम: टाइफून (चीन/जापान), हरिकेन (अटलांटिक), चक्रवात (हिंद महासागर), विली-विली (ऑस्ट्रेलिया)", "शीतोष्ण चक्रवात: वाताग्रों (ठंडी व गर्म वायुराशियों के मिलन) से उत्पन्न; स्थल और जल दोनों पर बन सकते हैं", "भूमध्य रेखा पर कोरिऑलिस बल शून्य होने के कारण 0° से 5° अक्षांशों के मध्य उष्णकटिबंधीय चक्रवात कभी नहीं बनते"],
        "q_en": "Why do intense tropical cyclones NEVER form in the immediate vicinity of the Equator (between 0° and 5° latitudes)?",
        "q_hi": "भूमध्य रेखा के ठीक निकट (0° से 5° अक्षांशों के मध्य) तीव्र उष्णकटिबंधीय चक्रवात कभी क्यों नहीं बनते?",
        "options_en": ["Absence of Coriolis force at the Equator (कोरिऑलिस बल का अभाव)", "Insufficient sea surface temperature", "Absence of low pressure systems", "Excessive wind shear"],
        "options_hi": ["भूमध्य रेखा पर कोरिऑलिस बल का अभाव (Coriolis force is zero)", "समुद्र का तापमान अपर्याप्त होना", "निम्न दाब प्रणालियों का न होना", "अत्यधिक पवन अपरूपण"],
        "correct_idx": 0,
        "exp_en": "Coriolis force is zero at the equator and too weak between 0° and 5° to impart the rotational spin necessary to initiate and maintain a cyclone vortex.",
        "exp_hi": "भूमध्य रेखा पर कोरिऑलिस बल शून्य होता है, जिसके कारण हवाएं वृत्ताकार घूमने के बजाय सीधे निम्न दाब की ओर भर जाती हैं और चक्रवाती भंवर नहीं बन पाता।",
        "cue_en": "No cyclones at Equator = Zero Coriolis Force.",
        "cue_hi": "भूमध्य रेखा पर चक्रवात नहीं = शून्य कोरिऑलिस बल।",
        "wrong_en": ["Crucial physical factor.", "Equatorial sea surface is very warm (>27°C).", "Equator has ITCZ low pressure.", "Incorrect reason."],
        "wrong_hi": ["चक्रवात न बनने का मुख्य कारण।", "भूमध्य रेखा पर समुद्र बहुत गर्म होता है।", "वहां आईटीसीजेड निम्न दाब रहता है।", "गलत कारण।"]
    },
    {
        "name_en": "Koeppen's Climate Classification System (A, B, C, D, E & H Groups)",
        "name_hi": "कोपेन का जलवायु वर्गीकरण: मुख्य जलवायु समूह (A, B, C, D, E एवं H)",
        "concepts_en": ["Formulated by Wladimir Koeppen (1884, revised 1918/1936) based on vegetation, temperature, and precipitation patterns", "Group A (Tropical Moist): All months >18°C (Af rainforest, Am monsoon, Aw savanna)", "Group B (Dry Climates): Potential evaporation exceeds precipitation (BWh hot desert, BSh semi-arid steppe)", "Group C (Mild Mid-Latitude): Coldest month between -3°C and 18°C (Cwa monsoon subtropical, Cs Mediterranean with dry summers)", "Group D (Continental/Severe Mid-latitude), Group E (Polar: ET Tundra, EF Ice Cap), Group H (Highland)"],
        "concepts_hi": ["व्लादिमीर कोपेन द्वारा वनस्पति, तापमान और वर्षा के आधार पर 1884 में प्रतिपादित और 1918/1936 में संशोधित", "समूह A (उष्णकटिबंधीय): सभी महीनों का औसत तापमान >18°C (Af वर्षावन, Am मानसून, Aw सवाना)", "समूह B (शुष्क जलवायु): वाष्पीकरण वर्षा से अधिक (BWh गर्म मरुस्थल, BSh अर्ध-शुष्क स्टेपी)", "समूह C (उष्ण समशीतोष्ण): सबसे ठंडे महीने का तापमान -3°C से 18°C (Cs भूमध्यसागरीय - शुष्क ग्रीष्मकाल व शीतकालीन वर्षा)", "समूह D (महाद्वीपीय), समूह E (ध्रुवीय: ET टुंड्रा, EF स्थायी हिमाच्छादित), समूह H (पर्वतीय जलवायु)"],
        "q_en": "In Koeppen's climate classification, which unique climate type is characterized by dry warm summers and mild rainy winters (Cs designation)?",
        "q_hi": "कोपेन के जलवायु वर्गीकरण में 'Cs' अक्षर द्वारा दर्शाई जाने वाली वह विशिष्ट जलवायु कौन सी है, जिसकी प्रमुख विशेषता 'शुष्क ग्रीष्मकाल और शीतकालीन वर्षा' होती है?",
        "options_en": ["Mediterranean Climate (भूमध्यसागरीय जलवायु)", "Tropical Monsoon Climate", "Humid Subtropical Climate", "Taiga Boreal Climate"],
        "options_hi": ["भूमध्यसागरीय जलवायु (Mediterranean Climate - Cs)", "उष्णकटिबंधीय मानसूनी जलवायु", "आर्द्र उपोष्ण जलवायु", "टैगा बोरियल जलवायु"],
        "correct_idx": 0,
        "exp_en": "The Mediterranean climate (Koeppen Cs) is characterized by dry hot/warm summers and wet mild winters under the seasonal shift of westerly winds.",
        "exp_hi": "भूमध्यसागरीय जलवायु (Cs) की सबसे विशिष्ट पहचान यह है कि यहां ग्रीष्म ऋतु शुष्क रहती है और वर्षा शीतकाल में पछुआ हवाओं द्वारा होती है (खट्टे फलों की खेती हेतु प्रसिद्ध)।",
        "cue_en": "Winter rainfall & dry summer = Mediterranean (Cs).",
        "cue_hi": "शीतकालीन वर्षा व शुष्क ग्रीष्म = भूमध्यसागरीय जलवायु।",
        "wrong_en": ["Distinctive Cs climate.", "Summer rain monsoon (Am).", "Year-round rain subtropical (Cfa).", "Cold subpolar forest (Dfc)."],
        "wrong_hi": ["Cs का सही अर्थ।", "ग्रीष्मकालीन मानसूनी वर्षा (Am)।", "साल भर वर्षा वाली जलवायु।", "ठंडी उपध्रुवीय जलवायु।"]
    },
    {
        "name_en": "El Niño, La Niña & Southern Oscillation (ENSO) Phenomena",
        "name_hi": "अल नीनो, ला नीना एवं दक्षिणी दोलन (ENSO परिघटना)",
        "concepts_en": ["Walker Circulation: Normal conditions feature warm pool in western Pacific and cold upwelling off Peru", "El Niño ('The Christ Child'): Periodic warming of central and eastern tropical Pacific; suppresses Peruvian upwelling; causes droughts/monsoon failure in India and Australia, floods in Peru", "La Niña: Abnormally cold sea surface temperatures in eastern Pacific; strengthens Indian southwest monsoon", "ENSO (El Niño Southern Oscillation) links atmospheric pressure swing (Darwin vs Tahiti) with oceanic warming"],
        "concepts_hi": ["वॉकर संचरण: सामान्य स्थिति में पश्चिमी प्रशांत में गर्म जल और पेरू तट पर ठंडा जल ऊपर (Upwelling) उठता है", "अल नीनो ('बाल ईसा'): मध्य और पूर्वी प्रशांत महासागर का असामान्य रूप से गर्म हो जाना; पेरू के तट पर ठंडे जल का ऊपर उठना रुक जाता है; भारत में मानसूनी वर्षा कमजोर पड़ती है व सूखा पड़ता है", "ला नीना ('छोटी बच्ची'): पूर्वी प्रशांत का असामान्य रूप से अत्यधिक ठंडा होना; भारत में सामान्य से अधिक मजबूत मानसूनी वर्षा लाता है", "दक्षिणी दोलन (Southern Oscillation): प्रशांत और हिंद महासागर के बीच वायुदाब का उलटफेर (डार्विन बनाम ताहिती)"],
        "q_en": "Which oceanic-atmospheric phenomenon involving anomalous periodic warming of surface waters in the eastern tropical Pacific typically leads to deficient monsoon rainfall and droughts in India?",
        "q_hi": "पूर्वी उष्णकटिबंधीय प्रशांत महासागर के सतही जल के असामान्य रूप से गर्म होने की वह कौन सी परिघटना है, जो आमतौर पर भारत में कमजोर मानसून और सूखे का कारण बनती है?",
        "options_en": ["El Niño (अल नीनो)", "La Niña", "Indian Ocean Dipole (Positive)", "Madden-Julian Oscillation"],
        "options_hi": ["अल नीनो (El Niño)", "ला नीना (La Niña)", "सकारात्मक हिंद महासागर द्विध्रुव", "मैडेन-जूलियन दोलन"],
        "correct_idx": 0,
        "exp_en": "El Niño involves the warming of sea surface temperatures in the equatorial central and eastern Pacific, weakening the Walker circulation and disrupting India's southwest monsoon.",
        "exp_hi": "अल नीनो के दौरान पूर्वी प्रशांत महासागर का जल गर्म हो जाता है, जिससे भारतीय उपमहाद्वीप पर उच्च वायुदाब बनकर दक्षिण-पश्चिम मानसूनी हवाएं कमजोर पड़ जाती हैं।",
        "cue_en": "El Niño = Pacific warming -> Weak Indian Monsoon.",
        "cue_hi": "अल नीनो = प्रशांत में गर्माहट -> कमजोर भारतीय मानसून।",
        "wrong_en": ["Suppresses Indian monsoon.", "Cools eastern Pacific, aids Indian monsoon.", "Positive IOD aids Indian monsoon.", "Intra-seasonal traveling wave."],
        "wrong_hi": ["मानसून को कमजोर करता है।", "मानसून को मजबूत करता है।", "सकारात्मक द्विध्रुव मानसून हेतु अच्छा होता है।", "अंतरा-मौसमी तरंग।"]
    }
]

print("Loaded S08 successfully")
